const AndamanNicobarData = [
    {
      id: 1, 
      image: "assets/Andaman/Beaches/Baratang Island.jpg",
      name: "Baratang Island",
      category: "Beaches",
      description: "https://www.go2andaman.com/baratang/",
      info : "Baratang is famous for its natural wonders; from impressive Limestone Caves and dense mangrove creeks. There are tidal swamp forests and small but fascinating Mud Volcanoes. ",
      map : "https://goo.gl/maps/rn7WdxMkovSKrYq86",
    },
    {
      id: 2,
      image: "assets/Andaman/Beaches/Diglipur Island.jpg",
      name: "Diglipur Island",
      category: "Beaches",
      description: "https://www.go2andaman.com/diglipur/",
      info : "Diglipur is a vast region that people mostly visit for Kalipur turtle nestling and the Saddle Peak Trekking. But there are more places of interest like Alfred caves and the Craggy island which are slowly opening up as tourism destinations.",
      map : "https://goo.gl/maps/avh3eWmq72NABecXA",
    },
    {
      id: 3,
      image: "assets/Andaman/Beaches/Havelock Island.jpg",
      name: "Havelock Island",
      category: "Beaches",
      description: "https://www.go2andaman.com/havelock-island/",
      info : "Swaraj or Havelock Island is famous for its entrancing white sandy beaches – among the most beautiful beaches in Andaman. It is also famous for its marvelous reef and rapturous swimming elephants.",
      map : "https://goo.gl/maps/sgLJLwAWhMqYtwUXA",
    },
    {
      id: 4,
      image: "assets/Andaman/Beaches/Neil Island.png",
      name: "Neil Island",
      category: "Beaches",
      description: "https://www.go2andaman.com/neil-island/",
      info : "Neil Island is best known for its unparalleled biodiversity and unexplored span of dense tropical forests and greenery complemented by white sand beaches and rich coral reefs.",
      map : "https://goo.gl/maps/nzynTKuCyQMYAZFq6",
    },
    {
      id: 5,
      image: "assets/Andaman/Beaches/Port Blair.jfif",
      name: "Port Blair",
      category: "Beaches",
      description: "https://www.tourmyindia.com/states/andaman/port-blair.html",
      info : "Port Blair on South Andaman Island is the capital city of the Andaman and Nicobar Islands, an Indian territory in the Bay of Bengal. ",
      map : "https://goo.gl/maps/pkMN2G7xhtCYLrgL7",
    },
    {
      id: 6,
      image: "aassets/Andaman/Beaches/Rangat Island.png",
      name: "Rangat Island",
      category: "Beaches",
      description: "https://www.go2andaman.com/long-island/",
      info : " If you are visiting the Andaman and Nicobar Islands, then Rangat/Long Island is definitely a place you must not miss. It has crystal clear waves from the deep blue sea to the cool breeze that sweeps you off your feet.",
      map : "https://goo.gl/maps/atW6hhP13tTDRppm7",
    },
    {
      id: 7,
      image: "assets/Andaman/Beaches/Ross Island.jpg",
      name: "Ross Island",
      category: "Beaches",
      description: "https://www.eternalandamans.com/ross-island-andaman",
      info : "Ross Island Penal Colony was a convict settlement that was established in 1858 in the remote Andaman Islands by the British colonial government in India, primarily to jail a large number of prisoners from the Indian Rebellion of 1857, also known as the Indian Mutiny.",
      map : "https://goo.gl/maps/NWyRBoVtHpYUM8oCA",
    },
    {
      id: 8,
      image: "assets/Andaman/Religious/Laxminarayana Temple.jpg",
      name: "Laxminarayana Temple",
      category: "Religious",
      description: "https://www.pinterest.com/pin/472737292134349145/",
      info : "Laxmi Narayan Temple, dedicated to Goddess Laxmi, the Hindu goddess of wealth and prosperity, and her divine consort Lord Vishnu. There is a statue of Lord Shiva with his wife, Goddess Parvati too. The temple structure has carved archways and is surrounded by well-manicured lawns, where visitors can enjoy a moment of quiet meditation.",
      map : "https://goo.gl/maps/N3fTkwm7F1ccLgk98",
    },
    {
      id: 9, 
      image: "assets/Andaman/Religious/Rama Temple.jpg",
      name: "Rama Temple",
      category: "Religious",
      description: "https://www.andaman.gov.in/tourism/tour_travel_agent",
      info : "Shree Rama Temple (Synagogue) is located in South Andaman, Andaman and Nicobar, India. Address of Shree Rama Temple is Lamba Line, Port Blair, Andaman and Nicobar Islands 744103, India.",
      map : "https://www.google.com/search?q=+Rama+Temple+andaman+and+nicobar&tbm=lcl&sxsrf=ALiCzsYlVJqb6N2vp3Jg2NH8ogIwq9_mbA%3A1668168626967&ei=sjtuY6DJOueHz7sPl8iXwA0&ved=0ahUKEwig6r2zjKb7AhXnw3MBHRfkBdgQ4dUDCAk&uact=5&oq=+Rama+Temple+andaman+and+nicobar&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAMyBAgjECc6BQgAEKIEULYDWI0IYKIOaABwAHgBgAHOAYgBiwiSAQUwLjUuMZgBAKABAcABAQ&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[13.048448899999999,92.9787008],[10.6157366,92.5335763]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2",
    },
     {
        id: 10,
        image: "assets/Andaman/Religious/Sri Vettimalai Mutugan Temple.jpg",
        name: "Sri Vetrimalai Murugan Temple",
        category: "Religious",
        description: "https://www.holidify.com/places/andaman-nicobar-islands/sri-vetrimalai-murugan-temple-sightseeing-1254775.html",
        info : "Sri Vetrimalai Murugan Temple is an important pilgrimage site located in Andaman dedicated to Lord Murugan. Idols of Lord Ganesha, Lord Shiva and Goddess Parvati are also placed inside the temple. The edifice is inspired by the Dravidian style of architecture and looks simply amazing and spellbinding.",
        map : "https://goo.gl/maps/9sa2454CPTx4mevg9",
     },
      {
        id: 11,
        image: "assets/Andaman/Religious/Lord Shiva Temple.jpg",
        name: "Lord Shiva Temple",
        category: "Religious",
        description: "https://www.tourmyindia.com/states/andaman/pilgrimage.html",
        info : "Lord Shiva Temple is one the greatest attraction for travellers in Andaman and Nicobar. This is situated in Port Blair.",
        map : "https://www.google.com/search?tbs=lf:1,lf_ui:2&tbm=lcl&sxsrf=ALiCzsa20_SKdjKRzKFkmKkL8x6obuczMg:1668169521078&q=Lord+Shiva+Temple+andaman+and+nicobar+islands&rflfq=1&num=10&rldimm=8812451392991420812#rlfi=hd:;si:8970857435477507782,l,Ci1Mb3JkIFNoaXZhIFRlbXBsZSBhbmRhbWFuIGFuZCBuaWNvYmFyIGlzbGFuZHNI5bjlrvavgIAIWkEQABABEAIYABgBGAIYAxgFGAYiLWxvcmQgc2hpdmEgdGVtcGxlIGFuZGFtYW4gYW5kIG5pY29iYXIgaXNsYW5kc5IBDGhpbmR1X3RlbXBsZaoBGRABKhUiEWxvcmQgc2hpdmEgdGVtcGxlKAA;mv:[[12.834225199999999,94.0211336],[6.6734594000000005,92.4448527]]",
     },
      {
        id: 12,
        image: "assets/Andaman/Wildlife/Landfall Island Wildlife sanctuary.jpg",
        name: "Landfall Island Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.india-tours.com/wildlife/landfall-island-wildlife-sanctuary",
        info : "This area is home to the indigenous aka-chari tribe. This Sanctuary spreads across 29.28 square kilometers and houses a plentitude of wildlife peculiar to this area. Between beautiful blue lagoons and clear sandy beaches the Landfall Island Wildlife Sanctuary promises to satisfy every nature lovers travel cravings.",
        map : "https://www.google.com/search?q=Landfall+Island+Wildlife+sanctuary%2C+Andaman+and+Nicobar+location&sxsrf=ALiCzsZ0GISZ9Hc04R8dSGsnmhuWig0ipQ%3A1668170319380&ei=T0JuY5_uFuW_3LUP14ql-AE&ved=0ahUKEwjf0b7akqb7AhXlH7cAHVdFCR8Q4dUDCA8&uact=5&oq=Landfall+Island+Wildlife+sanctuary%2C+Andaman+and+Nicobar+location&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzoKCAAQRxDWBBCwAzoNCAAQ5AIQ1gQQsAMYAToECCMQJzoFCCEQoAE6BwghEKABEAo6BAghEBU6BAghEApKBAhNGAFKBAhBGABKBAhGGAFQ0wNYtidg8CpoAXAAeACAAcoBiAGnEpIBBjAuMTQuMZgBAKABAcgBDcABAdoBBggBEAEYCQ&sclient=gws-wiz-serp",
     },
      {
        id: 13,
        image: "assets/Andaman/Wildlife/Cuthbert Bay Wildlife sanctuary.jpg",
        name: "Cuthbert Bay Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.seawatersports.com/places/andaman/cuthbert-wildlife-sanctuary-in-andaman",
        info : "Spread across the 5.80 km out of  8 km of Cuthbert bay beach is the nesting place for turtles which is spread up to 600 meters inside the land from the level of high tide.  It is always a pleasure to witness the new life taking form in the world. And Cuthbert bay wildlife sanctuary in Andaman and Nicobar gives you that divine pleasure by allowing you to visit the sanctuary during the nesting period. ",
        map : "https://goo.gl/maps/s5SrWT3VX9jyqo6X8",
      },
      {
        id: 14,
        image: "assets/Andaman/Wildlife/Mahatma Gandhi Marine National Park.jpg",
        name: "Mahatma Gandhi Marine National Park",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g297583-d499993-Reviews-Mahatma_Gandhi_Marine_National_Park-Andaman_and_Nicobar_Islands.html",
        info : "Mahatma Gandhi Marine National Park is famous for being home to an exquisite coral reef, and colorful schools of fishes of every size and shape. Due to the absence of predatory fishes near the beaches and coral reefs, it is a safe place to go scuba diving.",
        map : "https://goo.gl/maps/DQ6dUhtauajCeiSi6",
      },
      {
        id: 15,
        image: "assets/Andaman/Wildlife/Mount Harriet National Park.jpg",
        name: "Mount Harriet National Park",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g297584-d2369429-Reviews-Mount_Harriet_National_Park-Port_Blair_South_Andaman_Island_Andaman_and_Nicobar_I.html",
        info : "The park's well-known faunal species are Andaman wild pigs (an endangered species), saltwater crocodiles, turtles and robber crabs. The park is also a butterfly hotspot. The picture on the back side of ₹ 20 banknote has been taken at the park.",
        map : "https://goo.gl/maps/yWtJobNEi4HBFTpXA",
      },
      {
        id: 16,
        image: "assets/Andaman/Wildlife/Interview island wildlife sanctuary.jpg",
        name: "Interview Island Wildlife sanctuary",
        category: "Wildlife",
        description: "https://www.india-tours.com/wildlife/interview-island-wildlife-sanctuary",
        info : "The Interview Island Wildlife Sanctuary is the largest island sanctuary in the Andaman and Nicobar Islands, and is the main attraction of the Union Territory. The sanctuary was established in 1985 to protect the elephants, along with its exotic flora and fauna to perfectly balance the scenic beauty around.",
        map : "https://goo.gl/maps/nV7Ud3E8j3kCvSLQA",
      },
       {
        id: 17, 
        image: "assets/Andaman/Heritage/Cellular Jail.jpg",
        name: "Cellular Jail",
        category: "Heritage",
        description: "https://southandaman.nic.in/tourist-place/cellular/",
        info : "A massive three storeyed structure of Cellular Jail was constructed to incarcerate political prisoners in isolation and physical hardships in order to suppress freedom struggle against British colonial rulers.",
        map : "https://goo.gl/maps/eHYb9iairkwZDH1y6",
      },
      {
        id: 18,
        image: "assets/Andaman/Heritage/Balidan Vedi.jpg",
        name: "Balidan Vedi",
        category: "Heritage",
        description: "https://www.tourmyindia.com/states/andaman/balidan-vedi.html",
        info : "Balidan Vedi or State Martyr's Memorial, Andaman and Nicobar, On 30th January 1944 unfortunate 44 victims were selected for death sentence. These people were loaded in trucks and taken to a far-off place called Homfrey Gunj which is about 18 kilometers away from Port Blair.",
        map : "https://goo.gl/maps/51VMfsFzkLELWhFD8",
     },
      {
        id: 19,
        image: "assets/Andaman/Heritage/Aberdeen Heritage.jfif",
        name: "Aberdeen Heritage",
        category: "Heritage",
        description: "https://andamanholidays.com/blog/andaman-activities/andaman-heritage-walk/",
        info : "The Heritage Walk is for almost 1 km that includes 9 points that can be covered in an hour. Beginning from Netaji Club Ground, the walk covers places like Clock Tower, Police Temple, Police Masjid, Police Mandir, Supply Barrack Lane, Andaman Club and finally concludes at Development Commissioner's Bungalow.",
        map : "https://goo.gl/maps/iPTRrhgGYixSy9Kt8",
     },
      {
        id: 20,
        image: "assets/Andaman/Heritage/Netaji Flag Hoisting Memorial.jpg",
        name: "Netaji Flag Hosting Memorial",
        category: "Heritage",
        description: "https://www.tripadvisor.in/ShowUserReviews-g7058854-d20945915-r755441793-Netaji_Flag_Hoisting_Memorial-Telangana.html",
        info : "Netaji Subhash Chandra Bose hoisted the Indian flag first time from Port Blair, Andaman and Nicobar Islands. He hoisted the Indian flag first time on 30th December 1943.",
        map : "https://goo.gl/maps/73KVEiX5cWumsVjt9",
     },
      {
        id: 21,
        image: "assets/Andaman/Food/Barbeque Food.jpg",
        name: "Barbeque Food",
        category: "Food",
        info : "The barbeque food is always mouth-watering food for all non-vegan. The trekkers or backpackers enjoy barbeque food from the top of the island, in the middle of the forests or even in the center of the sea. The tourists who have visited the Andaman Islands can realize the real taste of barbeque food from the Andaman Nicobar Island. ",
      },
      {
        id: 22,
        image: "assets/Andaman/Food/Sweet and Sour Lobster.jpg",
        name: "Sweet and Sour Lobster",
        category: "Food",
        info : "Sweet and Sour Chili Sauce Lobster is called Lobster Saus Asam Manis or Lobster Saus Singapura in Andaman. For making this lips smacking delicious lobster, it's not all about techniques. The ingredients is the most important factor. Choose the live lobster if it's available, or at least pick the fresh lobster.",
      },
      {
        id: 23,
        image: "assets/Andaman/Food/Coconut Prawn Curry.jpg",
        name: "Coconut Prawn Curry",
        category: "Food",
        info : "The a creamy coconut milk curry will undoubtedly add a zing to your whole eating experience. This is another delicious dish that is ha highly flavoured curry with an authentic taste. It tastes amazing when it is served with rice.",
      },
      {
        id: 24,
        image: "assets/Andaman/Food/Fish Curry.jpg",
        name: "Fish Curry",
        category: "Food",
        info : "Fish Curry is an amazing dish from Andaman. As we all know, this place being really near to the sea, one can get a lot of options for fish from right there. So, the Seafood lovers need to definitely be attempting this recipe when in Andaman.",
      },
      {
        id: 25, 
        image: "assets/Andaman/Food/Seafood n Jimbaran.jpg",
        name: "Seafood in Jimbaran",
        category: "Food",
        info : "Jimbaran seafood Dine is a place where people enjoy a sensation of eating grilled seafood on the beachside of Jimbaran.",
      },
      {
        id: 26,
        image: "assets/Andaman/Food/Grilled Fish.jpg",
        name: "Grilled Fish",
        category: "Food",
        info : "Grilled Fish, it is another delicious seafood variant in Andaman. Butter, parsley, chili flakes, cloves are the main ingredients of Grilled Fish. The taste of this grilled lobster can’t match with any other seafood of Andaman.",
      },
      
      
  
  ];
  
  export default AndamanNicobarData;


 