const AndhraPradeshData = [
    {
      id: 1, 
      image: "assets/AndhraPradesh/HillStation/Ananthgiri Hills.png",
      name: "Ananthagiri Hills",
      category: "Hill Station",
      description: "https://www.thrillophilia.com/tours/ananthagiri-resort-araku",
      info : "Ananthagiri has a famous temple located in this forested region, which is also the birthplace of Musi River. It is situated at a distance of about 90 km from Hyderabad City and a popular destination for trekking and for those who love adventure.",
      map : "https://goo.gl/maps/wGLWx1Mvt4VdvdUY6",
    },
    {
      id: 2,
      image: "assets/AndhraPradesh/HillStation/Araku Valley.png",
      name: "Araku Valley",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/hotel-listing/?checkin=date_2&checkout=date_3&city=CTAKV&mmPoiTag=POI|Araku%20Valley|POI63196|&roomStayQualifier=2e0e&locusId=CTAKV&country=IN&locusType=city&cmp=SEM|D|DH|G|Neighbourhood|DH_POI_Exact_Locus|CTAKV_POI63196_Araku%20Valley|&ef_id=Cj0KCQiAgribBhDkARIsAASA5bvpUE-AkhJC56XFuRrWqB_Nxv3V8fd0LojNHSCUmyaQ9SgvCkhMbS0aAiMZEALw_wcB:G:s",
      info : "Araku is famous for its coffee plantations surrounded by beautiful gardens, streams, waterfalls and valleys that are covered with lush green forests. ",
      map : "https://goo.gl/maps/KNfphmr1uUx37TWq7",
    },
    {
      id: 3,
      image:"assets/AndhraPradesh/HillStation/Horsley Hills.png",
      name: "Horsley Hills",
      category: "Hill Station",
      description: "https://www.agoda.com/en-in/city/horsley-gb.html?device=c&network=g&adid=579381847593&rand=10686589148949342452&expid=&adpos=&aud=aud-951004860236:kwd-303039959918&site_id=1891440&tag=aad91dd1-8467-4aeb-87ae-b0d8a52cee26&nhakw=1&gclid=Cj0KCQiAgribBhDkARIsAASA5buzLzBgoKVAr2OTXxQu84iQZfrElFF9vcSRzMCPlTfzWED1LL0kdGUaArarEALw_wcB&checkin=2022-11-20&checkout=2022-11-21&adults=1&childs=0&rooms=1&los=1",
      info : "Horsley also called the 'Ooty of Andhra' is one of the most visited hill stations of Andhra Pradesh. It is a perfect blend of the charming, rustic quality of AP and the luxurious setting of the hills. The place is covered with dense forests and varied flora and fauna including 150+ species of birds.",
      map : "https://goo.gl/maps/yWEJXFzp4PB5bvFL9",
    },
    {
      id: 4,
      image: "assets/AndhraPradesh/HillStation/Nallamala Hills.jfif",
      name: "Nallamala Hills",
      category: "Hill Station",
      description: "https://www.outlookindia.com/traveller/ot-getaway-guides/nallamala_hills_the_tranquil_retreat/",
      info : "The forest has a good tiger population, and a part of the forest belongs to the Nagarjunsagar-Srisailam Tiger Reserve. One can often see leopards in these forests.",
      map : "https://goo.gl/maps/hhVL8iWD1GNC4ssm6",
    },
    {
      id: 5,
      image: "assets/AndhraPradesh/HillStation/Papikondalu.png",
      name: "Papikondalu",
      category: "Hill Station",
      description: "https://aptourismrajahmundri.com/",
      info : "Papi kondalu is a lovely place whose scenery resembles the scenery of Kashmir (North India). The beautiful scenery of Papi kondalu, the waterfalls at Munivaatam, and the peaceful atmosphere at this tribal area give a pleasant look and peace to visitors, making it a special attraction for tourists.",
      map : "https://www.google.com/search?tbs=lf:1,lf_ui:14&tbm=lcl&sxsrf=ALiCzsZDSJlrY_2RR_ekgE_zSZQ0IblYKA:1668155250831&q=Papi+kondalu,+Andhra+pradesh&rflfq=1&num=10&ved=2ahUKEwjXtp_J2qX7AhXBjOYKHcIjAfkQtgN6BAgPEAY#rlfi=hd:;si:5072669348729452687,l,ChxQYXBpIGtvbmRhbHUsIEFuZGhyYSBwcmFkZXNoSJCXwZrxgYCACFolEAAQARgCGAMiG3BhcGkga29uZGFsdSBhbmRocmEgcHJhZGVzaJIBDXRyYXZlbF9hZ2VuY3maASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVUlBNblpZVFU5UkVBRaoBFBABKhAiDHBhcGkga29uZGFsdSgA,y,JfewT3ew-CI;mv:[[17.829307699999998,81.9747622],[14.811655400000001,78.65630519999999]]",
    },
    {
      id: 6,
      image: "assets/AndhraPradesh/Fort/Chandragiri Fort.webp",
      name: "Chandragiri Fort",
      category: "Forts",
      description: "https://www.triphobo.com/places/tirupati-india/chandragiri-fort",
      info : "Chandragiri was the fourth capital of Vijayanagar Empire and is most famous for its historical fort built in the 11th century as well as the Raja and Rani Palaces found within it. It was in the year 1646 when the fort was won over by the Golkonda territory and then came under Mysore rule.",
      map : "https://goo.gl/maps/9T4a7TjVVSiMmSPW7",
    },
    {
      id: 7,
      image: "assets/Maharshtra/HillStation/matheran.jpg",
      name: "Gandikota Fort",
      category: "Forts",
      description: "https://www.tripadvisor.in/Attraction_Review-g9596249-d3203584-Reviews-Gandikota_Fort-Gandikota_Kadapa_District_Andhra_Pradesh.html",
      info : "There is a massive fort which is surrounded by natural deep valleys, impassable hills and boulders making it a very secured fort. The fort can be accessed only from one direction. There is Pennar river flowing beside it in the valley which makes it look like a huge canyon.",
      map : "https://goo.gl/maps/7ru5NsumsMCDpBF28",
    },
    {
      id: 8,
      image: "assets/AndhraPradesh/Fort/kurnool fort.jpeg",
      name: "Kurnool Fort",
      category: "Forts",
      description: "https://www.goibibo.com/hotels/hotels-in-kurnool-ct/",
      info : "The town of Kurnool is famous for its mighty caves, temples, and for being a historical hub of India. Although Belum caves will always be very special to my heart, there are some other excellent historical places to visit in this town.",
      map : "https://goo.gl/maps/h2PssUcj8DRAbY6a9",
    },
    {
      id: 9, 
      image: "assets/AndhraPradesh/Fort/Udayagiri Fort.jfif",
      name: "Udayagiri Fort",
      category: "Forts",
      description: "https://xploreall.com/blog/udayagiri-fort-nellore/",
      info : "Inside the walls are the ancient remains of tombs, temples, and palaces. A part of the hill is so precipitous and thus inaccessible, the cliffs being in places nearly 1,000 feet high, and every path up to the fort was commanded by lines of defence forces.",
      map : "https://www.google.com/search?q=udayagiri+fort%2C+andhra+pradesh&tbm=lcl&sxsrf=ALiCzsYno2VO4NA7BaoptwM_agPYMusPcg%3A1668156118571&ei=1gpuY8y7IofB3LUPy_y70AI&oq=udayagiri+fort&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAEYADIECCMQJzIECCMQJzIECCMQJzIFCAAQgAQyBAgAEEMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABFAAWABgwBBoAHAAeACAAekBiAHpAZIBAzItMZgBAMABAQ&sclient=gws-wiz-local#rlfi=hd:;si:17260446536518832036,l,Ch51ZGF5YWdpcmkgZm9ydCwgYW5kaHJhIHByYWRlc2hIqveW0uWAgIAIWisQABABGAAYARgCGAMiHXVkYXlhZ2lyaSBmb3J0IGFuZGhyYSBwcmFkZXNokgENaGlzdG9yaWNfc2l0ZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSWGRFNDNVRFpuUlJBQqoBFhABKhIiDnVkYXlhZ2lyaSBmb3J0KAA,y,RK8sUNfBOsQ;mv:[[14.881669899999999,79.3090258],[14.864427,79.27344269999999]]",
    },
    {
      id: 10, 
      image: "assets/AndhraPradesh/Fort/Vizianagarm Fort.jpg",
      name: "Vizianagaram Fort",
      category: "Forts",
      description: "https://xploreall.com/blog/vizianagaram-fort/",
      info : "Vizianagaram fort is an early 18th-century fort in the city of Vizianagaram in northeastern Andhra Pradesh, South India. It was built by Vijaya Rama Raju, the Maharaja of Vizianagaram in 1713.",
      map : "https://goo.gl/maps/yvuZ6dj8KA8f9gnD7",
    },
    {
      id: 11,
      image: "assets/AndhraPradesh/Religious/Kanaka Durga temple.jfif",
      name: "Kanaka Durga temple",
      category: "Religious",
      description: "https://kanakadurgamma.org/en-in/home",
      info : "It is mentioned in the Hindu scriptures that the deity in the Kanakadurga temple is regarded as 'Swayambhu' or self-manifested, hence considered very powerful. Kanaka Durga worshipped in the temple is Mahalakshmi form of Lakshmi Durga.",
      map : "https://goo.gl/maps/X8yGDNcxSm1eMJb87",
    },
      {
        id: 12,
        image: "assets/AndhraPradesh/Religious/Lepakshi Temple.jfif",
        name: "Lepakshi Temple",
        category: "Religious",
        description: "https://www.holidify.com/places/lepakshi/lepakshi-temple-sightseeing-5156.html",
        info : "The temple is built in the Vijayanagar architectural style and has beautiful sculptures adorning the walls. There is a huge Nandi bull made from a single granite stone. Lepakshi has many murals from the Vijayanagar Era and the famous sculpture of the snake on the Nagalinga.",
        map : "https://www.google.com/search?tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsZfbLn52xN6_Wvcy3MfN4LkWn9iIA:1668156884739&q=Lepakshi+Temple,+Andhra+Pradesh&rflfq=1&num=10&rldimm=15918703609710325167&ved=2ahUKEwjeoK3U4KX7AhXE63MBHfvKCvoQu9QIegQIEBAJ#rlfi=hd:;si:15918703609710325167;mv:[[13.8080541,77.6189998],[13.7909849,77.5954903]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:1",
      },
      {
        id: 13,
        image: "assets/Maharshtra/WildLife/Nagzira.jpg",
        name: "Srikalahasti Temple",
        category: "Religious",
        description: "https://amaragroup.net/sri-kalahasti-rahu-ketu-pooja-timings-booking-benefits-price/",
        info : "Srikalahasti temple, situated 36 km away from Tirupati is famous for its Vayu Lingam (Wind Lingam), one of the Panchabhoota Sthalams, representing wind. The temple is also regarded as Rahu-Ketu kshetra and Dakshina Kailasam.",
        map : "https://goo.gl/maps/rJApad1PsqVq3Q386",
      },
      {
        id: 14,
        image: "assets/AndhraPradesh/Religious/Srisailam.png",
        name: "Srisailam",
        category: "Religious",
        description: "https://myoksha.com/srisailam-temple/",
        info : "Srisailam Sri Mallikarjuna Swamy Temple is one of the 18 Maha Shakti Peetha. The legend of Daksha Yaga and Sati's self-immolation resulted in the emergence of Sri Parvati in the place of Sati Devi and making Shiva a householder. This mythology is the story behind the origin of Shakti Peethas.",
        map : "https://www.google.com/search?q=Srisailam%20Temple%2C%20Andhra%20Pradesh&sxsrf=ALiCzsaWHh9Ax3qaO-WxPMzTW07whxMJ3w:1668157414605&ei=yQ9uY5azOLGW3LUP1cONqAE&ved=2ahUKEwjxzIHR4qX7AhXO0nMBHRbXBeYQvS56BAgJEAE&uact=5&oq=Srisailam+Temple%2C+Andhra+Pradesh&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIGCAAQBxAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yCAgAEAgQHhAKMgYIABAIEB4yBQgAEIYDMgUIABCGAzIFCAAQhgM6CggAEEcQ1gQQsAM6DQgAEOQCENYEELADGAE6BAgjECc6BAguEEM6BQgAEIAEOggIABAHEB4QCjoICAAQCBAHEB46CggAEAgQBxAeEApKBAhNGAFKBAhBGABKBAhGGAFQ6gNYyxhg-yloAXABeACAAf8BiAGTCZIBBTAuNi4xmAEAoAEByAENwAEB2gEGCAEQARgJ&sclient=gws-wiz-serp&tbs=lf:1,lf_ui:2&tbm=lcl&rflfq=1&num=10&rldimm=18151670623180571245&lqi=CiBTcmlzYWlsYW0gVGVtcGxlLCBBbmRocmEgUHJhZGVzaEisj7qmvoKAgAhaMxABEAIQAxgAGAEYAhgDIh9zcmlzYWlsYW0gdGVtcGxlIGFuZGhyYSBwcmFkZXNoKgIIA5IBDGhpbmR1X3RlbXBsZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSTk1UVlFNSFZSUlJBQqoBDhABKgoiBnRlbXBsZSgA&sa=X&rlst=f#rlfi=hd:;si:18151670623180571245,l,CiBTcmlzYWlsYW0gVGVtcGxlLCBBbmRocmEgUHJhZGVzaEisj7qmvoKAgAhaMxABEAIQAxgAGAEYAhgDIh9zcmlzYWlsYW0gdGVtcGxlIGFuZGhyYSBwcmFkZXNoKgIIA5IBDGhpbmR1X3RlbXBsZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSTk1UVlFNSFZSUlJBQqoBDhABKgoiBnRlbXBsZSgA;mv:[[16.0808443,78.87514089999999],[16.0691421,78.8598933]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2",
      },
      {
        id: 15,
        image: "assets/AndhraPradesh/Religious/Tirupati.jpg",
        name: "Tirupati",
        category: "Religious",
        description: "https://tirupatibalaji.ap.gov.in/#/login",
        info : "Tirupati is one of the most visited pilgrimage centre in India, famous for its landmark temples, mostly dedicated to the incarnations of Lord Vishnu. The destination holds several legendary tales to tell, that fascinates tourists from across the world.",
        map : "https://www.google.com/maps/place/Tirumala,+Tirupati,+Andhra+Pradesh/@13.6816399,79.3464804,14z/data=!3m1!4b1!4m5!3m4!1s0x3bb2b562cc4e1291:0x85a1996b4b87bcf6!8m2!3d13.6807357!4d79.3508975",
      },
      {
        id: 16,
        image: "assets/AndhraPradesh/Religious/Varaha Lakshmi Narasimha temple.webp",
        name: "Varaha Lakshmi Narasimha temple",
        category: "Religious",
        description: "https://tms.ap.gov.in/SMCHLM/cnt/accommodation",
        info : "About 16 km from Vizag lies a densely wooded hill known as Simhachalam. The top of this hill is home to an ancient Vishnu temple. Constructed in the Kalinga style of architecture, Lord Varaha Lakshmi Narasimha is the presiding deity of the holy shrine.",
        map : "https://goo.gl/maps/RYv3foX2Ag5tySfx5",
      },
       {
        id: 17, 
        image: "assets/AndhraPradesh/Heritage/Amaravathi.jpg",
        name: "Amaravathi",
        category: "Heritage",
        description: "https://www.makemytrip.com/bus-tickets/amaravathi-city-online-booking.html",
        info : "Amaravati was a seat of Buddhism prior to the rise of Satavahanas, and a stupa and monastery were built there during the reign of Emperor Ashoka (269-232 BC) under Mauryan Empire.",
        map : "https://goo.gl/maps/bDgUWtRUnxFEuPtN9",
      },
      {
        id: 18,
        image: "assets/AndhraPradesh/Heritage/Gandikota.jpg",
        name: "Gandikota",
        category: "Heritage",
        description: "https://campingatgandikota.business.site/?gclid=Cj0KCQiAgribBhDkARIsAASA5bu4coIemsJS1Flh9sCJz23lClbGvJh8U4ooU4IlcF89Z3Hn7oP5dnEaAov-EALw_wcB",
        info : "This small hamlet is more famous for the beautiful gorge at the Pennar river and the Belum caves. Admiring nature's view of these places is just one of the things that take you breath away here.",
        map : "https://goo.gl/maps/rKujRwSKEh3yoFsP7",
      },
      {
        id: 19,
        image: "assets/AndhraPradesh/Heritage/Lepakshi.jpg",
        name: "Lepakshi",
        category: "Heritage",
        description: "https://www.holidify.com/places/lepakshi/lepakshi-temple-sightseeing-5156.html",
        info : "The temple is built in the Vijayanagar architectural style and has beautiful sculptures adorning the walls. There is a huge Nandi bull made from a single granite stone. Lepakshi has many murals from the Vijayanagar Era and the famous sculpture of the snake on the Nagalinga.",
        map : "https://www.google.com/search?tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsZfbLn52xN6_Wvcy3MfN4LkWn9iIA:1668156884739&q=Lepakshi+Temple,+Andhra+Pradesh&rflfq=1&num=10&rldimm=15918703609710325167&ved=2ahUKEwjeoK3U4KX7AhXE63MBHfvKCvoQu9QIegQIEBAJ#rlfi=hd:;si:15918703609710325167;mv:[[13.8080541,77.6189998],[13.7909849,77.5954903]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:1",
      },
      {
        id: 20,
        image: "assets/AndhraPradesh/Heritage/Rajahmundry.jpg",
        name: "Rajahmundry",
        category: "Heritage",
        description: "https://www.booking.com/searchresults.en-gb.html?aid=306395&label=rajahmundry-LHKCglrc40xiXvHvo1ZsWQS392930750366%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-11525605706%3Alp9300569%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YZVcNNsENnH02-pWD53qm9c&sid=c324ae8fc8adac31eeb08de5d87b7a0b&city=-2108662&redirected=1&redir",
        info : "Rajahmundry is a city on the eastern banks of the sacred Godavari River, in the southeast Indian state of Andhra Pradesh. It’s home to the huge, riverside ISKCON Temple complex. North, along the river, Hindu devotees bathe in the Godavari from Saraswati and Pushkar ghats.",
        map : "https://goo.gl/maps/u2ScAujHnuFrDM3x6",
      },
      {
        id: 21,
        image: "assets/AndhraPradesh/Heritage/Undavalli Caves.jpg",
        name: "Undavalli Caves",
        category: "Heritage",
        description: "https://www.yatra.com/indian-monuments/guntur/undavalli-caves",
        info : "Undavalli caves is famous for its four storeyed rock cut temple. On the ground floor, you can see only pillars. On the first floor, you can see many idols such as Ganesha. The second floor is a must visit place.",
        map : "https://goo.gl/maps/qXGUmvhTS9z2xWm67",
      },
      {
        id: 22,
        image: "assets/AndhraPradesh/Beaches/Barua.png",
        name: "Baruva Beach",
        category: "Beaches",
        description: "https://www.viharadarshani.in/2019/07/baruva-beach-haritha-resort-images-price-srikakulam.html",
        info : "At this location, the Mahendratanaya River fuses into the Bay of Bengal. Next, to the beach resort, a lighthouse was built. Baruva Beach is one of Andhra Pradesh’s oldest beaches.",
        map : "https://goo.gl/maps/WfNb2SfExg2yKFCW7",
      },
      {
        id: 23,
        image: "assets/AndhraPradesh/Beaches/Ramkrishna Beach.png",
        name: "Ramakrishna Beach",
        category: "Beaches",
        description: "https://www.booking.com/landmark/in/ramkrishna-beach.en.html?aid=314920;label=ramkrishna-beach-FJdgCmb3QAKTA2sFyG03wwS388474860951:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-30676859099:lp9300569:li:dec:dm:ppccp=UmFuZG9tSVYkc2RlIyh9YZnKoGAh3tLoA_MNQwn0RI8;ws=&gclid=Cj0KCQiAgribBhDkARIsAASA5bs9wW01l7ipz2WLxO8D9qvTCG0QUkLutvG-Y6Limn2vmU7n5GIW1FMaAuajEALw_wcB",
        info : "The Ramakrishna beach is a beautiful spot for relaxation and pleasure is a natural beautic scene. There is an imposing Kali Temple near this beach. The aquarium here is an added attraction. The roaring sounds of sea gives enormous pleasure.",
        map : "https://goo.gl/maps/drM16mta2LB2HvVV9",
      },
      {
        id: 24,
        image: "assets/AndhraPradesh/Beaches/Rushikonda.png",
        name: "Rushikonda Beach",
        category: "Beaches",
        description: "https://www.booking.com/landmark/in/rishikonda-beach.en.html?aid=314920;label=rishikonda-beach-CU4Be_JLINYvYzVnf0mEPgS260534898428:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-412579554212:lp9300569:li:dec:dm:ppccp=UmFuZG9tSVYkc2RlIyh9YZnKoGAh3tLoA_MNQwn0RI8;ws=&gclid=Cj0KCQiAgribBhDkARIsAASA5buVctcRlD6RQSX-8COd98_O2xJpp4x12l_OvwkIAsAHo6D16B4IIJAaAv_7EALw_wcB",
        info : "Rushikonda beach is widely known for its golden sands and tidy waves of Bay of Bengal. Surrounded by green plants, Rushikonda beach looks picture perfect attracting nature lovers in huge numbers.",
        map : "https://goo.gl/maps/6Pk7hS6qgPa7T8216",
      },
      {
        id: 25, 
        image: "assets/AndhraPradesh/Beaches/Valkalapudi.png",
        name: "Valkalapudi Beach",
        category: "Beaches",
        description: "https://www.justdial.com/Kakinada/Hotels-in-Vakalapudi/nct-10255012",
        info : "The NTR Beach at Vakalapudi has turned into one of the major tourist destinations with the Tourism Department giving a complete facelift to the seashore by spending ₹46 crore.",
        map : "https://goo.gl/maps/96WDp34dUZppf5wYA",
      },
      {
        id: 26,
        image: "assets/AndhraPradesh/Beaches/Yarada Beach.png",
        name: "Yarada Beach",
        category: "Beaches",
        description: "https://www.tripadvisor.in/Attraction_Review-g297588-d1921864-Reviews-Yarada_Beach-Visakhapatnam_Visakhapatnam_District_Andhra_Pradesh.html",
        info : "The beach is situated at a distance of 15 km from Visakhapatnam and does not remain very crowded. Since not many people gather here all the time, Yarada Beach is by far one of the safest and cleanliest beaches in India at present. The area is covered with coconut and banana plantations.",
        map : "https://goo.gl/maps/pD2Jh6vkB49gjJE47",
      },
      {
        id: 27,
        image: "assets/Andaman/Wildlife/Interview island wildlife sanctuary.jpg",
        name: "Coringa Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/HotelsNear-g1584832-d5787981-Coringa_Wildlife_Sanctuary-Kakinada_East_Godavari_District_Andhra_Pradesh.html",
        info : "Coringa Wildlife Sanctuary is famous and well-known for its saltwater crocodiles and various salt-tolerant species of flora like Avincinia, Rhizophora and many more.",
        map : "https://goo.gl/maps/YPvZwzDjhQvh878b9",
      },
      {
        id: 28,
        image: "assets/AndhraPradesh/wildlife/kambalakonda wildlife sanctuary.jpg",
        name: "Kambalakonda Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.goibibo.com/destinations/visakhapatnam/places-to-visit-in-visakhapatnam/kambalakonda-wildlife-sanctuary-near-visakhapatnam-4441942092936188574/",
        info : "The most important species found in the area is the Indian leopard. The sanctuary has been under the Andhra Pradesh Forest Department since March 10, 1970. They have now begun making it more suitable for tourism purposes.",
        map : "https://goo.gl/maps/uJz1bERqyKkoQaFk6",
      },
      {
        id: 29,
        image: "assets/AndhraPradesh/wildlife/Rollapadu wildlife sanctuary.jpg",
        name: "Rollapadu Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.trawell.in/andhra/kurnool/rollapadu-wildlife-sanctuary",
        info : "Rollapadu Wildlife Sanctuary known primarily as a habitat of the great Indian bustard, the species has suffered a drastic fall in its numbers in the sanctuary in recent years.",
        map : "https://goo.gl/maps/uA8rBei4GWPnPpjt6",
      },
      {
        id: 30,
        image: "assets/Maharshtra/Heritage/chikhaldara.jpg",
        name: "Sri Venkateswara National Park",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g297587-d3912809-Reviews-Sri_Venkateswara_National_Park-Tirupati_Chittoor_District_Andhra_Pradesh.html",
        info : "Sri Venkateswara Wildlife Sanctuary is 525.97 sq kms and it is declared as Sanctuary on 02-09-1985. Presently there are 82 different species of mammals, birds, reptiles with a total of 1079 wild animals.",
        map : "https://www.google.com/search?tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsZVBqexUGBdkcz989rNqzeihJQNdg:1668161716483&q=sri+venkateswara+national+park+andhra+pradesh&rflfq=1&num=10&ved=2ahUKEwi-mafU8qX7AhUiD7cAHaJ2AnQQtgN6BAgYEAE#rlfi=hd:;si:9323437914369324601,l,Ci1zcmkgdmVua2F0ZXN3YXJhIG5hdGlvbmFsIHBhcmsgYW5kaHJhIHByYWRlc2hIys3Gl4evgIAIWj8QABABEAIQAxgCGAMYBBgFIi1zcmkgdmVua2F0ZXN3YXJhIG5hdGlvbmFsIHBhcmsgYW5kaHJhIHByYWRlc2iSAQ9uYXRpb25hbF9mb3Jlc3SaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUXlNVXRsYkdoQlJSQUKqASYQASoiIh5zcmkgdmVua2F0ZXN3YXJhIG5hdGlvbmFsIHBhcmsoAA,y,w2_b0WHKiY4;mv:[[18.6259296,83.1266502],[12.8983378,78.6433796]]",
      },
      {
        id: 31,
        image: "assets/AndhraPradesh/wildlife/Krishna Wildlife Sanctuary.jpg",
        name: "Krishna Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tourtravelworld.com/india/guntur/krishna-sanctuary.htm",
        info : "The Northern part of the Sanctuary is covered by back waters of Bay of Bengal. They provide appropriate ecosystem and refuge for fish, marine invertebrate, and birds.",
        map : "https://goo.gl/maps/aAHhrVk4L6zCrie4A",
      },
      {
        id: 32,
        image: "assets/AndhraPradesh/Food/Hyderabadi Biryani.jpg",
        name: "Hyderabadi Biryani",
        category: "Food",
        info : "Hyderabadi biryani, also known as Hyderabadi dum biryani, is a style of biryani from Hyderabad, India made with basmati rice and meat. Originating in the kitchens of the Nizam of Hyderabad, it combines elements of Hyderabadi and Mughlai cuisines.",
      },
      {
        id: 33,
        image: "assets/AndhraPradesh/Food/Royalla  Vepudu.jpg",
        name: "Royyala Yeppadu:",
        category: "Food",
        info : "This spicy fried prawn curry is a delicious treat for all the sea-food lovers. After all, who does not love the spicy crunchy prawns",
      },
      {
        id: 34, 
        image: "assets/AndhraPradesh/Food/Pulaasa pulusu.JPG",
        name: "Pulasa Pulusu",
        category: "Food",
        info : "This extremely rare seasonal fish curry is very healthy too. If you visit the coasts of Andhra Pradesh during the right season, do not forget to feast on a plate of the delicious curry. So, when you relax in a beach in Vishakhapatnam, remember to have a feast with Pulasa Pulusu before retiring in an hourly couple friendly hotel in Visakhapatnam.",
      },
      {
        id: 35,
        image: "assets/AndhraPradesh/Food/Pesarattu.jfif",
        name: "Pesarattu",
        category: "Food",
        info : "The Dosa variety prepared with moong dal is a delicious and healthy delight. It is a very unique variety of Dosa, native to the Andhra kitchen. In some varieties, the dosa is cooked with upma stuffing.",
      },
      {
        id: 36,
        image: "assets/AndhraPradesh/Food/Punugulu.jpg",
        name: "Punugulu",
        category: "Food",
        info : "The deep fried idli batter is a delectable crunchy snack. You can also eat it as an appetizer or as a side-dish during a meal. Nevertheless, you cannot miss this delicious food item.",
      },
      {
        id: 37,
        image: "assets/AndhraPradesh/Food/Natu Kodi Pulusu.jpg",
        name: "Natu Kodi Pulusu",
        category: "Food",
        info : "The pepper chicken and Guntur chicken are mouth-wateringly delicious, but the chicken cooked with poppy seeds is very tasty. The poppy seeds add a rich aroma, flavor and texture to the rich and tangy taste of other pickles.",
      },
  ];
  
  export default AndhraPradeshData;


 