const  ArunachalPradeshData = [
    {
      id: 1, 
      image: "assets/ArunachalPradeh/HillStation/Tawang.jpg",
      name: "Tawang",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/tawang-hotels.html",
      info : "Perched at a height of 11,155 ft near the Indo-Bhutan border, Tawang, the beautiful land of the Monpa tribes, is the most famous hill station in Arunachal Pradesh.",
      map : "https://goo.gl/maps/93wvMHfv2pgqaJhw9",
    },
    {
      id: 2,
      image: "assets/ArunachalPradeh/HillStation/Zero Valley.jpg",
      name: "Zero Valley",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/ziro_valley_resorts-details-itanagar.html",
      info : "It is famous for paddy-cum-pisciculture cultivation. The area is renowned for the terrace paddy fields where the unique system of poly-culture and water management is practiced by the local people. Mainly inhabited by the Apatani tribe, the town wears a festive look during festivals celebrated by the Apatani people.",
      map : "https://goo.gl/maps/Y91gr9GvqKYxobCf7",
    },
    {
      id: 3,
      image: "assets/ArunachalPradeh/HillStation/Pasighat.jpg",
      name: "Pasighat",
      category: "Hill Station",
      description: "https://www.tripadvisor.in/Hotels-g2282376-Pasighat_East_Siang_District_Arunachal_Pradesh-Hotels.html",
      info : "Pasighat is the land of the mighty Siang and indigenous hanging bridges. A waterfall graces the mountain cliffs and chills the vicinity.",
      map : "https://goo.gl/maps/cYkN22wWwULz6Kop7",
    },
    {
      id: 4,
      image: "assets/ArunachalPradeh/HillStation/Itanagar.jpg",
      name: "Itanagar",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/itanagar-hotels.html",
      info : "Known for its scenic beauty, Buddhist culture and heritage, the capital of Arunachal Pradesh, Itanagar, offers a perfect experience with its inimitable culture and friendly locals.",
      map : "https://goo.gl/maps/6mwKwjvKn5saGZ5u5",
    },
    {
      id: 5,
      image: "assets/ArunachalPradeh/HillStation/Gorichen Peak.jpg",
      name: "Gorichen Peak",
      category: "Hill Station",
      description: "https://www.tourmyindia.com/states/arunachalpradesh/gorichen-peak.html",
      info : "Gorichen is the highest scalable peak in Arunachal Pradesh, towering at a height of over 21,300 ft above sea level. Because of its elevation, Gorichen remains snowbound throughout the year and has captivated the hearts of many seasoned mountaineers and adventure-loving trekkers.",
      map : "https://goo.gl/maps/L9H8o1ztL1GZFfQDA",
    },
    {
      id: 6,
      image: "assets/ArunachalPradeh/HillStation/Bomdila.jpg",
      name: "Bomdila",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/bomdila-hotels.html?cmp=SEM|D|DH|G|DSA|DH_DSA_Desktop|Hotels|ETA|Regular|&ef_id=YiYd2wALY9yswwBH:20221125183706:s",
      info : "Apart from its religious significance, the monastery is also known for its natural beauty. Stunning vistas that you can see from here are fabulous and breathtaking.",
      map : "https://goo.gl/maps/7Gx6dMUXNnXArjuX9",
    },
    {
      id: 7,
      image: "assets/ArunachalPradeh/Religious/Buddha -Temple.jfif",
      name: "Buddha Temple",
      category: "Religious",
      description: "https://www.tourgenie.com/travel-diaries/travel-blogs/theravada-buddhist-temple",
      info : "Theravada Buddhist Temple is also phenomenal. The peaceful environs of Theravada Buddhist Temple make it one of the most visited attractions of the Itanagar city in Arunachal Pradesh.",
      map : "https://goo.gl/maps/mETBCzMJyfJMGSf56",
    },
    {
      id: 8,
      image: "assets/ArunachalPradeh/Religious/Clilipam.jpg",
      name: "Clilipam",
      category: "Religious",
      description: "https://westkameng.nic.in/tourist-place/chillipam-monastery/",
      info : "Chillipam Gompa, the secluded sanctuary is adorned with some of the region's most magnificent Buddhist art. Monastery is built on a promontory which offers spectacular 270 degree views of the surrounding Eastern Himalayan valleys. ",
      map : "https://goo.gl/maps/eh8J1W5wwD6F3nYV6",
    },
    {
      id: 9, 
      image: "assets/ArunachalPradeh/Religious/Gorsam Chorten.jpg",
      name: "Gorsam Chorten",
      category: "Religious",
      description: "https://www.tripadvisor.in/Attraction_Review-g858483-d10305296-Reviews-Gorsam_Chorten-Tawang_Tawang_District_Arunachal_Pradesh.html",
      info : "he sky looming high stupa about 92 Km from Tawang was constructed by Lama Prathar from Kharman village in Zemithang, in 13th Century A.D.",
      map : "https://goo.gl/maps/e7MZqkmSsjE174u27",
    },
     {
        id: 10,
        image: "assets/ArunachalPradeh/Religious/Parshuram kund.jpg",
        name: "Parshuram kund",
        category: "Religious",
        description: "https://www.tripadvisor.in/HotelsNear-g12379325-d7250940-Parshuram_Kund-Lohit_District_Arunachal_Pradesh.html",
        info : "It is a shrine of all-India importance located in the lower reaches of the Lohit River. Thousands of pilgrims visit the place in winter every year, especially on the Makar Sankranti day for a holy dip in the sacred kund which is believed to wash away one's sins.",
        map : "https://goo.gl/maps/bfp6GgpimrZCyw9S6",
     },
      {
        id: 11,
        image: "assets/ArunachalPradeh/Religious/The Golden Pagoda.jpg",
        name: "The Golden Pagoda",
        category: "Religious",
        description: "https://www.tripadvisor.in/Hotel_Review-g858484-d13007509-Reviews-Golden_Pagoda_Eco_Resort-Namsai_Namsai_District_Arunachal_Pradesh.html",
        info : "Within the golden pagoda is housed a beautiful gilded statue of Buddha which is modelled on the kala Buddha of Nalanda archive. The area also houses a centre for cultural research of the Tai Khampti-singpho tribes, a library and a monastery.",
        map : "https://goo.gl/maps/uKtyMyiGeHWtdVwy6",
     },
      {
        id: 12,
        image: "assets/ArunachalPradeh/Religious/Thupsung Dhargye Ling.jpg",
        name: "Thupsung Dhargye Ling",
        category: "Religious",
        description: "https://www.tripadvisor.in/Attraction_Review-g1486505-d13335850-Reviews-Thupsung_Dhargye_Ling-Dirang_West_Kameng_District_Arunachal_Pradesh.html",
        info : "Thupsung Dhargye Ling is a temple and learning institute for the study of Tibetan Buddhism by laypeople and monks, located in the Himalayan village of Dirang, India. The name, Thupsung Dhargye Ling was given by His Holiness, the Dalai Lama and means: Place of Flourishing of the Buddha's Speech.",
        map : "https://goo.gl/maps/JGz8NqfUNDoDQHTU9",
     },
      {
        id: 13,
        image: "assets/Maharshtra/WildLife/Nagzira.jpg",
        name: "Bhalukpong Fort",
        category: "Fort",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/bhalukpong-fort.html",
        info : "Bhalukpong is a beautiful town in the West Kameng district of Arunachal Pradesh. It is known for its scenic beauty, the Sessa Orchid Sanctuary and the Pakhui Wildlife Sanctuary. It is also famous for adventure sports such as angling, river rafting and others.",
        map : "https://goo.gl/maps/5wt9QaKPxgfQfKck8",
      },
      {
        id: 14,
        image: "assets/ArunachalPradeh/Forts/Bhismaknagar Fort.jpg",
        name: "Bhismaknagar Fort",
        category: "Fort",
        description: "https://www.placeforvacations.com/bhismaknagar-fort-in-arunachal-pradesh",
        info : "The Bhismaknagar Fort is a major sightseeing point in Arunachal Pradesh. The fort was built in the 8th century BC. It is the oldest of all the archaeological sites constructed in the area. This fort in the Dibang Valley district is regarded sacred by the Idu Mishims. It symbolizes the glory of the past. Built with clay bricks and adorned with pottery, the fort was constructed in the 4th century.",
        map : "https://goo.gl/maps/T6ma7fZYs8HfPHb68",
      },
      {
        id: 15,
        image: "assets/ArunachalPradeh/Forts/Ita Fort.jpg",
        name: "Ita Fort",
        category: "Fort",
        description: "https://www.makemytrip.com/hotels/hotel_itafort-details-itanagar.html",
        info : "Ita Fort in Itanagar town is an important historical sites in the state of Arunachal Pradesh, India. The name literally means fort of bricks (brick being called 'Ita' in the Assamese language).",
        map : "https://goo.gl/maps/4xU64NJPGFFUPikh9",
      },
      {
        id: 16,
        image: "assets/ArunachalPradeh/heritage/Bomdila Monastery.jpg",
        name: "Bomdila Monastery",
        category: "Heritage Sites",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/bomdila-monastery.html",
        info : "This little town, set amidst the hills and the valleys in eastern Himalayan ranges, is worth visiting. Most people make a quick stop at Bomdila before moving further into the more popular Tawang and beyond, but Bomdila deserves at least a few days.",
        map : "https://goo.gl/maps/VU4ATdBWPyfgWqfJ8",
      },
       {
        id: 17, 
        image: "assets/ArunachalPradeh/heritage/Jaswant Garh.jpg",
        name: "Jaswant Garh",
        category: "Heritage Sites",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/jaswant-garh-war-memorial.html",
        info : "Jaswant Garh is a famous tourist attraction in Arunachal Pradesh and it is widely visited all year round. Jaswant Garh was famously known as Jaswantgarh War Memorial and this memorial is garland in honor of late Jaswant Singh Rawat. He was an Indian rifleman of 4 Garhwal Rifles, Uttarakhand and for his bravery; Jaswant Rawat was honored by a memorial at the post where he fought the Chinese army.",
        map : "https://goo.gl/maps/4gY7bb8qHa3xSxBs6",
      },
      {
        id: 18,
        image: "assets/ArunachalPradeh/heritage/Malinithan.jpg",
        name: "Malinithan",
        category: "Heritage Sites",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/malinithan.html",
        info : "Malinithan is a restricted monument that contains the ruins of an early mediaeval Hindu temple, making it archaeologically significant. It is near the beautiful town of Likabali in Arunachal Pradesh and is situated in the foothills of the Siang mountains. The temple is on the northern bank of the Brahmaputra river.",
        map : "https://goo.gl/maps/dmwHNw155FCoiWRBA",
     },
      {
        id: 19,
        image: "assets/ArunachalPradeh/heritage/Pangsau Pass.jpg",
        name: "Pangsau Pass",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/Attraction_Review-g297589-d1459807-Reviews-Pangsau_Pass-Arunachal_Pradesh.html",
        info : "The Pangsau Pass, the Indo-Burma (Myanmar) border is just 12 Km away from Nampong where the famous the Lake of no Return can be viewed from the Pass. Nampong and Pangsau Pass were considered to be “Hell gate” or “Hell Pass” due to difficult terrains in the Indo-Burma Patkai mountain Range.",
        map : "https://goo.gl/maps/n29evpas3cdXKjk58",
     },
      {
        id: 20,
        image: "assets/ArunachalPradeh/heritage/Tuting Tehsil.jpg",
        name: "Tuting Tehsil",
        category: "Heritage Sites",
        description: "https://timesofindia.indiatimes.com/travel/things-to-do/a-first-hand-guide-to-the-tuting-singha-trek-in-arunachal-pradesh/articleshow/50349627.cms",
        info : "Tuting is a village Panchayat in Upper Siang district in the north-eastern state of Arunachal Pradesh, India. The Upper Siang District is popular for its natural beauty. It is home to 11 Administrative Circles and has a total population of 33,146.",
        map : "https://goo.gl/maps/cHjyYPnt7ibgEeJn9",
     },
      {
        id: 21,
        image: "assets/ArunachalPradeh/heritage/Bomdila Monastery.jpg",
        name: "Tawang Buddhist Monastery",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/AttractionToursAndTickets-g858483-d2311100-Tawang_Buddhist_Monastery-Tawang_Tawang_District_Arunachal_Pradesh.html",
        info : "The Monastery is the second biggest and oldest in Asia and is known as the Tawang Ganden Namgyal Lhatse i.e., the celestial paradise of divine site chosen by the horse was founded by Merag Lodroe Gyamtso in the year 1680-81. The Dalai Lama gave him a painting of goddess Palden Lhamo to be kept in the monastery.",
        map : "https://goo.gl/maps/GWuwaMcnFJkzPfGy7",
     },
      {
        id: 22,
        image: "assets/ArunachalPradeh/Lakes/Geker Sinying.jpg",
        name: "Geker Sinying",
        category: "Lakes",
        description: "https://www.tripadvisor.in/ShowUserReviews-g946396-d2648877-r743621633-Ganga_Lake-Itanagar_Papum_Pare_District_Arunachal_Pradesh.html",
        info : "Geker Sinying is a lake in Itanagar, the capital of Arunachal Pradesh. It is one of the most popular places in Itanagar. People from all around visit this place as a recreation spot and for the picture perfect view of this lake.",
        map : "https://goo.gl/maps/uhJpyVrkQJscwxkT6",
     },
      {
        id: 23,
        image: "assets/ArunachalPradeh/Lakes/Glow Lake.jpg",
        name: "Glow Lake",
        category: "Lakes",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/glow-lake.html",
        info : "Glow lake, a pristine lake spread over an area of 8 sqkm, is an ideal place for an adventure enthusiast! Falling in the lap of Kamlang Tiger Reserve, it is famous for its rich biodiversity.",
        map : "https://goo.gl/maps/edsYXJ7WC9zEBccj7",
      },
      {
        id: 24,
        image: "assets/ArunachalPradeh/Lakes/Mehao Lake.jpg",
        name: "Mehao Lake",
        category: "Lakes",
        description: "https://www.tripadvisor.in/Attraction_Review-g2295164-d4138908-Reviews-Mehao_Lake-Roing_Lower_Dibang_Valley_Arunachal_Pradesh.html",
        info : "The absolutely clear water of the lake attracts huge number of wild ducks. It is a vast lake covering an area of about 4 sq. km. The surroundings of this lake are extremely rich in flora and fauna.",
        map : "https://goo.gl/maps/wLZPCRWFoEDdqM2f8",
      },
      {
        id: 25, 
        image: "assets/ArunachalPradeh/Lakes/Penga Teng Tso Lake.jpg",
        name: "Penga Teng Tso Lake",
        category: "Lakes",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/pankang-teng-tso-lake.html",
        info : "Penga Teng Tso or PT Tso as it is locally known, is a high altitude lake that is located at around 12,000 feet in the Eastern Himalayas of Arunachal Pradesh. This serene looking lake is located amidst sensational natural beauty with snow capped mountains surrounding it on all sides.",
        map : "https://goo.gl/maps/VEd3p8LQW8Sd4z9r9",
      },
      {
        id: 26,
        image: "assets/ArunachalPradeh/Lakes/Sela Lake.jpg",
        name: "Sela Lake",
        category: "Lakes",
        description: "https://www.tripadvisor.in/AttractionToursAndTickets-g858483-d1307664-Sela_Pass-Tawang_Tawang_District_Arunachal_Pradesh.html",
        info : "Sela Pass is breathtaking place always covered in snow providing some beautiful views of the eastern Himalayan range. The rocky pass is also home to one of Arunachal's most beautiful lakes - the Sela Lake.",
        map : "https://goo.gl/maps/ZqHspgbwsTUwoB4i7",
      },
      {
        id: 27,
        image: "assets/ArunachalPradeh/Lakes/Sungester Lake.jpg",
        name: "Sangestar Lake",
        category: "Lakes",
        description: "https://www.thetourindia.com/sangetsar-lake.php",
        info : "Formed by a flash flood after an earthquake in the year 1950, Madhuri Lake is originally known as Shonga-tser Lake, which is one of the most popular lakes in Tawang, Arunachal Pradesh. The lake was renamed so after the shooting of Bollywood movie Koyla, starring Madhuri Dixit, the beautiful actress.",
        map : "https://goo.gl/maps/FPo8hdR6rZghr9U96",
      },
      {
        id: 28,
        image: "assets/Maharshtra/Heritage/chatrapati shahu museum.jpg",
        name: "Mouling National Park",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/mouling-national-park.html",
        info : "Ornamental plants like foxtail, orchids are abundant in this area. The park has also an impressive area of animals and birds. Many endangered species like takins, snowclouded leopard, golden languor, hornbill, monal scalater, serrow are spotted here.",
        map : "https://goo.gl/maps/XE8zdwCiV3UYgkSf7",
      },
      {
        id: 29,
        image: "assets/Maharshtra/Heritage/chatrapati terminus11.jpg",
        name: "Namdapha National Park",
        category: "Wildlife",
        description: "https://visatoexplore.in/namdapha-national-park-arunachal-pradesh-complete-information/.html",
        info : "It is only park in the World to have the four Feline species of big cat namely the Tiger (Panthera Tigris), Leopard (Panthera Pardus), Snow Leopard (Panthera Uncia) and Clouded Leopard (Neofelis Nebulosa) and numbers of Lesser cats.",
        map : "https://goo.gl/maps/GheZSdyuKAyByctk9",
      },
      {
        id: 30,
        image: "assets/Maharshtra/Heritage/chikhaldara.jpg",
        name: "Dibang Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/dibang-wildlife-sanctuary.html",
        info : "Dibang Wildlife Sanctuary is the largest of all as it is located on 4150 sq km. It is the diversity in wildlife of this sanctuary that attracts wildlife photographers to take unique snaps of the endangered species of animals and plants. You will also get mesmerized by the soothing atmosphere and the lush green vegetation of this sanctuary. If you are looking for camping or trekking, this place is suitable for you.",
        map : "https://goo.gl/maps/D5Epq5bW89pxB3py8",
      },
      {
        id: 31,
        image: "assets/Maharshtra/Heritage/elephanta caves.jpg",
        name: "Pakhui Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g2295096-d3954869-Reviews-Pakke_Wildlife_Sanctuary_and_Tiger_Reserve-Bhalukpong_Sonitpur_District_Assam.html",
        info : "There are around 300 species of birds you can see here. This place is also known as Pakke Tiger Reserve because it is the home of Royal Bengal Tigers. This place is great for having a picnic with your friends and family, surrounded by the natural beauty of perennial rivers and seasonal waterfalls.",
        map : "https://goo.gl/maps/sXjeM3RWZDstUAj3A",
      },
      {
        id: 32,
        image: "assets/Maharshtra/Heritage/gateway of india.jpg",
        name: "Daying Ering Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/daying-ering-wildlife-sanctuary.html",
        info : "Named after Dr. D. Ering, this sanctuary is mainly famous for the migratory birds from Mongolia and Siberia. Twenty five percent of this sanctuary is covered with water bodies; therefore, migratory birds, like wild ducks, waterfowls, storks, etc. find this place appropriate to migrate in each winter season. ",
        map : "https://goo.gl/maps/a7kXR1T6GLKCBYeBA",
      },
      {
        id: 33,
        image: "assets/Maharshtra/Forts/daulatabad.jpg",
        name: "Mehao Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/states/arunachalpradesh/mehao-wildlife-sanctuary.html",
        info : "Once you are here, you will realize that you are in heaven as it is known as the ‘ real ocean of green paradise on earth’. This is a spot for those who seek unspoiled and untouched natural beauty. If you are looking for hardcore adventure, this sanctuary can welcome you warmly. It is the home of numerous species of birds, reptiles, butterflies, fishes, etc. ",
        map : "https://goo.gl/maps/mX6UC6mbviWQTEqj7",
      },
      {
        id: 34, 
        image: "assets/ArunachalPradeh/Food/Lukter.png",
        name: "Lukter",
        category: "Food",
        info : "A roasted beef slice is called Lukter. Sprinkle dry red chilli seeds on it for better taste. It is crisp and goes perfectly well with rice. . If you are visiting Tawang in December and intend to celebrate the New Year, then this snack is perfect for the evening.",
      },
      {
        id: 35,
        image: "assets/ArunachalPradeh/Food/Apong.jpg",
        name: "Apong",
        category: "Food",
        info : "The favourite drink of Arunachal is this rice. It is the most loved drink of the North Eastern state. It is not that strong and is had by people there on every special occasion. It is cheap and easily available.",
      },
      {
        id: 36,
        image: "assets/ArunachalPradeh/Food/Momos.jpg",
        name: "Momos",
        category: "Food",
        info : "Oh, nothing sounds more awesome than this dish when you are in the hills. You can get it with stuffed vegetables or chicken or yak meat. The flavor, the aroma, the ambience around when you devour momos is the perfect picture of a nice trip. You will not find better momos in any other part of India than the North Eastern states.",
      },
      {
        id: 37,
        image: "assets/ArunachalPradeh/Food/Dung Po.jpg",
        name: "Dung Po",
        category: "Food",
        info : "It is beautiful steamed rice. The locals cook it in brass utensils. The rice is placed in leaves so that they don’t spread. They keep one vessel over the other; One has boiling water and the other one has the rice. The aroma of the leaves will make you hungry.",
      },
      {
        id: 38,
        image: "assets/ArunachalPradeh/Food/Laksa Stock.jpg",
        name: "Laksa Stock",
        category: "Food",
        info : "Being a very innovative dish, Laksa Stock is made with coconut milk, noodles, and anything else you want. The people who eat non-veg also add eggs, chicken, etc to it and on the other hand, the vegetarian people add grated cheese, paneer, etc to make it more interesting and delicious.",
      },
      {
        id: 39,
        image: "assets/ArunachalPradeh/Food/Ngatok.jpg",
        name: "Ngatok",
        category: "Food",
        info : "It is a traditional dish which they always make in the old way. They pack fish in leaves, then they cook it on a stone that is hot. Isn’t it unique? Marination of the fish contains all the spices and herbs. Serve it with Dung Po or Apong.",
      },
      {
        id: 40,
        image: "assets/ArunachalPradeh/Food/Smoked Bamboo Meat with Leaf.jpg",
        name: "Smoked Bamboo Meat with Leaf",
        category: "Food",
        info : "It is an ethnic dish which includes roasting meat in a bamboo. Meat is put inside and on large bamboo pieces. Locals keep the meat marinated with spices and herbs and then roast it.",
      },
      
  
  ];
  
  export default ArunachalPradeshData;


 