const AssamData = [
    {
      id: 1, 
      image: "assets/Assam/Hill Station/Siliguri.jpg",
      name: "Siliguri",
      category: "Hill Station",
      description: "https://www.fabhotels.com/blog/places-to-visit-in-siliguri/",
      info : "The picturesque city is endowed with the best of nature, full to the brim with its rolling green tea gardens and the snow-clad Himalayan mountaintops peeking into the horizon at a distance. Owing to its rich wildlife population, tourism in Siliguri is synonymous with its wildlife safari facilities.",
      map : "https://goo.gl/maps/LVgsc4NbcrygCm7WA",
    },
    {
      id: 2,
      image: "assets/Assam/Hill Station/Haflong.jpg",
      name: "Haflong",
      category: "Hill Station",
      description: "https://www.tripadvisor.in/Hotels-g2322205-Haflong_Dima_Hasao_District_Assam-Hotels.html",
      info : "This hill-station becomes your ideal spot for some great fun and adventure. Wrapped in the serenity of nature, this hill station in Assam is decorated with lush greenery, misty hills and panoramic landscapes. Not just natural beauty, but this location is famous for adventure activity options as it offers trekking and paragliding.",
      map : "https://goo.gl/maps/P1KCxjyM3up7McvR8",
    },
    {
      id: 3,
      image: "assets/Maharshtra/HillStation/khandala.jpg",
      name: "Silsako",
      category: "Hill Station",
      description: "https://www.makemytrip.com/hotels/hotel_shoolin_grand-details-guwahati.html",
      info : "Silsako Lake view point is a wetland and lake located at the heart of the Guwahati city and surrounded by villages like Satgaon, Hengrabari and Mathgharia in Kamrup Metropolitan district of Assam.",
      map : "https://goo.gl/maps/T61X9wAhXGtzb3NQ9",
    },
    {
      id: 4,
      image: "assets/Assam/Hill Station/Diphu.jpg",
      name: "Diphu",
      category: "Hill Station",
      description: "https://www.tripadvisor.in/HotelsNear-g2285515-d4142955-Diphu_Station-Diphu_Karbi_Anglong_District_Assam.html",
      info : "Diphu becomes one of the famous hill stations where you can relax and witness the magic of nature.Visit the place and don’t forget to visit the Shiva Mandir, Lokhimon Temple, Deopani Durga Mandir, Khanduli, Amreng and Kohora which are some of the renowned sacred spots and tourist attractions in this beautiful hill-station.",
      map : "https://goo.gl/maps/Wjxxakt1GCEsEWtG6",
    },
    {
      id: 5,
      image: "assets/Assam/Hill Station/Gangtok.jpg",
      name: "Nagarbera Hills",
      category: "Hill Station",
      description: "https://www.stayapart.in/hotels-in-nagarbera/",
      info : "Nagarbera is a village in Kamrup district. It is on south bank of river Brahmaputra and is 90.6 km from Guwahati city. It has a mesmerizing scenic beauty.",
      map : "https://goo.gl/maps/Ubz4Rf9HBDbhTczEA",
    },
    {
      id: 6,
      image: "assets/Assam/Hill Station/-kalimpong.jpg",
      name: "Dhaneshwari Hills",
      category: "Hill Station",
      description: "https://www.booking.com/region/in/assam.en.html?aid=1610833;label=assam-bFlIUFrdwSvtyTSZ_1C7PgS349826178460:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-429532961991:lp9300569:li:dec:dm:ppccp=UmFuZG9tSVYkc2RlIyh9YTiRJUvwM0AZLEcK3RQ9LlA;ws=&gclid=CjwKCAiAyfybBhBKEiwAgtB7fvYK_RpkU_zP6YhwQxEDVtgdHvgZTFBiacU_cydjt-ILMp1pfxyfDhoCXgkQAvD_BwE",
      info : "A perfect collage of lush green hills, sparkling water, and opulent valleys, It is one of the best and most popular hill stations",
      map : "https://goo.gl/maps/62B6hTAhJwqyNWwv6",
    },
    {
      id: 7,
      image: "assets/Assam/Religious/Kadareshwar Temple.jpg",
      name: "Kedareswara Temple",
      category: "Religious",
      description: "https://www.tourmyindia.com/states/assam/kedareswar-temple.html",
      info : "The reigning deity of the temple is the Hindu God, Shiva. This is a well known medieval Shiva temple established in 1753 by the king from Ahom dynasty.  The uniqueness of this temple lies in the fact that it has the rare self originated phallic symbol, or Swayambhu Linga, that too in the Ardhanariswara, or androgynous form..",
      map : "https://goo.gl/maps/AQ5DaGDEWMxZhkwq7",
    },
    {
      id: 8,
      image: "assets/Assam/Religious/kamakhya temple.jfif",
      name: "kamakhya temple",
      category: "Religious",
      description: "https://www.booking.com/landmark/in/kamakhya-temple.en.html?aid=1486641;label=kamakhya-temple-900057259-27-S558116286695:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-1211623140474:lp9300569:li1007745:dec:dm;ws=&gclid=CjwKCAiAyfybBhBKEiwAgtB7flywibBlm3iZhMlnLsI3OypQNfCNiqPyYp3H_mCP_iuGX2Nf3dxZTBoCVwMQAvD_BwE",
      info : "Counted among the most sacred shaktipeethas (devotional shrines where the severed body parts of Goddess Sati fell), the temple is believed to be the place where the womb of the goddess fell.",
      map : "https://goo.gl/maps/BY9EfQtzvoDVuuDz7",
    },
    {
      id: 9, 
      image: "assets/Assam/Religious/Poa Mecca.jfif",
      name: "Poa Mecca",
      category: "Religious",
      description: "https://www.tourmyindia.com/states/assam/powa-mecca.html",
      info : "Poa Macca is a place of pilgrimage for the Muslims and is located at Hajo. It is believed that by offering prayers here the faithfuls gain one fourth of the spiritual enlightenment of what could be gained at Mecca.",
      map : "https://goo.gl/maps/pHffSCbcm8x9B1ZVA",
    },
     {
        id: 10,
        image: "assets/Assam/Religious/Purva Tirupati Balaji Temple.jpg",
        name: "Purva Tirupati Balaji Temple",
        category: "Religious",
        description: "https://www.tripadvisor.in/Attraction_Review-g503692-d7757268-Reviews-Purva_Tirupati_Shri_Balaji_temple-Guwahati_Kamrup_Metropolitan_District_Assam.html",
        info : "This shrine is dedicated to Lord Venkateswara and is considered to be a very holy place for the Hindu pilgrims. The temple has a very unique architectural design and is built over a large area of land.",
        map : "https://goo.gl/maps/73osxNWC4Byfuuo49",
     },
      {
        id: 11,
        image: "assets/Assam/Religious/Shiva Dol Temple.jfif",
        name: "Shiva Dol Temple",
        category: "Religious",
        description: "https://www.goibibo.com/destinations/sibsagar/places-to-visit-in-sibsagar/shivadol-4150318194247874820/",
        info : "The Sivadol or Shiva temple, built in the Shikhara architecture (more specifically Ahom temple architecture), has a central tower which is said to be the tallest Shiva temple tower in India at a height of 104 feet (32 m). The base of the temple measures 195 ft (59 m) in circumference.",
        map : "https://goo.gl/maps/y8dUvMg1iskg5Tw2A",
     },
      {
        id: 12,
        image: "assets/Assam/Religious/Sukreshwar Temple.jpg",
        name: "Sukreshwar Temple",
        category: "Religious",
        description: "https://www.tourmyindia.com/states/assam/sukresvara-temple.html",
        info : "In Assam this temple is located on Itakhulli hill or Sukreswar hill in Guwahati. It too provides visitors with a beautiful view of the Brahmaputra River as the temple is located at the Southern bank of the river. The picturesque view of the river is really breathtaking which gives immense pleasure to the visitors.",
        map : "https://goo.gl/maps/58PHmAA15RR4kqRCA",
     },
      {
        id: 13,
        image: "assets/Assam/Religious/Umananda Temple.jpg",
        name: "Umananda Temple",
        category: "Religious",
        description: "https://www.yatra.com/utilities/temple/umananda-temple-guwahati",
        info : "Umananda Temple is a Shiva temple located at the Peacock Island in the middle of river Brahmaputra. It was built by the Ahom King Gadadhar Singha (1681–1696), who was a devout Shaivaite. It is known as smallest inhabited riverine island in the world.",
        map : "https://goo.gl/maps/iPUr7JoRMFipGXXD8",
      },
      {
        id: 14,
        image: "assets/Assam/Heritage Sites/Charaideo.jpg",
        name: "Charaideo",
        category: "Heritage Sites",
        description: "https://www.yatra.com/indian-monuments/sivasagar/group-of-maidams",
        info : "Even though the capital moved to other places over the course of the 600 years of rule, Charaideo remained the symbol of Ahom power. It is now known for its collection of maidams, tumuli or burial mounds of the Ahom kings and Ahom royalty.",
        map : "https://goo.gl/maps/3KphBghoC74NmEkaA",
      },
      {
        id: 15,
        image: "assets/Assam/Heritage Sites/Kareng Ghar.jpg",
        name: "Kareng Ghar",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/HotelsNear-g2037918-d3733054-Kareng_Ghar_Talatal_Ghar-Sibsagar_Sivsagar_District_Assam.html",
        info : "Kareng Ghar also known as The Garhgaon Palace, is located in Garhgaon 15 kilometres (9.3 mi) from Sivasagar, Assam, India. Of all Ahom ruins, the Kareng Ghar is one of the grandest examples of Ahom architecture. The palace structures were made of wood and stone.",
        map : "https://goo.gl/maps/QBsJjQBY7EYrPhx37",
      },
      {
        id: 16,
        image: "assets/Assam/Heritage Sites/Rang  Ghar.jpg",
        name: "Rang  Ghar",
        category: "Heritage Sites",
        description: "https://www.yatra.com/indian-monuments/sivasagar/ranghar-paviliion",
        info : "The Rang Ghar in Assam is known to be one of the earliest such pavilions of India. This outdoor stadium was constructed between the years of 1744-1751. It was built by the king Pramatta Singha. This a fascinating structure.",
        map : "https://goo.gl/maps/G7wqeiGUenXG26n37",
      },
       {
        id: 17, 
        image: "assets/Assam/Heritage Sites/Satras.png",
        name: "Satras",
        category: "Heritage Sites",
        description: "https://www.tourmyindia.com/states/assam/kamalabari-satra.html",
        info : "The satras consist of a large prayer hall facing a simple shrine, surrounded by dormitories and bathing tanks for monks. The satras also offer guest accommodation where devotees and visitors not only take part in worship of Vishnu and Krishna,but also watch traditional bhaona performances.",
        map : "https://goo.gl/maps/WtR1DZFH63E8L2R8A",
      },
      {
        id: 18,
        image: "assets/Assam/Heritage Sites/Surya Pahar.png",
        name: "Surya Pahar",
        category: "Heritage Sites",
        description: "https://www.expedia.co.in/Sri-Surya-Pahar-Hotels.0-l553248621562263160-0.Travel-Guide-Filter-Hotels",
        info : "Another important significance of Sri Surya Pahar is that it was once a confluence of three religions as evident from the innumerable sculptures and other relics belonging to Hinduism, Buddhism and Jainism.",
        map : "https://goo.gl/maps/ymGMqLLwW6TrSfmE6",
     },
      {
        id: 19,
        image: "assets/Assam/Forts/Garchuk Lachit Garh.webp",
        name: "Garchuk Lachit Garh",
        category: "Forts",
        description: "https://www.touristlink.com/india/garchuk-lachit-garh/overview.html",
        info : "The fort was constructed under the Ahom kingdom during the times of Lachit Borphukan around the year 1670 CE, and stretches from the northern Fatasil hills at Garchuk locality cutting across the National Highway (N.H.)-37 at Garchuk Charali to the southern hills via Pamahi and Moinakhurung. The length of the fortification is about 3 km.",
        map : "https://goo.gl/maps/gauA4PPkDrYmurrM6",
     },
      {
        id: 20,
        image: "assets/Assam/Forts/Garh Doul.jpg",
        name: "Garh Doul",
        category: "Forts",
        description: "https://www.fabhotels.com/blog/india-tourism/assam-tourism/",
        info : " The remains are datable to 7th and 8th century CE. In Hindu mythology, it is the site of the fortress which was built by Banasura to keep his daughter Usha. Usha spent her early age in this place.",
        map : "https://goo.gl/maps/hBrHRn5E9ea1hgS67",
     },
      {
        id: 21,
        image: "assets/Assam/Forts/Kareng Ghar.jpg",
        name: "Kareng Ghar",
        category: "Forts",
        description: "https://www.tripadvisor.in/HotelsNear-g2037918-d3733054-Kareng_Ghar_Talatal_Ghar-Sibsagar_Sivsagar_District_Assam.html",
        info : "Also known as The Garhgaon Palace, is located in Garhgaon 15 kilometres (9.3 mi) from Sivasagar, Assam, India. Of all Ahom ruins, the Kareng Ghar is one of the grandest examples of Ahom architecture. The palace structures were made of wood and stone.",
        map : "https://goo.gl/maps/bftQDaqwtrwMkq2b9",
     },
      {
        id: 22,
        image: "assets/Assam/Forts/Matiabag Palace.jfif",
        name: "Matiabag Palace",
        category: "Forts",
        description: "https://www.tripadvisor.in/SmartDeals-g12440667-Gauripur_Dhubri_District_Assam-Hotel-Deals.html",
        info : "It is a beautiful palace at Matiabag hill and on bank of the Godadhar river. Because of this it is called Matiabag Rajbari. It was used as Hawakhana by the Royal family of Gauripur.",
        map : "https://goo.gl/maps/gp3zs6EUo7paSFrw5",
     },
      {
        id: 23,
        image: "assets/Assam/Forts/Talatal Ghar.jpg",
        name: "Talatal Ghar",
        category: "Forts",
        description: "https://www.tripadvisor.in/HotelsNear-g2037918-d3733054-Kareng_Ghar_Talatal_Ghar-Sibsagar_Sivsagar_District_Assam.html",
        info : "Initially built as an army base, the Talatal Ghar is famous for housing two secret tunnels. It was said to be a stronghold of the Ahoms during wars. The Rangpur Palace is the underground structure within the Talatal Ghar; its sibling the Kareng Palace making up the four floors above ground level.",
        map : "https://goo.gl/maps/254tefC6kgiT7yQX7",
      },
      {
        id: 24,
        image: "assets/Assam/Wildlife/Kaziranga National Park.jpg",
        name: "Kaziranga National Park",
        category: "Wildlife",
        description: "https://www.kaziranganationalparkindia.in/online-kaziranga-safari-booking.html?gclid=CjwKCAiA7IGcBhA8EiwAFfUDsW9II_UODGhaxXOIGsAQuOG4BjQzh7_bQCmTyfogqBA1-AtMVh3rGRoC6vcQAvD_BwE",
        info : "Kaziranga is regarded as one of the finest wildlife refuges in the world. The park's contribution in saving the Indian one-horned rhinoceros from the brink of extinction at the turn of the 20th century to harbouring the single largest population of this species is a spectacular conservation achievement.",
        map : "https://g.page/kaziranga-park-assam?share",
      },
      {
        id: 25, 
        image: "assets/Assam/Wildlife/Borail wildlife sanctuary.jpg",
        name: "Borail wildlife sanctuary",
        category: "Wildlife",
        description: "https://wildtrails.in/borail-wildlife-sanctuary/",
        info : "Borail Wildlife Sanctuary is one of the largest sanctuaries in Assam and is famous for Tropical Moist Evergreen and Semi-Evergreen Forests. Here, you will come across many species of mammals including Chinese pangolin, Flying Fox, Slow Loris, Stump-Tailed Macaque, Rhesus Macaque, Capped langur, Hoolock Gibbon and Himalayan Black Bear among others.",
        map : "https://goo.gl/maps/4UjBN6KwU5Cenocp9",
      },
      {
        id: 26,
        image: "assets/Assam/Wildlife/Amchang wildlife sanctuary.jpg",
        name: "Amchang wildlife sanctuary",
        category: "Wildlife",
        description: "https://www.thrillophilia.com/tours/adventure-day-out-at-amchang-wildlife",
        info : "The Amchang Wildlife Sanctuary is a wildlife sanctuary located on the eastern fringe of Guwahati, Assam, India. The sanctuary is known for hosting rare and endangered birds and animals. Amchang's habitat is dominated by tropical moist deciduous forest with semi-evergreen forest in depressions and river-valleys.",
        map : "https://goo.gl/maps/9fjtsahTk4b5BJnJ8",
      },
      {
        id: 27,
        image: "assets/Assam/Wildlife/Pobitora wildlife sanctuary.jpg",
        name: "Pobitora wildlife sanctuary",
        category: "Wildlife",
        description: "https://nexplore.org/activities/activity_booking.php?activity_id=10",
        info : "Pobitora is mainly famous for its great Indian One-horned rhinoceros. Besides rhinoceros, the other animals are leopard, wild boar, Barking deer, wild buffalo etc. Assam's Pobitora Wildlife Sanctuary is also home to more than 2000 migratory birds and various reptiles. It is also an Important Bird Area.",
        map : "https://goo.gl/maps/GBMeGFSfRM3vTAcD9",
      },
      {
        id: 28,
        image: "assets/Assam/Wildlife/Hoollongapar wildlife-sanctuary.jpg",
        name: "Hoollongapar wildlife sanctuary",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g1155926-d2532219-Reviews-Hoollongapar_Gibbon_Sanctuary-Jorhat_Jorhat_District_Assam.html",
        info : "Hoollongapar Gibbon Sanctuary, (earlier known as the Gibbon Wildlife Sanctuary or Hollongapar Reserve Forest), is a protected region, famous for being home to country's only ape species and only nocturnal primate (of Northeastern India) called the Bengal slow loris.",
        map : "https://goo.gl/maps/2bj9XyKj8rvwMHCr9",
      },
      {
        id: 29,
        image: "assets/Assam/Wildlife/Manas wildlife sanctuary.jpg",
        name: "Manas National Park",
        category: "Wildlife",
        description: "https://www.manasnationalparkonline.in/",
        info : "On a gentle slope in the foothills of the Himalayas, where wooded hills give way to alluvial grasslands and tropical forests, the Manas sanctuary is home to a great variety of wildlife, including many endangered species, such as the tiger, pygmy hog, Indian rhinoceros and Indian elephant.",
        map : "https://goo.gl/maps/NPAfhmHJWn7s1deU6",
      },
      {
        id: 30,
        image: "assets/Assam/Food/Baanhgajor Lagot Kukura.png",
        name: "Baanhgajor Lagot Kukura",
        category: "Food",
        info : "One of the most popular dishes in Assam food cuisine, this is essentially chicken cooked with bamboo shoots and lentil. Try this if you want to experience the unique flavour of bamboo shoots which is mostly uncommon in other dishes.", 
      },
      {
        id: 31,
        image: "assets/Assam/Food/Duck Meat Curry.png",
        name: "Duck Meat Curry",
        category: "Food",
        info : "Duck meat is a dish generally reserved for special occasions. If cooked properly, the dish can blow you away thanks to the use of whole spices. It is generally cooked with Ash Gourd but one can also cook it sesame, pumpkin, lentil and more.", 
      },
      {
        id: 32,
        image: "assets/Assam/Food/Khaar.jpg",
        name: "Khaar",
        category: "Food",
        info : "This meat delicacy is made from the main ingredient khaar on which it is named and also has raw papaya, pulses, and taro. The preparation also involves filtering all of the above through dried banana leaves for its distinct signature flavour. ", 
      },
      {
        id: 33,
        image: "assets/Assam/Food/Masor Tenga.png",
        name: "Masor Tenga",
        category: "Food",
        info : "This tangy curry is one of the most popular food in Assam. The fish is slow cooked with a broth made from outenga, tomatoes, and lemon and offers an extremely tangy refreshing flavour once done. This is one dish every Assamese definitely loves. ", 
      },
      {
        id: 34,
        image: "assets/Assam/Food/Pura.jpg",
        name: "Pura",
        category: "Food",
        info : "Any sort of grilled or roasted vegetable in the Assamese cuisine is known as Pura. It can refer to a meat or vegetable dish. There are various types of such dishes available in the cuisine which is just as popular as the other dishes.", 
      },
      {
        id: 35,
        image: "assets/Assam/Food/Thekera Tenga Hoite Maas.png",
        name: "Thekera Tenga Hoite Maas",
        category: "Food",
        info : "This is a fish dish which is prepared with certain local ingredients. Catfish is used in the preparation of this dish, which is usually sour. Mustard is an essential part of this dish without which this dish is truly incomplete.", 
      },
      
  ];
  
  export default AssamData;


 