const BiharData = [
    {
      id: 1, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: "Brahmayoni Hill",
      category: "Hill Station",
      description: "https://www.cleartrip.com/hotels/india/gaya/landmark/brahmayoni-hill/",
      info : "Brahmayoni is a sacred hill near Gaya in Bihar, which is mentioned in Mahabharata and Buddhist records. Devotees who wish to visit this temple must go through a grueling climb of 424 high stone steps to reach the top of the hill, atop which lies this temple.",
      map : "https://goo.gl/maps/jwCvoJwQ3HAPKKjq5",
    },
    {
      id: 2,
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: "Ramshila Hill",
      category: "Hill Station",
      description: "https://www.rome2rio.com/s/Ramshila-Hill",
      info : "Ramshila Hill situated on the south-east side of Gaya is considered to be the most sacred place as it is believed that Lord Rama had offered 'pinda' on the hill. The name of the hill is associated with Lord Rama.",
      map : "https://goo.gl/maps/UQrevBJLTCk55x9MA",
    },
    {
      id: 3,
      image: "assets/Maharshtra/HillStation/khandala.jpg",
      name: "Pretshila Hill",
      category: "Hill Station",
      description: "https://timesofindia.indiatimes.com/travel/destinations/pretshila-hill/articleshow/52430383.cms",
      info : "Pretshila Hill (meaning Hill of Ghost), around 8 km north-west of Gaya, is a revered place for Hindus where they do pind daan (a religious ritual performed for the peace of the departed souls). On top of the hill lies a temple dedicated to Lord Yama, who as per Hindu mythology is the God of Death.",
      map : "https://goo.gl/maps/PdHbMEMwTQEYdMhQ6",
    },
    {
      id: 4,
      image: "assets/Maharshtra/HillStation/lavasa.jpg",
      name: "Pragbodhi Hill",
      category: "Hill Station",
      description: "https://www.tripadvisor.com/ShowUserReviews-g424922-d3187549-r337958339-Dungeswari_Hills-Bodh_Gaya_Gaya_District_Bihar.html",
      info : "Around 7 km from Bodh Gaya, on a hill, is located Pragbodhi (meaning prior to enlightenment). It is believed that Lord Buddha spent seven years living an austere life in a cave in this hill before he attained enlightenment. His belief during his stay was that one can find the truth through asceticism.",
      map : "https://goo.gl/maps/j7v9edmaukHomG9v5",
    },
    {
      id: 5,
      image: "assets/Maharshtra/HillStation/mahabaleshwar.jpg",
      name: "Gurpa Peak",
      category: "Hill Station",
      description: "https://tourism.bihar.gov.in/en/destinations/gaya/gurpa-hill",
      info : "There is a temple named Gurupada on Gurpa hill which is assumed to have footprints of “Lord Vishnu”. This place has gained popularity among the pilgrims of Buddhism and Hinduism. From the top of the Gurpa peak, one can get a breathtaking view of the surrounding countryside. It is an ideal place for meditation.",
      map : "https://goo.gl/maps/JLGVBSrzjFoW4pZM9",
    },
    {
      id: 6,
      image: "assets/Bihar/Religious/Mahabodhi Temple.jpg",
      name: "Mahabodhi Temple",
      category: "Religious",
      description: "https://www.makemytrip.com/hotels/hotels-in-near_mahabodhi_temple-bodhgaya.html",
      info : "Mahabodhi Temple Complex is of great relevance as it marks the most important event in the life of Lord Buddha, the moment when Prince Siddhartha attained Enlightenment and became Buddha, an event that shaped human thought and belief.",
      map : "https://goo.gl/maps/SBsdTNmwzw7R7vaf9",
    },
    {
      id: 7,
      image: "assets/Bihar/Religious/Mithila Shakti Peeth.jpg",
      name: "Mithila Shakti Peeth",
      category: "Religious",
      description: "https://renghaholidays.com/packages/757/Mithila%20Janakpur,%20Mithila%20Sakthi%20Peedam,Bihar%2051%20Sakthi%20Peedangal",
      info : "Mithila Shakti Peeth is one of the most revered temples in Bihar. Mythologies suggest that it is one of the 52 legendary Shakti Peethas as Devi Sati's left shoulder (Vama Skandha) fell here. Hindu devotees come here in large numbers seeking fulfillment of worldly desires.",
      map : "https://goo.gl/maps/CW2opu8YM1FPskmS6",
    },
    {
      id: 8,
      image: "assets/Bihar/Religious/Pathar ki masjid.jpg",
      name: "Pathar ki masjid",
      category: "Religious",
      description: "https://www.travelmyglobe.com/Destination/India/Patna/Pathar-ki-Masjid-Patna",
      info : "Parwez Shah, the son of Mughal emperor Jahangir (Jehangir), built Pathar Ki Masjid on the banks of River Ganga when he was the governor of Bihar. Literally translating into stone mosque, it is widely considered to be one of the few remaining sites displaying Mughal architecture in the city.",
      map : "https://goo.gl/maps/Le9VVtYuRbRvTvXD6",
    },
    {
      id: 9, 
      image: "assets/Bihar/Religious/Patna Sahib Gurudwara.jpg",
      name: "Patna Sahib Gurudwara",
      category: "Religious",
      description: "https://www.thrillophilia.com/tours/gurudwara-tour-in-patna",
      info : "Takht Sri Patna Sahib also known as Harmandir Sahib, is a Gurdwara in the neighbourhood of Patna Sahib, India. It was to commemorate the birthplace of Guru Gobind Singh, the tenth Guru of the Sikhs on December 1666.",
      map : "https://goo.gl/maps/No5eHiX7SSRwKMEn6",
    },
     {
        id: 10,
        image: "assets/Bihar/Religious/Rajgir Temple.jpg",
        category: "Religious",
        description: "https://www.booking.com/city/in/rajgir.en-gb.html",
        info : "It was the birthplace of the 20th Jain Tirthankar Munisuvrata, and is closely associated with the Mahavira and Gautama Buddha. Both Mahavira and Buddha taught their beliefs in Rajgir during the 6th and 5th century BC, and the Buddha was offered a forest monastery here by the king Bimbisara.",
        map : "https://goo.gl/maps/3RHYuhbVDEJrmxbw5",
     },
      {
        id: 11,
        image: "assets/Bihar/Religious/Vishnupad Temple.jpeg",
        name: "Vishnupad Temple",
        category: "Religious",
        description: "https://tourism.bihar.gov.in/en/destinations/gaya/vishnupad-temple",
        info : "Vishnupad Mandir is called so as it is believed to feature a 40-cm-long footprint of Lord Vishnu in a basalt rock. As the story goes, Lord Vishnu killed demon Gayasur at this place by stamping his foot on his chest. After Lord Vishnu pushed the demon under the earth with his foot, his footprint was retained in a rock.",
        map : "https://goo.gl/maps/yXfz8SH8Uj7zWZQ27",
     },
      {
        id: 12,
        image: "assets/Bihar/Forts/Buxar Fort.jpg",
        name: "Buxar Fort",
        category: "Fort",
        description: "https://in.hotels.com/de10664122/book-near-buxar-fort-buxar-india-hotel-rooms/",
        info : "Buxar is famous since the epic period for being the seats of eminent saints, battlefield of Gods and Demons as per Puranas and a combat zone between foreign invasion and countrymen in modern history.",
        map : "https://goo.gl/maps/gaP4CgzhiCY3VzNr8",
     },
      {
        id: 13,
        image: "assets/Bihar/Forts/Darbhanga Fort.jpg",
        name: "Darbhanga Fort",
        category: "Fort",
        description: "https://www.triphobo.com/places/darbhanga-india/darbhanga-fort",
        info : "Darbhanga Fort is also called Ram Bagh Fort, because it is situated in Rambagh Palace inside the fort. Rambagh campus is surrounded by walls and spreads in about 85 acres of land.it is very beautiful and big fort in Darbhanga district of bihar.",
        map : "https://goo.gl/maps/47fjw4eVARBRrLVh8",
      },
      {
        id: 14,
        image: "assets/Bihar/Forts/Jagdishpur Fort.jpg",
        name: "Jagdishpur Fort",
        category: "Fort",
        description: "https://tourism.bihar.gov.in/en/destinations/bhojpur/jagdishpur-fort",
        info : "The fort is ancient as well as historic and is known to be the residence of foremost freedom fighter, Babu Veer Kunwar Singh. It is a double-storied massive building and two big tanks facing the front. A big statue of Babu Veer Kunwar Singh is cemented in front of the main building.",
        map : "https://goo.gl/maps/2AKJ47f3cRFCfu6t8",
      },
      {
        id: 15,
        image: "assets/Bihar/Forts/Jalagarh Fort.png",
        name: "Jalagarh Fort",
        category: "Fort",
        description: "https://www.makemytrip.com/bus-tickets/jagdishpur_bihar-city-online-booking.html",
        info : "Jalalgarh Fort is an almost 300 years old ruined fort located at 20 km north of Purnia, Bihar, India. The fort was built by Syed Muhammed Jalaluddin Khan. It is also believed by some people that fort was built by Saif Khan, the nawab of Purnia in 1722. Experts claims, this fort is an embodiment of the beauty of both Hindu and Islamic architecture.",
        map : "https://goo.gl/maps/qhdGU6VMqjWaEEVf7",
      },
      {
        id: 16,
        image: "assets/Bihar/Forts/Munger Fort.jfif",
        name: "Munger Fort",
        category: "Fort",
        description: "https://www.yatra.com/hotels/hotels-in-munger",
        info : "Munger is known for Sita Manpatthar (Sita charan) Sitacharan temple situated on a boulder in the middle of the Ganges in Munger (Mithilanchal) is the main center of public faith regarding Chhath festival.",
        map : "https://goo.gl/maps/MkQHdAwPKECndUAF6",
      },
       {
        id: 17, 
        image: "assets/Bihar/Forts/Shergarh Fort.jpg",
        name: "Shergarh Fort",
        category: "Fort",
        description: "https://rohtas.nic.in/tourist-place/sher-garh-fort/",
        info : "The fort was built between 1540 to 1545 by Emperor Sher Shah Suri. In the 16th century the fort was known as Bhurkuda Qila. It is also claimed that the fort was built by Kharwar rulers and subsequently captured by Sher Shah Suri in 1530.",
        map : "https://goo.gl/maps/6h7bQkcc99Kb6BKt8",
      },
      {
        id: 18,
        image: "assets/Bihar/Heritage Sites/Barabar Caves.jfif",
        name: "Barabar Caves",
        category: "Heritage Sites",
        description: "https://www.thrillophilia.com/tours/barabar-caves-tour-from-patna",
        info : "Barabar caves can be dated back to the 3rd Century BC to the times of the Mauryan Empire (322 BCE -185 BCE). Barabar Caves were constructed by emperor Ashoka for the use of Ajivaka ascetics, Hence, it is renowned as the place of origin of the Ajivika sect. Barabar hill caves are Buddhist caves.",
        map : "https://goo.gl/maps/kqfUKmbowF3rfGdm7",
     },
      {
        id: 19,
        image: "assets/Bihar/Heritage Sites/Bodhgaya.jpg",
        name: "Bodhgaya",
        category: "Heritage Sites",
        description: "https://www.makemytrip.com/hotels/bodhgaya-hotels.html",
        info : "Considered one of the most important Buddhist pilgrimage sites, it's dominated by the ancient brick Mahabodhi Temple Complex, built to mark the site where the Buddha attained enlightenment beneath a sacred Bodhi Tree.",
        map : "https://goo.gl/maps/FgHhjiNQXy57couw8",
     },
      {
        id: 20,
        image: "assets/Bihar/Heritage Sites/Golghar.jpg",
        name: "Golghar",
        category: "Heritage Sites",
        description: "https://tourism.bihar.gov.in/en/destinations/patna/gol-ghar",
        info : "Golghar, an enormous granary, was built by Captain John Garstin for British army in 1786, after the terrible impact of 1770 famine. The winding stairway around this monument offers a brilliant view of the city and the Ganga flowing nearby. ",
        map : "https://goo.gl/maps/YUiemcHqSY16PsEU6",
     },
      {
        id: 21,
        image: "assets/Bihar/Heritage Sites/Maner Sharif.jfif",
        name: "Maner Sharif",
        category: "Heritage Sites",
        description: "https://tourism.bihar.gov.in/en/destinations/patna/maner-sharif",
        info : "Maner Sharif shelters two very popular Muslim tombs: One of the tombs is of Sufi saint Makhdoom Yahya Maneri, known as the Bari Dargah (the great shrine). The other one is of Makhdum Shah Daulat, popularly called Chhoti Dargah (the small shrine).",
        map : "https://goo.gl/maps/SJYx4ZvPacK4of1a9",
     },
      {
        id: 22,
        image: "assets/Bihar/Heritage Sites/Navlakha Palace.jpg",
        name: "Navlakha Palace",
        category: "Heritage Sites",
        description: "https://www.holidify.com/state/bihar/navlakha-palace-sightseeing-1257285.html",
        info : "Navlakha Palace, also known as Rajnagar Palace, is an ancient royal palace which is a popular heritage building in the region. Built by Maharaja Rameshwar Singh, the palace formerly boasted of well paved gardens, tinkering ponds, temple complexes and the like.",
        map : "https://goo.gl/maps/mMWmeez6NLJo85ut9",
     },
      {
        id: 23,
        image: "assets/Bihar/Heritage Sites/Takth Shri Patna Sahib.jpeg",
        name: "Takhat Shri Patna Sahib",
        category: "Heritage Sites",
        description: "https://tourism.bihar.gov.in/en/destinations/patna/takht-shri-harmandir-sahib",
        info : "A symbol of valour and fearlessness, the shrine inspires great piety in pilgrims and holds pride of place in the glorious heritage of Patna City. Takhat Sri Harimandir Sahib Ji also known as Patna Sahib.",
        map : "https://goo.gl/maps/GfUQgYko1ZzxCUDK7",
      },
      {
        id: 24,
        image: "assets/Bihar/Heritage Sites/Tomb of Sher Shah Suri.jpeg",
        name: "Tomb of Sher Shah Suri",
        category: "Heritage Sites",
        description: "https://www.makemytrip.com/hotels/sasaram-hotels-near-sher_shah_suri_tomb.html",
        info : "The tomb was built in memory of Emperor Sher Shah Suri, a Pathan from Bihar who defeated the Mughal Empire and founded the Suri Empire in northern India. He died in an accidental gunpowder explosion in the fort of Kalinjar on 13 May 1545 AD.",
        map : "https://goo.gl/maps/LACxLrY8Rfj8VdB99",
      },
      {
        id: 25, 
        image: "assets/Bihar/Wildlife/Bhimbandh Wildlife.jpeg",
        name: "Bhimbandh Wildlife",
        category: "Wildlife",
        description: "https://tourism.bihar.gov.in/en/destinations/munger/bheembandh-sanctuary",
        info : "The area is famous for its hot springs, in the valleys and at the foothills including springs at Bhimbandh, Sita Kund and Rishi Kund. Of these, the Bhimbandh springs are the hottest, with a temperature of 52°C to 65°C, and provide ample opportunities for the exploration of geothermal energy potential.",
        map : "https://goo.gl/maps/UnpZ69WSXjQG8B7t9",
      },
      {
        id: 26,
        image: "assets/Bihar/Wildlife/Kaimur Wildlife Sanctuary.jpg",
        name: "Kaimur Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.india-tours.com/wildlife/kaimur-wildlife-sanctuary",
        info : " It is the largest wildlife reserve spread out at the Bihar-Uttar Pradesh border. Apart from its wildlife and vegetation, this sanctuary is famous for its lakes as waterfalls too. Along with this, this reserve containsrock arts, caves of ancient historic times, and a collection of antique fossils.",
        map : "https://goo.gl/maps/Fk4ZmBJrgNVHoGYE6",
      },
      {
        id: 27,
        image: "assets/Bihar/Wildlife/Kanvar Lake Bird Sanctuary.webp",
        name: "Kanvar Lake Bird Sanctuary",
        category: "Wildlife",
        description: "https://tourism.bihar.gov.in/en/destinations/begusarai/kanvar-lake",
        info : "This lake draws water from the confluence of the Gandak, the Bia and the Kareh river – is situated near Manjhaul, 22 km northwest of Begusarai, the district headquarters. The verdant surrounding with plenty of aquatic vegetation around the lake attracts thousands of birds during the winter season.",
        map : "https://goo.gl/maps/WFGjQwoqcDbjiBpc9",
      },
      {
        id: 28,
        image: "assets/Bihar/Wildlife/Nagi Dm Sanctuary.jpg",
        name: "Nagi Dam Sanctuary",
        category: "Wildlife",
        description: "https://www.hindustantimes.com/cities/patna-news/1st-bird-festival-at-nagi-nakti-bird-sanctuaries-in-bihar-to-start-from-january-101610613205676.html",
        info : "Nagi-Nakti bird sanctuary has been selected for this event because of its uniqueness. Apart from the dense deciduous forests, moram land and variety of birds and animals, there’s unique rock formation in the area.",
        map : "https://goo.gl/maps/GXNrSsKJTiuoKYzn7",
      },
      {
        id: 29,
        image: "assets/Bihar/Wildlife/Pant Wildlife Sanctuary.jpg",
        name: "Pant Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.joonsquare.com/zoo-and-wildlife-sanctuary/pant-wildlife-sanctuary-nalanda",
        info : "The sanctuary has substantial faunal diversity with 28 species of large mammals, 183 species of birds, 39 species of reptiles, 11 species of amphibians, 13 species of fish and 51 species of butterfly, many of whom are threatened.",
        map : "https://goo.gl/maps/wWowSXSU6afRoAJZ9",
      },
      {
        id: 30,
        image: "assets/Bihar/Wildlife/Kaimur Wildlife Sanctuary.jpg",
        name: "Valmiki National Park",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Hotel_Review-g2294718-d6208756-Reviews-Valmiki_Tiger_Resort-Valmiki_National_Park_Bihar.html",
        info : "The Valmiki National Park is a tiger reserve in the West Champaran district of Bihar. This reserve surrounds the Gangetic plains biogeographic zone. The park is home to nearly 200+ bird species and various exotic and endangered animals, making it an ideal tourist spot.",
        map : "https://goo.gl/maps/vBD7a51xdpVUZ71A6",
      },
      {
        id: 31,
        image: "assets/Bihar/Food/Chicken Korma.png",
        name: "Chicken Korma",
        category: "Food",
        info : "Infusion of freshly grounded spices and flavor of mustard oil gives it a distinct aroma that instantly tantalizes the taste buds. Chicken Korma in Bihar is unique in flavor and aroma, it is definitely the most delectable dish that everyone must try.",
      },
      {
        id: 32,
        image: "assets/Bihar/Food/Dal Pitha.png",
        name: "Dal Pitha",
        category: "Food",
        info : "Dal Pitha of Bihar has rice flour covering that certainly is a good replacement for maida, and stuffed with spicy lentil to add a distinct flavour. These steamed Pithas are truly divine.",
      },
      {
        id: 33,
        image: "assets/Bihar/Food/Kadhi Badi.png",
        name: "Kadhi Badi",
        category: "Food",
        info : "Kadhi Badi in Bihar has its unique flavor that is distinct from all other variants of Kadhi. The soothing sour curd preparation of Bihar is savored by all in the routine as well as is prepared on all the auspicious occasions such as Chhath puja in Bihar.",
      },
      {
        id: 34, 
        image: "assets/Bihar/Food/Khaja.png",
        name: "Khaja",
        category: "Food",
        info : "Khaja is a savory which has been a part of Bihar for 2000 years. This crispy dessert is similar to Baklava. Khaja is a famous sweet dish of Bihar that is made of multiple layers and has a wafery crunch. It melts in the mouth instantly and is super tasty.",
      },
      {
        id: 35,
        image: "assets/Bihar/Food/Litti  Chokha.png",
        name: "Litti  Chokha",
        category: "Food",
        info : "The traditional recipe of Litti is as old as the Magadha Kingdom that has gained popularity due to its good shelf life and the technique of preparation which requires fewer resources. Healthy and rich in protein, Litti is a smoky flavored ball of wheat, filled with Sattu that is roasted on a coal fire.",
      },
      {
        id: 36,
        image: "assets/Bihar/Food/Malpua.png",
        name: "Malpua",
        category: "Food",
        info : "Bihar is a delightful place for people who relish sweets and desserts and Malpua is a dessert that local folks can swear by. The pancakes made of flour, milk and mashed bananas that are deep-fried and dunked in sugar syrup are a mandatory dish in all the feasts and fasts of the state.",
      },
      {
        id: 37,
        image: "assets/Bihar/Food/Mutton Kebabs.png",
        name: "Mutton Kebabs",
        category: "Food",
        info : "Mutton Kebabs in Bihar are a blend of mild spices, meat fillets, and raw papaya infused with mustard oil. The smoky flavor and tenderness of Kebabs are so heavenly and luscious, trust me, you will ask for more. ",
      },
      
  ];
  
  export default BiharData;


 