const ChhattisgarhData = [
    {
      id: 1, 
      image: "assets/Chhattisgarh/Religious/Bambleshwari Temple.jpg",
      name: "Bambleshwari Temple",
      category: "Religious",
      description: "https://www.readermaster.com/dongargarh-ropeway-ticket-booking-online/",
      info : "The Maa Bamleshwari Devi Temple, situated on a 1,600 feet high hilltop, is a popular landmark. It is of great spiritual importance and several legends are associated with this shrine too.",
      map : "https://goo.gl/maps/N7nBMWKUAPeH4gWs7",
    },
    {
      id: 2,
      image: "assets/Chhattisgarh/Religious/Bhoramdeo Temple.jpg",
      name: "Bhoramdeo Temple",
      category: "Religious",
      description: "https://www.tripadvisor.in/Hotel_Review-g1798392-d2040516-Reviews-Bhoramdeo_Jungle_Retreat-Kawardha_Kabirdham_District_Chhattisgarh.html",
      info : "This temple is dedicated to Lord Shiva. The temple is artificially situated between the mountain ranges, it was built during the period from 7th to 11th century. There is a glimpse of the Khajuraho temple in the temple here, hence this temple is also called “Khajuraho of Chhattisgarh”.",
      map : "https://goo.gl/maps/HNbyW1v4JjfeYHxV6",
    },
    {
      id: 3,
      image: "assets/Chhattisgarh/Religious/Dudhdhari Temple.jpg",
      name: "Dudhadhari Temple",
      category: "Religious",
      description: "https://www.makemytrip.com/hotels/poi-homestays-near-dudhadhari_temple-raipur_chhattisgarh.html",
      info : "A Hindu temple dedicated to Lord Rama, Dudhadhari temple boasts original Ramayana-era sculptures, making it one of the rarest of its kind in the country. Built by Kalchuri ruler Jait Singh in the 17th century, the structure's outer walls feature exquisite sculptures related to Lord Rama.",
      map : "https://goo.gl/maps/xiJg95x3AQDkFWd86",
    },
    {
      id: 4,
      image: "assets/Chhattisgarh/Religious/Laxman Temple.jpg",
      name: "Laxman Temple",
      category: "Religious",
      description: "https://www.yatra.com/indian-monuments/mahasamund/laxman-temple-sirpur",
      info : "Laxman Temple in Sirpur is one of the most famous structures in the city. It is believed to be one of the best examples of brick temples in India and is dedicated to Lord Vishnu. The intricate carvings on the exterior of the temple make it special.",
      map : "https://goo.gl/maps/6zT8poY2q6NPPaFK6",
    },
    {
      id: 5,
      image: "assets/Chhattisgarh/Religious/Mahamaya Temple.jpg",
      name: "Mahamaya Temple",
      category: "Religious",
      description: "https://mahamayaratanpur.com/accomodation/",
      info : "Mahamaya Temple is a temple dedicated to Goddess Durga, Mahalaksmi located at Ratanpur of Bilaspur district in Chhattisgarh, India and is one of the 52 Shakti Peethas, shrines of Shakti, the divine feminine, spread across India.",
      map : "https://goo.gl/maps/9jKrVBjS6vfwgKwN9",
    },
    {
      id: 6,
      image: "assets/Chhattisgarh/Religious/Shivrinarayan Temple.jpeg",
      name: "Shivrinarayan Temple",
      category: "Religious",
      description: "https://www.makemytrip.com/hotels/shivrinarayan-hotels.html",
      info : "Shivrinarayan is the place where Shabri tasted the berry fruits for their sweetness to be given to Lord Rama. Ram Van Gaman Path connects the places where Lord Rama halted during his exile expanding from the North of Chhattisgarh (Koriya) to the South (Sukma).",
      map : "https://goo.gl/maps/aQkZmpp1cCkVvxiV8",
    },
    {
      id: 7,
      image: "assets/Chhattisgarh/Forts/Chitradurga Fort.jpg",
      name: "Chaiturgarh Fort",
      category: "Forts",
      description: "https://hotelandplace.com/hotels/chaiturgarh-fort",
      info : "Chaiturgarh (also known as Lafagarh) is situated at a height of 3,060 feet (930 m) on a hilltop. It is protected by strong natural walls and is considered as one of the strongest natural forts.",
      map : "https://goo.gl/maps/baSCwwvKaZtXPELV6",
    },
    {
      id: 8,
      image: "assets/Chhattisgarh/Forts/Bidar Fort.jpg",
      name: "Ratanpur Fort",
      category: "Forts",
      description: "https://www.nativeplanet.com/travel-guide/ratanpur-the-beautiful-splendour-of-bilaspur-in-chhattisgarh-004772.html",
      info : "Ratanpura, originally known as Ratnapura, was the capital of Kalachuris of Ratnapura, who were a branch of the Kalachuris of Tripuri. According to the 1114 CE Ratanpur inscription of the local king Jajjaladeva I, his ancestor Kalingaraja conquered Dakshina Kosala region, and made Tummana (modern Tuman) his capital.",
      map : "https://goo.gl/maps/PLKDNYrvpqsb3AFL8",
    },
    {
      id: 9, 
      image: "assets/Chhattisgarh/Forts/Kangra Fort.jpg",
      name: "Kosagaigarh",
      category: "Forts",
      description: "https://www.booking.com/resorts/region/in/chhattisgarh-central.en-gb.html",
      info : "Kosagaigarh is a village situated 25 kms off Korba-Katghora Road on the hillocks of Putka Pahad. This was built by Raja. Natural walls protect it and so only at some parts the builders felt the need of constructing walls.",
      map : "https://goo.gl/maps/s619YDiuxutV6CCz8",
    },
     {
        id: 10,
        image: "assets/Chhattisgarh/Forts/Chitradurga Fort.jpg",
        name: "Chitradurga Fort",
        category: "Forts",
        description: "https://www.yatra.com/indian-monuments/chitradurga/chitradurga-fort",
        info : "Chitradurga Fort is known as a stone fort due to its ramparts being made of heavy blocks of granite. It has several concentric walls, multiple entrances, four unseen passages, and thirty-five secret paths. In addition to all these features, the fort also has 2000 watchtowers.",
        map : "https://goo.gl/maps/MgaDTYYtRJ1r2PDu5",
     },
      {
        id: 11,
        image: "assets/Chhattisgarh/Forts/Orchha Fort.jpg",
        name: "Malhar Fort",
        category: "Forts",
        description: "https://www.chhattisgarhtourism.in/malhar/",
        info : "Malhars antique charm and mesmerizing sculptures create an ambience that can never be forgotten.. This town is in the list of “Ancient Monuments and Archaeological Sites and Remains of National Importance” maintained by Archaeological Survey of India.",
        map : "https://goo.gl/maps/2g2vxLzD6qDMmt9p9",
     },
      {
        id: 12,
        image: "assets/Chhattisgarh/Forts/Kangra Fort.jpg",
        name: "Kotgarh Fort",
        category: "Forts",
        description: "https://www.makemytrip.com/bus-tickets/raipur-cg-bhawanathpur-booking.html",
        info : "It is noted for its apple cultivation and offers visitors a chance to walk through lovely apple orchards and pine forests.",
        map : "https://goo.gl/maps/hGZPJu9XSyF9Q1TJA",
     },
      {
        id: 13,
        image: "assets/Chhattisgarh/Heritage Sites/Bastar Palace.jpg",
        name: "Bastar Palace",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/HotelsNear-g1893706-d2343026-Bastar_Palace-Bastar_Bastar_District_Chhattisgarh.html",
        info : "The Bastar Palace located in Jagdalpur is a historical monument which has an impressive art and architectural work with exquisite carvings and engravings on walls and ceilings. Bastar Palace was built by the rulers of Bastar and speaks of many legends of gallantry and heroism of these kings.",
        map : "https://goo.gl/maps/CwjHsDm9rdJDVqWZ6",
      },
      {
        id: 14,
        image: "assets/Chhattisgarh/Heritage Sites/Gadhiya Mountain.jpg",
        name: "Gadiya Mountain",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/Attraction_Review-g2285360-d3202932-Reviews-Gadiya_Mountain-Kanker_Kanker_District_Chhattisgarh.html",
        info : "Gadiya Mountain, Kanker is well known for a tank, that never dries up. It does not dry up even in the hot summers. Named after the two daughters of the king Dharma Dev, Sonai and Rupai are the two parts of the tank.",
        map : "https://goo.gl/maps/6UATifo4ivKaodeF8",
      },
      {
        id: 15,
        image: "assets/Chhattisgarh/Heritage Sites/Kanker Palace.jpg",
        name: "Kanker Palace",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/Hotel_Review-g2285360-d2561839-Reviews-Kanker_Palace_Heritage-Kanker_Kanker_District_Chhattisgarh.html",
        info : "Kanker is famous for its untouched forests, unique tribal villages and the last but not least the Royal Kanker Palace along with some fine century-old colonial buildings.",
        map : "https://goo.gl/maps/VTx8xRLnn2GBBqdi9",
      },
      {
        id: 16,
        image: "assets/Chhattisgarh/Heritage Sites/Kawardha Palace.jpg",
        name: "Kawardha Palace",
        category: "Heritage Sites",
        description: "https://www.tripadvisor.in/Hotel_Review-g1798392-d1798394-Reviews-Palace_Kawardha-Kawardha_Kabirdham_District_Chhattisgarh.html",
        info : "The Palace of Kawardha is said to have been designed and built under Maharaja Dharamraj Singh between the period 1936 and 1939. It now forms one of the prime Tourist Attractions in Kawardha.",
        map : "https://goo.gl/maps/pex5F2fFQ6cSu32cA",
      },
       {
        id: 17, 
        image: "assets/Chhattisgarh/Heritage Sites/Kutumsar Caves.jpg",
        name: "Kutumsar Caves",
        category: "Heritage Sites",
        description: "https://www.gosahin.com/places-to-visit/kailash-and-kotumsar-cave/",
        info : "Kotumsar cave is a major attraction for people interested in ecotourism. It is a limestone cave formed on the Kanger limestone belt, situated near the bank of the River Kanger, a tributary of the Kolab River.",
        map : "https://goo.gl/maps/JsSThybUdmc3hjvj6",
      },
      {
        id: 18,
        image: "assets/Chhattisgarh/Wildlife/Achanakmar Wildlife Sanctuary.jfif",
        name: "Achanakmar Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.chhattisgarhtourism.co.in/achanakmar-tiger-reserve-chhattisgarh.html",
        info : "Achanakmar Tiger Reserve is situated in Bilaspur district of Chhattisgarh. Even a short trek through this park easily reveals its extraordinary beauty and biodiversity, The most favorable time to visit Tiger Reserve is from the month of November to the month of June.",
        map : "https://goo.gl/maps/jJNxzZuZveoFRUmT6",
     },
      {
        id: 19,
        image: "assets/Chhattisgarh/Wildlife/Barnawapara Wildlife Sanctuary.jpg",
        name: "Barnawapara Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://serviceonline.gov.in/chhattisgarh/serviceLinkHome.html?serviceToken=GRdn6COhmL791",
        info : "Being near the Mahanadi River, it is intensely rich in flora and fauna. The sanctuary is home to tiger, sloth bear, a few species of deer and many rare birds. It is ideal for backcountry enthusiasts to explore.",
        map : "https://goo.gl/maps/KDJ5vLqSU1qftNmi8",
     },
      {
        id: 20,
        image: "assets/Chhattisgarh/Wildlife/Bhoramdev Wildlife Sanctuary.jpeg",
        name: "Bhoramdev Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/blog/bhoramdeo-wildlife-sanctuary-recognised-tiger-reserve/",
        info : "Bhoramdev Sanctuary is spread over Green Hariers. Expanded in the area of 352 square kilometer, this sanctuary boasts many natural and prehistoric features in it. ",
        map : "https://goo.gl/maps/CcwyWjujdpQPK4tZ6",
     },
      {
        id: 21,
        image: "assets/Chhattisgarh/Wildlife/Gomarda Wildlife Sanctuary.jpg",
        name: "Gomarda Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.indianvisit.com/wildlife/gomarda-wildlife-sanctuary.html",
        info : "The sanctuary was inaugurated in 1975 and is home to a number of exotic wildlife – especially deers and antelopes. Other animals prominently seen are Barking deers, Chausingha, Sloth Bear, Wild Boar, Nilgiri, Sambhars and Jackals. The bird community is fairly vivid too.",
        map : "https://goo.gl/maps/tdziYrgpcTs7CCtD8",
     },
      {
        id: 22,
        image: "assets/Chhattisgarh/Wildlife/Sitanadi Wildlife Sanctuary.jpg",
        name: "Sitanadi Wildlife Sanctuary",
        category: "Wildlife",
        description: "https://www.tripadvisor.in/Attraction_Review-g2287339-d4138807-Reviews-Sitanadi_Wildlife_Sanctuary-Dhamtari_Dhamtari_District_Chhattisgarh.html",
        info : "A famous tourist attraction which was a paradise for nature enthusiasts which was established in 1974 and keeping the natural beauty throughout for many more years. Trekking area, adventure and more. A secure place for the endangering wildlife varieties and a place to study about them and their habitat.",
        map : "https://goo.gl/maps/kkeYRtQ5dKMiFffLA",
     },
      {
        id: 23,
        image: "assets/Maharshtra/Religious/trimbakeshwar.jpg",
        name: "Mainpat Hills",
        category: "Hill Station",
        description: "https://chhattisgarhtourism.co.in/mainpat-chhattisgarh.html",
        info : "Mainpat is famous for its greenery, waterfalls, Budha monastery and Jungles. The hill station is gradually becoming papular among tourist for its natural beauty and landscapes.",
        map : "https://g.page/mainpat_hills?share",
      },
      {
        id: 24,
        image: "assets/Maharshtra/Religious/tuljabhavani mata.jpg",
        name: "Chirmiri Hill",
        category: "Hill Station",
        description: "https://www.tripadvisor.in/HotelsNear-g3605969-d4142756-Chirmiri_Station-Barbaspur_Durg_District_Chhattisgarh.html",
        info : "Be it the lush greenery or the mighty mountain peaks or the surreal rivers, Chirmiri will make you fall in love with itself just in a single visit. Located right along the banks of the astounding Hasdeo river, which is one of the most prominent tributaries of the great Mahanadi river, Chirmiri also boasts of serving home to some dense forests that in turn house exotic range of flora and fauna.",
        map : "https://goo.gl/maps/9GhMxURw9A3zNYAH8",
      },
      {
        id: 25, 
        image: "assets/Maharshtra/Heritage/aga khana.jpg",
        name: "Baila Dila Hill",
        category: "Hill Station",
        description: "https://www.tripadvisor.in/Attraction_Review-g1893706-d3170480-Reviews-Bailadila_Mountains-Bastar_Bastar_District_Chhattisgarh.html",
        info : "Bailadila is one of the most popular destinations in the state and is located at an elevation of 1276 meters. This hill is blessed with some of the most beautiful waterfalls in the state. Also, you can experience its thrilling forest and blissful gardens.",
        map : "https://goo.gl/maps/RYJ6JeYL95JyUCsy5",
      },
      {
        id: 26,
        image: "assets/Maharshtra/Heritage/Ajanta ellora caves.jpg",
        name: "Gadiya Mountains",
        category: "Hill Station",
        description: "https://www.tripadvisor.in/Attraction_Review-g2285360-d3202932-Reviews-Gadiya_Mountain-Kanker_Kanker_District_Chhattisgarh.html",
        info : "Gadiya Mountain is the highest mountain of Kanker. It is a natural fort and was once declared as the capital by King Dharma Dev of the Kandra dynasty. There is a water tank situated on the hilltop which never dries up. The Doodh river flows down the mountains.",
        map : "https://goo.gl/maps/4sAVPs22Nj2De6Ps7",
      },
      {
        id: 27,
        image: "assets/Maharshtra/Heritage/Bibi ka ma.jpg",
        name: "Ambikapur",
        category: "Hill Station",
        description: "https://www.makemytrip.com/hotels/ambikapur-hotels.html",
        info : "A place of forests and hills, Ambikapur in Chattisgarh is an ancient city that dates back to the mythological epics of the Ramayana and the Mahabharata. It is widely believed that Lord Rama, Lakshman and Sita visited this region during their 14-year-long exile.",
        map : "https://goo.gl/maps/Kno7RErw5srC6ucFA",
      },
      {
        id: 28,
        image: "assets/Chhattisgarh/Food/Aamat.png",
        name: "Aamat",
        category: "Food",
        info : "This delectable delicacy of the state is prepared with mixed vegetables which is cooked along with the ginger garlic paste and various spices to enhance the flavor of the dish. Traditionally the dish is prepared in the bamboo shoots. The bamboo keeps the flavor of the ingredients in intact and also adds the unique aroma to the dish.",
      },
      {
        id: 29,
        image: "assets/Chhattisgarh/Food/Bafauri.png",
        name: "Bafauri",
        category: "Food",
        info : "Bafuari is a healthy alternative for the oily pakodas which are every Indian favourite snack. Bafauri is a famous dish of the state which is cooked in Chana Daal flour. Various vegetables and spices add the mouth-savoring taste to the dish. ",
      },
      {
        id: 30,
        image: "assets/Chhattisgarh/Food/Bara.png",
        name: "Bara",
        category: "Food",
        info : "Bara is basically a light snack which is made from the fermented Urad Dal. Various vegetables and spices are added along with the fermented lentils to add the perfection to this famous dish of the state.",
      },
      {
        id: 31,
        image: "assets/Chhattisgarh/Food/Chila.png",
        name: "Chila",
        category: "Food",
        info : "Chila is flat chapati like dish which is prepared with the rice batter mixed with the Urad Daal. The dish is very easy to cook and is very delicious in the taste. Chila is an important part of the breakfast meal of the people of Chhattisgarh.",
      },
      {
        id: 32,
        image: "assets/Chhattisgarh/Food/Dubki Kadi.png",
        name: "Dubki Kadi",
        category: "Food",
        info : "Dubki Kadi is a pulse-like dish which is mainly cooked with the curd. The pakodas of gram flour are added to the dish which is best complemented with the tangy curry of curd and spices.",
      },
      {
        id: 33,
        image: "assets/Chhattisgarh/Food/Faraa.png",
        name: "Faraa",
        category: "Food",
        info : ". Faraa are made in the form of dumpling, the main ingredient of dish being rice. The dough of rice along with the minimum spices are seasoning of coriander leaves is put to steam to get the light and healthy snack that hails from Chhattisgarh.",
      },
      {
        id: 34, 
        image: "assets/Chhattisgarh/Food/Khurma.png",
        name: "Khurma",
        category: "Food",
        info : "The roasted vermicelli are added to the boiling water along with sugar syrup and rich dry fruits to get an absolutely lip-smacking sweet dish which will surely satisfy your sweet tooth.",
      },
      {
        id: 35,
        image: "assets/Chhattisgarh/Food/Muthia.jpg",
        name: "Muthia",
        category: "Food",
        info : "Muthia is prepared with the rice batter which is seasoned with various spices. The dish is not fried but is steamed and hence it retains the original flavor of its ingredients. Muthia is a famous dish of the state which is usually enjoyed in the breakfast.",
      },
      
  ];
  
  export default ChhattisgarhData;


 