const GujaratData = [
    {
      id: 1, 
      image: "assets/Gujrat/HillStation/Don Hill.jpg",
      name: "Don Hill",
      category: "HillStation",
      description: "https://www.agoda.com/don-hill-beach-resort/hotel/goa-in.html?cid=1844104",
      info : "Nestled in the Sahyadri range, at an altitude of about 1000 m, this Dangi enclave derives its name from the Snake God revered by the tribals and translates as 'the abode of serpents', Saputara.",
      map : "https://goo.gl/maps/jogHHh8a6B7GwVuc6",
    },
    {
      id: 2,
      image: "assets/Gujrat/HillStation/Saputara Hills.jpg",
      name: "Saputara Hill",
      category: "HillStation",
      description: "https://www.booking.com/searchresults.en-gb.html?aid=306395&label=saputara-in-wCT5a21wtJ4jaSkEXWB_DQS393001047098%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atiaud-1110454565467%3Akwd-307987501190%3Alp1007786%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YZVcNNsENnH02-pWD53qm9c&sid=c324ae8fc8adac31eeb08de5d87b7a0b&city=900053668&redirected=1&redirected_from_city=1&source=city&",
      info : "Saputara is famous for its scenic hills and waterfalls which makes it one of the most incredible hill stations to visit in India. It is also home to native Dang tribes and their rich culture.",
      map : "https://goo.gl/maps/sbECcsXzPL5j5BXZA"
     },
    {
      id: 3,
      image: "assets/Gujrat/HillStation/Wilson Hill.jfif",
      name: "Wilson Hill",
      category: "HillStation",
      description: "https://www.tripadvisor.in/HotelsNear-g661301-d4088697-Wilson_Hill-Valsad_Valsad_District_Gujarat.html",
      info : "Wilson Hills stands in a densely forested region close to the Pangarbari Wildlife Sanctuary. It is one of the few hill stations in the world from which it is possible to glimpse the sea.",
      map : "https://goo.gl/maps/iTmdrx42E2h6y31P9"},
    {
      id: 4,
      image: "assets/Gujrat/Religious/Somnath Temple.webp",
      name: "Somnath Temple",
      category: "Religious",
      description: "https://www.booking.com/searchresults.en-gb.html?aid=306395&label=somnath-in-LUSQ2oDaudXqke8iW6zqkgS392972671598%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atiaud-1110454565467%3Akwd-30659625121%3Alp1007786%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YZVcNNsENnH02-pWD53qm9c&sid=c324ae8fc8adac31eeb08de5d87b7a0b&city=-2111788&redirected=1&redirected_from_city=1&source=city&",
      info : "It is one of the most sacred pilgrimage sites for Hindus and is believed to be first among the twelve jyotirlinga shrines of Shiva.Shree Somnath is first among the twelve Aadi Jyotirlings of India. ",
      map : "https://goo.gl/maps/q4tGjY1sQg1ChvqXA",
      },
    {
      id: 5,
      image: "assets/Gujrat/Religious/Dwarkadhish Tenmple.jpg",
      name: "Dwarkadhish Temple",
      category: "Religious",
      description: "https://www.booking.com/landmark/in/dwarkadhish-temple.en-gb.html?aid=356980&label=gog235jc-1DCAUobEISZHdhcmthZGhpc2gtdGVtcGxlSDNYA2hsiAEBmAEJuAEXyAEM2AED6AEBiAIBqAIDuALBsrObBsACAdICJDA0ZWNjZWRiLTM1YzYtNDNhOS04MzQ2LTU3YjY2MTk2MGFkNNgCBOACAQ&sid=c324ae8fc8adac31eeb08de5d87b7a0b&inac=0&keep_landing=1&",
      info : "The Dwarkadhish temple, also known as the Jagat Mandir and occasionally spelled Dwarakadheesh, is a Hindu temple dedicated to Krishna, who is worshiped here by the name Dwarkadhish, or 'King of Dwarka'.",
      map : "https://goo.gl/maps/kofXvedLv5pfHQXk6"
    },
    {
      id: 6,
      image: "assets/Gujrat/Religious/Nageshwar temple.jpg",
      name: "Nageshwar temple",
      category: "Religious",
      description: "https://www.makemytrip.com/hotels/dwarka-hotels-near-nageshwar_temple.html",
      info : "Nageshwar Temple is the massive 80 feet tall statue of Lord Shiva. The temple itself is characterised by typical Hindu architecture.",
      map : "https://goo.gl/maps/3CNsyzwvvQULpb6J9"
    },
    {
      id: 7,
      image: "assets/Gujrat/Religious/Sheth Hutheesinh Temple.jpg",
      name: "Sheth Hutheesing Temple",
      category: "Religious",
      description: "https://www.gujaratpackage.com/hutheesing-jain-temple/",
      info : "Established in 1848, the Hutheesing Jain Temple is one of the most revered Jain temples in Ahmedabad,this temple project, initially taken up by Sheth Hutheesing Kesarisinh was further completed by his wife ",
      map : "https://goo.gl/maps/8D2ahsGbFTwUdkV89"
    },
    {
        id: 8, 
        image: "assets/Gujrat/Religious/Ambaji Temple.jpg",
        name: "Ambaji Temple",
        category: "Religious",
        description: "https://www.bhigwanbirdsanctuary.com/",
        info : "The shrine of Shri Amba is regarded as a revered shrine by the Shakta Shaktism sect of Hinduism. It is believed that the Heart of Sati Devi has fallen here. ",
        map : "https://goo.gl/maps/f49qrAzwDt55LNmCA",
      },
      {
        id: 9,
        image: "assets/Gujrat/Religious/Somnath Temple.webp",
        name: "Swaminarayan Akshardham Temple",
        category: "Religious",
        description: "https://akshardham.com/gujarat/visitor-info/",
        info : "Akshardham temple in Gandhinagar is managed by the flourishing Hindu Swaminarayan Group. Spread in 23 acres of manicured yards, this significant temple was constructed by around 1000 craftsmens.",
        map : "https://goo.gl/maps/ckPaiT7QeuBHUUT26",
       },
      {
        id: 10,
        image: "assets/Gujrat/Heritage/Rani ki Vav.jpg",
        name: "Rani ki Vav",
        category: "Heritage",
        description: "https://www.thrillophilia.com/tours/rani-ki-vav-patan",
        info : "Rani-ki-Vav is an exceptional example of a distinctive form of subterranean water architecture of the Indian subcontinent, the stepwell, which is located on the banks of the Saraswati River in Patan.",
        map : "https://g.page/theranikivav?share"
       },
      {
        id: 11,
        image: "assets/Gujrat/Heritage/Mohabbat Maqbara.jpg",
        name: "Mahabat Maqbara",
        category: "Heritage",
        description: "https://www.tripadvisor.in/Attraction_Review-g303879-d4071257-Reviews-Mahabat_Maqbara-Junagadh_Junagadh_District_Gujarat.html",
        info : "Mahabat Maqbara is a mausoleum and its unique architecture makes it one of the most important attractions of Junagarh. It houses the tombs of Mohabbat khanji and Bahaduddin Hasainbhai in the Bahadudd.",
        map : "https://goo.gl/maps/AuAsQ9k2xuQr1gvV6"
      },
      {
        id: 12,
        image: "assets/Gujrat/Heritage/Adalaj Stepwell.jpg",
        name: "Adalaj Stepwell",
        category: "Heritage",
        description: "https://ahmedabadtourism.in/adalaj-stepwell-ahmedabad",
        info : "The stepwell was built by Mahmud Begada in 1411, to commemorate Queen Rudabai, wife of Veersinh, the Vaghela chieftain. It served both a utilitarian and spiritual purpose for the people around.",
        map : "https://goo.gl/maps/5RhqycFgSrPtrhWA7",
        },
      {
        id: 13,
        image: "assets/Gujrat/Heritage/Laxmi Vilas palace.jpg",
        name: "Laxmi Vilas palace",
        category: "Heritage",
        description: "https://www.viator.com/en-IN/Gujarat-attractions/Laxmi-Vilas-Palace/d24557-a23752",
        info : "It's elaborate interiors boast well-maintained mosaics, chandeliers and artworks, as well as a highly impressive collection of weaponry and art.",
        map : "https://goo.gl/maps/5pwZnFZKdHgy6W9S9"
      },
      {
        id: 14,
        image: "assets/Gujrat/Heritage/Sarkhej Roza.jpg",
        name: "Sarkhej Roza",
        category: "Heritage",
        description: "https://www.thrillophilia.com/attractions/sarkhej-roza",
        info : "Sarkhej Roza is a mosque, tomb and palace complex dedicated to the memory of Ahmed Shah I's spiritual advisor, Ahmed Khattu Ganj Baksh.",
        map : "https://goo.gl/maps/u26HmWK3Q4SUEeuFA"
      },
      {
        id: 15,
        image: "assets/Gujrat/Heritage/Sun Temple.jpg",
        name: "Sun Temple",
        category: "Heritage",
        description: "https://www.yatra.com/indian-monuments/modhera/modhera-sun-temple",
        info : "Sun Temple was built in 1026-27 CE during the reign of Bhima I of the Chaulukya dynasty. As you enter the historical complex, you first come across the magnificent kund known as the Ramakund, built in rectangular shape .",
        map : "https://goo.gl/maps/8R9hJHhubGGEbgXU6"
      },
       {
        id: 16, 
        image: "assets/Gujrat/Forts/Bhujia Fort.jpg",
        name: "Bhujia Fort",
        category: "Forts",
        description: "https://www.triphobo.com/places/bhuj-india/bhujia-hill",
        info : "The fort was constructed for the defense of the city by Jadeja Chiefs. The construction of Bhujia fort was started by Rao Godji I (1715–1718) ruler of Kingdom of Kutch as a sort of outwork defense for Bhuj.",
        map : "https://goo.gl/maps/LhRrDFqLTGadYPnZA",
      },
      {
        id: 17,
        image: "assets/Gujrat/Forts/Kanthkot Fort.jpg",
        name: "Kanthkot Fort",
        category: "Forts",
        description: "https://www.thrillophilia.com/attractions/kanthkot-fort",
        info :"Kanthkot fort also has a sun temple showing an image of the god of sun with folded hands. Its architectural importance also lures the tourists making it one of the most visited tourist destinations in Kucth.",
        map : "https://goo.gl/maps/rb1zrCssWsTDYBAv5",
       },
      {
        id: 18,
        image: "assets/Gujrat/Forts/Roha- Fort.jpg",
        name: "Roha- Fort",
        category: "Forts",
        description: "https://www.trawell.in/gujarat/mandvi/roha-fort",
        info : "It was the seat of Roha Jagir. One hundred twenty Soomra Rajput princesses sought asylum with Abda (Jagirdar of Abdasa) who died in the battle with Allaudin Khilji. Consequently, all the princesses sacrificed their lives and took samadhi here.",
        map : "https://goo.gl/maps/kg2ffAnfx4XH37Y5A",
       },
      {
        id: 19,
        image: "assets/Gujrat/Forts/Tera Fort.jpg",
        name: "Tera Fort",
        category: "Forts",
        description: "https://www.inspirock.com/india/kutch/tera-fort-a5457179521",
        info : "Behind the stone wall lies an imposing fort wall with strategically built gates. Once a Rajwadu village, Tera has been home to diverse communities – Bhanushali, Koli, Harijan, Parghi, Muslim, Jain, Luhana, Rajput, and Brahmin. ",
        map : "https://goo.gl/maps/y4V7eztj3G8mvzn77",
      },
      {
        id: 20,
        image: "assets/Gujrat/Forts/Pavangadh Fort.jfif",
        name: "Uparkot Fort",
        category: "Forts",
        description: "https://www.gujarattourism.com/saurashtra/junagadh/uparkot-fort.html",
        info : "Uparkot Fort is said to have once withstood a 12-year siege. The fort is also famous for 2 stepwells – Adi Kadi Vav and Navghan Kuvo and the nearby Uparkot Caves, which are a part of the Junagadh Buddhist Cave Groups.",
        map : "https://goo.gl/maps/txXRNW3tBajYEurY6",
      },
      {
        id: 21,
        image: "assets/Gujrat/Forts/Zinzuwada Fort.jpg",
        name: "Zinzuwada Fort",
        category: "Forts",
        description: "https://www.holidayhome.co.in/zinzuwada-india",
        info : "Zinzuwada is one of the finest examples of Hindu fortifications in India, without Islamic influence. The town Zinzuwada has four gateways in four directions: Madapol Gate, Rakshaspol Gate, Harijan Gate and Dhama Gate.",
        map : "https://goo.gl/maps/inuiAwZFNpWVVV9N6",
      },
      {
        id: 22,
        image: "assets/Gujrat/Beaches/Chorwad Beach.jpg",
        name: "Chorwad Beach",
        category: "Beaches",
        description: "https://www.tourism-of-india.com/chorwad.html",
        info : "Chorwad Beach seafront on Arabian Sea has white, sandy beach. It offers many attractions and scenic views. Visitors can enjoy here rocky hills, fishing, scooting, skiing, parasailing, boat rides, and many more activities.",
        map : "https://www.google.com/search?q=Chorwad+Beach%2C+gujarat+map&biw=1536&bih=722&tbm=lcl&sxsrf=ALiCzsZN1A1sKS2wYp2nzed8K5LqIeEgFw%3A1668097986745&ei=widtY4z7LIPQ2roPhYyUkAo&ved=0ahUKEwiM5MyfhaT7AhUDqFYBHQUGBaIQ4dUDCAk&uact=5&oq=Chorwad+Beach%2C+gujarat+map&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAMyBAgjECc6BggAEAcQHjoICAAQCBAeEA86AggmOgUIABCGAzoFCAAQogQ6BwgjELACECdQvwRYxRNgwhxoAHAAeACAAeoBiAHOC5IBBTAuMS42mAEAoAEBwAEB&sclient=gws-wiz-local",
      },
      {
        id: 23,
        image: "assets/Gujrat/Beaches/Daman Beach.jpg",
        name: "Daman Beach",
        category: "Beaches",
        description: "https://www.makemytrip.com/hotels/daman-hotels.html",
        info : "Daman is famous for its beautiful beaches, portugues colonical architecture, churches and the mesmirizing beauty of twin towns of Nani-Daman and Moti-Daman.",
        map : "https://goo.gl/maps/QCqTormAn99tbS4n9",
      },
      {
        id: 24, 
        image: "assets/Gujrat/Beaches/Diu Beach.webp",
        name: "Diu Beach",
        category: "Beaches",
        description: "https://www.makemytrip.com/hotels/diu-hotels.html",
        info : "Diu is also known for its unique Hoka Trees which can be found on the Nagoa beach. Plus, you can also indulge in various fascinating adventure sports ranging from camel rides to water sports to long walks in the beach.",
        map : "https://www.google.com/search?sxsrf=ALiCzsZtAGXXFo_fQ4Bc2-Q64nx4u-n7Hw:1668098604651&q=Diu+Beach+,gujarat++location&npsic=0&rflfq=1&rldoc=1&rllag=20709296,70986093,1204&tbm=lcl&sxsrf=ALiCzsZtAGXXFo_fQ4Bc2-Q64nx4u-n7Hw:1668098604651&sa=X&ved=2ahUKEwjv5p7Gh6T7AhXtg1YBHYPGAaoQtgN6BAgNEAE&biw=1536&bih=722&dpr=1.25#rlfi=hd:;si:;mv:[[20.7406664,71.0145944],[20.6997827,70.9051597]]",
      },
      {
        id: 25,
        image: "assets/Gujrat/Beaches/Dumas Beach.jpg",
        name: "Dumas Beach",
        category: "Beaches",
        description:  "https://www.makemytrip.com/hotels/surat-hotels-near-dumas_beach.html",
        info : "umas beach is known for its black sand and is considered to be haunted because it was once used as a Hindu cremation site, according to folklore.",
        map : "https://goo.gl/maps/G3Bg2Dq6yTgNtxc79",
       },
      {
        id: 26,
        image: "assets/Gujrat/Beaches/Mandvi Beach.jpg",
        name: "Mandvi Beach",
        category: "Beaches",
        description:  "https://www.booking.com/landmark/in/mandvi-beach.en-gb.html?aid=356980&label=gog235jc-1DCAUobEIMbWFuZHZpLWJlYWNoSDNYA2hsiAEBmAEJuAEXyAEM2AED6AEBiAIBqAIDuAKX2rSbBsACAdICJDNmZDMyNGUzLWQ0NzItNGVkMC1iOGVhLTQyN2JmZmU1NjU5M9gCBOACAQ&sid=c324ae8fc8adac31eeb08de5d87b7a0b&inac=0&keep_landing=1&",
        info : "Mandvi is famous for a 400 year old shipbuilding industry & craftman who use traditional techniques to build ships for domestic & international clients. ",
        map : "https://goo.gl/maps/LY4w9qfgKbeLMrds6",
       },
      {
        id: 27,
        image: "assets/Maharshtra/Heritage/chatrapati shahu museum.jpg",
        name: "Barda Wildlife sanctuary",
        category: "Wildlife",
        description: "https://hotelandplace.com/hotels/barda-wildlife-sanctuary",
        info : "The Sanctuary exhibits great variety of fauna including variety of butterflies, Lion, Chinkara, Sambar, crocodile and chameleon, ratel, leopard, wolf, Spotted Eagle and Crested Hawk-Eagle. ",
        map : "https://www.google.com/search?bih=664&biw=1536&hl=en-GB&tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsas-PnIkY2cTXCAbhv5Q-VU9hZCnA:1668100464194&q=Barda+Wildlife+sanctuary+gujarat&rflfq=1&num=10&rldimm=16372184347864754278&ved=2ahUKEwidt_i8jqT7AhUyqlYBHTiHCHMQu9QIegQIehAJ#rlfi=hd:;si:3161036928902330275,l,CiBCYXJkYSBXaWxkbGlmZSBzYW5jdHVhcnkgZ3VqYXJhdEjB29e60LCAgAhaMBAAEAEQAhgAGAEYAhgDIiBiYXJkYSB3aWxkbGlmZSBzYW5jdHVhcnkgZ3VqYXJhdJIBDXdpbGRsaWZlX3BhcmuaASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVTnBlVFYyZUU1bkVBRaoBIBABKhwiGGJhcmRhIHdpbGRsaWZlIHNhbmN0dWFyeSgA,y,CtXcTHa9X0c;mv:[[24.6254031,74.4329557],[20.7349501,68.4102506]]",
      },
      {
        id: 28,
        image: "assets/Maharshtra/Heritage/chatrapati terminus11.jpg",
        name: "Gir National Park",
        category: "Wildlife",
        description:"https://girlion.gujarat.gov.in/",
        info : "Gir Forest National Park and Wildlife Sanctuary, also known as Sasan-Gir, is a wildlife sanctuary and shielded forest area in Gujarat, India. Gujarat is famous for lions all over the world.",
        map : "https://goo.gl/maps/WU2uWQsv3bVcT2Kv5",
        },
      {
        id: 29,
        image: "assets/Gujrat/WildLife/Jambughoda Wildlife Sanctuary.jpg",
        name: "Jambughoda Wildlife Sanctuary",
        category: "Wildlife",
        description:"https://www.gujaratexpert.com/jambughoda-wildlife-sanctuary/",
        info : "The wildlife sanctuary consists of forested hills with teeming wildlife and avian species. Teak, mahua and bamboo thickets cover the length and breadth of the forest, which is occupied by wild boars, nilgais (blue bull), jackals, hyenas, barking deer.",
        map : "https://goo.gl/maps/kRg5Gugx5xyxvSJM7",
      },
      {
        id: 30,
        image: "assets/Gujrat/WildLife/Marine National Park.jpg",
        name: "Marine National Park",
        category: "Wildlife",
        description: "https://mnpcs.gov.in/",
        info : "The beaches of the Gujarat coast are breeding grounds for the Green Sea Turtle and other marine turtles. In the deeper sea of this area lives the whale shark, feeding off plankton, considered the largest fish in the world, now endangered because it is killed for its flesh and cartilage oil.",
        map : "https://goo.gl/maps/zQbXDVAiknRHRgCS8",
      },
      {
        id: 31,
        image: "assets/Gujrat/WildLife/Purna Wildlife sanctuary.jpg",
        name: "Purna Wildlife sanctuary",
        category: "Wildlife",
        description: "https://surattourism.in/purna-wildlife-sanctuary-surat",
        info : "The forests support a rich tribal culture in the form of houses, dresses, jewelry, agriculture, fishing, musical instruments, folk dances etc. When the sun sets, one may listen to the distant sounds of folk dances, tribal songs and their improvised musical instruments Pavry and drums.",
        map : "https://goo.gl/maps/Wt4uaJ8VvjrKWi2i6",
      },
      {
        id: 32,
        image: "assets/Gujrat/WildLife/Velavadar National Park.jpg",
        name: "Velavadar National Park",
        category: "Wildlife",
        description:"https://gujaratdarshanguide.com/velavadar-national-park-booking/",
        info : "The national park has been classified as 4B Gujarat-Rajwada biotic province of semi-arid bio-geographical zone. Flat land, dry grasses and herds of antelope have always attracted visitors to this park which has a grassland ecosystem.",
        map : "https://www.google.com/search?bih=722&biw=1536&hl=en-GB&tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsYj-F5mQgGjWvKsGDPPLmg8itS3ag:1668101845991&q=Velavadar+National+Park+gujarat&rflfq=1&num=10&ved=2ahUKEwiBxurPk6T7AhVtr1YBHT1sCqkQtgN6BAgPEAY#rlfi=hd:;si:;mv:[[22.16159,73.61180410000001],[20.6847139,71.2652064]]",
      },
      {
        id: 33,
        image: "assets/Gujrat/Food/Gujrati Thali.png",
        name: "Gujarati Thali",
        category: "Food",
        info : "To taste the excellent vegetarian Gujarati cuisine, is to have a Thali Meal the ultimate delightful vegetarian fare. The traditional Gujarati Thali is one of the best ways to know the Gujarati Cuisine. ", 
      },
      {
        id: 34,
        image: "assets/Gujrat/Food/Khandvi.jfif",
        name: "Khandvi",
        category: "Food",
        info : "Soft rolls made of gram flour and tempered with coconut, mustard seeds, and curry leaves, these melt-in-the-mouth snacks are extremely appetizing.", 
      },
      {
        id: 35,
        image: "assets/Gujrat/Food/Khichu.jpg",
        name: "Khichu",
        category: "Food",
        info : "This steaming hot snack comes together in minutes and tastes yummilicious. This could be the quickest-to-make farsan on this list. A thick porridge-like mixture made from rice flour and seasoned with cumin seeds and green chilli, khichu is served with a splash of groundnut oil and cayenne pepper.", 
      },
      {
        id: 36,
        image: "assets/Gujrat/Food/Khaman.png",
        name: "Khaman",
        category: "Food",
        info : "Similar to the dhokla, but definitely not the same, khaman is made from only gram flour and is usually lighter in colour and softer than the dhokla. The secret is adding more baking soda to the batter to make it fluffier and spongier.", 
      },
      {
        id: 37,
        image: "assets/Gujrat/Food/Dabeli.jpg",
        name: "Dabeli",
        category: "Food",
        info : "The Kutchi Dabeli is garnished with pomegranate pearls and roasted peanuts, and served with a chutney made from tamarind, dates, garlic, and red chilies.", 
      },
      {
        id: 38,
        image: "assets/Gujrat/Food/Ghooghra.jpg",
        name: "Ghooghra",
        category: "Food",
        info : "No festival in Gujarat is complete without Ghooghra. Ghughra is traditional Gujarati Sweets/Dessert. It is also known as Karanji, Gujia or gujhia. Ghughra is fried desserts filled with coconut and dry fruits.", 
      },
  
  ];
  
  export default GujaratData;


 