const JammuKashmirData = [
  {
    id: 1, 
    image: "assets/Jammu & Kashmir/Forts/Akhnoor Fort (Jammu).jpg",
    name: "Akhnoor Fort",
    category: "Forts",
    description: "https://www.abhibus.com/bus/akhnoor-bus-tickets",
    info:" The Akhnoor fort which lies towards east of the town, on the bank of the Chenab river holds great significance and is extremely important for reconstruction of the past history. The fort was built by Raja Alam Singh in 1802. ",
    map : "https://goo.gl/maps/pMxNcrAoWE9tGqtbAB",
  },
  {
    id: 2,
    image: "assets/Jammu & Kashmir/Forts/Amar Mahal Palace (Jammu).jpg",
    name: "Amar Mahal Palace",
    category: "Forts",
    description:  "https://www.goibibo.com/destinations/jammu/places-to-visit-in-jammu/amar-mahal-palace-museum-669534706962280375/",
    info:"To get a glimpse into the royal past of Jammu & Kashmir, one should visit the Amar Mahal, a famous tourist attraction in Jammu city. Once a palace constructed for Raja Amar Singh,it is now a museum housing several important artefacts, the most attractive one of which is the Golden Throne weighing 120 kilograms.",
    map : "https://goo.gl/maps/f9eJy5eMfLDoj99x7",
   },
  {
    id: 3,
    image: "assets/Jammu & Kashmir/Forts/Hari Parbat Fort (Srinagar).jpg",
    name: "Hari Parbat Fort",
    category: "Forts",
    description:"https://www.tripadvisor.in/Attraction_Review-g297623-d338347-Reviews-Hari_Parbat-Srinagar_Srinagar_District_Kashmir_Jammu_and_Kashmir.html",
    info:"Hari Parbat (Kashmiri pronunciation: [haːri parbatʰ]), also called Koh-i-Maran (Kashmiri pronunciation: [koːhi maːraːn]), is a hill overlooking Srinagar, the largest city and the capital of Jammu and Kashmir, India.",
    map : "https://goo.gl/maps/KffVSYUMsNN1eY5NA"
   },
  {
    id: 4,
    image: "assets/Jammu & Kashmir/Forts/Mubarak Mandi Palace (Jammu).jpg",
    name: "Mubarak Mandi Palace",
    category: "Forts",
    description: "https://www.triphobo.com/places/jammu-india/mubarak-mandi-palace",
    info:"Mubarak Mandi is a Palace in Jammu, India. The palace was the royal residence of the Maharaja of Jammu and Kashmir from the Dogra dynasty. It was their main seat till 1925 when Maharaja Hari Singh moved to the Hari Niwas Palace in the northern part of Jammu.",
    map : "https://goo.gl/maps/XZBz7tRfVWhDwnFa7"},
  {
    id: 5,
    image: "assets/Jammu & Kashmir/Forts/Ramnagar Fort (Jammu).jpg",
    name: "Ramnagar Fort",
    category: "Forts",
    description: "https://udhampur.nic.in/tourist-place/ramnagar-fort/",
    info:"Ramnagar is situated on the left bank of Kud river in mid Himalayan range, about 40 kms west of Udhampur. Ramnagar also served as the captial of old Bandarlta State. During the reign of Maharaja Ranjit Singh, it came under Sikh ruke and Raja Suchet Singh.",
    map : "https://goo.gl/maps/oakrQPfypiEhQZXL7",
    },
  {
    id: 6,
    image: "assets/Jammu & Kashmir/Forts/Sheesh Mahal Ramnagar (J&K) (1).jpg",
    name: "Sheesh Mahal Ramnagar",
    category: "Forts",
    description: "https://www.redbus.in/buses/ramnagar-uttrakhand-bus-tickets",
    info:"Sheesh Mahal of Ramnagar is a historical royal mansion of Jammu and Kashmir. It is located just adjacent to Ramnagar Fort in Ramnagar of Udhampur district.The palace got its name Sheesh Mahal from its adorned mirror work and thus it also named as Palace of Mirror.",
    map : "https://goo.gl/maps/tigZa7waG5HKZu9S9"
  },
 {
  id: 7, 
  image: "assets/Jammu & Kashmir/Heritage/Akhnoor Fort, Jammu.jpg",
  name: "Akhnoor Fort",
  category: "Heritage",
  description: "https://www.abhibus.com/bus/akhnoor-bus-tickets",
  info:" The Akhnoor fort which lies towards east of the town, on the bank of the Chenab river holds great significance and is extremely important for reconstruction of the past history. The fort was built by Raja Alam Singh in 1802. ",
  map : "https://goo.gl/maps/pMxNcrAoWE9tGqtbAB",
},
{
  id: 8,
  image: "assets/Jammu & Kashmir/Heritage/Amar Mahal, Jammu.jpg",
  name: "Amarmahal Palace",
  category: "Heritage",
  description:  "https://www.goibibo.com/destinations/jammu/places-to-visit-in-jammu/amar-mahal-palace-museum-669534706962280375/",
  info:"To get a glimpse into the royal past of Jammu & Kashmir, one should visit the Amar Mahal, a famous tourist attraction in Jammu city. Once a palace constructed for Raja Amar Singh,it is now a museum housing several important artefacts, the most attractive one of which is the Golden Throne weighing 120 kilograms.",
  map : "https://goo.gl/maps/f9eJy5eMfLDoj99x7",
 },
  {
      id: 9, 
      image: "assets/Jammu & Kashmir/Heritage/bahu Fort, Jammu.jpg",
      name: "Bahu Fort",
      category: "Heritage",
      description: "hhttps://jammu.nic.in/tourist-place/bahu-fort-jammu/",
      info:" Situated 5 kms away from the city centre, Bahu Fort stands on a rock face on the left bank of the river Tawi. Perhaps the oldest fort and edifice in the city, it was constructed originally by Raja Bahulochan over 3,000 years ago.",
      map : "https://goo.gl/maps/qTEJchnb88m6YsYi7",
    },
    {
      id: 10,
      image: "assets/Jammu & Kashmir/Heritage/Hari Parbat Fort, Srinagar.jpg",
      name: "Hari Parbat Fort",
      category: "Heritage",
      description:"https://www.tripadvisor.in/Attraction_Review-g297623-d338347-Reviews-Hari_Parbat-Srinagar_Srinagar_District_Kashmir_Jammu_and_Kashmir.html",
      info:"Hari Parbat (Kashmiri pronunciation: [hari parbatʰ]), also called Koh-i-Maran (Kashmiri pronunciation: [koːhi maːraːn]), is a hill overlooking Srinagar, the largest city and the capital of Jammu and Kashmir, India.",
    map : "https://goo.gl/maps/KffVSYUMsNN1eY5NA"
      },
    {
      id: 11,
      image: "assets/Jammu & Kashmir/Heritage/Mughal Gardens, Srinagar.jpg",
      name: "Mughal Gardens",
      category: "Heritage",
      description: "https://rb.nic.in/rbvisit/rbvisit_mughal.aspx",
      info:"Spread over a vast expanse of 15 acres, Mughal Gardens has often been portrayed, and deservedly so, as the soul of the Presidential Palace. The Mughal Gardens draw its inspiration from the Mughal Gardens of Jammu and Kashmir",
      map : "https://goo.gl/maps/axV2ePaogJKUVeDJ7"
     },
    {
      id: 12,
      image: "assets/Jammu & Kashmir/Heritage/Pari Mahal, Srinagar.jpg",
      name: "Pari Mahal",
      category: "Heritage",
      description: "https://www.abhibus.com/?msclkid=40b1195b6ad21660d41b7a35470b5113&utm_source=bing&utm_medium=cpc&utm_campaign=APSRTC_India&utm_term=apsrtc%20online%20bus%20ticket%20booking&utm_content=APSRTC",
      info:"Pari Mahal or Peer Mahal, also known as The Palace of Fairies, is a seven-terraced garden located at the top of Zabarwan mountain range, overlooking the city of Srinagar and the south-west of Dal Lake in the Indian union territory of Jammu and Kashmir. ",
      map : "https://goo.gl/maps/cKh3zGZjw5dM1FrV9"
    },
    {
      id: 13,
      image: "assets/Jammu & Kashmir/HillStation/aruvalley.jpg",
      name: "Aruvalley",
      category: "Hill Stations",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Aru is a village, tourist spot in the Anantnag District of Jammu and Kashmir, India. It lies 53km from Anantnag city, the district headquarter. It is located around 12 km from Pahalgam, 11 km upstream from the Lidder River",
      map : "https://goo.gl/maps/GkxHHFK3uSLrbJxq5",
      },
    {
      id: 14,
      image: "assets/Jammu & Kashmir/HillStation/dah hanu-village-.jpg",
      name: "Dah Hanu Village",
      category: "Hill Stations",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Dah Hanu or Dha and Hanu, popularly known as Aryan villages of Ladakh, are located in Dhahanu valley in North-East of Ladakh, about 160km from Leh town. ",
      map : "https://goo.gl/maps/zQdw1kMvV5amR3if9"
    },
    {
      id: 15,
      image: "assets/Jammu & Kashmir/HillStation/gulmarg.jpg",
      name: "Gulmarg",
      category: "Hill Stations",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Gulmarg, known as Gulmarag in Kashmiri, is a town, hill station, popular skiing destination, and notified area committee in the Baramulla district of Jammu and Kashmir, India. It is located at a distance of 31 km from Baramulla and 49 km from Srinagar.",
      map : "https://goo.gl/maps/kYpsDa49dwa43JH37"
    },
    {
      id: 16,
      image: "assets/Jammu & Kashmir/HillStation/pahalgam.jpg",
      name: "Pahalgam",
      category: "Hill Stations",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Pahalgam is a hill station in the north Indian state of Jammu and Kashmir. Mountain trails run northeast to Amarnath Cave Temple, a Hindu shrine and site of the annual Amarnath Yatra pilgrimage.",
      map : "https://goo.gl/maps/cQFGTpSi7cv1hJsz6"
    },
     {
      id: 17, 
      image: "assets/Jammu & Kashmir/HillStation/patnitop.jpg",
      name: "Patnitop",
      category: "Hill Stations",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Patnitop is a hill station, located, near Udhampur city in the Udhampur district of Jammu and Kashmir, India. It is in located on the Jammu-Srinagar National Highway, 112 km from Jammu, on the way from Udhampur to Srinagar.",
      map : "https://goo.gl/maps/QKBifLvsjaQgt5PK8",
    },
    {
      id: 18,
      image: "assets/Jammu & Kashmir/HillStation/srinagar.jpg",
      name: "Srinagar",
      category: "Hill Stations",
      description:  "https://www.redbus.in/online-booking/jksrtc",
      info:"Srinagar is the largest city and the summer capital of Jammu and Kashmir, India. It lies in the Kashmir Valley on the banks of the Jhelum River, a tributary of the Indus, and Dal and Anchar lakes.",
      map : "https://goo.gl/maps/aZJatVsMn2NPqDCB9",
     },
    {
      id: 19,
      image: "assets/Jammu & Kashmir/Religious/Amarnath-Cave.jpg",
      name: "Shri Amarnath Cave",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Located in Jammu and Kashmir, the Amarnath Cave is a Hindu Shrine and is visited by lakhs of people every year. It is located at an altitude of 3,888 m. The Amarnath falls into the categories of the most famous Hindu Shrines.",
      map : "https://goo.gl/maps/P5dq2Ci7eoyPPobMA"
     },
    {
      id: 20,
      image: "assets/Jammu & Kashmir/Religious/Charar-e-Sharief.jpg",
      name: "Charar-E-Sharif",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Charar-e-Sharief (also spelled Charar-i-Sharief, Charari Sharief, Chrari-Sharif, etc.) is a Sufi Muslim shrine and mosque situated in the town of Charari Sharief in Budgam district of Jammu and Kashmir union territory, India.",
      map : "https://goo.gl/maps/MUCdB6aS7BteMJrk7"},
    {
      id: 21,
      image: "assets/Jammu & Kashmir/Religious/Jamia-Masjid.jpg",
      name: "Jamia Masjid",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Jamia Masjid was built in 1402 by Sultan Sikandar. The existing construction was done on the orders of Mughal Emperor Aurangzeb Alamgir in 1672.",
      map : "https://goo.gl/maps/YXVaUQN1KLwJHNkW9",
      },
    {
      id: 22,
      image: "assets/Jammu & Kashmir/Religious/The-Lord-Surya-or-Martand-Temple.jpg",
      name: "Martand Surya Temple",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"The Martand Sun Temple is a Hindu temple located near the city of Anantnag in the Kashmir Valley of Jammu and Kashmir (union territory), India. It dates back to the eighth century AD and was dedicated to Surya, the chief solar deity in Hinduism",
      map : "https://goo.gl/maps/vrAEETMeoYBTMBvu6"
    },
    {
      id: 23,
      image: "assets/Jammu & Kashmir/Religious/Vaishno-Devi.png",
      name: "Vaishno Devi",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Vaishno Devi Temple is one of the richest temples in India. Authors Michael Barnett and Janice Gross Stein says, 'Mata Vaishno Devi Shrine in Jammu has an annual income of about $16 million, mainly from offerings by devotees'",
      map : "https://goo.gl/maps/TWyzbG9uxReZBnM26"
    },
    {
      id: 24,
      image: "assets/Jammu & Kashmir/Religious/Ziarat-Dastgir-Sahib.jpg",
      name: "Ziarat Dastgir Sahib",
      category: "Religious",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Dastgeer Sahib is a 200-year-old shrine situated in Khanyar.It has the old Quran written by Ali Ibn Abi Talib A.S, and the relic which is locally called Mouia Pak, a hair strand of Abdul Qadir Gilani.",
      map : "https://goo.gl/maps/w6AmNHRepmoBPdDp8"
    },
    {
      id: 25, 
      image: "assets/Jammu & Kashmir/WildLife/Achabal Wildlife Sanctuary.jpg",
      name: "Achbal Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Achabal Wildlife Sanctuary is in Anantnag district of Kashmir, 65 kilometres south of Srinagar. It spreads over an area of 0.50 km.The Achabal forest area was once designated as a Game Reserve by the then Maharaja of Kashmir.",
      map : "https://goo.gl/maps/DsSvSn9RnzUfjHL6A",
    },
    {
      id: 26,
      image: "assets/Jammu & Kashmir/WildLife/dachigam national park.jpg",
      name: "Dachigam National Park",
      category: "Wildlife Sanctuaries",
      description:  "https://www.redbus.in/online-booking/jksrtc",
      info:"Dachigam National Park is a national park located, 22 kilometres (14 mi) from Srinagar city in Srinagar district of Jammu and Kashmir, India on the east side of Dal Lake.",
      map : "https://goo.gl/maps/W2r3y58px49gzErC6",
     },
    {
      id: 27,
      image: "aassets/Jammu & Kashmir/WildLife/Hirpora Wildlife Sanctuary.jpg",
      name: "Hirpora Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Hirpora Wildlife Sanctuary or Heerpora Wildlife Sanctuary is located in Shopian district of Jammu and Kashmir, 70 kilometers south of Srinagar. It spreads over an area of 341 km 2. ",
      map : "https://goo.gl/maps/xqz5ttS6wCxkvHpy6"
     },
    {
      id: 28,
      image: "assets/Jammu & Kashmir/WildLife/Kazinag National Park.jpg",
      name: "Kazinag National Park",
      category: "Wildlife Sanctuaries",
      description: "https://www.redbus.in/online-booking/jksrtc",
      map : "https://www.google.com/maps/place/Melghat+Tiger+Reserve/@21.4060416,77.1485163,17z/data=!3m1!4b1!4m6!3m5!1s0x3bd7ab82e128568b:0x542a36b7efdedfa2!8m2!3d21.4060416!4d77.1485163!16s%2Fm%2F03wfn48?hl=en-GB"},
    {
      id: 29,
      image: "assets/Jammu & Kashmir/WildLife/Kishtwar High Altitude National Park.jpg",
      name: "Kishtwar High Altitude National Park",
      category: "Wildlife Sanctuaries",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"Kazinag National Park is a commissioned future national park in Baramulla city of the Baramulla district in the Indian union territory of Jammu and Kashmir. It is part of a proposal for a trans-Karakoram peace park with Pakistan. ",
      map : "https://goo.gl/maps/kha5TpKEMwhDMA5u5",
      },
    {
      id: 30,
      image: "assets/Jammu & Kashmir/WildLife/Overa Aru Wildlife Sanctuary.jpg",
      name: "Overa Aru Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.redbus.in/online-booking/jksrtc",
      info:"The Overa-Aru Wildlife Sanctuary is a protected area in Aru Valley, Pahalgam near Anantnag city in Anantnag district of Jammu and Kashmir, India. It lies 46 km from Anantnag city, the district headquarter.",
      map : "https://goo.gl/maps/qvX5H8eyZwdqyqn79",
    },
    {
      id: 31,
      image: "assets/Jammu & Kashmir/Food/Chaaman.jpg",
      name: "Chaaman",
      category: "Food",
      info:"Tamatar Chaaman is a Kashmiri paneer dish with lots of spices. Fried pieces of paneer combined with a spicy tomato gravy. ",
    
    },
    {
      id: 32,
      image: "assets/Jammu & Kashmir/Food/Haakh.jpg",
      name: "Haakh",
      category: "Food",
      info:" Haakh- Collard Greens cooked in Kashmiri Style ; A staple Kashmiri dish.  These greens are simply cooked, yet taste heavenly. This can be made with Kohl Rabi greens/Kai lan/ spinach/ collard greens as well. "
     ,
    },      {
      id: 33,
      image: "assets/Jammu & Kashmir/Food/Kaahwa.jpg",
      name: "Kaahwa",
      category: "Food",
      info:"he Kashmiri kahwah is made by boiling green tea leaves with local saffron, cinnamon, cardamom and occasionally Kashmiri roses. It is generally served with sugar or honey and crushed nuts, usually almonds or walnuts. ",
      
    },
    {
      id: 34, 
      image: "assets/Jammu & Kashmir/Food/Kashmiri-Dum-Aloo.jpg",
      name: "Kashmiri Dum Aloo",
      category: "Food",
      info:"Dum aloo, also called alu dum, is a traditional Indian dish with origins in Kashmir. The dish consists of potatoes, tomatoes, and onions that are cooked together in curry or masala sauce.",
     
    },
    {
      id: 35,
      image: "assets/Jammu & Kashmir/Food/rogan josh.jpg",
      name: "Rogan Josh",
      category: "Food",
      info:"Rogan josh is an aromatic lamb curry that is believed to be of Persian origin, although today it is more closely associated with the Kashmir region of India. The stew is characterized by tender meat and a thick, fiery red sauce coming from deseeded Kashmiri chillies."
      
     },
    {
      id: 36,
      image: "assets/Jammu & Kashmir/Food/Sheer-Chai.jpg",
      name: "Sheer Chai",
      category: "Food",
      info:"Sheer Chai is a pink colored tea with taste as unique as its appearance with a rich and a creamy texture that makes it look somewhat similar to Ladhaki butter tea.",
     
     },
    

];

export default JammuKashmirData;