const KarnatakaData = [
  {
    id: 1, 
    image: "assets/Karnataka/Beaches/devbagh-beach-karwar-2.jpg",
    name: "Devbagh Beach",
    category: "Beaches",
    description: "https://www.redbus.in/bus-tickets/",
    info:"Devbagh is the most popular beach in the coastal city of Karwar, headquarters of the Uttara Kannada district. Devbagh beach is really a perfect getaway for tourists searching for privacy as well as calm.",
    map : "https://goo.gl/maps/oZ9qHZVxgr4xozXcA",
  },
  {
    id: 2,
    image: "assets/Karnataka/Beaches/Kudle-Beach.jpg",
    name: "Kudle Beach",
    category: "Beaches",
    description:  "https://www.redbus.in/bus-tickets/",
    info:"Kudle Beach is one of the many beaches of Gokarna,situated only a short trek from Om Beach. A complete recluse, this beach offers, a walk along the shore or simply sit and observe the never-ceasing tides.",
    map : "https://goo.gl/maps/7G1uFxAiNHKF6HGY6",
   },
  {
    id: 3,
    image: "assets/Karnataka/Beaches/Kasarkod-beach.jpg",
    name: "Kasarkod Beach",
    category: "Beaches",
    description: "https://www.redbus.in/bus-tickets/",
    info:"The Kasarkod beach stretches up to a distance of 5 Kilometers. This virgin beach is covered in white sand and surrounded by Casuarinas. ",
    map : "https://goo.gl/maps/XJm4d4V8bcH5AQNo9",
   },
  {
    id: 4,
    image: "assets/Karnataka/Beaches/Padubidri-Beach.jpg",
    name: "Padubudri Beach",
    category: "Beaches",
    description: "https://www.redbus.in/bus-tickets/",
    info:"The Padubidri beach is located in Udupi, in Karnataka. Apart from Kasarkod, this beach also has won the Blue Flag Tag which it truly deserves. This beachfront is excellent for witnessing glamorous sunsets as well as sunrises.",
    map : "https://goo.gl/maps/Acx8ZAKPzHY4Sp2z7"
  },
  {
    id: 5,
    image: "assets/Karnataka/Beaches/Tannirbhavi-Beach.jpg",
    name: "Tannirbhavi Beach ",
    category: "Beaches",
    description: "https://www.redbus.in/bus-tickets/",
    info:"Tannirbhavi Beach is a popular beach near Mangaluru city in coastal Karnataka. Beach Activities: Tannirbhavi beach is a safe place for beach activities with family, thanks to the presence of life guards and large crowds.",
    map : "https://goo.gl/maps/MjtTcajsoWo8pVQz9",
    },
  {
    id: 6,
    image: "assets/Karnataka/Beaches/Paradise-Beach1.jpg",
    name: "Paradise Beach",
    category: "Beaches",
    description: "https://www.redbus.in/bus-tickets/",
    info:"Paradise Beach, also known as Plage Paradiso, is situated in Chunnambar, close to Pondicherry town. Adorned with the golden sand, this famous and highly sought after beach is always swaying in a cold sea breeze.",
    map : "https://goo.gl/maps/MTihhbf3vJJQxSwSA"
  },
  {
    id: 7,
    image: "assets/Karnataka/Forts/anegondi_fort.jpg",
    name: "Anegondi Fort",
    category: "Forts",
    description: "https://ksrtc.in/oprs-web/",
    info:"In Kannada language, Anegundi means the elephant pit. This place was used for bathing the elephants of Vijayanagara Empire and also became the first capital of the empire.",
    map : "https://goo.gl/maps/CcYvcbRTG8vALDDH6"
  },
  {
    id: 8,
    image: "assets/Karnataka/Forts/bidar_fort.jpg",
    name: "Bidar Fort",
    category: "Forts",
    description: "https://ksrtc.in/oprs-web/",
    info:"Bidar Fort,the city and the district are all affixed with the name Bidar. Sultan Alla-Ud Din Bahman of the Bahmanid Dynasty shifted his capital from Gulbarga to Bidar in 1427 and built his fort along with a number of Islamic monuments.",
    map : "https://goo.gl/maps/a1so4TCLx6CTD7cG7"
  },
  {
      id: 9, 
      image: "assets/Karnataka/Forts/chitradurga_fort.jpg",
      name: "Chitradurga Fort",
      category: "Forts",
      description: "https://ksrtc.in/oprs-web/",
      info:"Chitradurga Fort, or as the British called it Chitaldoorg, is a fortification that straddles several hills and a peak overlooking a flat valley in the Chitradurga District, Karnataka, India.",
      map : "https://goo.gl/maps/Gp8ayx3BNTtFdg9X9",
    },
    {
      id: 10,
      image: "assets/Karnataka/Forts/gulbarga_fort.jpg",
      name: "Gulbarga Fort",
      category: "Forts",
      description:  "https://ksrtc.in/oprs-web/",
      info:"The Gulbarga Fort is located in Kalaburagi in the Kalaburagi district of North Karnataka. It was subsequently significantly enlarged in 1347 by Al-ud-din Hasan Bahmani of the Bahmani Dynasty after he cut off his ties with the Delhi Sultanate.",
      map : "https://goo.gl/maps/S1EwPFSfM7oup4w27",
     },
    {
      id: 11,
      image: "assets/Karnataka/Forts/manjarabad_fort.jpg",
      name: "Manjarabad Fort",
      category: "Forts",
      description: "https://ksrtc.in/oprs-web/",
      info:"Manjarabad fort is a star fort built in 1792 by Tipu Sultan the then Sarvadhakari/ruling on behalf of Mysore King of Mysore following French star-shaped fort designs made popular by Sébastien Le Prestre de Vauban",
      map : "https://goo.gl/maps/goizinbt11Q4DNgY6"
     },
    {
      id: 12,
      image: "assets/Karnataka/Forts/saundatti_fort.jpg",
      name: "Saundatti Fort",
      category: "Forts",
      description: "https://ksrtc.in/oprs-web/",
      info:"Saundatti Fort is located atop a small hill and is said to have been built by Jayappa Desai in the early 18th century. However, later on, the fort was captured by Hyder Ali of the Mysore Kingdom. ",
      map : "https://goo.gl/maps/KgqNNBmuCQ9yv38z6"
    },
    {
      id: 13,
      image: "assets/Karnataka/Heritage/bangalorepalace.jpg",
      name: "Banglore Palace",
      category: "Heritage",
      description: "https://ksrtc.in/oprs-web/",
      info:"Bangalore Palace is a royal palace located in Bengaluru, Karnataka, India, in an area that was owned by Rev. J. Garrett, the first principal of the Central High School in Bangalore, now famous as Central College. ",
      map : "https://g.page/bangalorepalace?share",
      },
    {
      id: 14,
      image: "assets/Karnataka/Heritage/belur-1024x683.jpg",
      name: "Belur",
      category: "Heritage",
      description: "https://ksrtc.in/oprs-web/",
      info:"Belur, is a Town Municipal Council and taluka in Hassan district in the state of Karnataka, India. The town is renowned for its Chennakeshava Temple, one of the finest examples of Hoysala architecture .",
      map : "https://goo.gl/maps/vxta22AuV4MRfSQX6",
    },
    {
      id: 15,
      image: "assets/Karnataka/Heritage/Srirangapatna_tipu_palace-1.jpg",
      name: "Srirangapatna Tipu Palace",
      category: "Heritage",
      description: "https://ksrtc.in/oprs-web/",
      ibfo:"Tipu Sultan’s Summer Palace in Srirangapatna, also referred to as Dariya Daulat Bagh was being used as summer retreat by former Mysuru ruler, Tipu Sultan. Tipu Sultan’s summer palace was built during 1778-1784 AD.",
      map : "https://goo.gl/maps/z3EXaNUUYFsmFYVa9",
    },
    {
      id: 16,
      image: "assets/Karnataka/Heritage/gulbarga-606.jpeg",
      name: "Gulbarga",
      category: "Heritage",
      description: "https://ksrtc.in/oprs-web/",
      info:"Gulbarga Officially known as Kalaburagi, Gulbarga lies in the state of Karnataka in India. It's one of the major cities in North Karnataka which was under the rule of the Bahmani Empire for a long time.",
      map : "https://goo.gl/maps/dtMSmSbcQXksTtNV6"
    },
     {
      id: 17, 
      image: "assets/Karnataka/Heritage/mysore-palace.jpg",
      name: "Mysore Palace",
      category: "Heritage",
      description: "https://ksrtc.in/oprs-web/",
      info:"The Mysore Palace, also known as Amba Vilas Palace, is a historical palace and a royal residence. It is located in Mysore, Karnataka. It used to be the official residence of the Wadiyar dynasty and the seat of the Kingdom of Mysore.",
      map : "https://goo.gl/maps/xyXPQMRiVezFDfuR9",
    },
    {
      id: 18,
      image: "assets/Karnataka/Heritage/somnathpur.jpg",
      name: "Somnathapura",
      category: "Heritage",
      description:  "https://ksrtc.in/oprs-web/",
      info:"Somnathpur is a home to the popular Keshava temple built during the reign of Hoysala emperors. The temple stands erect as a symbol of great authority and skills possessed by Hoysala rulers.",
      map : "https://goo.gl/maps/1heqKvheW5mUr3PA8",
     },
    {
      id: 19,
      image: "assets/Karnataka/Hillstation/Agumbe.jpg",
      name: "Agumbe",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"Agumbe is a high-altitude village in the southwest Indian state of Karnataka. Surrounded by the Western Ghats mountains and lush rainforest, it’s known its many waterfalls, such as Onake Abbi, Bakarna and Jogi Gundi falls. ",
      map : "https://goo.gl/maps/rhG4vSXvdCzLHHKS8",
     },
    {
      id: 20,
      image: "assets/Karnataka/Hillstation/br.jpg",
      name: "BR Hills",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"The Biligirirangana Hills, commonly called BR Hills, is a hill range situated in south-eastern Karnataka, at its border with Tamil Nadu in South India. The area is called Biligiriranganatha Swamy Temple Wildlife Sanctuary or simply BRT Wildlife Sanctuary.",
      map : "https://goo.gl/maps/K4upUF5q1TAk2EedA"},
    {
      id: 21,
      image: "assets/Karnataka/Hillstation/CHIKMAGALUR.jpg",
      name: "Chikmagalur",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"Chikmagalur is situated in the Malenadu region of Karnataka in the Deccan plateau in the foothills of the Western Ghats. It is situated at an elevation of 1,090 metres (3,580 ft) above mean sea level.",
      map : "https://goo.gl/maps/kte37ACMjWjCZriQ6",
      },
    {
      id: 22,
      image: "assets/Karnataka/Hillstation/Madikeri.jpg",
      name: "Madikeri",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"Madikeri is a famous hill station in Karnataka, which maintains a minimum temperature of 11°C in summer and 4.5°C in winter. Tourists can visit this place to enjoy its pleasant weather and lush green beauty.",
      map : "https://goo.gl/maps/mck55nNpnQpMM2729"
    },
    {
      id: 23,
      image: "assets/Karnataka/Hillstation/NANDI-HILLS.jpg",
      name: "Nandi Hils",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"Nandi Hills, or Nandidurg, is a hill fortress in the south Indian state of Karnataka. Tipu Sultan Fort, a summer retreat of the namesake 18th-century ruler, features stone carvings and wall paintings.",
      map : "https://goo.gl/maps/buMB7TJb1ygNLw1s6"
    },
    {
      id: 24,
      image: "assets/Karnataka/Hillstation/Raamadevara Betta.jpg",
      name: "Raamadevara Betta",
      category: "Hill Stations",
      description: "https://ksrtc.in/oprs-web/",
      info:"Ramdevara Betta is situated 50 kilometres away from Bangalore in the district of Ramanagara. The famous blockbuster Sholay was shot on this picturesque Hill. Since the 1970s this location has become extremely popular among tourists.",
      map : "https://goo.gl/maps/eTsgcnCYpE87fMz47"
    },
    {
      id: 25, 
      image: "assets/Karnataka/Religious/baba-budangiri.jpg",
      name: "Baba Budangiri",
      category: "Religious",
      description: "https://ksrtc.in/oprs-web/",
      info:"Baba Budangiri is a mountain in the Baba Budan range of the Western Ghats of India.Baba Budangiri is known for its shrine to the Sufi saint Baba Budan, a pilgrimage site for both Hindus and Muslims .",
      map : "https://goo.gl/maps/FmjyZXyLMsaxTJUt7",
    },
    {
      id: 26,
      image: "assets/Karnataka/Religious/Gokarna.jpg",
      name: "Gokarna Mahabaleshwar Temple",
      category: "Religious",
      description:  "https://ksrtc.in/oprs-web/",
      info:"Gokarna Mahabaleshwar Temple is located in the coastal town of Gokarna in Karnataka.The Hindu Saint Sri Adi Shankaracharya established the Shree Ramachandrapura Mutt in Gokarna who look after the administration of the Gokarna Temple. ",
      map : "https://goo.gl/maps/Xp7KnzRsjv9kFH9g7",
     },
    {
      id: 27,
      image: "assets/Karnataka/Religious/Kolluur-Mookambika-Temple.jpg",
      name: "Kollar Mookambika",
      category: "Religious",
      description: "https://ksrtc.in/oprs-web/",
      info:"Sri Mookambika Temple in Kollur, Udupi district attracts devotees from all parts of South India. The village of Kollur lies amid the green canopy of the Western Ghats, on the base of Kodachadri Hill.",
      map : "https://goo.gl/maps/hg6JrRtrXbPsjKEA8"
     },
    {
      id: 28,
      image: "assets/Karnataka/Religious/Murudeshwar.jpg",
      name: "Murudeshwar",
      category: "Religious",
      description: "https://ksrtc.in/oprs-web/",
      info:"Murdeshwar is a town in Uttara Kannada district in the state of Karnataka, India.It is famous for the world's second tallest Shiva statue, the town lies on the coast of the Arabian Sea and is also famous for the Murudeshwara Temple.",
      map : "https://goo.gl/maps/Fp7sAgULdifrpfC16"},
    {
      id: 29,
      image: "assets/Karnataka/Religious/Srirangapatna-1.jpg",
      name: "Srirangapatna",
      category: "Religious",
      description: "https://ksrtc.in/oprs-web/",
      info:"Srirangapatna is a town and is the headquarters of one of the seven Taluks of Mandya district, in the Indian State of Karnataka. Located near the city of Mandya, it is of religious, cultural and historic importance.",
      map : "https://goo.gl/maps/vJ6Y9rAR1JADpqyPA",
      },
    {
      id: 30,
      image: "assets/Karnataka/Religious/UDUPI.jpg",
      name: "Udupi",
      category: "Religious",
      description: "https://ksrtc.in/oprs-web/",
      info:"Sri Krishna Temple in Udupi is an important pilgrimage site in South India. Thousands of devotees throng this temple town to offer prayers to Lord Krishna. ",
      map : "https://goo.gl/maps/FvysEwRcVw6wWeqH8"
    },
    {
      id: 31,
      image: "assets/Karnataka/WildLife/Anshi-National-Park.jpg",
      name: "Anshi National Park",
      category: "Wildlife Sancturies",
      description: "https://ksrtc.in/oprs-web/",
      info:"The Anshi National Park is an evergreen tropical rainforest situated in the North Kannada district in Karnataka. The park covering an area of 340 sq km is considered as India’s most endangered wildlife park.",
      map : "https://goo.gl/maps/TJ1eJ2ttJ7LZUXEU6"
    },
    {
      id: 32,
      image: "assets/Karnataka/WildLife/Kabini-National-Park.jpg",
      name: "Kabini National Park",
      category: "Wildlife Sancturies",
      description: "https://ksrtc.in/oprs-web/",
      info:"Kabini National Park is a popular wildlife destination of South India,located in the state of Karnataka.On the banks of one of its prime attraction, Kabini River, one can easily spot wild animals like elephants and tigers.",
      map : "https://goo.gl/maps/L22B2i9MJEbQWc3u5"
    },
    {
      id: 33,
      image: "assets/Karnataka/WildLife/Kudremukh-National-Park.jpg",
      name: "Kudremukh National Park",
      category: "Wildlife Sancturies",
      descripion: "https://ksrtc.in/oprs-web/",
      info:"The Kudremukh National Park is located at a distance of 96 km from the district of Chikmagalur in the state of Karnataka in India. ",
      map : "https://goo.gl/maps/NZX9Hw4wwSzPgwFg6"
    },
    {
      id: 34, 
      image: "assets/Karnataka/WildLife/Mookambika-Wildlife-Sanctuary.jpg",
      name: "Mookambika Wildlife Sanctury",
      category: "Wildlife Sancturies",
      description: "https://ksrtc.in/oprs-web/",
      info:"Mookambika Wildlife Sanctuary is a protected wildlife sanctuary in the southern state of Karnataka in India. It derives its name from the presiding deity 'Goddess Mookambika' of the popular Kollur Mookambika Temple.",
      map : "https://goo.gl/maps/o92hbrmvY4DjgNcy9",
    },
    {
      id: 35,
      image: "assets/Karnataka/WildLife/Nagarhole-National-Park-2.jpg",
      name: "Nagarhole National Park",
      category: "Wildlife Sancturies",
      description:  "https://ksrtc.in/oprs-web/",
      info:"Nagarhole National Park is a national park located in Kodagu district and Mysore district. It is one of India's premier Tiger Reserves along with the adjoining Bandipur Tiger Reserve and Wayanad Wildlife Sanctuary.",
      map : "https://goo.gl/maps/nheVhhmqS3Pcf6Q68",
     },
    {
      id: 36,
      image: "assets/Karnataka/WildLife/Pilikula-Nisargadhama.jpeg",
      name: "Pilikula Nisargdhama",
      category: "Wildlife Sancturies",
      description: "https://ksrtc.in/oprs-web/",
      info:"Pilikula Nisarga Dhama (Pilikula) is a major eco-education and tourism development project promoted by the District Administration of Dakshina Kannada in the beautiful city of Mangaluru in Karnataka State, India."
      ,map : "https://goo.gl/maps/ZyWuoAkgTvrtxF7P6"
     },
     {
      id: 37,
      image: "assets/Karnataka/Food/Allugedda.jpg",
      name: "Allugedda",
      category: "Food",
      info:"Allugedda is a dish of potatoes mashed with tomato, onion and black gram. They are usually served as a side dish with dosa or rice. Allugedda can be prepared as spicy and hot as one's preference.",
      
    },
    {
      id: 38,
      image: "assets/Karnataka/Food/Bisi Bele Bath.jpg",
      name: "Bisi Bela Bath",
      category: "Food",
      info:"Bisi Bele Bath is a traditional recipe of Karnataka that is prepared in every Kannadiga's home. The dish has a distinct coconut flavour and is available at any restaurant in Bangalore. The recipe is a complicated one that involves many vegetables and flavours but the dish is a must try. ",
    
    },
    {
      id: 39,
      image: "assets/Karnataka/Food/Coorg Pandi Curry.jpg",
      name: "Coorg Pandi Curry",
      category: "Food",
      info:"Coorg Style Pandi Curry is a specialty pork dish of Coorgi Cuisine. Spicy, rich and flavorful pork dish is unique and special with the distinct flavor of Kachampuli extract. This extract is peculiar to the region and the tribal folks have mastered the art. ",
      
    },
    {
      id: 40, 
      image: "assets/Karnataka/Food/Haalbai.jpg",
      name: "Haalbai",
      category: "Food",
      info:"Haalbai is a famous sweet from Karnataka that is made from rice, coconut and jaggery. Coconut milk is also added to give a distinct coconut flavour and to help in combining the ingredients. The sweet is prepared during festive seasons. It can be served warm or cool as per one's preference.        ",
    
    },
    {
      id: 41,
      image: "assets/Karnataka/Food/Kundapura Koli Saaru.jpg",
      name: "Kundapura Koli Saaru ",
      category: "Food",
      info:"Kundapura Koli Saaru is another style of Chicken curry and is very popular on the Mangalorean coastal region. The gravy of the curry is made from onion, garlic, ginger and other spices along with coconut milk. The curry is perfect to have with neer dosa, roti or even rice.        ",
    },
    {
      id: 42,
      image: "assets/Karnataka/Food/Mysore  Pak.jpg",
      name: " Mysore Pak",
      category: "Food",
      info:"Mysore Pak is a simple but very famous sweet that is popular all across India. Mysore Pak is made from three ingredients only - Besan (Gram Flour), Ghee and sugar. The texture of the sweet feels rich due to besan and ghee. The sweet is widely distributed especially during Diwali."},
      
   
     
];

export default KarnatakaData;
