const KeralaData = [
  {
    id: 1, 
    image: "assets/Kerala/Beaches/alleppey-beach-kerala-sunset.jpg",
    name: "Alappuzha beach,Alleppey",
    category: "Beaches",
    description: "https://www.trawell.in/kerala/alleppey/alappuzha-beach",
    info:"Alappuzha, or Alleppey is referred to as the Venice of the East which has always enjoyed an important place in the maritime history of Kerala. Presently it is famous for its boat races, backwater holidays, beaches, marine products and coir industry. ",
    map : "https://goo.gl/maps/Q1VJLaRWRpsYEaes5",
  },
  {
    id: 2,
    image: "assets/Kerala/Beaches/bekal-kerala.jpg",
    name: "Bekal Beach",
    category: "Beaches",
    description:  "https://www.rome2rio.com/s/Bekal/Kerala",
    info:"Situated on the broad expanse of the Malabar coastline, Bekal beach is popular for its backwaters, forts and scenic beauty. It's a very small region on the shores of Arabian Sea, which is known for its unparalleled charm that holds various attractions ",
    map : "https://goo.gl/maps/PN2pJKwcNekukTb5A",
   },
  {
    id: 3,
    image: "assets/Kerala/Beaches/beypore-beach.jpg",
    name: "Beypore Beach",
    category: "Beaches",
    description: "https://www.goibibo.com/destinations/kozhikode/places-to-visit-in-kozhikode/beypore-5422766535183736839/",
    info:"Beypore beach is located 15 km away from Kadavu, at the jaws of Chaliyar River. The charming beach is just like a treasure of peace and tranquility with its picturesque atmosphere, wide stretches of golden sands and fascinating coconut trees",
    map : "https://goo.gl/maps/Et1rXyHy2LJJfiFk9"
   },
  {
    id: 4,
    image: "assets/Kerala/Beaches/kappad-beach-kerala.jpg",
    name: "Kappad Beach",
    category: "Beaches",
    description: "https://www.tripadvisor.in/Attraction_Review-g297635-d1908801-Reviews-Kappad_Beach-Kozhikode_Kozhikode_District_Kerala.html",
    info:"Kappad beach is a very calm beach and have very much historical importance. It's said that Vasco Da Gama from Portugal landed here in the shore of Kappad. This is a very clam beach. There is hure rock in one side of this beach.",
    map : "https://goo.gl/maps/RGDHAPwi8Ny4svLs5"},
  {
    id: 5,
    image: "assets/Kerala/Beaches/marari-beach-kerala-alleppey.jpg",
    name: "Marari Beach",
    category: "Beaches",
    description: "https://www.rome2rio.com/s/Marari-Beach/Kovalam",
    info:"Marari Beach, a secluded little known beach destination in the Alappuzha, is located about 11 km from Alappuzha town.The fisherfolk of Mararikulam and their gentle ways of life are some of the attractions here",
    map : "https://goo.gl/maps/ro6qrUVL5Nz9oHU2A",
    },
  {
    id: 6,
    image: "assets/Kerala/Beaches/varkala-beach-cliff.jpg",
    name: "Varkala Beach",
    category: "Beaches",
    description: "https://www.rome2rio.com/s/Varkala/Juhu-Beach",
    info:"Varkala beach is the only place in southern Kerala where cliffs are found adjacent to the Arabian Sea. These cliffs are of tertiary sedimentary formation, and named by geologists as Varkala Formation.",
    map : "https://goo.gl/maps/VmbNuPTxjGu7L3p97"
  },
  {
      id: 7, 
      image: "assets/Kerala/Forts/bekalforte.jpg",
      name: "Bekal Fort",
      category: "Forts",
      description: "https://www.goibibo.com/destinations/bekal/places-to-visit-in-bekal/bekal-fort/",
      info:"Bekal Fort was built by Shivappa Nayaka of Keladi in 1650 AD, at Bekal. It is the largest fort in Kerala, spreading over 40 acres (160,000 m 2 ). The fort appears to emerge from the sea.",
      map : "https://goo.gl/maps/gCgph3WGiEnqd7qK7",
    },
    {
      id: 8,
      image: "assets/Kerala/Forts/eastforte.jpg",
      name: "East Fort",
      category: "Forts",
      description:  "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"East Fort, located in the heart of Thiruvananthapuram.Sri Padmanabha Swamy Temple is located in the heart of the fort along with a few other attractions like Ganesha Temple, Gandhi Park and Kuthiramalika Palace museum.",
      map : "https://goo.gl/maps/6QDM9qRpuZvxky5FA",
     },
    {
      id: 9,
      image: "assets/Kerala/Forts/kannurforte.jpg",
      name: "Kannur Fort",
      category: "Forts",
      description: "https://www.rome2rio.com/map/Nagpur/Fort-Road",
      info:"Set on a headland that juts into the Arabian Sea, the Kannur Fort is one of the ancient forts in the country. Located along the Malabar coast, the laterite, triangular fort was built by the first Portuguese Viceroy ",
      map : "https://goo.gl/maps/5U6wzKAHsYHcnc3e9"
     },
    {
      id: 10,
      image: "assets/Kerala/Forts/KottappuramFort_20200113161107.jpg",
      name: "Kottappuram Fort",
      category: "Forts",
      description: "https://www.rome2rio.com/map/Nagpur/Thuruthipuram-Bridge-Kottapuram-Kodungallur-Kerala-680664-India",
      info:"Kottappuram Fort is a typical European style of architecture.This fort was built with the locally available large laterite stones, sea rocks, granites stones, big clay bricks and liquefied lime stones which were used as concrete pavements.",
      map : "https://goo.gl/maps/eG3Ck88satokB5v49"
    },
     {
      id: 11, 
      image: "assets/Kerala/Forts/palakkadforte.jpg",
      name: "Pallakad Fort",
      category: "Forts",
      description: "https://www.rome2rio.com/map/Nagpur/New-Civil-Nagar-Palakkad-Kerala-678001-India",
      info:"Palakkad Fort is an old fort situated in the heart of Palakkad city of Kerala state, southern India. It was recaptured and rebuilt grandly by Sultan Hyder Ali in 1766 A.D and remains one of the best-preserved forts in Kerala.",
      map : "https://goo.gl/maps/Qd6VnkKJdYPm3Kkx9",
    },
    {
      id: 12,
      image: "assets/Kerala/Forts/Pallimpur fort.jpg",
      name: "Pallippuram Fort",
      category: "Forts",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Pallippuram Fort is a fort in Pallippuram, Vyppin, Ernakulam district of Kerala, south India. It was built by the Portuguese in 1503 and is the oldest existing European fort in India. ",
      map : "https://goo.gl/maps/hhoPCwvZ1SZLRJ517",
     },
    {
      id: 13,
      image: "assets/Kerala/Heritage/AnjengoFort_Main_thumb.jpg",
      name: "Anjengo Fort",
      category: "Heritage",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Anjengo or Anjuthenguwas a small stretch of land with five coconut trees at the time and the fort was named after the same. The old English Fort that once stood here would be constantly attacked by foreign powers for centuries.",
      map : "https://goo.gl/maps/wdAnjv4KVBwt5DEh6"
     },
    {
      id: 14,
      image: "assets/Kerala/Heritage/BekalFort_.jpg",
      name: "Bekal Fort",
      category: "Heritage",
      description: "https://www.goibibo.com/destinations/bekal/places-to-visit-in-bekal/bekal-fort/",
      info:"Bekal Fort was built by Shivappa Nayaka of Keladi in 1650 AD, at Bekal. It is the largest fort in Kerala, spreading over 40 acres (160,000 m 2 ). The fort appears to emerge from the sea.",
      map : "https://goo.gl/maps/gCgph3WGiEnqd7qK7"},
    {
      id: 15,
      image: "assets/Kerala/Heritage/EdakkalCaves_(Near Wayand).jpg",
      name: "Edakkal Caves",
      category: "Heritage",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Edakkal Caves also Edakal, are two natural caves at Edakkal, in Wayanad district of Kerala.The caves are situated 1,200 m (3,900 ft) above sea level on Ambukutty Mala, on the Mysore Plateau, in the Western Ghats.",
      map : "https://g.page/edakkal-caves?share",
      },
    {
      id: 16,
      image: "assets/Kerala/Heritage/Kasaragod.jpg",
      name: "Kasaragod",
      category: "Heritage",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Kasaragod is a municipal town and administrative headquarters of Kasaragod district in the state of Kerala, India. Established in 1966, Kasaragod was the first municipal town in the district.",
      map : "https://goo.gl/maps/Vub5uVxubastn8Wu8"
    },
    {
      id: 17,
      image: "assets/Kerala/Heritage/KrishnapuramPalace_Main_thumb.jpg",
      name: "Krishnapuram Palace",
      category: "Heritage",
      description:  "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"The Krishnapuram Palace is a palace and museum located in Kayamkulam near Alappuzha in Alappuzha district, Kerala in southwestern India. It was built in the 18th century by Anizham Thirunal Marthanda Varma.",
      map : "https://goo.gl/maps/NJC5ShAjgFB7kqLKA",
     },
    {
      id: 18,
      image: "assets/Kerala/Heritage/Thrissur.jpg",
      name: "Thrissur",
      category: "Heritage",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Thrissur, formerly Trichur, also known by its historical name Thrissivaperur, is a city and the headquarters of the Thrissur district in Kerala, India. It is the third largest urban agglomeration in Kerala after Kochi and Kozhikode.",
      map : "https://goo.gl/maps/iPs4PQbLkVTYThGs5"
     },
    {
      id: 19,
      image: "assets/Kerala/Hill Stations/Devikulam.png",
      name: "Devikulam",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Devikulam is a wonderful picnic spot located 8 kilometres away from Munnar. Its velvet lawns and vast range of exotic flora and fauna have made it a must visit spot for all who are in the vicinity. ",
      map : "https://goo.gl/maps/8tWVeXKbARzdMT8C8"},
    {
      id: 20,
      image: "assets/Kerala/Hill Stations/Gavi.jpg",
      name: "Gavi",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Gavi is a famous eco-tourist spot in Kerala which is popular after 'Alistair International' the world acclaimed tourism major listed it among the leading Eco-tourism centers and gavi is a  must-see places in India.",
      map : "https://goo.gl/maps/VNao6u85SjoeoTB77",
      },
    {
      id: 21,
      image: "assets/Kerala/Hill Stations/Munnar.jpg",
      name: "Munnar",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Munnar is a town and hill station in the Idukki district of the southwestern Indian state of Kerala. Munnar is situated at around 1,600 metres (5,200 ft) above mean sea level, in the Western Ghats mountain range.",
      map : "https://goo.gl/maps/m7akujSRbdZqgfuF9"
    },
    {
      id: 22,
      image: "assets/Kerala/Hill Stations/Peermade.png",
      name: "Peermade",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Peermade,also spelt Peerumade is a village,Grama Panchayat and hill station in the state of Kerala, India.It lies 915 metres above sea level in the Western Ghats about 85 kilometres east of Kottayam.",
      map : "https://goo.gl/maps/xDNaeKb8wPvgrDJVA"
    },
    {
      id: 23,
      image: "assets/Kerala/Hill Stations/Thenmala.jpg",
      name: "Thenmala",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Thenmala is a tourist destination in the eastern side of Kollam district in Kerala, India. The place is world-famous because of the presence of the first eco-tourism centre in India.",
      map : "https://goo.gl/maps/2svrYLFK29heHRmf9"
    },
    {
      id: 24,
      image: "assets/Kerala/Hill Stations/Wayanad-1068x712.jpg",
      name: "Wayanad",
      category: "Hill Stations",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Renowned worldwide for its awe-inspiring beauty, lush-green landscape and serene environment, Wayanad is an enchanting hill station on the earth located on the Western Ghats in the state of Kerala.",
      map : "https://goo.gl/maps/UG5vQMpGvvx1PBTB7"
    },
    {
      id: 25, 
      image: "assets/Kerala/Religious/Guruvayur-Temple.jpg",
      name: "Guruvayur Temple",
      category: "Religious",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Guruvayur Temple is a Hindu temple dedicated to Guruvayurappan, a form of Vishnu, located in the town of Guruvayur in Kerala, India. It is one of the most important places of worship for Hindus in Kerala and Tamil Nadu",
      map : "https://goo.gl/maps/R8yoLuUXgNjX9xEq7",
    },
    {
      id: 26,
      image: "assets/Kerala/Religious/Kollam.jpg",
      name: "Kollam",
      category: "Religious",
      description:  "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Kollam , also known by its former name Quilon pronunciation (help·info), is an ancient seaport and city on the Malabar Coast of India bordering the Laccadive Sea, which is a part of the Arabian Sea. ",
      map : "https://goo.gl/maps/ZUJz5pepTxwofSXD6",
     },
    {
      id: 27,
      image: "assets/Kerala/Religious/Kottayam.jpg",
      name: "Kottayam",
      category: "Religious",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Kottayam is a city in the Indian state of Kerala. Flanked by the Western Ghats on the east and the Vembanad Lake and paddy fields of Kuttanad on the west. It is the district headquarters of Kottayam district, located in south-west Kerala. ",
      map : "https://goo.gl/maps/PJiC5cyhzVtQfppA8"
     },
    {
      id: 28,
      image: "assets/Kerala/Religious/Sabarimala-Temple-in-Kerala.jpg",
      name: "Sabarimala Temple",
      category: "Religious",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"The Sabarimala Temple is a temple complex located at Sabarimala hill inside the Periyar Tiger Reserve in the Perinad Village, Pathanamthitta district, Kerala, India. It is one of the largest annual pilgrimage sites in the world with an estimate of over 10 to 15 million devotees visiting every year.",
      map : "https://goo.gl/maps/t9mpyPbJUtdFsxvq8"},
    {
      id: 29,
      image: "assets/Kerala/Religious/Sri-Padmanabhaswamy-temple.jpg",
      name: "Sri-Padmanabhaswamy Temple",
      category: "Religious",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"The Padmanabhaswamy Temple is located in Thiruvananthapuram (popularly known as Trivandrum), the capital of the state of Kerala in India. The name Thiruvananthapuram which means ‘the city of Lord Ananta’ is an indication of the temple's deep connection with the city.",
      map : "https://goo.gl/maps/Garmg9zmNHbjjiiw7",
      },
    {
      id: 30,
      image: "assets/Kerala/Religious/Thrissur (1).jpg",
      name: "Thrissur",
      category: "Religious",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Thrissur, formerly Trichur, also known by its historical name Thrissivaperur, is a city and the headquarters of the Thrissur district in Kerala, India. It is the third largest urban agglomeration in Kerala after Kochi and Kozhikode.",
      map : "https://goo.gl/maps/iPs4PQbLkVTYThGs5"
    },
    {
      id: 31,
      image: "assets/Kerala/WildLife/chinnar-wildlife-sanctuary.gif",
      name: "Chinnar Wildlife Sanctuary",
      category: "Wildlife Sancturies",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Chinnar Wildlife Sanctuary is located 18 km north of Marayoor on State Highway 17 in the Marayoor and Kanthalloor panchayats of Devikulam taluk in the Idukki district of Kerala state in South India. ",
      map : "https://goo.gl/maps/4xyQaD97gRLRYNGX9"
    },
    {
      id: 32,
      image: "assets/Kerala/WildLife/eravikulam-national-park.gif",
      name: "Eravikulam National Park",
      category: "Wildlife Sancturies",
      description: "https://www.eravikulamnationalpark.in/landing/axRegister.php",
      info:" Eravikulam National Park is a 97 km national park located along the Western Ghats in the Idukki and Ernakulam districts of Kerala in India. Situated between 10º05'N and 10º20' north, and 77º0' and 77º10' east.",
      map : "https://goo.gl/maps/iRLzSxPne3nSKHhp9"
    },
    {
      id: 33,
      image: "assets/Kerala/WildLife/idukki-wildlife-sanctuary.gif",
      name: "Idukki Wildlife Sanctuary",
      category: "Wildlife Sancturies",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Idukki district is among the most naturally endowed districts in Kerala and the Idukki Wildlife Sanctuary is a prime example. Located about 450-750 m above sea level, the sanctuary is cradled by the Cheruthoni and Periyar Rivers.",
      map : "https://goo.gl/maps/xMmCsn8vnQZTF6ZT8"
    },
    {
      id: 34,
      image: "assets/Kerala/WildLife/parambikulam-tiger-reserve05.gif",
      name: "Parambikulam Tiger Reserve",
      category: "Wildlife Sancturies",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Parambikulam Tiger Reserve, which also includes the erstwhile Parambikulam Wildlife Sanctuary, is a 643.66 square kilometres (248.5 sq mi) protected area lying in Palakkad district and Thrissur district of Kerala state, South India.",
      map : "https://goo.gl/maps/iTgR3EeC3FogUio27"
     },
    {
      id: 35,
      image: "assets/Kerala/WildLife/thattekad-wildlife-sanctuary.gif",
      name: "Thattekad Wildlife Sanctuary",
      category: "Wildlife Sancturies",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"The Thattekkad Bird Sanctuary, covering an area of barely 25 km 2,and located about 12 km from Kothamangalam, was the first bird sanctuary in Kerala. Salim Ali, one of the best known ornithologists, described this sanctuary as the richest bird habitat on peninsular India.",
      map : "https://goo.gl/maps/pnjdjoEHEj5mSfGZA"},
    {
      id: 36,
      image: "assets/Kerala/WildLife/kumarakom-bird-sanctuary.gif",
      name: "Kumarakom Bird Sanctuary",
      category: "Wildlife Sancturies",
      description: "https://www.rome2rio.com/s/Fort-Station-India/Kerala",
      info:"Kumarakom Bird Sanctuary (also known as Vembanad Bird Sanctuary) is situated at Kumarakom in Kottayam taluk of Kottayam district in the Indian state of Kerala, on the banks of Vembanad Lake. Set in the Kerala Backwaters, the bird sanctuary is visited by many migratory bird species.",
      map : "https://goo.gl/maps/KQaMnrtkivsTRWwW9",
      },
      {
        id: 37,
        image: "assets/Kerala/Food 2/Banana Fritters.jpg",
        name: "Banana Fritters",
        category: "Food",
        info:"Banana fritters are a type of dessert made by coating or incorporating bananas in a sweet batter, then frying them in oil. Most banana fritters are bite-sized, and can be made either with whole banana segments or mashed fruit formed into round balls.",
        
      },
      {
        id: 38,
        image: "assets/Kerala/Food 2/Iddiyappam.jpg",
        name: "Iddiyappam",
        category: "Food",
        info:"Idiyappam recipe with step by step pics. Idiyappam also known as Nool puttu are string hoppers. Basically these are sevai or seviyan made with rice flour dough. Idiyappam along with Puttu and Appam are a common breakfast in Kerala. ",
      
      },
      {
        id: 39,
        image: "assets/Kerala/Food 2/kerala Style Fish Molee.jpg",
        name: "Kerala Style Fish Molee",
        category: "Food",
        info:"Fish Molee (Fish Molly or Meen Moilee) is a Kerala style Fish Curry where fish is cooked in a coconut milk based gravy. Enjoy this curry with a bowl of steamed rice or appam. ",
        
      },
      {
        id: 40, 
        image: "assets/Kerala/Food 2/Malabar Parota.jpg",
        name: "Malabar Parota",
        category: "Food",
        info:"MALABAR PARATHA is the most popular street food in south India, and you can find parotta stalls across the street at stone’s throw away distance. Malabar parotta is a very renowned and popular bread in Kerala and Tamilnadu.  ",
      
      },
      {
        id: 41,
        image: "assets/Kerala/Food 2/Sadhya.jpg",
        name: "Sadhya ",
        category: "Food",
        info:"The Famous Kerala Wedding Food – Sadhya.The king of all the kerala foods particularly produced Onam and also various other parties the sadhya is a multi-course meal that consists of numerous vegan curries to be consumed with rice and also the last dessert training course will certainly be payasam. ",
      },
      {
        id: 42,
        image: "assets/Kerala/Food 2/padala payasam.jpg",
        name: " Padala payasam",
        category: "Food",
        info:"A conventional dessert, arranged throughout the event of Onam or any various other festivals is an easy rice dessert or kheer, made in mostly all the homes across Kerala. One of the most authentic variation of this Kerala food recipe is constructed out of rice ada, sugar, milk and ghee. Nevertheless any kind of unique event is lacking without the favorite payasam! "},
        
     
    
];

export default KeralaData;
