const LadakhData = [
    {
      id: 1, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: "Hemis National Park",
      category: "Wildlife",
      description: "https://www.yatrablog.com/ladakh-wildlife",
      info : "Established in 1981, the wildlife reserve has been named after one of the famous monasteries in Ladakh, the Hemis Gompa. The at-a-glance view is amazing – surrounded by the Indus and Markha Rivers, Sumdah, Rumbak and Zanskar ranges. Being located on the leeward side or rain shadow of the Himalayas, the park has dry forests of Juniper, Birch, Fir, Populus, Salix and Alpine and Steppe trees.",
      map : "https://www.google.com/maps/place/Hemis+National+Park/@33.7187211,77.3882224,15z/data=!4m2!3m1!1s0x0:0xf74ea9833e5618e2?sa=X&ved=2ahUKEwiz8fuEru37AhVvS2wGHXSaAw8Q_BJ6BQiAARAI",
    },
    {
      id: 2,
      image: "assets/Maharshtra/HillStation/igatpuri.jpg",
      name: "Karakoram (Nubra Shyok) Wildlife Sanctuary",
      category: "Wildlife",
      description: "https://www.yatrablog.com/ladakh-wildlife",
      info : "Named after the Karakoram Ranges, this sanctuary is home and breeding ground for a wide range of wild plants and animals. Domicile to the Tibetan Antelope, Shapo, Wild Yak, Bharal, Leopards, Himalayan Mouse and Lynx, you can also spot rare goat and wild sheep species like the Ibex, Argali and Ladakhi Urial. Bactrian Camels can also be found in the area. Tufted Duck, Booted Eagle, Golden Eagle, Gadwall, Grey Plover and Boarded Vultures are few of the many species of birds you can spot here.",
      map : "https://www.google.com/maps/place/Karakoram+(Nubra+Shyok)+Wildlife+Sanctuary/@34.160483,77.5883115,12.92z/data=!4m5!3m4!1s0x0:0xb615ff0dbeb23c9c!8m2!3d34.1525864!4d77.5770535",
     },
    {
      id: 3,
      image: "assets/Maharshtra/HillStation/khandala.jpg",
      name: "Changthang Cold Desert Wildlife Sanctuary",
      category: "Wildlife",
      description: "https://www.thrillophilia.com/changthang-cold-desert-wildlife-sanctuary",
      info : "Changthang Cold Desert Wildlife Sanctuary encompasses two of the world-famous high altitude water lakes, Tsomoriri and Pangong Tso. The altitude of the sanctuary varies from 14000 to 19000 feet, and the topography is formed of deep gorges and vast plateaus. There are around 11 lakes and 10 marshes in the Changthang Cold Desert Sanctuary, and the majestic River Indus dances through the sanctuary, dividing it into two parts.",
      map : "https://www.google.com/maps/place/Changthang+Cold+Desert+Wildlife+Sanctuary/@33.9627315,78.2013318,17z/data=!3m1!4b1!4m5!3m4!1s0x38fe1e7538ba5a2f:0xb1972240f5d9ad3a!8m2!3d33.9627315!4d78.2035205",
     },
    {
      id: 4,
      image: "assets/Maharshtra/HillStation/lavasa.jpg",
      name: "Thiksay Monastery",
      category: "Religious",
      description: "https://en.wikipedia.org/wiki/Thikse_Monastery",
      info : "Thikse Gompa or Thikse Monastery (also transliterated from Ladakhi as Tiksey, Thiksey or Thiksay) is a gompa (Tibetan-style monastery) affiliated with the Gelug sect of Tibetan Buddhism. It is located on top of a hill in Thiksey approximately 19 kilometres (12 mi) east of Leh in Ladakh, India. It is noted for its resemblance to the Potala Palace in Lhasa, Tibet, and is the largest gompa in central Ladakh",
      map : "https://www.google.com/maps/place/Thiksey+Monastery/@34.0568266,77.6669626,15z/data=!4m2!3m1!1s0x0:0xfc0ddd49e1b9fa4a?sa=X&ved=2ahUKEwiA2rz3rO37AhU5k1YBHT01DfEQ_BJ6BQiKARAI",
    },
    {
      id: 5,
      image: "assets/Maharshtra/HillStation/mahabaleshwar.jpg",
      name: "Gurdwara Pathar Sahib",
      category: "Religious",
	  description: "https://discoverlehladakh.in/gurudwara-pathar-sahib.htm",
      info : "Gurudwara Pathar Sahib, a beautiful Gurudwara constructed in the memory of Guru Nanak ji, founder guru of the Sikh faith, is about 25km from Leh on Leh-Kargil road, just before Magnetic Hill point.Gurudwara Pathar Sahib was built in 1517 to commemorate the visit of Guru Nanak Dev ji to Ladakh. A large number of tourists visit this religious and historic shrine while travelling to Magnetic Hill Point, Sangam Point, Alchi or Kargil.",
      map : "https://www.google.com/maps/place/Gurudwara+Pathar+Sahib/@34.1919737,77.3756324,15z/data=!4m2!3m1!1s0x0:0x82912e2f8632cb2d?sa=X&ved=2ahUKEwjU6enTrO37AhVqm1YBHWGND6AQ_BJ6BAh_EAg",
      },
    {
      id: 6,
      image: "assets/Maharshtra/HillStation/malshej.jpg",
      name: "Shanti Stupa",
      category: "Religious",
      description: "https://www.tourmyindia.com/states/ladakh/shanti-stupta-leh.html",
      info : "Shanti Stupa is the major attraction in Leh. Perched on the mountain top, this religious place also offers a panoramic view of the city and the surroundings, the history of Shanti Stupa states that was built in 1991 by Japanese Buddhist Bhikshu, Gyomyo Nakamura as a part of the Peace Pagoda mission. It holds the relics of the Buddha at its base that were enshrined by the 14th Dalai Lama.",
      map : "https://www.google.com/maps/place/Shanti+Stupa/@34.1736196,77.5749988,15z/data=!4m2!3m1!1s0x0:0xc90661126729dda8?sa=X&ved=2ahUKEwjR34GtrO37AhWjs1YBHQpmDH0Q_BJ6BQiDARAI",
    },
    {
      id: 7,
      image: "assets/Maharshtra/HillStation/matheran.jpg",
      name: "Diskit Gompa",
      category: "Religious",
      description: "https://www.travelogyindia.com/leh-ladakh/diskit-monastery.html",
      info : "The main and unique attraction of Diskit monastery is a gigantic statue of Lord Buddha on the top of it. This popular monastery is located in the Nubra valley of Ladakh. This famous tourist attraction is considered as one of the oldest as well as the largest Buddhist center in Ladakh. The Diskit monastery was constructed during the 14th century by Changzem Tserab Zangpo.The huge 100 foot Maitra Buddha statue was inaugurated by the well-known holy priest Dalai Lama is the key attraction among a number of tourists across the globe.",
      map : "https://www.google.com/maps/place/Diskit+Gompa/@34.5409579,77.5606881,15z/data=!4m2!3m1!1s0x0:0xcc9160287e99f4a?sa=X&ved=2ahUKEwii8tvtq-37AhUQSWwGHeDgAfEQ_BJ6BQiNARAI",
    },
    {
      id: 8,
      image: "assets/Maharshtra/HillStation/panchgani.jpg",
      name: "Alchi Monastery",
      category: "Religious",
      description: "https://www.tourmyindia.com/states/ladakh/alchi-monastery.html",
      info : "Known as the oldest monastery in Ladakh, Alchi Monastery is basically a monastic complex situated in Alchi Village in Leh District. The complex has four separate settlements with monuments dating back to different times. The paintings in Alchi Monastery are some of the oldest surviving paintings in Ladakh.",
      map : "https://www.google.com/maps/place/Alchi+Monastery+-+Choskhor/@34.2236972,77.1752278,15z/data=!4m2!3m1!1s0x0:0xfe5350522339645b?sa=X&ved=2ahUKEwi1ioHbq-37AhVWbN4KHUUbDNkQ_BJ6BAh_EAg",
    },
    {
        id: 9, 
        image: "assets/Maharshtra/WildLife/Bhigwan.png",
        name: "Hemis Monastery",
        category: "Religious",
        description: "https://www.incredibleindia.org/content/incredibleindia/en/destinations/leh-ladakh/hemis-monastery.html",
		info : "The Hemis Monastery is the biggest and very richly endowed monastery of Ladakh. It was built in 1630. Impressive and intriguing, Hemis is different from the other important monasteries of Ladakh. The monastery is decorated on all four sides by colourful prayer flags which flutter in the breeze and send prayers to Lord Buddha.",
		map : "https://www.google.com/maps/place/%E0%A4%B9%E0%A5%87%E0%A4%AE%E0%A4%BF%E0%A4%B8+%E0%A4%97%E0%A5%8B%E0%A4%AE%E0%A5%8D%E0%A4%AA%E0%A4%BE/@33.9125964,77.7029689,15z/data=!4m2!3m1!1s0x0:0xda0d6bb89ecbb853?sa=X&ved=2ahUKEwjp9LPFq-37AhVIyGEKHRT6AiEQ_BJ6BQiIARAI",
      },
      {
        id: 10,
        image: "assets/Maharshtra/WildLife/BhimaShankar.png",
        name: "Sculpture at Drass",
        category: "Heritage",
        description: "https://www.outlookindia.com/outlooktraveller/explore/story/59097/drass-edge-zanskar",
		info : "The town of Drass is 60 km beyond Kargil, bordering Kashmir’s Minamar meadows. Drass is the second-coldest inhabited place on Earth, the first being the Siberian village of Oymyakon. It is also where the Hungarian explorer Alexander Csoma de Koros, aka Sikander Beg, met Superintendent of the East India Company’s Stud and seminal Great Gamer, William Moorcroft.",
		map : "https://www.google.com/maps/dir//Dras+194102/@34.428256,75.7393813,15z/data=!4m17!1m7!3m6!1s0x38e301a9623197c3:0xb0db567896cb47b2!2sDras+194102!3b1!8m2!3d34.4269074!4d75.7458708!4m8!1m0!1m5!1m1!1s0x38e301a9623197c3:0xb0db567896cb47b2!2m2!1d75.7458708!2d34.4269074!3e2",
       },
      {
        id: 11,
        image: "assets/Maharshtra/WildLife/koyna.png",
        name: "Rock Cut Sculpture at Mulbekh",
        category: "Heritage",
        description: "https://asoulwindow.com/mulbekh-monastery-chamba-statue-ladakh/#About_Mulbekh_Monastery",
		info : "A recently constructed small Buddhist Gompa sits at the feet of the statue of Chamba. Built as recently as the year 1975, the Mulbekh Monastery is a must visit place near Kargil. What makes it a top place to see in Ladakh is the fact that it is off the beaten track. ",
		map : "https://www.google.com/maps/place/Mulbekh+Monastery/@34.5538147,76.1325935,17z/data=!3m1!4b1!4m5!3m4!1s0x38e3230055555555:0x3322c1bd0d52676e!8m2!3d34.5538147!4d76.1347822",
       },
      {
        id: 12,
        image: "assets/Maharshtra/WildLife/melghat.jpg",
        name: "Lamayuru Monastery",
        category: "Heritage",
        description: "https://www.adotrip.com/destination-detail/lamayuru-monastery",
		info : "Lamayuru Monastery, also known as the Yuru Monastery, is one of the ancient Tibetan Buddhist Monasteries, located at Lamayouro, in the Leh District of Jammu & Kashmir, India. Many times, it is also referred by the name of Yungdrung Tharpaling Monastery. ",
		map : "https://www.google.com/maps/place/The+Lamayuru+Monastery/@34.2830063,76.7741881,15z/data=!4m2!3m1!1s0x0:0x98241af475802b40?sa=X&ved=2ahUKEwj3n8LAqu37AhUTsVYBHR5CAc4Q_BJ6BAh5EAg",
     },
      
      {
        id: 13,
        image: "assets/Maharshtra/WildLife/Rahekuri.png",
        name: "Likir Monastery",
        category: "Heritage",
        description: "https://en.wikipedia.org/wiki/Likir_Monastery",
		info : "Likir Monastery or Likir Gompa (Klud-kyil) is a Buddhist monastery in Ladakh, Northern India. It is located at 3700m elevation, approximately 52 kilometres (32 mi) in the west of Leh. It is picturesquely situated on a little hill in the valley, in Likir village near the Indus River about 9.5 kilometres (5.9 mi) north of the Srinigar to Leh highway.It belongs to the Gelugpa sect of Tibetan Buddhism and was established in 1065 by Lama Duwang Chosje, under the command of the fifth king of Ladakh, Lhachen Gyalpo (Lha-chen-rgyal-po).",
		map : "https://www.google.com/maps/place/Likir+Gompa/@34.2931967,77.21511,15z/data=!4m2!3m1!1s0x0:0xa6caa86810327768?sa=X&ved=2ahUKEwjww4Grqu37AhXAr1YBHRyWA2kQ_BJ6BQiOARAI",
      },
      {
        id: 14,
        image: "assets/Maharshtra/WildLife/tadoba.jpg",
        name: "Magnetic Hill",
        category: "HillStation",
        description: "https://leh.nic.in/tourist-place/magnetic-hill/",
		info : "Magnetic Hill lies on the Leh-Kargil-Srinagar National Highway in the Trans-Himalayan region. To the east of the Magnetic Hill flows the Sindhu River, making the surroundings a photographer’s delight.",
		map : "https://www.google.com/maps/place/Magnetic+Hill,+194101/data=!4m2!3m1!1s0x38fd9838a0409b27:0x93a1a42e751c8c2e?sa=X&ved=2ahUKEwiwr_eMqu37AhVJslYBHfqNAvMQ8gF6BAhtEAE",
      },
       {
        id: 15, 
        image: "assets/Maharshtra/Religious/haji ali.jpg",
        name: "Khardung-la Pass",
        category: "HillStation",
        description: "",
		info : "Khardung La or Khardung Pass is a mountain pass in the Leh district of the Indian union territory of Ladakh.The pass is on the Ladakh Range, north of Leh, and connects the Indus river valley and the Shyok river valley. It also forms the gateway to the Nubra valley, beyond which lies the Siachen Glacier. ",
		map : "https://www.google.com/maps/place/Khardung+La/@34.2787342,77.6045697,17z/data=!3m1!4b1!4m5!3m4!1s0x38fdc0fef3b9c14b:0x37ec5dd55776d9f1!8m2!3d34.2787271!4d77.6046756!5m1!1e4",
      },
      {
        id: 16,
        image: "assets/Maharshtra/Religious/mahalakshmiji.jpg",
        name: "Nubra valley",
        category: "HillStation",
        description: "https://www.india.com/travel/nubra-valley/",
		info : "Nubra Valley is the northernmost part of Jammu and Kashmir. Situated about 150 km from Leh, Nubra Valley is known as the Orchard of Ladakh and was originally called Ldumra which meant the valley of flowers.Surrounded by snowcapped Himalayan ranges, Nubra valley lies sandwiched between Tibet and Kashmir. The view of the valley is picturesque and breathtaking.",
		map : "https://www.google.com/maps/dir//Nubra+Valley,+194401/@34.6863141,77.567288,15z/data=!4m17!1m7!3m6!1s0x38fc367354176591:0x8bc4556bab23cae9!2sNubra+Valley!3b1!8m2!3d34.6863146!4d77.567288!4m8!1m0!1m5!1m1!1s0x38fc367354176591:0x8bc4556bab23cae9!2m2!1d77.567288!2d34.6863146!3e2!5m1!1e4",
       },
      {
        id: 17,
        image: "assets/Maharshtra/Religious/pandharpur.jpg",
        name: "Pangong lake",
        category: "HillStation",
        description: "https://leh.nic.in/tourist-place/pangong/",
		info : "Pangong Lake, one of the most famous lakes in Leh Ladakh, derives its name from the Tibetan word, “Pangong Tso”, which means “high grassland lake”. You could spend hours in contemplation here, and still not have enough of its beauty. Pangong Lake is also known to change colors, appearing blue, green and red at different times.",
		map : "https://www.google.com/maps/place/Pangong+Tso/data=!4m2!3m1!1s0x39002d69b6082a97:0xb7ba17e3c8c016a9?sa=X&ved=2ahUKEwjztueNqe37AhWaHHAKHVUKAg4Q8gF6BQiPARAB",
      },
      {
        id: 18,
        image: "assets/Maharshtra/Religious/shirdi.jpg",
        name: "Tso Moriri & Tso Kar lakes",
        category: "HillStation",
        description: "https://www.ju-lehadventure.com/cultural-tour-ladakh/tso-moriri-lake",
		info : "Tso Moriri is a deep blue lake situated at an altitude of 4530m is surrounded by barren mountains and towering snowcapped peaks over 6000m such as Mentok, Chamser and Lungser Kangri. The lake winds through the Rupshu valley, it is 26 km in length and about 5 km in breadth. Many animals can be found around the lake including marmots, blue sheep, kiang (wild ass), rare Tibetan wolves and migratory birds.",
		map : "https://www.google.com/maps/place/Tso+Moriri,+194404/data=!4m2!3m1!1s0x39011569dbf9ff71:0xd7f871fe3b84562d?sa=X&ved=2ahUKEwjmiqvyqO37AhWXad4KHaSYATkQ8gF6BQiKARAB",
        },
      {
        id: 19,
        image: "assets/Maharshtra/Religious/siddhivinayak.jpg",
        name: "Dha-Hanu valley",
        category: "HillStation",
        description: "https://discoverlehladakh.in/dah-hanu-valley.htm",
		info : "Dah Hanu or Dha and Hanu, popularly known as Aryan villages of Ladakh, are located in Dhahanu valley in North-East of Ladakh, about 160km from Leh town.he visitors are required to obtain an inner line permit to visit these Brokpa villages. The villages have both Buddhist and Muslim population and also have their own animist pantheon of Gods. Residents of Dah Hanu are best known as Indo-Aryan breed.",
		map : "https://www.google.com/maps/place/Dah/@34.6032405,76.511085,15z/data=!3m1!4b1!4m5!3m4!1s0x38fccd76540ffcff:0x7f0d177583d98a58!8m2!3d34.6029517!4d76.5069107",
      },
      {
        id: 20,
        image: "assets/Maharshtra/Religious/tuljabhavani mata.jpg",
        name: "Zanskar valley",
        category: "HillStation",
        description: "https://www.ladakh-tourism.net/blog/zanskar-valley/",
		info : "Zanskar valley is located in the Kargil district of the Union Territory of Ladakh at a distance of 463 km from Leh. The administrative headquarter of Zanskar, Padum, is situated at an elevation of 3669 m. The offbeat valley features a scenic landscape surrounded by Zanskar ranges giving it a gorgeous view.",
		map : "https://www.google.com/maps/place/Zanskar+194302/data=!4m2!3m1!1s0x390291f2ae1b57bb:0x736eba6f94fd593a?sa=X&ved=2ahUKEwiVlJOtqO37AhVGRd4KHfuhA4IQ8gF6BQiEARAB",
      },
      {
        id: 21, 
        image: "assets/Maharshtra/Heritage/aga khana.jpg",
        name: "Stok Kangri",
        category: "Mountain",
        description: "https://en.wikipedia.org/wiki/Stok_Kangri",
		info : "Stok Kangri (6,153 metres (20,187 ft)) is the highest mountain in the Stok Range of the Zazkar Mountains a Trans-Himalayan mountain in the Ladakh region of north India. The peak is located in Hemis National Park, 12 km southwest of the trailhead (3,610 metres (11,844 ft)) in the village of Stok and around 15 km southwest of the city of Leh, the capital of Ladakh.",
		map : "https://www.google.com/maps/place/Stok+Kangri,+194201/data=!4m2!3m1!1s0x38fd8ef226eba6ed:0xa019c9da08dc3cbd!5m1!1e4?sa=X&ved=2ahUKEwiTnamXqO37AhWG3GEKHV66AdUQ8gF6BQiPARAB",
      },
      {
        id: 22,
        image: "assets/Maharshtra/Heritage/Ajanta ellora caves.jpg",
        name: "Kang Yatse",
        category: "Mountain",
        description: "https://www.bikatadventures.com/Home/Itinerary/Kang-Yatse-II-Trek",
		info : "Located in Hemis National Park, Kang Yatse II, at 6,250M, is the shorter of the two cousins with Kang Yatse I towering beside it at 6,400M. As one of the highest trekking peaks in the vast expanse of the arid terrain in Ladakh, Kang Yatse II makes itself seen on day 6 of our trek as we make our way to its base through Markha Valley. The peak is a thing of sheer beauty standing tall in the middle of this dry land of scree and loose rocks.",
		map : "https://www.google.com/maps/place/Kang+Yatse+Hill,+194201/data=!4m2!3m1!1s0x39027349e6f674b9:0x6e38db1de6342bb9!5m1!1e4?sa=X&ved=2ahUKEwjYyoaEqO37AhWYdHAKHcTCCQkQ8gF6BQiDARAB",
       },
      {
        id: 23,
        image: "assets/Maharshtra/Heritage/Bibi ka ma.jpg",
        name: "Mentok Kangri",
        category: "Mountain",
		description: "https://www.bikatadventures.com/Home/Itinerary/Mentok-Kangri-Expedition",
		info : "The Mentok Kangri massif lies on the western shores of Tso Moriri in eastern Ladakh in the Rupsu valley. The three summits are at 6250 m, 6150 m, and 6210 m, connected by an easy ridge. Mentok Kangri II lies at 6,250 m, towering over the western edge of Tso Moriri. You will drive to Karzok on the banks of Tso Moriri, before setting base near the Rupshu plateau inhabited by the Changpa nomads.",
		map : "https://www.google.com/maps/place/Mentok+Kangri+I,+194404/data=!4m2!3m1!1s0x39016a6ca2f1a9e5:0x235c7365ba812816!5m1!1e4?sa=X&ved=2ahUKEwj5kOD0p-37AhVaed4KHeDuBOIQ8gF6BQiGARAB",
       },
      {
        id: 24,
        image: "assets/Maharshtra/Heritage/chatrapati shahu museum.jpg",
        name: "Chamser Kangri",
        category: "Mountain",
        description: "https://whitemagicadventure.com/blog/chamsher-kangri-mentok-kangri-and-lungser-kangri",
		info : "The twin peaks of Chamsher and Lungsher Kangri next to Tsomoriri Lake The area around the lake of Tso Moriri in Ladakh has a number of peaks crossing that magical height of 6000 metres and the three Kangri's listed below are without doubt the most popular. In the season which is June to August there are a number of small groups who make attempts on these peaks often after a trek.",
		map : "https://www.google.com/maps/place/Chamser+Kangri,+194404/data=!4m2!3m1!1s0x39011772733ba689:0xa848c1ffba0f0e7b!5m1!1e4?sa=X&ved=2ahUKEwib5YHKp-37AhXGdt4KHUPXC_QQ8gF6BAh2EAE",
	  },
	  {
        id: 25,
        image: "assets/Maharshtra/Heritage/chatrapati terminus11.jpg",
        name: "Lungser Kangri",
        category: "Mountain",
        description: "https://en.wikipedia.org/wiki/Lungser_Kangri",
		info : "Lungser Kangri is a mountain located in Ladakh, India.The mountain is located near the lake Tso Moriri and the village Karzok. It is 21,801 feet (6,645 m) high, making it the tallest mountain in the Rupshu area, as well as the second highest in the Mangrik area, which is located in the southern part of Ladakh county. The mountain is accessible from Markha Valley.",
		map : "https://www.google.com/maps/place/Lungser+Kangri,+194404/data=!4m2!3m1!1s0x39011796e0bd802f:0x7def8a13a2857bcc!5m1!1e4?sa=X&ved=2ahUKEwjvo_qpp-37AhU4QPUHHVsvDE0Q8gF6BAh7EAE",
        },
      {
        id: 26,
        image: "assets/Maharshtra/Heritage/chikhaldara.jpg",
        name: "Leh Palace",
        category: "Fort",
        description: "https://en.wikipedia.org/wiki/Leh_Palace",
		info : "Leh Palace also known as Lachen Palkar Palace is a former royal palace overlooking the city of Leh in Ladakh, India. It was constructed circa 1600 by Sengge Namgyal.The palace was abandoned when Dogra forces took control of Ladakh in the mid-19th century and forced the royal family to move to Stok Palace.",
		map : "https://www.google.com/maps/dir//leh+palace/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x38fdeb150c993295:0xc41a8d83a5a327e6?sa=X&ved=2ahUKEwjBlqiJp-37AhVbPnAKHSEWCPwQ9Rd6BQiIARAD",
      },
      {
        id: 27,
        image: "assets/Maharshtra/Heritage/elephanta caves.jpg",
        name: "Tsemo Fort & Gompa",
        category: "Fort",
        description: "https://www.lehladakhindia.com/tsemo-fort/",
		info : "Built in the 16th century is Tsemo (Victory) Fort, is just 15-minute climb-up opposite Chenrezi Lakhang with its ruins. This structure is actually visible from everywhere in Leh.This fort seems like a crown on the head of the Palace ridge.  This small but ruined palace contains of a number of worship flags. Directly underneath it is Tsemo gompa that is Tsemo monastery that consists of two temple buildings built in the 15th century, an eight meter tall gold-faced statue of Maitreya Buddha.",
		map : "https://www.google.com/maps/place/Tsemo+Goenkhang/@34.1673647,77.5883487,17z/data=!3m1!4b1!4m5!3m4!1s0x38fdeb14711a155f:0xa13926293f0efb17!8m2!3d34.1673647!4d77.5905374",
      },
      {
        id: 28,
        image: "assets/Maharshtra/Heritage/gateway of india.jpg",
        name: "Shey Palace",
        category: "Fort",
        description: "https://en.wikipedia.org/wiki/Shey_Monastery",
		info : "The Shey Palace complex are structures located on a hillock in Shey, 15 kilometres (9.3 mi) to the south of Leh in Ladakh, northern India on the Leh-Manali road. Shey was the summer capital of Ladakh in the past. It contains a huge Shakyamuni Buddha statue. It is the second largest Buddha statue in Ladakh",
		map : "https://www.google.com/maps/dir//Shey+Palace,+Leh+Manali+Hwy,+Shey,+194201/@34.071575,77.6327604,17z/data=!4m17!1m7!3m6!1s0x38fdeded11cb0639:0xaeb0a5246cdd1f48!2sShey+Palace,+Leh+Manali+Hwy,+Shey,+194201!3b1!8m2!3d34.071575!4d77.6327604!4m8!1m0!1m5!1m1!1s0x38fdeded11cb0639:0xaeb0a5246cdd1f48!2m2!1d77.6327604!2d34.071575!3e2",
      },
      {
        id: 29,
        image: "assets/Maharshtra/Forts/daulatabad.jpg",
        name: "Stok Palace & Museum",
        category: "Fort",
        description: "https://www.incredibleindia.org/content/incredibleindia/en/destinations/leh-ladakh/stok-palace-museum.html",
		info : "The Stok palace of the banished royal family is now converted into a museum which displays the richest collection of jewellery, ornaments, Thangkas and much more. It exhibits the ceremonial dresses, crowns, and centuries-old pieces of jewellery, which reflect the lifestyle and history of royalty in the region.",
		map : "https://www.google.com/maps/dir//Stok+Palace+%26+Museum/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x38fd92c791806a4f:0xe3e13cc5223f44a4?sa=X&ved=2ahUKEwiUy62Vpu37AhXOs1YBHYsxDYQQ9Rd6BAhoEAM",
      },
      {
        id: 30, 
        image: "assets/Maharshtra/Forts/lohogad.jpg",
        name: "Chiktan Palace/ Chiktan Khar",
        category: "Fort",
        description: "https://en.wikipedia.org/wiki/Chiktan_Fort",
        info : "Chiktan Fort, (Chiktan Castle) also known as Chiktan Khar, is a fort in the Chiktan village of Kargil district, Ladakh, India.the Chiktan fortress is shrouded in many mysteries. Legends of its making, numerous sinister and violent events, magical tales of wondrous creations and a heart-wrenching tailspin of destruction and apathy encompass the story of this fabulous fortress set in an almost fantastical location.",
		map : "https://www.google.com/maps/dir//Chiktan+Palace/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x38fd2a715b948367:0x504140f82670a905?sa=X&ved=2ahUKEwjU65jxpe37AhWojVYBHe2gAccQ9Rd6BAhmEAM",
      },
      {
        id: 31,
        image: "assets/Maharshtra/Forts/murud janjira.jpg",
        name: "Zamskhang Palace in Nubra Valley",
        category: "Fort",
        description: "https://timesofindia.indiatimes.com/travel/travel-news/zamskhang-palace-the-hidden-gem-of-nubra-valley-ladakh/articleshow/88511589.cms",
		info : "Zamskhang palace is said to have been built in the 17th century, and was home to the Governor’s family at that time.There is not much left of the palace now, but there is a prayer room that is still in use. Here inside this room you will find beautiful statues, and thangkas. Thangkas are beautiful Tibetan Buddhist paintings, usually done on cotton or silk. These paintings depict Buddhist deity, or a mandala.",
		map : "https://www.google.com/maps/dir//JJQ8%2BJRM+Zhimskhang+Palace,+Unnamed+Road,+Tiggur,+194401/@34.1431445,76.7504759,9z/data=!4m17!1m7!3m6!1s0x38fc350824958f21:0x7de40004469ea5c2!2sZhimskhang+Palace!8m2!3d34.6390931!4d77.6170369!15sChBaYW1za2hhbmcgUGFsYWNlkgESdG91cmlzdF9hdHRyYWN0aW9u4AEA!4m8!1m0!1m5!1m1!1s0x38fc350824958f21:0x7de40004469ea5c2!2m2!1d77.6170369!2d34.6390931!3e2",
       },
      {
        id: 32,
        image: "assets/Maharshtra/Forts/Pratapgad fort.jpg",
        name: "Yabgo Royal House: Turtuk, Baltistan",
        category: "Fort",
        description: "https://en.wikipedia.org/wiki/Khaplu_Palace",
		info : "Khaplu Palace locally known as Yabgo Khar, is an old fort and palace located in Khaplu. The palace, considered an architectural heritage site and a significant tourist attraction, was built in the mid-19th century to replace an earlier-dated fort located nearby. It served as a royal residence for the Raja of Khaplu.",
		map : "https://www.google.com/maps/dir//Khaplu+Palace,+Chaqchan+Rd,+Khaplu/@35.1517389,76.330789,17z/data=!4m17!1m7!3m6!1s0x38e4a9c3f2b7bd93:0xdeb1e2ffb2302965!2sKhaplu+Palace,+Chaqchan+Rd,+Khaplu!3b1!8m2!3d35.151739!4d76.3352683!4m8!1m0!1m5!1m1!1s0x38e4a9c3f2b7bd93:0xdeb1e2ffb2302965!2m2!1d76.3352683!2d35.151739!3e2",
       },
      {
        id: 33,
        image: "assets/Maharshtra/Forts/raigad.jpg",
        name: "Basgo Fort",
        category: "Fort",
        description: "https://www.wmf.org/project/basgo-gompa-maitreya-temples",
		info : "The mud-brick fortress of Basgo Gompa is perched high in the hills of Ladakh, between the Himalaya and Karakoram mountain ranges in northern India. The citadel and the three temples located within its rammed earth walls were built by Tibetan king Grags-pa-‘bum and his descendants in the sixteenth and seventeenth centuries A.D. The Chamchung, Chamba Lakhang, and Serzang temples, located on a man-made mound in the center of the complex, are dedicated to the Maitreya Buddha—the fifth incarnation of Sakyamuni.",
		map : "https://www.google.com/maps/place/Basgo+194101/@34.2197087,77.2486807,14z/data=!3m1!4b1!4m10!1m2!2m1!1sBasgo+Fort!3m6!1s0x38fda1f4d322886f:0x28f0003edb95c344!8m2!3d34.2131647!4d77.2850515!15sCgpCYXNnbyBGb3J0kgEIbG9jYWxpdHngAQA!16zL20vMGRtM3o2",
      },
      {
        id: 34,
        image: "assets/Maharshtra/Forts/shivneri.jpg",
        name: "Momos",
		category: "Food",
		info : "Momos is the most popular dish in Ladakh. It is a dumpling filled with meat or vegetable wrapped in dough. While momos stuffed with minced meat enjoys popularity among locals, veg momos are also savoured alike. These dumplings are either steamed or fried and served with dipping sauce.",
        },
      {
        id: 35,
        image: "assets/Maharshtra/Forts/Singagad Fort.jpg",
        name: "Thukpa",
        category: "Food",
		info : "Thukpa is the staple food of people of Ladakh. It is a soupy noodle dish with assorted vegetables (for vegetarians) and minced meat (for non-vegetarians). The noodle is made of wheat or barley flour. The broth, rich in spices, not only satiates the taste buds but also warms the body.",
      },
      {
        id: 36,
        image: "assets/Maharshtra/Forts/vijaydurg.jpg",
        name: "Skyu",
        category: "Food",
		info : "Skyu is a soup-based traditional speciality. The dish contains vegetable and dough kneaded into flattened thumb-sized balls. These flattened balls are then put in a pot with water and vegetables and cooked on low heat. Skyu is also served with meat",
      },
      {
        id: 37,
        image: "assets/Maharshtra/Beaches/alibaug.jpg",
        name: "Chhutagi",
        category: "Food",
		info : "Chhutagi is one of the distinctive Ladakhi delicacy rich in nutrition. The flattened dough is usually cut into circular shapes and then given the shape of a bow-tie. The dough is then cooked in a thick soup made of either vegetables or meat. Chhutagi is a heavy meal and is often served during harvest season to workers to give them energy.",
      },
      {
        id: 38, 
        image: "assets/Maharshtra/Beaches/ganpatipule beach.jpg",
        name: "Tingmo",
        category: "Food",
		info : "Tingmo is a delicate, soft and fluffy bun that is prepared from wheat flour without putting any filling. It is best served hot and is mostly served with meat.It is a staple food of Ladakh and is eaten for breakfast, lunch and dinner.",
      },
      {
        id: 39,
        image: "assets/Maharshtra/Heritage/elephanta caves.jpg",
        name: "Chhurpe",
        category: "Food",
        info:"Chhurpe, made from the milk of dzomo (a hybrid between domestic cattle and yak), is used as an ingredient to create flavourful delicacies in Ladakh. It is white and is added to thukpa to bring out flavour when vegetables or meat are not available in winter.",
        
      },
      {
        id: 40,
        image: "assets/Maharshtra/Heritage/gateway of india.jpg",
        name: "Chhang",
        category: "Food",
        info:"Chhang is Ladakh’s local beer and is served as a traditional drink to the guests. Barley is fermented to produce chhang which has an alcohol content of 5% to 7%. Chhang is consumed during festivals, weddings and other important functions.",
      
      },  
     
     
  ];
  
  export default LadakhData;


 