const MadhyaPradeshData = [
  {
    id: 1, 
    image: "assets/Madhya Pradesh/Forts/Asirgarh Fort.jpg",
    name: "Asirgarh Fort",
    category: "Forts",
    description: "https://www.madhya-pradesh-tourism.com/destination/Asirgarh-Fort-31",
    info:"Asirgarh is counted among invincible forts of India. ‘Fort’ word is also known as ‘Qila’ in Hindi word, Asirgarh Fort is situated in the famous Satpura Range, about 20 km north of the town of Burhanpur District of Central Indian state of Madhya Pradesh.",
    map : "https://goo.gl/maps/jkGocXAawBmPDCrAA",
  },
  {
    id: 2,
    image: "assets/Madhya Pradesh/Forts/GWALIOR fort.jpg",
    name: "Gwalior Fort",
    category: "Forts",
    description:  "https://gwalior.nic.in/en/tourist-place/the-fort/",
    info:"The Gwalior Fort commonly known as the Gwāliiyar Qila, is a hill fort near Gwalior, Madhya Pradesh, India. The fort has existed at least since the 10th century, and the inscriptions and monuments found within what is now the fort campus indicate that it may have existed as early as the beginning of the 6th century.",
    map : "https://goo.gl/maps/29ZPo9hsTm3LpBqC8",
   },
  {
    id: 3,
    image: "assets/Madhya Pradesh/Forts/Hindola_Mahal,_mandu_.jpg",
    name: "Deogarh Fort ",
    category: "Forts",
    description: "https://www.chhindwara.net/deogarh-fort/",
    info:"The Deogarh Fort or Devgarh Fort is one of the very old fort situated in Madhya Pradesh, India. It was the capital of a Gond Dynasty and is located in the present day town of Devgarh, at a distance of 42 km from the district headquarter Chhindwara. ",
    map : "https://goo.gl/maps/SbTvrH9o4Nrvd8D16"
   },
  {
    id: 4,
    image: "assets/Madhya Pradesh/Hill Stations/Pachmarhi Hill, Queen of The Satpuras.jpg",
    name: "Orchha Fort",
    category: "Forts",
    description: "https://www.tripadvisor.in/Attraction_Review-g319728-d2035158-Reviews-Orchha_Fort-Orchha_Tikamgarh_District_Madhya_Pradesh.html",
    info:"The Orchha Fort complex, which houses a large number of ancient monuments consisting of the fort, palaces, temple, and other edifices, is located in the Orchha town in the Indian state of Madhya Pradesh. The fort and other structures within it were built by the Bundela Rajputs.",
    map : "https://goo.gl/maps/da2LhMvrfxXcKM1q7"},
  {
    id: 5,
    image: "assets/Madhya Pradesh/Forts/Rajwada,Indore.jpg",
    name: "Rajwada,Indore",
    category: "Forts",
    description: "https://www.agoda.com/en-in/pages/agoda/default/DestinationSearchResult.aspx?city=3177&site_id=1758155&tag=3d386e63-1cb2-81c5-f24d-9954b6855f1b&msclkid=13c2e113ad6e101e9768826986c04454&utm_source=bing&utm_medium=cpc&utm_campaign=Intent%20Engine%20-%20009&utm_term=%2Bindore%20%2Brajwada&utm_content=indore%20rajwada%7Cci%3Aindore,%20madhya%20pradesh,%20india_3177",
    info:"The Rajwada is now state property under the Archeology who granted special permission for rebuilding the old wada (residence) which was the main Rajwada which was completely burnt during the 1984 riots, namely the building around the Tulsi Kund along with the temple that previously existed there",
    map : "https://goo.gl/maps/fpSZBwG7n1tBp4AT6",
    },
  {
    id: 6,
    image: "assets/Madhya Pradesh/Forts/Raja Mahal, Orchha Fort.jpg",
    name: "Raja Mahal,Orcha",
    category: "Forts",
    description: "https://www.tripadvisor.in/Attraction_Review-g319728-d3705375-Reviews-Raja_Mahal-Orchha_Tikamgarh_District_Madhya_Pradesh.html",
    info:"Raja Mahal was built by Madhukar Shah who ruled from 1554 to 1591. The interior of the mahal is royal, carving, embellishments, murals of God on different themes, mythical animals and people.",
    map : "https://goo.gl/maps/YtHbSNjCRCQPqzYL6"
  },
  {
      id: 7, 
      image: "assets/Madhya Pradesh/Heritage/Dauji ki haveli.jpg",
      name: "Dauji Ki Haveli",
      category: "Heritage",
      description: "https://www.holidify.com/places/orchha/dauji-ki-haveli-sightseeing-3110.html",
      info:"The centre of trading activities, Orchha gave birth to a new class of people- the Merchants. Intelligent and influential as they were, they used their wealth to build stunning monuments which were replicas of the palaces in which the royalty lived.",
      map : "https://goo.gl/maps/1YzkUYkwa7KUMXnX6",
    },
    {
      id: 8,
      image: "assets/Madhya Pradesh/Heritage/Hindola_Mahal,_mandu_.jpg",
      name: "Hindola Mahal,Mandu",
      category: "Heritage",
      description:  "https://www.madhya-pradesh-tourism.com/destination/Hindola-Mahal-49",
      info:"Hindola Mahal in Mandu is a popular historical monuments and tourist attractions during Mandu sightseeing. Its english translation is 'Swinging Palace'. It is a 'T' shaped building use as open air theater or audience hall",
      map : "https://goo.gl/maps/hp86wrdihXKnGhvu8",
     },
    {
      id: 9,
      image: "assets/Madhya Pradesh/Heritage/Jahaz mahal,mandu.jpg",
      name: "Jahaz Mahal",
      category: "Heritage",
      description: "https://www.madhya-pradesh-tourism.com/destination/Jahaz-Mahal-51",
      info:"The splendid architecture of Jahaz Mahal occupies an expense in the Mandu region of Madhya Pradesh. It was built during the reign of Mandu Sultan Ghiyas-ud-din Khilji, who is believed to have as many as 15,000 women as his consorts.",
      map : "https://goo.gl/maps/TSdjn3AJr3Qgu33u7"
     },
    {
      id: 10,
      image: "assets/Madhya Pradesh/Heritage/Sanchi_Stupa_.jpg",
      name: "Sanchi Stupa",
      category: "Heritage",
      description: "https://www.culturalindia.net/monuments/sanchi-stupa.html",
      info:"Sanchi is a Buddhist complex, famous for its Great Stupa, on a hilltop at Sanchi Town in Raisen District of the State of Madhya Pradesh, India. It is located, about 23 kilometres from Raisen town, district headquarter and 46 kilometres (29 mi) north-east of Bhopal, capital of Madhya Pradesh.",
      map : "https://goo.gl/maps/WhHnUt53j9EmpVgv9"
    },
     {
      id: 11, 
      image: "assets/Madhya Pradesh/Heritage/The Madhav Vilas Palace.jpg",
      name: "The Madhav Villas Palace",
      category: "Heritage",
      description: "https://www.indianholiday.com/tourist-attraction/shivpuri/madhav-vilas-palace.html",
      info:"Madhav Vilas Palace was built by Madha Rao Syindhy for his immortal beloved queen named Sakhya Raje Scindia. He belonged to the Maratha clans who ruled the Gwalior region in the 18th century AD.",
      map : "https://goo.gl/maps/7Y2ej6b485dw2B8H6",
    },
    {
      id: 12,
      image: "assets/Madhya Pradesh/Heritage/The Rock Shelters of Bhimbetka.jpg",
      name: "Bhimbetka",
      category: "Heritage",
      description:  "https://www.mptourism.com/bhimbetka.html",
      info:"The Bhimbetka rock shelters are an archaeological site, exhibiting the earliest traces of human life on the Indian subcontinent, and thus the beginning of the South Asian Stone Age. It was declared a World Heritage Site in 2003.",
      map : "https://goo.gl/maps/LVtuk2XYgaxgzDm27",
     },
    {
      id: 13,
      image: "assets/Madhya Pradesh/Heritage/The Madhav Vilas Palace.jpg",
      name: "Amarkantak Hill",
      category: "Hill Stations",
      description: "https://www.mptourism.com/destination-amarkantak.php",
      info:"Amarkantak ( NLK Amarakaṇṭaka) is a pilgrim town and a Nagar Panchayat in Anuppur, Madhya Pradesh, India. The Amarkantak region is a unique natural heritage area and is the meeting point of the Vindhya and the Satpura Ranges, with the Maikal Hills being the fulcrum.",
      map : "https://goo.gl/maps/G3885ETbcyL71Zqj7"
     },
    {
      id: 14,
      image: "assets/Madhya Pradesh/Hill Stations/Mandu Hill Known For Architectural Beauty.JPG",
      name: "Mandu Hill",
      category: "Hill Stations",
      description: "https://offbeatexplorers.com/mandav-madhya-pradesh-mandu-fort/",
      info:"Mandu is an ancient fort city surrounded by stone walls dotted with darwazas (gateways). It's also known for its Afghan architectural heritage. Landmark buildings include Hoshang Shah’s Tomb, a domed marble mausoleum, and the vast Jami Masjid mosque, with courtyards framed by colonnades. ",
      map : "https://goo.gl/maps/ToSeQzU7bDHm1Bwq7"},
    {
      id: 15,
      image: "assets/Madhya Pradesh/Hill Stations/Omkareshwar Hill A Sacred Hill Station.jpg",
      name: "Omkareshwar Hill",
      category: "Hill Stations",
      description: "https://www.tripadvisor.in/SmartDeals-g1508514-Omkareshwar_Khandwa_District_Madhya_Pradesh-Hotel-Deals.html",
      info:"It is one of the sacred hill stations. It is also called “Mini Varanasi”. It is present between the River Narmada and Kaveri. This place is in the form of ‘om’ because of the emergence of two valleys and a Narmada river at the centre. People of India believe that for more optimistic power can be gained in the temple called Ankleshwar temple. ",
      map : "https://goo.gl/maps/eVgtkhLzoHXhZZ2Q6",
      },
    {
      id: 16,
      image: "assets/Madhya Pradesh/Hill Stations/Pachmarhi Hill, Queen of The Satpuras.jpg",
      name: "Pachmarhi Hill",
      category: "Hill Stations",
      description: "https://www.tripadvisor.in/SmartDeals-g503700-Pachmarhi_Hoshangabad_District_Madhya_Pradesh-Hotel-Deals.html",
      info:"Widely known as the “Satpura ki Rani” or Queen of Satpura, Pachmarhi is a hill station located in Madhya Pradesh, in the Hoshangabad district. It was one of the towns that was founded by the British Raj during their occupation of the Indian subcontinent.",
      map : "https://goo.gl/maps/MhzLhympKXo1V1qY9"
    },
    {
      id: 17,
      image: "assets/Madhya Pradesh/Hill Stations/Shivpuri hill.jpg",
      name: "Shivpuri Hill",
      category: "Hill Stations",
      description:  "https://www.trivago.in/en-IN/srl?__wr=21&tc=18&themeId=2&sem_keyword=accommodation%20shivpuri&sem_creativeid=76003903737851&sem_matchtype=bb&sem_network=o&sem_device=c&sem_campaignid=367772578&sem_adgroupid=1216060313404568&sem_targetid=kwd-76004103265954%3Aloc-90&cipc=sem&cip=9129001363&msclkid=3e51284c7b04191d86f34b362b371c6a&search=200-424310",
      info:"It is one of the calmest places in India. In this busy world, it defines the meaning of peace. It is present at the height of 478 meters above sea level. It also contains Madhav Vilas Palace, which stands for its royal wealth and pride. This palace looks so stunning due to the red-pink colour and its smoothening architecture.",
      map : "https://goo.gl/maps/ghgYFD19HyrDvVPg6",
     },
    {
      id: 18,
      image: "assets/Madhya Pradesh/Hill Stations/Tamiya Hill An Offbeat Place.png",
      name: "Tamiya Hill",
      category: "Hill Stations",
      description: "https://www.mptourism.com/destination-tamia.php",
      info:"This hill station is situated near the Satpura National Park. In Pachmarhi, hill population is more. But in this station population is less when compared to Pachmarhi hill. So, it makes this hill station an offbeat place to visit with less crowd and more fun.",
      map : "https://goo.gl/maps/gbAr9zEL2kTL1eQW7"
     },
    {
      id: 19,
      image: "assets/Madhya Pradesh/Religious/Amarkantak.jpg",
      name: "Amarkantak",
      category: "Religious",
      description: "https://www.tripadvisor.in/SmartDeals-g1508510-Amarkantak_Anuppur_District_Madhya_Pradesh-Hotel-Deals.html",
      info:"Amarkantak is a pilgrim town and a Nagar Panchayat in Anuppur, Madhya Pradesh, India. The Amarkantak region is a unique natural heritage area and is the meeting point of the Vindhya and the Satpura Ranges, with the Maikal Hills being the fulcrum.",
      map : "https://goo.gl/maps/cs4ADQYgW66mg1mD7"},
    {
      id: 20,
      image: "assets/Madhya Pradesh/Religious/Chitrakoot.jpg",
      name: "Chitrakoot",
      category: "Religious",
      description: "https://tripsaround.in/chitrakoot-madhya-pradesh-the-hill-of-many-wonders-a-spiritual-place-to-rest-your-soul/",
      info:"Chitrakoot is a pilgrimage centre and a nagar panchayat in the Satna district in the state of Madhya Pradesh, India. Connected to the Indian epic Ramayana, it is a place of religious, cultural, historical and archaeological importance, situated in the Baghelkhand region.",
      map : "https://goo.gl/maps/DxuWrrAKXE4ce1FZ9",
      },
    {
      id: 21,
      image: "assets/Madhya Pradesh/Religious/Maheshwar-and-Omkareshwar-1024x685.jpg",
      name: "Shree Omkareshwar Jyotirlinga",
      category: "Religious",
      description: "http://omkareshwar.org/English",
      info:"Omkareshwar Jyotirlinga a shiv temple on Omkar mountain an island in mid Narmada, revered Hindu temple is the center of extreme faith. There are 12 jyotirlinga temples in world and omkareshwar is one fo them.",
      map : "https://goo.gl/maps/noCr1LW4nTKDZA9fA"
    },
    {
      id: 22,
      image: "assets/Madhya Pradesh/Religious/Orchha.jpg",
      name: "Orchha",
      category: "Religious",
      description: "http://www.orchha.in/about/",
      info:"Orchha is a town, near city of Niwari in Niwari district of Madhya Pradesh state, India. The town was established by rajput ruler Rudra Pratap Singh some time after 1501, as the seat of an eponymous former princely state of covering parts of central & north India, in the Bundelkhand region.",
      map : "https://goo.gl/maps/cN8yZtj6tL4G7Meg6"
    },
    {
      id: 23,
      image: "assets/Madhya Pradesh/Religious/Sonkash-Pushpagiri.jpg",
      name: "Pushpagiri Tirth",
      category: "Religious",
      description: "http://jaintirthtourism.com/madhya-pradesh-jaintirthkshetra/shri-1008-digambar-jain-siddha-kshetra,-reshandigiri-(nainagiri),-madhya-pradesh-tirthkshetra-in-chhatarpur.php",
      info:"Pushpagiri Temple Complex is a temple complex located in Kadapa district in Andhra Pradesh, India. Founded around 7th Century CE, it houses some of the oldest temple congregations in the region. There are multiple legends associated with the origin of the temple complex.",
      map : "https://goo.gl/maps/UKPy9VjZmpRDL9WP9"
    },
    {
      id: 24,
      image: "assets/Madhya Pradesh/Religious/Ujjain.jpg",
      name: "Ujjain",
      category: "Religious",
      description: "https://www.holidify.com/places/ujjain/",
      info:"Ujjain is an ancient city beside the Kshipra River in the central Indian state of Madhya Pradesh. An important Hindu pilgrimage destination, it’s known for the centuries-old Mahakaleshwar Temple, a towering structure with a distinctively ornate roof. ",
      map : "https://goo.gl/maps/364TN3V9ezPKSoAr8"
    },
    {
      id: 25, 
      image: "assets/Madhya Pradesh/WildLife/Bori Wildlife Sanctuary.jpg",
      name: "Bori Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.toftigers.org/park/bori-wildlife-sanctuary/",
      info:"The Bori Wildlife Sanctuary is a wildlife sanctuary in Hoshangabad District of Madhya Pradesh state in central India. The sanctuary covers an area of 646 km (249 sq mi), located in the northern foothills of the Satpura Range.",
      map : "https://goo.gl/maps/3HRKwAvqoNJwbE2K8",
    },
    {
      id: 26,
      image: "assets/Madhya Pradesh/WildLife/Gandhi Sagar Wildlife Sanctuary.jpg",
      name: "Gandhi Sagar Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description:  "https://www.natureinfocus.in/travel/guide/gandhi-sagar-wildlife-sanctuary",
      info:"Gandhi Sagar Sanctuary is a wildlife sanctuary situated on the northern boundary of Mandsaur and Nimach districts in Madhya Pradesh, India. It is spread over an area of 368.62 km (142.32 sq mi) adjoining Rajasthan state in India.",
      map : "https://goo.gl/maps/abLEfnaZnPLdFWBw9",
     },
    {
      id: 27,
      image: "assets/Madhya Pradesh/WildLife/Ghatigaon Wildlife Sanctuary.jpg",
      name: "Ghatigaon Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.madhya-pradesh-tourism.com/destination/Ghatigaon-Wildlife-Sanctuary-14",
      info:"Puranic name of Amarkantak was Riksha parvat. It is not only the Narmada which arises from Amarkantak, because theson River, initially referred to as Jwalawanti of Johila, the Mahanadi and the Amadoh, which is a major early tributary of the Godavari, all rise from within the Amarkantak plateau.",
      map : "https://goo.gl/maps/XLgykQLzu5mceTwR6"
     },
    {
      id: 28,
      image: "assets/Madhya Pradesh/WildLife/Narsinghgarh Wildlife Sanctuary.jpg",
      name: "Chidikho-Narsinghgarh Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://rajgarh.nic.in/en/tourist-place/chidikho-narsinghgarh/",
      info:"In the center of this sanctuary “Chidikho Lake” is situated which is one of the attraction among the tourists. This sanctuary is built by the rulers of the state and in the ancient time this sanctuary is used for hunting purpose by the rulers. ",
      map : "https://goo.gl/maps/FmedH2889V71ZcLh6"},
    {
      id: 29,
      image: "assets/Madhya Pradesh/WildLife/National Chambal Wildlife Sanctuary.jpg",
      name: "National Chambal Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.mptourism.com/national-chambal-sanctuary.html",
      info:"The cleanest of all, Chambal is haven for countless wildlife! The legend has it that the River Chambal originated from the blood of thousands of cows sacrificed by a ruthless king wanting supreme powers. ",
      map : "https://g.page/Palighatchambal?share",
      },
    {
      id: 30,
      image: "assets/Madhya Pradesh/WildLife/Noradehi Wildlife Sanctuary.jpg",
      name: "Nauradehi Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.nauradehiwls.in/",
      info:"Nauradehi Wildlife Sanctuary is the largest wildlife sanctuary in Madhya Pradesh. The sanctuary covers nearly 1197 km² area across three districts i.e. Sagar, Damoh and Narsinghpur, of Madhya Pradesh. The entire Sanctuary is situated on a plateau, forming part of upper Vindhyan range,",
      map : "https://goo.gl/maps/U2Pn1JiMg8HB5XfM8"
    },
    {
      id: 31,
      image: "assets/Madhya Pradesh/Food 3/dal-bafla.jpg",
      name: "Dal Bafla",
      category: "Food",
      info:"Dal Bafla that is fondly served in many parts of Madhya Pradesh has got its influence from Rajasthani cuisine. Dal Bafla is a mouth-watering cuisine which is very similar to the famous Dal Bati of Rajasthan. Bafla is a delicious treat of the wheat balls well cooked in ghee. The dish is well complemented with a bowl of Dal and coriander sauce (Hari chutney).",
    
    },
    {
      id: 32,
      image: "assets/Madhya Pradesh/Food 3/Mutton_Seekh_Kabab.jpg",
      name: "Seekh Kababs",
      category: "Food",
      info:"The food palate of Madhya Pradesh has got a strong influence from Mughal cuisines. In all the parts of the state, you will be served with some of the best Mughlai cuisines that are highly inspired by the Mughal style cooking. Seekh Kebabs are being one of the most savoured non-vegetarian dishes of Madhya Pradesh."
     ,
    },      {
      id: 33,
      image: "assets/Madhya Pradesh/Food 3/bhutte-ki-kees.jpg",
      name: " Bhutte Ka Kees",
      category: "Food",
      info:"Another healthy and yet delicious delicacy of Madhya Pradesh is Bhutte Ka Kees. As the name clearly suggests, this dish mainly comprises of corns. Grated corns are well-cooked with spices and skimmed milk which adds a slightly sweet taste to the dish. Mustard seeds and green chillies are further added to enhance the taste of this authentic cuisine of Madhya Pradesh. ",
      
    },
    {
      id: 34, 
      image: "assets/Madhya Pradesh/Food 3/chakki-ki-shak1.jpg",
      name: "Chakki Ki Shak",
      category: "Food",
      info:"Chakki ki Shak is a dish which has got its influence from Rajasthani cuisine. The dish is prepared with steamed dough which is later added to the gravy which is prepared with different kinds of Indian spices. The dish is best complemented with a bowl of curd and is fondly eaten in the whole of Madhya Pradesh.        ",
     
    },
    {
      id: 35,
      image: "assets/Madhya Pradesh/Food 3/indian-malpua1.jpg",
      name: "Malpua",
      category: "Food",
      info:"Say hello to the India’s own pancakes. Malpua is majorly prepared with flour, fried in ghee and then dipped in the sugar syrup to add the taste that will make you crave for the dish again and again. The dressing of some saffron can further enhance the taste of this dish. Malpua is best served with rabdi for a complete treat."
      
     },
    {
      id: 36,
      image: "assets/Madhya Pradesh/Food 3/jalebi.jpg",
      name: "Jalebi",
      category: "Food",
      info:"One dish that you will be seeing in every and nook of the state is Jalebi. And, trust me, you can expect a heavenly taste of this amazing delicacy of Madhya Pradesh even in the hidden interior of the state. The dish is prepared with utmost love in wheat flour, fried and then soaked in sugar syrup. The crisp taste of this sweet dish will revive your love for the most popular dish of Madhya Pradesh.",
     
     }, 
];

export default MadhyaPradeshData;
