const MaharashtraData = [
  {
    id: 1, 
    image: "assets/Maharashtra/Hill Stations/chikhaldara.jpg",
    name: "Chikhaldara",
    category: "HillStation",
    description: "https://www.kayak.co.in/horizon/sem/hotels/destination/c113632?lang=en&utm_campaign=Destination+-+IN+-+Chikhaldara+-+City%23113632&utm_content=City+-+booking+chikhaldara+-+T%3Dbooking+-+P%3Dnone+-+D%3DCity%23113632&utm_medium=cpc&utm_source=bing&utm_term=chikhaldara+booking&skipapp=true&rooms=1&kw=-1",
    info : "Chikhaldara (chikaldara, chikhaldhara) is located in Amaravati district of Vidarbha region. The only hill station in the Vidarbha region offers you an abundance of wildlife, viewpoints, lakes and waterfalls. Chikhaldara has many things to be explored. It is named after “Keechaka”.",
    map : "https://goo.gl/maps/zf6mobS8fv5ZhQ2Y8",
  },
  {
    id: 2,
    image: "assets/Maharashtra/Hill Stations/igatpuri.jpg",
    name: "Igatpuri",
    category: "HillStation",
    description:  "https://www.makemytrip.com/hotels/igatpuri-hotels.html",
    info : "Igatpuri is known for Vipassana International Academy, where ancient technique of meditation is taught called Vipassana. The place is one of the best places to visit in Maharashtra in monsoon. It is a hill station on busy Mumbai-Agra NH-3 only 45 km from Nashik and 130 km from Mumbai.",
    map : "https://goo.gl/maps/HZarP4qU4MLgVgfd8",
   },
  {
    id: 3,
    image: "assets/Maharashtra/Hill Stations/khandala.jpg",
    name: "khandala",
    category: "HillStation",
    description: "https://www.booking.com/district/in/lonavale/khandala.en-gb.html?aid=357028&label=bin859jc-1DCAcobEIRbG9uYXZhbGVfa2hhbmRhbGFIM1gDaGyIAQGYAQm4ARfIAQzYAQPoAQGIAgGoAgO4ApqR7ZsGwAIB0gIkZjZkN2YzMjAtMWZhMS00NmU4LThiYjAtZGU5ZDE3NDc3Y2M02AIE4AIB&sid=00e4eb464db1f76f593a04e6ed248a32&inac=0&keep_landing=1&",
    info : "Khandala is a popular hill station in Maharashtra, perched on the foothills of Sahyadri in the Western Ghats.",
    map : "https://goo.gl/maps/poZ1iCzmLc7rG3mB7"
   },
  {
    id: 4,
    image: "assets/Maharashtra/Hill Stations/lavasa.jpg",
    name: "Lavasa",
    category: "HillStation",
    description: "https://www.booking.com/city/in/lavasa.en.html?aid=2121859&label=msn-W7JuOZjh1GXX*cfmhgERnQ-80745499149445:tikwd-80745618660798:aud-807859093:loc-90:neo:mtb:lp1663:dec:qslavasa%20mh%20booking&utm_campaign=India&utm_medium=cpc&utm_source=bing&utm_term=W7JuOZjh1GXX*cfmhgERnQ&msclkid=03a8901ed29213fe87fff3659a7b5500",
    info : "Lavasa is India’s First Smart City. Smart City with 5 towns, with each having a distinct character, style and ethos.",
    map : "https://goo.gl/maps/d6Xsx2L54xgF5B2R6"},
  {
    id: 5,
    image: "assets/Maharashtra/Hill Stations/mahabaleshwar.jpg",
    name: "Mahabaleshwar",
    category: "HillStation",
    description: "https://www.booking.com/city/in/mahabaleshwar.en.html?aid=367295&label=msn-Kul4p*VNHHOy*0958g2iGw-79989573210587:tikwd-17264531755:loc-90:neo:mtp:lp1663:dec:qsmahabaleshwar%20mh%20booking&utm_campaign=India&utm_medium=cpc&utm_source=bing&utm_term=Kul4p*VNHHOy*0958g2iGw&msclkid=e77d77cdfbbe1b467bdc14b6b2f991b1",
    info : "The Mahabaleshwar Hill Station is Located in the green and mystical Sahyadri hills of the Western Ghats in the Satara district of Maharashtra, India, Mahabaleshwar is one of most renowned and relaxing hill stations of peninsular India.",
    map : "https://goo.gl/maps/xvmMFnVf6LRA7H7XA",
    },
  {
    id: 6,
    image: "assets/Maharashtra/Hill Stations/malshej.jpg",
    name: "Malshej",
    category: "HillStation",
    description: "https://www.tripadvisor.in/Attraction_Review-g2531523-d3705864-Reviews-Phansad_Bird_Sanctuary-Raigad_Raigad_District_Maharashtra.html",
    info : "A slender gorge tucked in the ragged hills of Western Ghats in the Pune District of Maharashtra, Malshej Ghat Hill Station is home to a varied species of flora and fauna. ",
    map : "https://goo.gl/maps/5DkW55E8i7VPBzNo9"
  },
  {
    id: 7,
    image: "assets/Maharashtra/Hill Stations/matheran.jpg",
    name: "Matheran",
    category: "HillStation",
    description: "https://www.maharashtratourism.gov.in/-/rehekuri-blackbuck-sanctuary",
    info : "Matheran is a hill station and a municipal council in Karjat Tahsil in the Raigad district in the Indian state of Maharashtra. Matheran is part of the Mumbai Metropolitan Region. Matheran is one of the smallest hill stations in India. ",
    map : "https://goo.gl/maps/y8Pu7FmY2AESNaes6"
  },
  {
    id: 8,
    image: "assets/Maharashtra/Hill Stations/panchgani.jpg",
    name: "Panchgani",
    category: "HillStation",
    description: "https://www.booking.com/city/in/panchgani.en.html?aid=339462&label=msn-ItgG9tQUl2AfRZ67BDYMiA-14131312102:tikwd-138106597625:aud-807859093:loc-90:neo:mtp:lp154691:dec:qspanchgani%20hill%20station%20maharashtra%20info%20booking&utm_campaign=India&utm_medium=cpc&utm_source=bing&utm_term=ItgG9tQUl2AfRZ67BDYMiA&msclkid=9f34e04c9bf614740cd883371f7202e7",
    info : "Panchgani is a hill station southeast of Mumbai in India’s Maharashtra state. It’s known for the Table Land, a huge volcanic plateau. Lookouts like Sydney Point and Parsi Point offer views of Dhom Dam lake and Kamalgad Fort, used as a prison by the British in the early 19th century.",
    map : "https://goo.gl/maps/T1sdsnHALfHsFKJQ7",
  },
  {
      id: 9, 
      image: "assets/Maharashtra/WildLife Sanctuaries/Bhigwan Bird Sanctuary.png",
      name: "Bhigwan Bird Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.bhigwanbirdsanctuary.com/",
      info : "Bhigwan is a small town on the outskirts of Pune at Pune-Solapur Highway which has a lot to offer. The Bhigwan Bird Sanctuary is a paradise of birds and especially the migratory birds, the most noteworthy being the Flamingos which arrive in the winters here. ",
      map : "https://goo.gl/maps/kcLzan23o4xFxZFe9",
    },
    {
      id: 10,
      image: "assets/Maharashtra/WildLife Sanctuaries/BhimaShankar.png",
      name: "Bhimashankar",
      category: "Wildlife Sanctuaries",
      description: "https://www.maharashtratourism.gov.in/-/bhimashankar-wild-life-sanctuary-1",
      info : "Bhimashankar Wildlife Sanctuary was created in the Ambegaon and Khed talukas of Pune District, in the Western Indian state of Maharashtra in order mainly to protect the habitat of the Indian Giant Squirrel. ",
      map : "https://goo.gl/maps/UwxC6LG1ati1fpkj6",
     },
    {
      id: 11,
      image: "assets/Maharashtra/WildLife Sanctuaries/koyna.png",
      name: "Koyna",
      category: "Wildlife Sanctuaries",
      description: "https://www.transindiatravels.com/maharashtra/koyna-wildlife-sanctuary/",
      info : "A luscious forest spanning over 423 square kilometers in Satara district of Maharashtra, Koyna Wildlife Sanctuary is known for its beautiful landscapes and abundant flora that offers a perfect environment for the mammals to survive.",
      map : "https://goo.gl/maps/JZ4rrhaBobhQ9zFm9"
     },
    {
      id: 12,
      image: "assets/Maharashtra/WildLife Sanctuaries/melghat.jpg",
      name: "Melghat",
      category: "Wildlife Sanctuaries",
      description: "https://www.magicalmelghat.in/",
      info : "Melghat, located in the Amaravati district of Maharashtra, is a tiger reserve wildlife sanctuary. Melghat Tiger Reserve is located on the southern offshoot of the Satpura Hill Range in Central India, called Gavilgarh Hill.",
      map : "https://goo.gl/maps/pFcpbxRRVH8wJ4MW6"
   },
    
    {
      id: 13,
      image: "assets/Maharashtra/WildLife Sanctuaries/Rahekuri Blackbuck Sanctuary.png",
      name: "Rehekuri Blackbuck Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.maharashtratourism.gov.in/-/rehekuri-blackbuck-sanctuary",
      info : "The Rehekuri Blackbuck Sanctuary is a dry deciduous scrub forested area with large areas covered in rich grasslands. Though blackbucks are the main species, the sanctuary is also home to much other wildlife and avifauna.",
      map : "https://goo.gl/maps/B6NoL12yWjo51YgW8"
    },
    {
      id: 14,
      image: "assets/Maharashtra/WildLife Sanctuaries/tadoba.jpg",
      name: "Tadoba",
      category: "Wildlife Sanctuaries",
      description: "http://tadoba.org.in/",
      info : "The Tadoba Andhari Tiger Reserve is a wildlife sanctuary in Chandrapur district of Maharashtra state in India. It is Maharashtra's oldest and largest national park. Created in 1955, the reserve includes the Tadoba National Park and the Andhari Wildlife Sanctuary.        ",
      map : "https://goo.gl/maps/dvRSjXYCZvFa3bxW8",
    },
     {
      id: 15, 
      image: "assets/Maharashtra/Religious Tours/haji ali.jpg",
      name: "HajiAli",
      category: "Religious",
      description: "https://www.maharashtratourism.gov.in/-/haji-ali-dargah",
      info : "The Haji Ali Dargah is one of Mumbai’s most iconic landmarks and must not be missed. It is not merely a Dargah or a tourist attraction; it is an entirely different experience. Despite the constant bustle, there is an aura of tranquility while entering the monument. ",
      map : "https://goo.gl/maps/j2RijiZksiqZbrpQA",
    },
    {
      id: 16,
      image: "assets/Maharashtra/Religious Tours/mahalakshmiji.jpg",
      name: "Mahalakshmi Temple",
      category: "Religious",
      description:  "https://mumbaicity.gov.in/tourist-place/mahalakshmi-temple/",
      info : "Mahalaxmi Temple is one of the most famous temples of Mumbai situated on Bhulabhai Desai Road in Mahalaxmi area. It is dedicated to Mahalakshmi the central deity of Devi Mahatmyam. The temple was built in 1831 by Dhakji Dadaji, a Hindu merchant.",
      map : "https://goo.gl/maps/DbSvojWqYFRxCBZj7",
     },
   
    {
      id: 17,
      image: "assets/Maharashtra/Religious Tours/pandharpur.jpg",
      name: "Pandharpur",
      category: "Religious",
      description: "https://www.maharashtratourism.gov.in/-/pandharpur",
      info : "PANDHARPUR – This is a holy place of Shri.Vitthal and Shri.Rukmini. It is also known as the Southern Kashi of India and Kuldaivat of Maharashtra State. It is located at a distance of 72 kms by road. from Solapur District headquarters.",
      map : "https://goo.gl/maps/HxxLaFbUyddU2BgJ9"},
    {
      id: 18,
      image: "assets/Maharashtra/Religious Tours/shirdi.jpeg",
      name: "Shirdi",
      category: "Religious",
      description: "https://www.shirdibaba.org/shirdi/acf.htm",
      info : "Sai Baba of Shirdi (c. 1838? - died 15 October 1918), also known as Shirdi Sai Baba, was an Indian spiritual master and fakir, considered to be a saint, revered by both Hindu and Muslim devotees during and after his lifetime.",
      map : "https://goo.gl/maps/7A3Jc6jEKjbe2WbV7",
      },
    {
      id: 19,
      image: "assets/Maharashtra/Religious Tours/siddhivinayak.jpg",
      name: "Shree Siddhivinayak Temple",
      category: "Religious",
      description: "https://www.siddhivinayak.org/",
      info : "The Shree Siddhivinayak Ganapati Mandir is a Hindu temple dedicated to Lord Shri Ganesh. It is located in Prabhadevi, Mumbai, Maharashtra. The temple has a small mandap with the shrine for Siddhi Vinayak (“Ganesha who grants your wish”).",
      map : "https://goo.gl/maps/fCjJV1FjntNchErT9"
    },
    {
      id: 20,
      image: "assets/Maharashtra/Religious Tours/tuljabhavani mata.jpg",
      name: "Tuljapur",
      category: "Religious",
      description: "https://osmanabad.gov.in/tourist-place/shri-tuljabhavani-mandir-tuljapur/",
      info : "Tuljabhavani Temple is a Hindu temple dedicated to the goddess Bhavani ( Parvati aspect of Durga).It is located in Tuljapur in Osmanabad district of Maharashtra and is considered as one of the 51 Shakti Pithas. It is situated 45 km from Solapur .The temple was built in c. 12th century CE.",
      map : "https://goo.gl/maps/huDvk3UYgVfGAcZLA"
    },
    {
      id: 21, 
      image: "assets/Maharashtra/Heritage Tours/aga khana.jpg",
      name: "Ajanta Ellora Caves",
      category: "Heritage",
      description: "https://www.holidify.com/places/ajanta-and-ellora-caves",
      info : "Ajanta and Ellora caves, considered to be one of the finest examples of ancient rock-cut caves, are located near Aurangabad in Maharashtra, India. Ajanta and Ellora caves complex is adorned with beautiful sculptures, paintings, and frescoes and include Buddhist monasteries, Hindu and Jain temples.",
      map : "https://goo.gl/maps/S77pJmH1JAaCSLyw9",
    },
    {
      id: 22,
      image: "assets/Maharashtra/Heritage Tours/Bibi ka ma.jpg",
      name: "Bibi ka Maqbara",
      category: "Heritage",
      description:  "https://www.holidify.com/places/aurangabad/bibi-ka-maqbara-sightseeing-1228.html",
      info : "Having a striking resemblance to Taj Mahal, the Bibi ka Maqbara is a beautiful mausoleum of Rabia- Ul - Daurani alias Dilras Banu Begum, the wife of Mughal Emperor Aurangzeb. Bibi ka Maqbara was constructed by Aurangzeb in the year 1661 in the memory of his wife. ",
      map : "https://goo.gl/maps/AErMh5PaB7JVbYay7",
     },
    {
      id: 23,
      image: "assets/Maharashtra/Heritage Tours/aga khana.jpg",
      name: "Aga Khan Palace",
      category: "Heritage",
      description: "https://www.maharashtratourism.gov.in/-/aga-khan-palace-popular-cities",
      info : "The Aga Khan Palace was built by Sultan Muhammed Shah Aga Khan III in Pune, India. The palace was an act of charity by the spiritual leader of the Nizari Ismaili Muslims, who wanted to help the poor in the neighbouring areas of Pune, who were drastically hit by famine.",
      map : "https://goo.gl/maps/ePkuqT3EKCxgMf6G9"
     },
    {
      id: 24,
      image: "assets/Maharashtra/Heritage Tours/elephanta caves.jpg",
      name: "Elephanta Caves",
      category: "Heritage",
      description: "https://www.maharashtratourism.gov.in/mr/-/elephanta-cave-popular-cities",
      info : "The 'City of Caves', on an island in the Sea of Oman close to Bombay, contains a collection of rock art linked to the cult of Shiva. Here, Indian art has found one of its most perfect expressions, particularly the huge high reliefs in the main cave.",
      map : "https://goo.gl/maps/AnihN9XCPFJJAzQs5"},
    {
      id: 25,
      image: "assets/Maharashtra/Heritage Tours/gateway of india.jpg",
      name: "Gateway of India",
      category: "Heritage",
      description: "https://mumbaicity.gov.in/tourist-place/gateway-of-india/",
      info : "The Gateway of India is an arch-monument built in the early 20th century in the city of Bombay (Mumbai), India. It was erected to commemorate the landing of King-Emperor George V, the first British monarch to visit India, in December 1911 at Strand Road near Wellington Fountain. ",
      map : "https://goo.gl/maps/35ndxsbsHnPmkaASA",
      },
    {
      id: 26,
      image: "assets/Maharashtra/Heritage Tours/shanivarwada.jpg",
      name: "Shanivarwada",
      category: "Heritage",
      description: "https://pune.gov.in/tourist-place/shaniwarwada/",
      info : "Shaniwar Wada a 13 storey palace of Peshwas was built by Bajirao-I, in the year 1736.It was head quarter of the Peshwas and it symbolizes Pune’s culture.The structure was built giving security the highest priority. The main entrance is known as ‘Delhi Darwaja’ & others have names like Ganesh, Mastani, Jambhal, Khidki. ",
      map : "https://goo.gl/maps/5H54sCfnAht9ZRge6"
    },
    {
      id: 27,
      image: "assets/Maharashtra/Forts Tours/daulatabad.jpg",
      name: "Daulatabad Fort",
      category: "Forts",
      description: "https://www.maharashtratourism.gov.in/mr/-/daultabad-devigiri-fort",
      info : "Daulatabad Fort, also known as Devagiri or Deogiri, is a historical fortified citadel located in Aurangabad, Maharashtra, India. It was the capital of the Yadava dynasty (9th century–14th century CE), for a brief time the capital of the Delhi Sultanate (1327–1334), and later a secondary capital of the Ahmadnagar Sultanate (1499–1636)..",
      map : "https://goo.gl/maps/jg3fgjdKqdFSFNd16"
    },
    {
      id: 28,
      image: "assets/Maharashtra/Forts Tours/lohogad.jpg",
      name: "Lohagad Fort",
      category: "Forts",
      description: "https://www.holidify.com/places/khandala/lohagad-fort-sightseeing-2347.html",
      info : "Lohagad is one of the many hill forts of Maharashtra state in India. Situated close to the hill station Lonavala and 52 km (32 mi) northwest of Pune, Lohagad rises to an elevation of 1,033 m (3,389 ft) above sea level. The fort is connected to the neighboring Visapur fort by a small range. ",
      map : "https://goo.gl/maps/VTeRor1QFZNymUb56https://goo.gl/maps/VTeRor1QFZNymUb56"
    },
    {
      id: 29,
      image: "assets/Maharashtra/Forts Tours/murud janjira.jpg",
      name: "Murud Janjira",
      category: "Forts",
      description: "https://www.holidify.com/places/murud-janjira/",
      info : "Murud-Janjira is the local name of a famous fort and tourist place situated on an island just off the coastal city of Murud, in the Raigad district of Maharashtra, India. The word Janjira is not native to India, and may have originated after the Arabic word Jazeera, which means Island.",
      map : "https://goo.gl/maps/NanEDPmACx421UnG6"
    },
    {
      id: 30, 
      image: "assets/Maharashtra/Forts Tours/Pratapgad fort.jpg",
      name: "Pratapgad",
      category: "Forts",
      description: "https://www.satara.gov.in/en/tourist-place/pratapgad/",
      info : "Pratapgad literally 'Valour Fort' is a large mountain fort located in Satara district, in the Western Indian state of Maharashtra .The fort's historical significance is due to the Battle of Pratapgad in 1659.The fort is now a popular tourist destination.",
      map : "https://goo.gl/maps/Avk2Mn2DMqu4EjsW6",
    },
    {
      id: 31,
      image: "assets/Maharashtra/Forts Tours/shivneri.jpg",
      name: "Shivneri",
      category: "Forts",
      description:  "https://www.punetrekkers.com/shivneri-fort",
      info : "Shivneri Fort is a hill fort having a triangular shape and has its entrance from the South-west side of the hill. Apart from the main gate there is an entrance to the fort from side called locally as the chain gate, where in one has to hold chains to climb up to the fort gate. ",
      map : "https://goo.gl/maps/1bjiJieqVCFzdyb56",
     },
    {
      id: 32,
      image: "assets/Maharashtra/Forts Tours/Singagad Fort.jpg",
      name: "Sinhagad Fort",
      category: "Forts",
      description: "https://www.holidify.com/places/pune/sinhagad-fort-sightseeing-125028.html",
      info : "Sinhagad is a hill fortress located at around 35 km southwest of the city of Pune, India. Some of the information available at this fort suggests that the fort could have been built 2000 years ago. The caves and the carvings in the Kaundinyeshwar temple stand as proofs for the same. ",
      map : "https://www.google.com/maps/place/Koyna+Wildlife+Sanctuary/@17.7691381,73.7399131,17z/data=!4m6!3m5!1s0x3bc26db900008b51:0xebf3979d1af2cb85!8m2!3d17.769133!4d73.7421018!16zL20vMGQ4eGZ0?hl=en-GB"
     },
    {
      id: 33,
      image: "assets/Maharashtra/Beaches/alibaug.jpg",
      name: "Alibag",
      category: "Beaches",
      description: "https://www.holidify.com/places/alibag/",
      info : "Alibaug (also spelled as Alibag) is a small coastal town in the Konkan region of Maharashtra, known for its beaches, villas, and beautiful scenery. Alibag is very popular as a weekend getaway from the cities of Mumbai and Pune. ",
      map : "https://goo.gl/maps/8urTRBUPaSGgz2PZ8"},
    {
      id: 34,
      image: "assets/Maharashtra/Beaches/ganpatipule beach.jpg",
      name: "Ganpatipule Beach",
      category: "Beaches",
      description: "https://www.holidify.com/places/ganapatipule/ganapatipule-beach-sightseeing-1800.html",
      info : "Blessed with tranquil landscapes along the Konkan coast in Maharashtra, Ganapatipule is known to be a haven for beach lovers. Attracting a dozen tourists who look forward to having a getaway in the realm of nature with peace and tranquillity.",
      map : "https://goo.gl/maps/p8t9tyoLALNipZ7G7",
      },
    {
      id: 35,
      image: "assets/Maharashtra/Beaches/juhu.jpg",
      name: "Juhu Beach",
      category: "Beaches",
      description: "https://www.agoda.com/en-in/pages/agoda/default/DestinationSearchResult.aspx?poi=140082&site_id=1758155&tag=f44dfa82-a620-fcf5-c852-58d629294bf6&msclkid=c3ee7aed970411a77a0019909884d8ed&utm_source=bing&utm_medium=cpc&utm_campaign=Intent%20Engine%20-%20011&utm_term=%2Bmumbai%20%2Bjuhu%20%2Bbeach&utm_content=mumbai%7Cpo%3Ajuhu%20beach_140082",
      info : "Juhu Beach is located on the shores of the Arabian Sea. It stretches for six kilometres up to Versova .The short, rocky formations make up the Juhu Beach unlike the Marina Beach in Chennai that is primarily sandy.",
      map : "https://goo.gl/maps/WitMwx8eiTkczG99A"
    },
    {
      id: 36,
      image: "assets/Maharashtra/Beaches/Tarkarli Beach.png",
      name: "Tarkarli Beach",
      category: "Beaches",
      description: "https://www.agoda.com/en-in/pages/agoda/default/DestinationSearchResult.aspx?city=702306&site_id=1758155&tag=99c83dcb-00cc-2120-51e0-fc7e34b21c2a&msclkid=f3f9fc805bef1e685d799ffd4bbbaf33&utm_source=bing&utm_medium=cpc&utm_campaign=Intent%20Engine%20-%20009&utm_term=%2Btarkarli%20%2Bbeach&utm_content=tarkarli%20beach%7Cci%3Amalvan_702306",
      info : "Tarkarli is a village in Malvan taluka in Sindhudurg district in the Indian state of Maharashtra. It is a beach destination and remote place in southern Maharashtra. Few years ago, Tarkarli beach is declared as a Queen Beach of Konkan region.",
      map : "https://goo.gl/maps/H4M22RwCi7S9bgp89"
    },
    {
      id: 37,
      image: "assets/Maharashtra/Beaches/Shivardhan Beach.png",
      name: "Shivardhan Beach",
      category: "Beaches",
      description: "https://www.tripadvisor.in/Attraction_Review-g1162202-d8682502-Reviews-Shrivardhan_Beach-Shrivardhan_Raigad_District_Maharashtra.html",
      info : "The expansive and clean beach at Shrivardhan in Raigadh district is a clean beach and is a long stretch on the Arabian Sea. Being quite near to Mumbai, it forma a good weekend break.",
      map : "https://goo.gl/maps/d2qq2DypjXvmy19z6"
    },
    {
      id: 38, 
      image: "assets/Maharashtra/Beaches/Harihareshwar beach.png",
      name: "Harihareshwar Beach",
      category: "Beaches",
      description: "https://www.tripadvisor.in/Attraction_Review-g1447522-d4088523-Reviews-Harihareshwar_Beach-Harihareshwar_Raigad_District_Maharashtra.html",
      info : "Harihareshwar is renowned tourist spot in Konkan for its temples and beaches. Moreover, it is said as Devbhumi or Temple Town. Harihareshwar alone have two beaches − one, straight beach about 2.4 km long in front of Harihareshwar Temple, and the other beach is about 2 km in an L shape just in front of MTDC Resort.",
      map : "https://goo.gl/maps/rZrcD8NnHqAkDaK56",
    },
    {
      id: 39,
      image: "assets/Maharashtra/Food/Vada pav.jpg",
      name: "Vada Pav",
      category: "Food",
      info:"Vada Pav is one of the most famous fast food of Maharashtra people. If you will visit Mumbai you will find Vada Pav at every corner. Many times when I am in a hurry and can’t have breakfast I buy Vada Pav at the local railway station. It would cost me around Rs 8-10.",
      
    },
    {
      id: 40,
      image: "assets/Maharashtra/Food/Puranpoli.jpg",
      name: "Puran Poli",
      category: "Food",
      info:"Puran Poli is the sweet dish of Maharashtra. I call it sweet paratha because of its look. It is made up of Chana dal, cardamom, wheat, and sugar.Puran Poli is famous in many parts of India. You will find different varieties of Puran Poli depending upon the place.  ",
    
    },
    {
      id: 41,
      image: "assets/Maharashtra/Food/Pithal Bhakri.jpg",
      name: "Pithla Bhakri",
      category: "Food",
      info:"Pithla Bhakri is one of the most popular staple foods of rural Maharashtra. Pithla is made from Chickpea flour/ Gram flour and is very tasty. Bhakri is round bread made up of mainly wheat or bajra. Nowadays Pithla Bhakri is gaining some traction in cities also.        ",
      
    },
    {
      id: 42, 
      image: "assets/Maharashtra/Food/Thaliipeeth.jpg",
      name: "Thalipeeth",
      category: "Food",
      info:"Thalipeeth is one of the most protein-rich foods of Maharashtra people. It is multigrain bread prepared by rice, wheat, bajra, jowar, chana, urad, etc.  Apart from that coriander seeds, cumin seeds, green vegetables are also used. It is one of the tastiest traditional food of Maharashtra.        ",
    
    },
    {
      id: 43,
      image: "assets/Maharashtra/Food/Misal.jpg",
      name: "Misal",
      category: "Food",
      info:"If you like eating spicy food then you are definitely going to like it. Misal is made up of sprouted lentils, species, onions, tomatoes, etc. On top of that, they squeeze some lemon juice. It is mainly served with butter Pav and yogurt. ",
    },
    {
      id: 44,
      image: "assets/Maharashtra/Food/Malvani Thali.jpg",
      name: "Malvani Cuisine",
      category: "Food",
      info:"Malvani Cuisine is best traditional food of Malvani region of Maharashtra. It is mainly served in the South Konkan region of Maharashtra. Most of the Malvani cuisines are non-veg but there are various veg cuisines also. Coconut is the predominant part of Malvani Cuisine."},
      
   
   
];

export default MaharashtraData;


