const NagalandData = [
    {
      id: 1, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: "Semoma/Khonoma fort",
      category: "Fort",
      description: "https://www.deccanherald.com/sunday-herald-travel/khonoma-asias-envy-and-pride-713641.html",
      info : "The Khonoma Fort, built of broken rocks, and which has seen numerous demolitions and reconstructions is the pride of the Angamis. Just beside the fort, one can see the battle-shield made of elephant hide, the village gong and an array of large bamboo.Khonoma is an Angami Naga village located about 20 km west from the state capital, Kohima in Nagaland, India. The village is referred to as Khwüno-ra. The total population of the village is about 1943, settled in 424 households. It is the first green village in India.",
      map : "https://www.google.com/maps/place/Semoma,+Upper+Circular+Rd,+Khonoma,+Nagaland+797002/@25.6556298,94.0217123,18.56z/data=!4m5!3m4!1s0x0:0x6e38819f6ca13589!8m2!3d25.6556618!4d94.0217868",
    },
    {
      id: 2,
      image: "assets/Maharshtra/HillStation/khandala.jpg",
      name: "Kachri rajbari fort",
      category: "Fort",
      description: "https://en.wikipedia.org/wiki/Ruins_of_Kachari_Rajbari",
      info : "Ruins of Kachari Rajbari are a set of ruins located in Dimapur, Nagaland in Northeast India. Their history dates back to the 10th century when they appeared during the Kachari civilization. The Kachari Rajbari Ruins are a series of mushroom domed pillars. They were created by the Kachari Kingdom, which ruled Dimapur before the Ahom invasion into the territory during the 13th century. ",
      map : "https://www.google.com/maps/dir//WP3Q%2BFX9+Kachari+Rajbari+(Ruins+of+a+Fort),+Walford+Rd,+Walford+Colony,+Dimapur,+Nagaland+797117/@23.8293128,77.294441,5z/data=!4m18!1m8!3m7!1s0x3745e1bdf64e273d:0xa600dcb40a543bc6!2sKachari+Rajbari+(Ruins+of+a+Fort)!8m2!3d25.9036572!4d93.7399864!15sChNLYWNocmkgcmFqYmFyaSBmb3J0kgETaGlzdG9yaWNhbF9sYW5kbWFya-ABAA!16s%2Fg%2F11s7057pcl!4m8!1m0!1m5!1m1!1s0x3745e1bdf64e273d:0xa600dcb40a543bc6!2m2!1d93.7399864!2d25.9036572!3e2",
     },
    {
      id: 3,
      image: "assets/Maharshtra/HillStation/malshej.jpg",
      name: "Naga heritage village",
      category: "Heritage",
      description: "https://www.tourmyindia.com/states/nagaland/naga-heritage-village.html	",
      info : "Naga Heritage Village also known as Kisama Heritage Village is only one in Nagaland. The place is wrapped in breathtaking scenic views at the foothills of the lustrous and evergreen hills on the borderline of this village. It is surrounded by all types of flora. Naga Heritage village is rich in its tradition and cultural activities.",
      map : "https://www.google.com/maps/dir//naga+heritage+village/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x374620862956f199:0xee7aae4c467ce975?sa=X&ved=2ahUKEwjV-OyQiO37AhUaAIgKHccnCqoQ9Rd6BAh1EAM",
    },
    {
      id: 4,
      image: "assets/Maharshtra/HillStation/matheran.jpg",
      name: "Kohima war cemetery",
      category: "Heritage",
      description: "https://en.wikipedia.org/wiki/Kohima_War_Cemetery",
      info : "Kohima War Cemetery is a memorial dedicated to soldiers of the 2nd British Division of the Allied Forces who died in the Second World War at Kohima, the capital of the Indian state of Nagaland in April 1944. The soldiers died on the battleground of Garrison Hill in the tennis court area of the Deputy Commissioner's residence. ",
      map : "https://www.google.com/maps/dir//Kohima+War+Cemetery,+Midland+Colony,+Kohima,+Nagaland+797005/@25.6676293,94.1029515,15z/data=!4m17!1m7!3m6!1s0x0:0xf058c8c814688900!2sKohima+War+Cemetery,+Midland+Colony,+Kohima,+Nagaland+797005!3b1!8m2!3d25.6676293!4d94.1029515!4m8!1m0!1m5!1m1!1s0x374621a4549dc845:0xf058c8c814688900!2m2!1d94.1029515!2d25.6676293!3e2",
    },
    {
      id: 5,
      image: "assets/Maharshtra/HillStation/panchgani.jpg",
      name: "Khonoma village",
      category: "HillStation",
      description: "https://en.wikipedia.org/wiki/Khonoma",
      info : "Khonoma is an Angami Naga village located about 20 km west from the state capital, Kohima in Nagaland, India. The village is referred to as Khwüno-ra. The total population of the village is about 1943, settled in 424 households. It is the first green village in India.",
      map : "https://www.google.com/maps/dir//Khonoma,+Nagaland+797002/@25.6524092,94.0240508,16z/data=!4m17!1m7!3m6!1s0x37461e0d4243ac01:0xa9b1f77fdd37785d!2sKhonoma,+Nagaland+797002!3b1!8m2!3d25.6523425!4d94.0229921!4m8!1m0!1m5!1m1!1s0x37461e0d4243ac01:0xa9b1f77fdd37785d!2m2!1d94.0229921!2d25.6523425!3e2",
    },
    {
        id: 6, 
        image: "assets/Maharshtra/WildLife/Bhigwan.png",
        name: "Dimapur",
        category: "HillStation",
        description: "https://www.tourmyindia.com/states/nagaland/dimapur.html",
		info : "The gateway to Nagaland, Dimapur is an irresistible part of Northeast, and a must-visit travel places. Dimapur in Naga means the ‘the city near a great river.’ With Dhansiri River on one side, and wooden meadows flanking the other, Dimapur was the former capital of the Kachari tribe, traces of which can be seen even today.",
		map : "https://www.google.com/maps/dir//Dimapur,+Nagaland/@25.8608191,93.7464512,12z/data=!4m17!1m7!3m6!1s0x3745e1f28b41fff3:0xdccf69dd5fa3c95!2sDimapur,+Nagaland!3b1!8m2!3d25.9091406!4d93.7265605!4m8!1m0!1m5!1m1!1s0x3745e1f28b41fff3:0xdccf69dd5fa3c95!2m2!1d93.7265605!2d25.9091406!3e2",
      },
      {
        id: 7,
        image: "assets/Maharshtra/WildLife/BhimaShankar.png",
        name: "Mokokchunh",
        category: "HillStation",
        description: "https://www.holidify.com/places/Mokokchung",
		info : "Mokokchung is the most significant urban centre in all of Nagaland after Dimapur and Kohima and the home of Ao Naga.The popular tourist spots in the area include the District Museum, the Town main park, (located just above the Town Center), Unman village (which is regarded as the oldest and largest) and the Ao village. ",
		map : "https://www.google.com/maps/place/Mokokchung,+Nagaland/@26.3221123,94.5182561,14z/data=!3m1!4b1!4m5!3m4!1s0x3747a9b0b63694b1:0xa9c827ff52311e58!8m2!3d26.3220358!4d94.5134629",
       },
      {
        id: 8,
        image: "assets/Maharshtra/WildLife/koyna.png",
        name: "Phek",
        category: "HillStation",
        description: "https://www.holidify.com/places/phek",
		info : "Phek is a hilly area rich in flora and fauna. Apart from the spell bounding hills, Shilloi lake is an important attraction.The important and spellbinding hills of Phek district are Kapamodz and Zanibou, while the main rivers are Tizu, Lanye, and Sedzu. The Khezhakeno tourist village also stands out as a must see here.",
		map : "https://www.google.com/maps/place/Phek,+Nagaland/data=!4m2!3m1!1s0x3747d69501ba4e85:0xf2073bbd2205fb7?sa=X&ved=2ahUKEwjby6vlie37AhWOAqYKHXjwDowQ8gF6BAhzEAE",
       },
      {
        id:9,
        image: "assets/Maharshtra/WildLife/melghat.jpg",
        name: "Dzukou valley",
        category: "HillStation",
        description: "https://www.kipepeo.in/trips/dzukou-valley-trek/",
		info : "Dzukou Valley, a lesser known pocket of paradise for trekkers and wanderers in search of solitude amidst nature, is situated at the border of Nagaland and Manipur.Located at 2438 meters above sea level and behind the Japfu Peak (Nagaland’s second highest), Dzukou Valley is believed to have gotten its name from its namesake river which means ‘cold waters’.",
		map : "https://www.google.com/maps/place/Dzukou+Valley,+Manipur/@25.2425997,91.2512678,8.12z/data=!4m10!1m2!2m1!1sdzukou+valley!3m6!1s0x37489f5930712773:0xcff1a7f40e50782c!8m2!3d25.5071024!4d94.133465!15sCg1kenVrb3UgdmFsbGV5Wg8iDWR6dWtvdSB2YWxsZXmSARJ0b3VyaXN0X2F0dHJhY3Rpb26aASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTjFPSFF5ZW1oUlJSQULgAQA!16s%2Fg%2F11fkf4w59s",
      },
      {
        id: 10,
        image: "assets/Maharshtra/WildLife/Nagzira.jpg",
        name: "Ntangki national park",
        category: "Wildlife",
        description: "https://peren-district.nic.in/tourist-place/ntangki-national-park/",
		info : "Located 40 km from the town of Peren and about 37 km from Dimapur is the Ntangki National Park also known as the Intanki by many. Spread over a distance of 200 sq km, this park was established by the British administrators in the year 1923. Considered one of the best National Parks in the North East, it has thick rain forests which creates natural habitat for many birds, reptiles and mammals.",
		map : "https://www.google.com/maps/dir//GGXC%2BV68+Ntanki+National+Park,+Peren,+Nagaland+797110/@25.5496528,93.5205641,15z/data=!4m16!1m6!3m5!1s0x0:0x41230abb3bf841f3!2sNtanki+National+Park!8m2!3d25.5496528!4d93.5205641!4m8!1m0!1m5!1m1!1s0x374f5995d67ae307:0x41230abb3bf841f3!2m2!1d93.5205641!2d25.5496528!3e2",
        },
      {
        id: 11,
        image: "assets/Maharshtra/WildLife/Phansad.png",
        name: "Ghosu bird sanctuary",
        category: "Wildlife",
        description: "https://www.tourmyindia.com/states/nagaland/ghosu-bird-sanctuary.html",
		info : "Located about 9 kilometres from the district headquarters of Zunheboto, Ghosu Bird Sanctuary houses a wide range of avifauna. It is a home to many species and hosts more than 20 endangered bird species within the sanctuary’s boundaries. Few of the commonly spotted birds of Ghosu Bird Sanctuary are little Bunting, Cuckoo, Himalayan Black Bulbul, Grey-Hooded Warbler, Oriental Magpie Robin, Great-Eared Nightjar and much more.",
		map : "",
      },
      {
        id: 12,
        image: "assets/Maharshtra/WildLife/Rahekuri.png",
        name: "Rangapahar reserve forest",
        category: "Wildlife",
        description: "https://wildtrails.in/rangapahar-wildlife-sanctuary/",
		info : "Rangapahar Reserve Forest is one of the famous tourist spot of Dimapur it is known for its wildlife. The conservation of the Rangapahar Reserve Forest was established in the year of 1961 because of the urgency that occur to protect the vegetation and wildlife from land encroachment.",
		map : "",
      },
      {
        id: 13,
        image: "assets/Maharshtra/WildLife/tadoba.jpg",
        name: "Fakim wildlife sanctuary",
        category: "Wildlife",
        description: "https://kiphire.nic.in/tourist-place/fakim-wild-life-sanctuary/",
		info : "Situated close to the India Myanmar border in the Pungro circle headquarter in Nagaland, Fakim Sanctuary with an area of 642 hectares is a must visit attraction on a wildlife tour to Nagaland. With hills, high ridges, deep gorges and narrow valleys; here one can see good variation in landscapes.",
		map : "https://www.google.com/maps/place/Fakim,+Nagaland+798611/@25.8255145,94.9364745,15z/data=!3m1!4b1!4m10!1m2!2m1!1sfakim+wildlife+sanctuary!3m6!1s0x3747f11840f723ff:0xb6cbfaf13bc1a23c!8m2!3d25.825516!4d94.954392!15sChhmYWtpbSB3aWxkbGlmZSBzYW5jdHVhcnmSAQhsb2NhbGl0eeABAA!16s%2Fg%2F12hkh0lc0 ",
      },
       {
        id: 14, 
        image: "assets/Maharshtra/Religious/haji ali.jpg",
        name: "Pulie Badze wildlife sanctuary",
        category: "Wildlife",
        description: "https://en.wikipedia.org/wiki/Pulie_Badze_Wildlife_Sanctuary",
		info : "Pulie Badze Wildlife Sanctuary is located in Kohima District of Nagaland. It was first designated as a protected area in 1980.The park is named after the 2,296-metre (7,533 ft) mountain Pulie Badze, which means Pulie's Seat, named after the legendary folktale character 'Pulie'.The park is home to a vast variety of birds like Tragopan Blythii, White-naped Yuhina and Dark-rumped swift.",
		map : "https://www.google.com/maps/place/Puliebadze,+Jotsoma,+Kohima/@25.6477122,94.0709231,17z/data=!3m1!4b1!4m5!3m4!1s0x3746202bdf662ca3:0xe0181957730f70ae!8m2!3d25.6477122!4d94.0731118",
      },
	  {
      id: 15,
      image: "assets/Maharshtra/HillStation/lavasa.jpg",
      name: "Nagaland Zoological Park",
      category: "Wildlife",
      description: "https://forest.nagaland.gov.in/nagaland-zoological-park/Nagaland",
      info : "Nagaland Zoological Park, Rangapahar is one of the Model Zoological Parks in India. It was initially granted recognition as a “mini” Zoo by Central Zoo Authority (CZA). Presently the Zoological Park is recognized as a Medium Zoo by the Central Zoo Authority, New Delhi.",
      map : "https://www.google.com/maps/dir//VP3F%2B6JH,+Rangapahar,+Nagaland+797112/@25.8530521,93.6540755,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3745e25e97bb88f7:0x3a26046ed05086ac!2m2!1d93.7241158!2d25.8530689",
      },
    {
      id: 16,
      image: "assets/Maharshtra/HillStation/mahabaleshwar.jpg",
      name: "Garampani Wildlife Sanctuary",
      category: "Wildlife",
      description: "https://thehillstimes.in/featured/a-visit-to-garampani-wildlife-sanctuary",
      info : "Garampani Wildlife Sanctuary which is considered one of the oldest sanctuaries of Assam. It is located in the Karbi Anglong district beside National Highway 39. It is about 25 km away from Golaghat town.Garampani is famous for its hot water spring. Such types of hot springs are also known as geothermal springs.",
      map : "https://www.google.com/maps/dir//9VVH%2B9G4,+Garampani,+Golaghat,+T.E.,+Naharbari+T.E.,+Assam/@26.3933582,93.8088001,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x374687bdb271d93d:0xbed986e60b160c14!2m2!1d93.8788404!2d26.3933752",
      },
	  {
      id: 17,
      image: "assets/Maharshtra/HillStation/igatpuri.jpg",
      name: "Singphan National Park",
      category: "Wildlife",
      description: "https://mon.nic.in/tourist-place/shangphan-wildlife-sanctuary/",
      info : "Some of the forests in Mon are Shingphan forest, Wanching forest, Tiru forest, Zangkhum forest, Shawot and Chen forests, Yei, Monyakshu, Pessao, Yongkao and Tobu forests. These forests are rich in timber.",
      map : "https://www.google.com/maps/place/Singphan+National+Park/@26.0276163,94.3927489,15z/data=!4m5!3m4!1s0x0:0x133cefa9d1191c37!8m2!3d26.0276163!4d94.3927489",
     },
      {
        id: 18,
        image: "assets/Maharshtra/Religious/mahalakshmiji.jpg",
        name: "Saramati peak",
        category: "Mountain",
        description: "https://en.wikipedia.org/wiki/Mount_Saramati",
		info : "Saramati is a peak rising above the surrounding peaks at the mountainous border of the Indian state of Nagaland and the Naga Self-Administered Zone of the Sagaing Region of Myanmar. It is located near the village of Thanamir in the Kiphire District of Nagaland.",
		map : "https://www.google.com/maps/place/Saramati+Peak/data=!4m2!3m1!1s0x3747f84067adb8a3:0x98848fa562e7f237!5m1!1e4?sa=X&ved=2ahUKEwjc6ZDZju37AhUsyosBHey4BJAQ8gF6BAh-EAE",
       },
      {
        id: 19,
        image: "assets/Maharshtra/Religious/Mount Mary Church.jpg",
        name: "Japfu peak",
        category: "Mountain",
        description: "https://www.incredibleindia.org/content/incredible-india-v2/en/destinations/kohima/japfu-peak.html",
		info : "One of the most difficult treks in Nagaland is the climb to the Japfu Peak, about 15 km from Kohima.Standing at an altitude of 3,048 m, the peak is Nagaland's second-highest and draws trekkers and adventure lovers for its scenic beauty and thrilling trails.",
		map : "https://www.google.com/maps/place/Saramati+Peak/data=!4m2!3m1!1s0x3747f84067adb8a3:0x98848fa562e7f237!5m1!1e4?sa=X&ved=2ahUKEwjc6ZDZju37AhUsyosBHey4BJAQ8gF6BAh-EAE",
       },
      {
        id: 20,
        image: "assets/Maharshtra/Religious/pandharpur.jpg",
        name: "Changkikong peak",
        category: "Mountain",
        description: "https://www.tripadvisor.ca/Attraction_Review-g1162208-d4138853-Reviews-Changkikong_Range-Mokokchung_Mokokchung_District_Nagaland.html",
		info : "The Changkikong Range in Nagaland is one of a scenic beauty. It is a parallel range, lying east to the Japukong Range. It is named after the man who is the founder of the village.A land with deep rooted folklore and warm inhabitants, and is a pristine and to a certain extent remote location of the Indian Union.",
		map : "https://www.google.com/maps/place/Changki+View+Point/@26.4183999,94.3740174,15z/data=!4m8!1m2!2m1!1schangkikong+nagaland!3m4!1s0x3746ff16feff1d2d:0x8f2885f41397fa09!8m2!3d26.4219508!4d94.3923262",
      },
      {
        id: 21,
        image: "assets/Maharshtra/Religious/shirdi.jpg",
        name: "Longwa Village",
        category: "HillStation",
        description: "https://www.tourmyindia.com/states/nagaland/longwa-village.html",
		info : "Longwa is one of the best places to visit in the North-east with such unique and interesting facts. It is abundant with scenic beauty like the Doyang River, Nagaland science centre, Hong Kong Market, Shilloi Lake and many more tourist attractions to see. Just nearby lie the camps of an Assam Rifles (AR) company and some miles away from the village, on a hill, there is a pillar, indicating the international border and ‘154 BP 1971-72’ is inscribed on it.",
		map : "https://www.google.com/maps/dir//M669%2B9G4+Longwa+Nagaland,+Longwa,+Nagaland+798621/@26.6454627,95.1038692,10.58z/data=!4m17!1m7!3m6!1s0x3738998af89060f9:0xcf8d8a284e5b0fe4!2sLongwa+Nagaland!8m2!3d26.6608835!4d95.2188227!15sChRwYWsga29pIG1vbiBuYWdhbGFuZJIBEnRvdXJpc3RfYXR0cmFjdGlvbuABAA!4m8!1m0!1m5!1m1!1s0x3738998af89060f9:0xcf8d8a284e5b0fe4!2m2!1d95.2188227!2d26.6608835!3e2",
        },
      {
        id: 22,
        image: "assets/Maharshtra/Religious/siddhivinayak.jpg",
        name: "Ongpangkong range",
        category: "Mountain",
        description: "https://en.wikipedia.org/wiki/Ongpangkong",
		info : "Ongpangkong is the largest mountain range in Mokokchung District in the Indian state of Nagaland. The district headquarters of Mokokchung is itself located in this range.Important villages are Longsa, Ungma, Chungtia, Longkhüm, Mokokchung Village, Khensa, Aliba, Mangmetong Mekuli, Kinunger, Chuchuyimpang.",
		map : "https://www.google.com/maps/place/Ongpangkong/@26.3109764,94.5550342,15z/data=!3m1!4b1!4m5!3m4!1s0x3747a87a6480463b:0x67868e6551231b6f!8m2!3d26.3109768!4d94.5550342!5m1!1e4",
      },
      {
        id: 23,
        image: "assets/Maharshtra/Religious/trimbakeshwar.jpg",
        name: "Mount tiyi",
        category: "Mountain",
        description: "https://www.tourmyindia.com/states/nagaland/mount-tiyi.html",
		info : "Mount Tiyi is one of the most popular tourist attractions of Wokha, Nagaland. While you are in North East India exploring and having an adventure up in the mountains and freshwater rivers, Mount Tiyi is definitely one of the places to visit. With amazing folklores and beautiful scenic views, Mount Tiyi is both a hotpot for tourism and education.",
		map : "https://www.google.com/maps/dir//mount+tiyi/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x37464ee62e5b6f5f:0xea648787a6996ccf?sa=X&ved=2ahUKEwi0r-3sje37AhXEEXAKHeM9AVYQ9Rd6BAhfEAM",
      },
      {
        id: 24,
        image: "assets/Maharshtra/Religious/tuljabhavani mata.jpg",
        name: "Zutho",
        category: "Food",
        info : "Zutho is a fermented rice beer of Nagaland equivalent to Apong. The drink is prepared by sprouting, fermentation by yeast and enzymes and is famous in Nagaland.",
      },
      {
        id: 25, 
        image: "assets/Maharshtra/Heritage/aga khana.jpg",
        name: "Hinkejvu",
        category: "Food",
        info : "Hinkejvu is an everyday meal of Naga people. It is cooked with colocasia, shredded cabbage leaves, mustard leaves, French beans and a pinch of salt. All of these ingredients are mixed together and are boiled in a vessel until it’s fully cooked to merge the savour for a perfect cuisine.",
      },
      {
        id: 26,
        image: "assets/Maharshtra/Heritage/Ajanta ellora caves.jpg",
        name: "Fish in bamboo",
        category: "Food",
        info : "Naga people often like to cook their food by using Bamboo tubes. The fishes are first marinated with spices and masala then filled inside the tube before it is kept on the fire to cook well. Once the fishes are cooked, the dish is ready to be consumed.",
       },
      {
        id: 27,
        image: "assets/Maharshtra/Heritage/Bibi ka ma.jpg",
        name: "Galho",
        category: "Food",
        info : "Galho is one of the soupiest Nagaland food recipes with a combination of rice, vegetables and meat. It is prepared using a mixture of seasonal green vegetables and is further flavored with smoked pork or chunks of pork fat. The dish is often topped with ginger-garlic and is considered an important dish in Naga culture.",
       },
      {
        id: 28,
        image: "assets/Maharshtra/Heritage/chatrapati shahu museum.jpg",
        name: "Aikibeye",
        category: "Food",
        info : "Aikibeye is a spicy non-vegetarian dish comprising of mustard leaf and Colocasia roots. It is cooked in very little water and salt. The gravy is generally thick which is due to the minimal use of water.",
      },
      {
        id: 29,
        image: "assets/Maharshtra/Heritage/chatrapati terminus11.jpg",
        name: "Akini",
        category: "Food",
        info : "Akini Chokibo is basically cooked by roasting and grounding the perilla seeds, soya beans and paddy field snails. The flavor can be enhanced by adding axone and lard from the pork.",
        },
      {
        id: 30,
        image: "assets/Maharshtra/Heritage/chikhaldara.jpg",
        name: "Samathu",
        category: "Food",
		info : "Samathu is a famous dish originating from the Sema/Sumi district in the state in which fermented soybean or axone is used with smoked pork to make a thick curry. A large amount of chilli powder is also added to make the dish spicy.",
      },

  ];
  
  export default NagalandData;


 