const TamilNaduData = [
    {
      id: 1, 
      image: "assets/tamil nadu/Beaches/Auroville Beach.jpg",
      name: "Auroville Beach ",
      category: "Beach ",
      description: " https://www.holidify.com/places/auroville/auroville-beach-sightseeing-4102.html ",
      info : "Named after the renowned Auroville township, it is a nice, clean, and well-maintained beach in South India and has golden-colored soft black volcanic sand scattered all around the place.the unexplored beaches of the city that offers an unparalleled setting with a calm and peaceful environment to people seeking some time away from the crowded areas. ",
      map : "https://www.google.com/maps/place/Auroville+Beach/@11.9864943,79.8454625,16z/data=!3m1!4b1!4m5!3m4!1s0x3a536412b097606f:0x9de480df736f6b1!8m2!3d11.9865408!4d79.8496571?hl=en-GB",
    },
    {
      id: 2, 
      image: "assets/tamil nadu/Beaches/Breezy Beach.jpg",
      name: "Breezy Beach ",
      category: "Beach ",
      description: "https://www.holidify.com/places/chennai/breezy-beach-sightseeing-1542.html ",
      info : " the Breezy beach in Chennai is ideal to spend some time with your friends or family. It is located in Valmiki Nagar and the area nearby is away from all disturbance. If you are in Chennai or you are planning to take a trip, keep this on the top of your list and make sure that you do not miss out on this spot.",
      map : " https://www.google.com/maps/place/Thiruvalluvar+Nagar+Beach/@12.9738429,80.2643913,17z/data=!3m1!4b1!4m5!3m4!1s0x3a525d4f4d093b9b:0x8266c8dcda901d5f!8m2!3d12.9736122!4d80.2664556?hl=en-GB",
    },
    {
      id: 3, 
      image: "assets/tamil nadu/Beaches/Covelong, Kovalam Beach.jpg",
      name: " Covelong, Kovalam Beach",
      category: "Beach ",
      description: "https://www.holidify.com/places/mahabalipuram/kovalam-sightseeing-2711.html ",
      info : "Kovalam Beach also was known as Covelong is an extremely beautiful beach located in the state of Tamil Nadu. This scenic beach is situated in a small fishing village called Covelong in the Kanchipuram district about 40 kilometres away from Chennai. In addition, this beach is known to provide the perfect ambience for 'surfing', and is known to be one of the few spots in the eastern coast where 'wind surfing' is frequently undertaken ",
      map : " https://www.google.com/maps/place/Kovalam+Beach/@12.7925925,80.2414692,15z/data=!4m9!1m2!2m1!1skovalam+beach+tamil+nadu!3m5!1s0x3a5265fdfba01295:0x4b58655a045dccec!8m2!3d12.7898039!4d80.2541667!15sChhrb3ZhbGFtIGJlYWNoIHRhbWlsIG5hZHVaGiIYa292YWxhbSBiZWFjaCB0YW1pbCBuYWR1kgESdG91cmlzdF9hdHRyYWN0aW9umgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVVJYY0Y5SGFHaDNSUkFC4AEA?hl=en-GB",
    }, 
      {
        id: 4, 
        image: "assets/tamil nadu/Beaches/Elliots_Beach_.jpg",
        name: "Edward Elliot's Beach ",
        category: "Beach ",
        description: "https://www.holidify.com/places/chennai/elliots-beach-sightseeing-1545.html ",
        info : " Set towards the south of Marina Beach, the Edward Elliot Beach was named after an erstwhile Chief Magistrate and superintendent of Police, Edward Elliot. He was the son of Governor of Madras, Hugh Elliot. The beach was often visited by the Britishers during the colonial era.",
        map : "https://www.google.com/maps/place/Edward+Elliot's+Beach/@13.0026001,80.2655658,15z/data=!3m1!4b1!4m5!3m4!1s0x3a5267e32aae06d9:0x844d8b2b103cf191!8m2!3d12.9988631!4d80.271761?hl=en-GB",
      },
      {
        id: 5, 
        image: "assets/tamil nadu/Beaches/kanayakumari beach.jpg",
        name: "Kanyakumari Beach ",
        category: "Beach ",
        description: "https://www.holidify.com/places/kanyakumari/kanyakumari-beach-sightseeing-2270.html ",
        info : "Kanyakumari Beach is one of the most pristine beaches in the waterfront town of Kanyakumari. It is located at the confluence of the Bay of Bengal, Arabian Sea and Indian Ocean. Beauty oozes here in the form of soft golden sand that is overlapped by shimmering waters of the endless sea. ",
        map : " https://www.google.com/maps/place/Kanyakumari+Beach/@8.086522,77.5531646,18z/data=!3m1!4b1!4m5!3m4!1s0x3b04ed310b4e670d:0xa41f5be93b4cba9a!8m2!3d8.0866137!4d77.5544412?hl=en-GB",
      },
      {
        id: 6, 
        image: "assets/tamil nadu/Beaches/Mahabalipuram.jpeg",
        name: "Mahabalipuram beach",
        category: "Beach ",
        description: "https://www.holidify.com/collections/beaches-in-mahabalipuram ",
        info : "Apart from sun and sand, Mahabalipuram beach is also known for many breathtaking attractions and places offering an ideal spot for holidaying. Mahabalipuram beach attracts a large number of visitors every year due to its water sports activities like diving, wind surfing, motor boating and sunbathing. ",
        map : " https://www.google.com/maps/place/Mahabalipuram+Beach/@12.6139832,80.1781045,14z/data=!3m1!4b1!4m5!3m4!1s0x3a53acaf771807fb:0xe8f764e4f0f1ec45!8m2!3d12.6121234!4d80.1969215?hl=en-GB",
      },
    {
      id: 7, 
      image: "assets/tamil nadu/Beaches/Marina Beach.jpg",
      name: " marina beach",
      category: "Beach ",
      description: "https://www.booking.com/landmark/in/marina-beach-santhome.en-gb.html?aid=356980&label=gog235jc-1DCAUobEIVbWFyaW5hLWJlYWNoLXNhbnRob21lSDNYA2hsiAEBmAEJuAEXyAEM2AED6AEBiAIBqAIDuAKlyrSbBsACAdICJDIyNGUyZGU3LTQ4NTMtNDFjNi1iNDg5LTc4MzE3ZWQxOGQ5MdgCBOACAQ&sid=0e3aebcb054530a75a957f7cea0a89c8&inac=0&keep_landing=1& ",
      info : "The Marina is a natural urban sandy beach along the Coramandel coast on the Bay of Bengal. Primarily sandy, the beach spans about 13 km (8.1 mi), running from near Fort St. George in the north to Besant Nagar in the south and is the longest natural urban beach in India. ",
      map : " https://www.google.com/maps/place/Marina+Beach/@13.0437205,80.2479748,14z/data=!3m1!4b1!4m5!3m4!1s0x3a52689bb60132bb:0x549cf8edf62b60a!8m2!3d13.0499526!4d80.2824026?hl=en-GB",
    },
    {
      id: 8, 
      image: "assets/tamil nadu/Beaches/Nettukuppam beach.jpg",
      name: "Nettukuppam beach ",
      category: "Beach ",
      description: " https://www.holidify.com/places/chennai/nettukuppam-sightseeing-121147.html",
      info : " Nettukuppam is the northernmost tip of Chennai and has a beach which is yet not tarnished by encroaching crowds. It is a solitary retreat for those who seek to enjoy the raging sea up close but in a peaceful environment. The saltwater creek of Ennore joins the sea here forming an estuary of sorts. The place is ideal to spend a peaceful time as it is still not on the radar of the maddening tourist crowd.",
      map : " https://www.google.com/maps/search/nettukuppam+beach/@13.1277107,80.2351239,12z/data=!3m1!4b1?hl=en-GB",
    }, 
    {
      id: 9, 
      image: "assets/tamil nadu/Beaches/Sanguthurai Beach.jpg",
      name: "Sanguthurai Beach ",
      category: "Beach ",
      description: "https://www.yatra.com/hotels/hotels-near-sanguthurai-beach-in-kanyakumari ",
      info : "Sanguthurai Beach is one of the calmest and cleanest places to see in Kanyakumari. The gorgeous beach with its white sand shorelines and the sparkling sea waters is breathtaking and fascinating. The cool breeze of the huge coconut trees lined up at the beach shores, soothes the human mind and soul. ",
      map : " https://www.google.com/maps/place/Sanguthurai+Beach/@8.1000526,77.4215837,17z/data=!3m1!4b1!4m5!3m4!1s0x3b04ee32eb582bed:0xc465ae43a8c13187!8m2!3d8.09988!4d77.4260661?hl=en-GB",
    },
    {
      id: 10, 
      image: "assets/tamil nadu/Beaches/Sothavilai Beach.jpg",
      name: "Sothavilai Beach ",
      category: "Beach ",
      description: "https://www.holidify.com/places/kanyakumari/sothavilai-beach-sightseeing-120989.html ",
      info : "The Sotha Vilai Beach is one of the most famous beaches that can be found in the entire district of Kanyakumari in Tamil Nadu. This beach is an offbeat attraction, which means that many people do not know about it, but the beach does deserve more attention than what it gets. The glorious beach stretches for over 4 kilometres, which makes it one of the longest natural beaches in the entire state, and the views that this attraction offers cannot be put into words. ",
      map : " https://www.google.com/maps/place/Chothavilai+Beach/@8.0932741,77.4386892,14z/data=!3m1!4b1!4m5!3m4!1s0x3b04ee12e0d389eb:0xaf94b0b2f33af1b9!8m2!3d8.0932684!4d77.4553176?hl=en-GB",
    },
    {
      id: 11, 
      image: "assets/tamil nadu/forts/Alamparai-Fort.jpg",
      name: " Alamparai Fort",
      category: "Fort ",
      description: "https://www.holidify.com/places/mahabalipuram/alamparai-fort-sightseeing-6257.html ",
      info : " the fort was listed in the International Tourism Fair in Berlin as one of the twenty lesser known tourist attractions in Tamil Nadu by The Tamil Nadu Tourism Development Corporation (TTDC). No matter what the present condition of the Alamparai fort is, the view is sure to take your breath away. As you walk across the enthralling fort, you'll find surprising traces of life in the form of shrubs, creepers, bushes and trees even on the walls.",
      map : " https://www.google.com/maps/place/Alamparai+Fort/@12.2661452,80.005718,17z/data=!3m1!4b1!4m5!3m4!1s0x3a530b578caee60b:0xf1d21b244f22fd4f!8m2!3d12.2661452!4d80.0102027?hl=en-GB",
    },
    {
      id: 12, 
      image: "assets/tamil nadu/forts/Droog-Fort.jpg",
      name: "Droog Fort",
      category: "Fort  ",
      description: "holidify.com/places/coonoor/droog-fort-sightseeing-120790.html ",
      info : "Droog fort is a historical place located 15km from the foothills of the Nilgiris. As per the legend, a demon resided at the fort many years back hence it is otherwise called Bakasura Malai. In the 18th century, Tipu Sultan used the fort as an outpost which is now a ruin with a wall remaining. ",
      map : " https://www.google.com/maps/place/The+Droog+Fort/@11.317027,76.8270843,17z/data=!3m1!4b1!4m5!3m4!1s0x3ba8ecaa66dbe3eb:0x65a55907db2c7b!8m2!3d11.317027!4d76.829273?hl=en-GB",
    },
    {
      id: 13, 
      image: "assets/tamil nadu/forts/Gingee-Fort.jpg",
      name: "Gingee Fort ",
      category: "Fort  ",
      description: "https://www.holidify.com/places/thiruvannamalai/gingee-fort-sightseeing-3748.html ",
      info : " Gingee is famous for its Gingee Fort, a popular tourist attraction. The Kon dynasty laid the foundations for the Gingee Fort in 1190 CE. The fort was later built by the Chola dynasty in the 13th century. In 1638, Gingee came under the control of Bijapur Sultanate from Vijayanagar.",
      map : " https://www.google.com/maps/place/Gingee+Fort/@12.2502134,79.3970108,17z/data=!3m1!4b1!4m5!3m4!1s0x3baccab595dd0d29:0xccc84b0196b8a280!8m2!3d12.2502134!4d79.3991995?hl=en-GB",
    },
    {
      id: 14, 
      image: "assets/tamil nadu/forts/Krishnagiri-Fort-Chennai.jpg",
      name: "Krishnagiri Fort ",
      category: "Fort  ",
      description: "https://www.yatra.com/hotels/hotels-in-krishnagiri ",
      info : "Krishnagiri is known as 'Mango Capital of India' as mangoes are cultivated as the main crop, and the land here is extremely fertile with rich access to fresh water making it amenable to growing crops. ",
      map : " https://www.google.com/maps/place/Krishnagiri+Fort/@12.5383611,78.2123763,17z/data=!3m1!4b1!4m5!3m4!1s0x3bac34b1f5cc1711:0xfec76f3649a57fb9!8m2!3d12.5383611!4d78.214565?hl=en-GB",
    },
    {
      id: 15, 
      image: "assets/tamil nadu/forts/Manora-Fort.jpg",
      name: " Manora Fort",
      category: "Fort  ",
      description: "https://www.sangamhotels.com/manora-fort/# ",
      info : "Manora Fort principally adopts its name “Manora”, from the corresponding English word “Minaret”. From the nearest shore, the hexagonal tower, which is built within the fort, is an 8-storied building, which is about 23-meters tall, looking over the majestic Bay of Bengal. ",
      map : " https://www.google.com/maps/place/Manora,+Monument,+Manora+Beach+Road,+Sarabendrarajanpattinam,+Tamil+Nadu+614723/@10.2688896,79.3027399,17z/data=!3m1!4b1!4m5!3m4!1s0x3b00034e8dc66eb5:0x7aa2e79287972b0b!8m2!3d10.2688896!4d79.3049286?hl=en-GB",
    },
    {
      id: 16, 
      image: "assets/tamil nadu/forts/Tiruchirapalli Rock Fort.jpg",
      name: "Tiruchirapalli Rock Fort ",
      category: "Fort",
      description: "https://www.makemytrip.com/hotels/hotel_rock_fort_view-details-tiruchirappalli.html ",
      info : "The Rockfort is the most prominent landmark of the city.There are three Hindu temples inside the Rockfort, the Ucchi Pillaiyar Temple, Thayumanavar Temple, and the Manikka Vinayakar Temple. The Manikka Vinayakar Temple is located at the foot of the hill, dedicated to Lord Ganesha. Manikka Vinayakar is the patron deity of the Trichy, and among the top Trichy places to visit. ",
      map : " https://www.google.com/maps/place/Tiruchirapalli+Rock+Fort,+N+Andar+St,+Tiruchirappalli,+Tamil+Nadu+620002/@10.8280246,78.6948141,17z/data=!3m1!4b1!4m5!3m4!1s0x3baaf5adf9463137:0xe702eeead1c8a232!8m2!3d10.8280246!4d78.6970028?hl=en-GB",
    },
    {
      id: 17, 
      image: "assets/tamil nadu/forts/sadras dutch fort.jpg",
      name: " Sadras Dutch Fort",
      category: "Fort  ",
      description: "https://www.booking.com/city/in/sadras.en-gb.html?aid=356980&label=gog235jc-1DCAMobEIGc2FkcmFzSDNYA2hsiAEBmAEJuAEXyAEM2AED6AEBiAIBqAIDuAKDzbSbBsACAdICJDY5NWI5OGU3LWIzNWMtNDk3YS1iNzI0LWVmOGM2NmM0Nzc1M9gCBOACAQ&sid=0e3aebcb054530a75a957f7cea0a89c8&inac=0&keep_landing=1& ",
      info : "The magnificent Sadras Fort, built for commercial purposes by the Dutch, is a vast compound enclosing a huge granary, stables, and structures used to mount elephants. Unfortunately, only one of these structures survives. ",
      map : " https://www.google.com/maps/place/Sadras+Dutch+Fort/@12.5256559,80.161427,17z/data=!3m1!4b1!4m5!3m4!1s0x3a53a9673fa48de5:0xdde81fb0025da149!8m2!3d12.5256559!4d80.1636157?hl=en-GB",
    },
    {
      id: 18, 
      image: "assets/tamil nadu/forts/Thirumayam-Fort.jpg",
      name: "Thirumayam Fort ",
      category: "Fort  ",
      description: "https://www.makemytrip.com/hotels/tirumayam-hotels.html ",
      info : "The shrines dedicated to Hanuman, Sakthi, Ganapathi, Karuppar (guardian deities of the fort) are noticed on the southern side and shrine to Bhairava on the northern side. Halfway to the top on the right side a chamber which was used as magazine was noticed. ",
      map : " https://www.google.com/maps/place/Thirumayam+Fort/@10.2475971,78.746907,17z/data=!3m1!4b1!4m5!3m4!1s0x3b007b5438c77865:0xdfa56b8bc6c4c773!8m2!3d10.2475971!4d78.7513917?hl=en-GB",
    },
    {
      id: 19, 
      image: "assets/tamil nadu/forts/Udaygiri-Fort.jpg",
      name: "Udayagiri Fort ",
      category: "Fort",
      description: "https://www.makemytrip.com/travel-guide/kanyakumari/udayagiri-fort-landmarks.html ",
      info : " the Udayagiri Fort is an ancient fort situated at Thuckalay town in the Kanyakumari district of Tamilnadu. It is one of the famous places of heritage in Tamilnadu, and among the most prominent tourist places in Kanyakumari.Originally a mud-fort, the Udayagiri Fort was used as a military barrack by Travancore rulers during the 17th century. In the initial days, the fort served as a prison for people who protested against Tipu Sultan - the ruler of Mysore. Later, it was rebuilt using massive blocks of granite by Maharaja Marthanda Varma of Travancore in the 18th century. The renovation of the fort was done under the supervision of De Lannoy, chief of the Dutch East India Company. It was once known as Dillanai Kottai, meaning De Lannoy's Fort, in the chief's honour. ",
      map : " https://www.google.com/maps/place/Udayagiri+Fort,+Noorul+Islam+University+to+Puliyuurkurichi,+Kumaracoil,+Tamil+Nadu+629180/@8.2427024,77.3381504,17z/data=!3m1!4b1!4m5!3m4!1s0x3b04f853f485bd8b:0xd3589adff0ad8b5b!8m2!3d8.2427024!4d77.3403391?hl=en-GB",
    },
    {
      id: 20, 
      image: "assets/tamil nadu/forts/Vattakottai-Fort.jpg",
      name: " Vattakottai Fort",
      category: "Fort",
      description: "https://www.holidify.com/places/kanyakumari/vattakottai-fort-sightseeing-8013.html ",
      info : "Vattakottai Fort, which translates to the 'Circular Fort' is a seaside fort near Kanyakumari, the southernmost tip of India. The fort is largely made of granite blocks and today, a part of the fort even extends into the sea. The Fort is now a protected site under the Indian Archaeological Department and a major renovation of the fort was undertaken recently by the Department. ",
      map : " https://www.google.com/maps/place/Vattakottai+Fort/@8.125627,77.5628073,17z/data=!3m1!4b1!4m5!3m4!1s0x3b048d525ee0e41d:0xde89971aceecd39d!8m2!3d8.125627!4d77.564996?hl=en-GB",
    },
    {
      id: 21, 
      image: "assets/tamil nadu/heritage tours/Arunachaleswara Temple.jpg",
      name: "Arunachaleswara Temple",
      category: "Heritage",
      description: " https://www.makemytrip.com/hotels/thiruvannamalai-hotels.html",
      info : "The story that revolves around this temple is about Lord Shiva appearing as a column of light or fire to eliminate the ego from the face of mankind. The story begins with two most revered Hindu deities and part of the Trimurthis [Three governing Hindu Gods] Lord Vishnu the preserver and Lord Brahma the creator argues with each other to impose the supremacy of one self over the other. ",
      map : " https://www.google.com/maps/place/Arulmigu+Arunachaleswarar+Temple/@12.2316461,79.0655512,17z/data=!3m1!4b1!4m5!3m4!1s0x3bacc0888c761eeb:0x2bbbe52dd9d1f2b2!8m2!3d12.2316461!4d79.0677399?hl=en-GB",
    },
    {
      id: 22, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: "Chidambaram ",
      category: "Heritage",
      description: "https://www.booking.com/city/in/chidambaram.en-gb.html?aid=356980&label=gog235jc-1DCAMobEILY2hpZGFtYmFyYW1IM1gDaGyIAQGYAQm4ARfIAQzYAQPoAQGIAgGoAgO4ArmdtJsGwAIB0gIkNTk1ZjhmZjMtYTgyYS00NDdhLTkwMTItNTQyNTU5M2RjODFk2AIE4AIB&sid=0e3aebcb054530a75a957f7cea0a89c8&inac=0&keep_landing=1&",
      info : "A beautiful temple town in the Cuddalore District of Tamil Nadu, Chidamabaram is famous for housing the marvellous Lord Nataraja Temple and the famed chariot festival. Situated 250 kms away from the city of Chennai, Chidambaram has been a place of architectural glory and religious importance since antiquity. ",
      map : " https://www.google.com/maps/place/Chidambaram,+Tamil+Nadu/@11.4015775,79.6626949,13z/data=!3m1!4b1!4m5!3m4!1s0x3a54c23aa1bce10b:0xe1a29e91a8ec81aa!8m2!3d11.4070449!4d79.6912455?hl=en-GB",
    },
    {
      id: 23, 
      image: "assets/tamil nadu/heritage tours/Darasuram temple.jpg",
      name: "Darasuram temple ",
      category: "Heritage",
      description: "https://www.trawell.in/tamilnadu/kumbakonam/darasuram-airavatheswar-temple ",
      info : "This temple is a storehouse of art and architecture. The vimana is 85 feet high. The front mandapam itself is in the form of a huge chariot drawn by horses. The temple has some exquisite stone carvings. ",
      map : " https://www.google.com/maps/place/Dharasuram+temple/@10.9482045,79.3438287,15z/data=!4m9!1m2!2m1!1sDarasuram+temple!3m5!1s0x3baacd15bd8b0bbb:0xedd65959af78b9ea!8m2!3d10.948385!4d79.356548!15sChBEYXJhc3VyYW0gdGVtcGxlWhIiEGRhcmFzdXJhbSB0ZW1wbGWSAQxoaW5kdV90ZW1wbGWaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUlZlbVZQYmkxQlJSQULgAQA?hl=en-GB",
    },
    {
      id: 24, 
      image: "assets/tamil nadu/heritage tours/Gangaikonda_Cholapuram.jpg",
      name: "Gangaikonda Cholapuram ",
      category: "Heritage",
      description: "https://www.holidify.com/places/thanjevur/gangaikonda-cholapuram-sightseeing-8117.html ",
      info : " The magnificence of the Gangaikonda Cholapuram along with Brihadishwara temple will enchant you and thrill you with its history and engineering. A place which is a testimony to the architectural and engineering genius of the region and the pride of one of the greatest empires of India - Chola Empire, Gangaikonda Cholapuram is a place worth exploring.",
      map : " https://www.google.com/maps/place/Gangaikonda+Cholapuram,+Tamil+Nadu+612901/@11.2083987,79.4464973,16z/data=!3m1!4b1!4m5!3m4!1s0x3a54d437d5de23ff:0xe1e285be9af19719!8m2!3d11.2075881!4d79.4513858?hl=en-GB",
    },
    {
      id: 25, 
      image: "assets/tamil nadu/heritage tours/Mahabalipuram.jpg",
      name: "Mahabalipuram ",
      category: "Heritage",
      description: "https://yatradham.org/yatradham-destinations/tamilnadu/mahabalipuram.html ",
      info : "The Group of Monuments at Mahabalipuram is a collection of 7th- and 8th-century CE religious monuments in the coastal resort town of Mahabalipuram, Tamil Nadu, India and is a UNESCO World Heritage Site. ",
      map : " https://www.google.com/maps/place/Mahabalipuram,+Tamil+Nadu+603104/@12.6223265,80.1736327,14z/data=!3m1!4b1!4m5!3m4!1s0x3a5254aa30074dc5:0x9d00999d9ca8933f!8m2!3d12.6207821!4d80.1944915?hl=en-GB",
    },
    {
      id: 26, 
      image: "assets/tamil nadu/heritage tours/Perumal _ Shiva Rockcut Temple, Malayadipatti.jpg",
      name: "Perumal & Shiva Rockcut Temple, Malayadipatti ",
      category: "Heritage",
      description: "https://www.trawell.in/tamilnadu/tiruchirappalli/malayadipatti-rock-cut-temples ",
      info : "There are two temples in Malayadipatti, one for Lord Shiva and the other for Lord Vishnu. Both temples are situated on the same hillock. Built in the 8th century by Pallavas, the Shiva temple is older than the Vishnu temple. Constructed by Kuvavan Sathan, the Shiva temple is named Vakeeswarar, according to epigraphic notes. This temple, popularly known as Alathurthali is situated towards the eastern side of the granite hill. ",
      map : " https://www.google.com/maps/place/Perumal+%26+Shiva+Rockcut+Temple,+Malayadipatti/@10.653744,78.8941002,17z/data=!3m1!4b1!4m5!3m4!1s0x3baa911b1117715b:0xdb4ecc03c866e5c7!8m2!3d10.653744!4d78.8962889?hl=en-GB",
    },

    {
      id: 27, 
      image: "assets/tamil nadu/religious tour/Madurai Meenakshi Amman Temple.jpg",
      name: "Madurai Meenakshi Amman Temple ",
      category: " Religious",
      description: "https://www.holidify.com/places/madurai/madurai-meenakshi-amman-temple-sightseeing-2684.html ",
      info : "The historic Meenakshi Amman temple is located on the southern bank of the Vaigai River, Madurai, Tamil Nadu. Built sometime between the year 1623 and 1655, the wonderful architecture of the place is renowned globally. Meenakshi Temple is primarily dedicated to Parvati, known as Meenakshi, and her spouse, Shiva. What makes this temple different from the others is the fact that both God and Goddess are worshipped together. ",
      map : " https://www.google.com/maps/place/Meenakshi+Amman+Temple/@9.9195098,78.1171531,17z/data=!3m1!4b1!4m5!3m4!1s0x3b00c58461e46987:0xf134621ce5286703!8m2!3d9.9195045!4d78.1193418?hl=en-GB",
    },
    {
      id: 28, 
      image: "assets/tamil nadu/religious tour/KUMBAKONAM.jpg",
      name: " Kumbakonam",
      category: "Religious ",
      description: "https://www.holidify.com/places/kumbakonam/ ",
      info : "Sandwiched between two great rivers of southern India, Cauvery and Arsala, Kumbakonam is a gorgeous temple town in the heart of the Thanjavur district of Tamil Nadu.The town is a place for the lovers of history and those seeking to understand India's cultural roots and Hinduism. ",
      map : " https://www.google.com/maps/place/Kumbakonam,+Tamil+Nadu/@10.9622546,79.3330471,13z/data=!3m1!4b1!4m5!3m4!1s0x3a5532b360353419:0x9ecb5d94413ad35!8m2!3d10.9601852!4d79.3844976?hl=en-GB",
    },
    {
      id: 29, 
      image: "assets/tamil nadu/religious tour/Sri Ranga Nathaswamy Temple.jpg",
      name: "Sri Ranga Nathaswamy Temple ",
      category: "Religious ",
      description: "https://www.holidify.com/places/tiruchi/sri-ranga-nathaswamy-temple-sightseeing-6033.html ",
      info : "Sri Ranganathaswamy Temple is situated in Srirangam Town of Trichy. The temple is devoted to Lord Ranganatha, a reclining form of Lord Vishnu. The temple complex along with the surrounding area covers a total area of 156 acres. ",
      map : " https://www.google.com/maps/place/Sri+Ranganatha+Swamy+Temple,+Srirangam/@10.8624192,78.6549542,14z/data=!4m9!1m2!2m1!1sSri+Ranga+Nathaswamy+Temple!3m5!1s0x3baaf677ebfd8c89:0xc57d350aa60b4c6c!8m2!3d10.8624192!4d78.6899731!15sChtTcmkgUmFuZ2EgTmF0aGFzd2FteSBUZW1wbGVaHSIbc3JpIHJhbmdhIG5hdGhhc3dhbXkgdGVtcGxlkgEQcGxhY2Vfb2Zfd29yc2hpcJoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VNdE0wdDVVSE5CUlJBQuABAA?hl=en-GB",
    },
    {
      id: 30, 
      image: "assets/tamil nadu/religious tour/AUROVILLE.jpg",
      name: "Auroville Matrimandir ",
      category: "Religious ",
      description: " https://www.holidify.com/places/auroville/matrimandir-sightseeing-4104.html",
      info : "The ‘Matrimandir’ which literally means the ‘Temple of the Mother’. It was founded by The Mother – MirraAlfassa in 1968 and was architecturally designed by the French architect Roger Anger. ",
      map : " https://www.google.com/search?q=auroville+matrimandir&tbm=lcl&sxsrf=ALiCzsa9jr0LnXPY-RGv6kG_uKPV_h0rIw%3A1668093005576&ei=TRRtY-LkIrX14-EPsNGn4A0&oq=Auroville+Matrimandir&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAEYADIECCMQJzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABFAAWABg-A9oAHAAeACAAe4BiAHuAZIBAzItMZgBAKABAqABAcABAQ&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[12.0072779,79.8107797],[12.0069363,79.8104269]]?hl=en-GB",
    },
    {
      id: 31, 
      image: "assets/tamil nadu/religious tour/Annamalaiyar temple.jpg",
      name: " Annamalaiyar temple",
      category: "Religious ",
      description: " https://www.holidify.com/places/thiruvannamalai/",
      info : "Annamalaiyar Temple, a breathtaking temple complex dedicated to Lord Shiva, is located in the bustling town of Thiruvannamalai, at the base of Annamalai Hills in the South Indian state of Tamil Nadu. As you walk closer to the grand temple complex, you'll notice how marvellously the structures have been built. This 25-acre complex is sure to mesmerize you with its beauty and elegance ",
      map : " https://www.google.com/maps/place/Arulmigu+Arunachaleswarar+Temple/@12.2450832,79.0513624,14z/data=!4m9!1m2!2m1!1sAnnamalaiyar+temple!3m5!1s0x3bacc0888c761eeb:0x2bbbe52dd9d1f2b2!8m2!3d12.2316461!4d79.0677399!15sChNBbm5hbWFsYWl5YXIgdGVtcGxlWhUiE2FubmFtYWxhaXlhciB0ZW1wbGWSARBwbGFjZV9vZl93b3JzaGlwmgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVVJKTUdKVFdIRlJSUkFC4AEA?hl=en-GB",
    },
    {
      id: 32, 
      image: "assets/tamil nadu/religious tour/Velankanni Church.jpg",
      name: " Velankanni Church",
      category: "Religious ",
      description: "https://www.holidify.com/places/velankanni/velankanni-church-sightseeing-6142.html ",
      info : "Located on the sandy shores of Bay of Bengal, Velankanni Church is considered as one of the holiest Christian pilgrimage destinations in India n and is situated on the Coromandel Coast, 350 km south of Chennai and 12 km south of Nagapattinam. It is said that Virgin Mary appeared here along with Baby Jesus around the end of the 16th and the beginning of the 17th century, after which Velankanni became a revered site for the Christian community. ",
      map : " https://www.google.com/maps/place/Old+Velankanni+Church/@10.6808028,79.8338236,16z/data=!4m9!1m2!2m1!1svelankanni+church!3m5!1s0x3a556fbb8cf6924b:0x7f633066dfc6be0c!8m2!3d10.6808028!4d79.8425783!15sChF2ZWxhbmthbm5pIGNodXJjaFoTIhF2ZWxhbmthbm5pIGNodXJjaJIBD2NhdGhvbGljX2NodXJjaJoBI0NoWkRTVWhOTUc5blMwVkpRMEZuU1VNdE1IRXRObGQzRUFF4AEA?hl=en-GB",
    },
    {
      id: 33, 
      image: "assets/tamil nadu/hill stations/ooty.jpg",
      name: "ooty ",
      category: "HillStation ",
      description: "https://www.holidify.com/places/ooty/ ",
      info : "Nestled amidst Nilgiri hills, Ooty, also known as Udagamandalam, is a hill station in Tamil Nadu which serves as a top-rated tourist destination. Once regarded as the summer headquarters of the East India Company, the Queen of the hills is a picturesque getaway. ",
      map : " https://www.google.com/maps/place/Ooty,+Tamil+Nadu/@11.411928,76.6216606,13z/data=!3m1!4b1!4m5!3m4!1s0x3ba8bd84b5f3d78d:0x179bdb14c93e3f42!8m2!3d11.4102038!4d76.6950324?hl=en-GB",
    },
    {
      id: 34, 
      image: "assets/tamil nadu/hill stations/Kodaikanal.jpg",
      name: "Kodaikanal ",
      category: "HillStation ",
      description: " holidify.com/places/kodaikanal/",
      info : "Located in the state of Tamil Nadu, Kodaikanal is one of the most famous honeymoon destinations in India. A Lakeside resort town of Tamil Nadu, Kodaikanal has a beautiful climate, mist-covered manicured cliffs and waterfall that come together to create the ideal setting for a perfect getaway. Kodaikanal means 'the gift of the forests'. ",
      map : " https://www.google.com/maps/place/Kodaikanal,+Tamil+Nadu/@10.2351929,77.4793623,14z/data=!3m1!4b1!4m5!3m4!1s0x3b0766637f0a0387:0x9ffae9373758c13c!8m2!3d10.2381136!4d77.4891822?hl=en-GB",
    },
    {
      id: 35, 
      image: "assets/tamil nadu/hill stations/coonoor.jpg.jpg",
      name: "Coonoor ",
      category: "HillStation ",
      description: "https://www.holidify.com/places/coonoor/ ",
      info : "One of the three beautiful Nilgiri hill stations, Coonoor is the second largest hill station of the Western Ghats. It is situated at an altitude of 1930 meters and just 19 km from Ooty. With slopes of tea plantations, dotted with many attractions and blessed with chilly weather throughout the year, this place is a perfect summer retreat.  ",
      map : " https://www.google.com/maps/place/Coonoor,+Tamil+Nadu/@11.3497859,76.7718226,14z/data=!3m1!4b1!4m5!3m4!1s0x3ba894efa2fd0d5b:0x192d8d872b04dbbb!8m2!3d11.3530022!4d76.7959095?hl=en-GB",
    },
    {
      id: 36, 
      image: "assets/tamil nadu/hill stations/yeracud.jpg",
      name: " Yercaud",
      category: "HillStation ",
      description: " https://www.holidify.com/places/yercaud/",
      info : "Nestled in the Shivaroy Hills of Tamil Nadu, Yercaud is a hill station in the Eastern Ghats steeped in abundant greenery. Commonly called ‘Ooty of the Poor’, this region has a history dating back to the time of the British. Located at an altitude of 4970 feet, Yercaud is known for its vast expanses of coffee plantations and great weather. ",
      map : " https://www.google.com/maps/place/Yercaud,+Tamil+Nadu+636601/@11.7748131,78.2009504,15z/data=!3m1!4b1!4m5!3m4!1s0x3babf42b4747d5eb:0x1d3ccd9945d5e7ee!8m2!3d11.7747924!4d78.2097052?hl=en-GB",
    },
    {
      id: 37, 
      image: "assets/tamil nadu/hill stations/_kolli-hills.webp",
      name: "Kolli Hills ",
      category: "HillStation ",
      description: "https://www.holidify.com/places/chennai/koli-hills-sightseeing-8260.html ",
      info : "With an ominous name which means ‘Mountain of Death’, Kolli Hills or Kolli Malai are a mountain range located in the Namakkal district of Tamil Nadu. It is relatively untouched by commercial tourism and therefore has retained most of its natural magnificence. ",
      map : " google.com/maps/place/Kolli+Hills/@11.3392332,78.2381363,11z/data=!3m1!4b1!4m5!3m4!1s0x3babb98203e2b5e9:0x18dc43aab135b9fa!8m2!3d11.2485139!4d78.3387066?hl=en-GB",
    },
    {
      id: 38, 
      image: "assets/tamil nadu/hill stations/Ketti Valley.webp",
      name: "Ketti Valley ",
      category: "HillStation ",
      description: "https://www.holidify.com/places/coonoor/ketti-valley-sightseeing-124410.html ",
      info : "Located in the beautiful hills extending from Coonoor to Ooty in Tamil Nadu is the beautiful Ketti Valley. The best way to visit this beautiful valley, that is if you want to really feel its beauty is to take the toy train which is like a 20-25 minute ride. ",
      map : " https://www.google.com/maps/place/Ketti+Valley,+Tamil+Nadu/@11.3693546,76.7051788,14z/data=!3m1!4b1!4m5!3m4!1s0x3ba895d09920e199:0x84b1b75ce5a9c19!8m2!3d11.3670143!4d76.7423094?hl=en-GB",
    },
    {
      id: 39, 
      image: "assets/tamil nadu/whildlife santuaries/Anamalai Wild Life Sanctuary.jpg",
      name: " Anamalai Wild Life Sanctuary",
      category: "Wild ",
      description: "https://www.holidify.com/state/tamil-nadu/anamalai-tiger-reserve-sightseeing-1253669.html ",
      info : "The Anamalai Tiger Reserve, more famously known as the Indira Gandhi Wildlife Sanctuary and National Park, located in the south of India is a unique reserve which has long since protected the endemic species of both plants and animals that reside here. ",
      map : " https://www.google.com/maps/place/Anaimalai+Tiger+Reserve/@10.4241043,77.1233713,17z/data=!3m1!4b1!4m5!3m4!1s0x3ba82a57e32f330b:0x837528b15369b92e!8m2!3d10.424099!4d77.12556?hl=en-GB",
    },
    {
      id: 40, 
      image: "assets/tamil nadu/whildlife santuaries/Vedanthangal Bird Sanctuary.jpg",
      name: "Vedanthangal Bird sanctuary ",
      category: "Wild  ",
      description: "https://www.holidify.com/places/vedanthangal/vedanthangal-bird-sanctuary-sightseeing-6137.html ",
      info : "Situated in the city of Kancheepuram, Vedanthangal Bird Sanctuary is a protected sanctuary covering a total area of 30 hectares. This sanctuary is a popular migratory home for around 40,000 different species of birds from all over the world. It is said that such a vast number of birds are attracted to this location because of its various small lakes that prove to be a fertile feeding ground for the birds. As soon as one enters here, the birds can be seen eating, swimming, homemaking, diving, squawking or simple perching on the trees. ",
      map : " https://www.google.com/maps/place/Vedanthangal+Bird+Sanctuary/@12.5454649,79.8538807,17z/data=!3m1!4b1!4m5!3m4!1s0x3a531c41b9d3652d:0x61e0072c7991c53d!8m2!3d12.5454597!4d79.8560694?hl=en-GB",
    },
    {
      id: 41, 
      image: "assets/tamil nadu/whildlife santuaries/Kalakkad Mundanthurai Tiger Reserve.jpg",
      name: " Kalakkad Wildlife Sanctuary",
      category: "Wild  ",
      description: "https://www.holidify.com/places/tuticorin/kalakkad-wildlife-sanctuary-sightseeing-6075.html",
      info : "The Kalakkad Wildlife sanctuary is one of the few national parks in South India that house the Tiger. Lion tailed macaque, Nilgiri langur, bonnet macaque, langur, Nilgiri tahr, sambar, sloth bear, gaur, elephant, flying squirrel, panther, wild dog and pangolin are some of the other animals found here. ",
      map : " https://www.google.com/maps/search/Kalakkad+Wildlife+Sanctuary,+Tamil+Nadu/@10.0281009,76.0894173,8z/data=!3m1!4b1?hl=en-GB",
    },
    {
      id: 42, 
      image: "assets/tamil nadu/whildlife santuaries/Mukurthi National Park.jpg",
      name: " Mukurthi National Park",
      category: " Wild ",
      description: "https://www.holidify.com/places/ooty/mukurthi-national-park-sightseeing-1254186.html ",
      info : " The culturally rich South-Indian state - Tamil Nadu – calls out tourists from all around the globe, and there is more than one reason to it. Be it the extravagance of architectural excellence in the form of magnificent temples, the serenity of the scenic beaches and the magical charm of the hill stations, Tamil Nadu is an absolute vacationers’ paradise.",
      map : " https://www.google.com/maps/place/Mukurthi+National+Park/@11.2922905,76.3807875,11z/data=!4m9!1m2!2m1!1sMukurthi+National+Park+Tamil+Nadu!3m5!1s0x3ba89c9f36bb89e3:0xc263ed7157cedab7!8m2!3d11.2403682!4d76.5434647!15sCiFNdWt1cnRoaSBOYXRpb25hbCBQYXJrIFRhbWlsIE5hZHWSAQ1uYXRpb25hbF9wYXJr4AEA?hl=en-GB",
    },
    {
      id: 43, 
      image: "assets/tamil nadu/whildlife santuaries/Koonthankulam or Kunthankulam Bird Sanctuary.jpg",
      name: "Koonthankulam or Kunthankulam Bird Sanctuary ",
      category: "Wild  ",
      description: "https://www.trawell.in/tamilnadu/tirunelveli/koonthakulam-bird-sanctuary ",
      info : "Koonthankulam Bird Sanctuary consists of Koonthankulam and Kadankulam irrigation tanks and is spread over an area of 1.29 sq. km. It is declared as a sanctuary in 1994. This sanctuary is actively protected and managed by the Koonthankulam village community. This sanctuary is an important Bird site in Tamilnadu and it attracts more than one lakh birds annually. The tourists visit the place in pursuit of seeing painted stork which is the major attraction of this place. ",
      map : " https://www.google.com/maps/place/Koonthankulam+Bird+Sanctuary/@8.498547,77.7299153,14z/data=!4m9!1m2!2m1!1sKoonthankulam+or+Kunthankulam+Bird+Sanctuary!3m5!1s0x3b04718204311c57:0x92c243816ec2db56!8m2!3d8.4961472!4d77.7574824!15sCixLb29udGhhbmt1bGFtIG9yIEt1bnRoYW5rdWxhbSBCaXJkIFNhbmN0dWFyeVouIixrb29udGhhbmt1bGFtIG9yIGt1bnRoYW5rdWxhbSBiaXJkIHNhbmN0dWFyeZIBBHBhcmuaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVUlBkazU2WVhOUlJSQULgAQA?hl=en-GB",
    },
    {
      id: 44, 
      image: "assets/tamil nadu/whildlife santuaries/Point Calimere Wildlife and Bird Sanctuary.jpg",
      name: "Point Calimere Wildlife Sanctuary (Kodiakarai) ",
      category: "Wild  ",
      description: "https://www.trawell.in/tamilnadu/thanjavur/point-calimere-wildlife-sanctuary ",
      info : "Point Calimere Wildlife and Bird Sanctuary is a 21.47-square-kilometre protected area in Tamil Nadu, South India along the Palk Strait where it meets the Bay of Bengal at Point Calimere at the southeastern tip of Nagapattinam District. ",
      map : " https://www.google.com/maps/place/Point+Calimere+Wildlife+Sanctuary+(Kodiakarai)/@10.2864315,79.827722,17z/data=!3m1!4b1!4m5!3m4!1s0x3aff8e4451aff3bb:0xaa329fcd2f62cd1d!8m2!3d10.2864262!4d79.8299107?hl=en-GB",
    },
    {
      id: 45, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
    {
      id: 46, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
    {
      id: 47, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
    {
      id: 48, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
    {
      id: 49, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
    {
      id: 50, 
      image: "assets/Maharshtra/HillStation/chikhaldara.jpg",
      name: " ",
      category: " ",
      description: " ",
      info : " ",
      map : " ?hl=en-GB",
    },
  ];
  
  export default TamilNaduData;


 