const TelanganaData = [
    {
      id: 1, 
      image: "assets/telangang/Beaches/chirala-beach.jpg",
      name: "Chirala Beach ",
      category: "Beaches",
      description: "https://www.holidify.com/state/andhra-pradesh/chirala-beach-sightseeing-124757.html ",
      info : "Also known as “Ksheerapuri”, the peaceful town of Chirala is located in Prakasam district of Andhra Pradesh. It was founded by Minchala Paleti Papayya and Minchala Paleti Perayya. Chirala is exclusively famous for its quiet beaches, splendid panoramic view and extremely hospitable people. Also famous for its handloom industry, Chirala is known as Mini Bombay or Chenna Bombay. ",
      map : " https://www.google.com/search?q=Chirala%20Beach&oq=Chirala+Beach&aqs=chrome..69i57j35i39j46i67i433i512j0i433i512j0i512l2j0i20i263i512j0i512l3.3278j0j15&sourceid=chrome&ie=UTF-8&tbs=lf:1,lf_ui:1&tbm=lcl&sxsrf=ALiCzsYgThOQeB25JCVh113EUbv5BxS3wA:1668100450099&rflfq=1&num=10&rldimm=446697647739040823&lqi=Cg1DaGlyYWxhIEJlYWNoSPTUlOOfroCACFoZEAEYABgBIg1jaGlyYWxhIGJlYWNoKgIIA5IBBWJlYWNomgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVU5UTkZCdVlTMW5SUkFCqgENEAEqCSIFYmVhY2goAA&phdesc=HAMpH9TCJho&ved=2ahUKEwjMkJy2jqT7AhXwzTgGHQ2zA6sQvS56BAgMEAE&sa=X&rlst=f#rlfi=hd:;si:446697647739040823,l,Cg1DaGlyYWxhIEJlYWNoSPTUlOOfroCACFoVEAEYABgBIg1jaGlyYWxhIGJlYWNokgEFYmVhY2iaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTlRORkJ1WVMxblJSQUKqAQ0QASoJIgViZWFjaCgA,y,HAMpH9TCJho;mv:[[18.907919126424325,94.49990921356053],[6.284253902513905,73.05459671356053],null,[12.67418013444776,83.77725296356053],6]?hl=en-GB",
    },
    {
      id: 2, 
      image: "assets/telangang/Beaches/gangavaram-beach.jpg",
      name: " Gangavaram beach",
      category: "Beaches",
      description: "https://www.holidify.com/places/visakhapatnam/gangavaram-beach-sightseeing-3908.html ",
      info : "One of the most beautiful beaches of the town, this one with palm trees and picture perfect sceneries attracts many film and TV serial makers. This beach with soft sands and cool breeze always provides a secluded atmosphere. ",
      map : " https://www.google.com/search?q=Gangavaram+beach&tbm=lcl&sxsrf=ALiCzsYWYm2sddABIj1Likvx4kwGahZnKQ%3A1668100464503&ei=cDFtY7G0HsCt4-EPw5eTiAQ&ved=0ahUKEwixrIu9jqT7AhXA1jgGHcPLBEEQ4dUDCAk&oq=Gangavaram+beach&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAwyBAgjECcyBQgAEIAEMgUIABCABDIFCAAQgAQyCggAEIAEEIcCEBQyBQgAEIAEMgUIABCABDIFCAAQgAQyCAgAEBYQHhAPMgUIABCGA1AAWABgnQ1oAHAAeACAAesIiAHrCJIBAzctMZgBAKABAqABAcABAQ&sclient=gws-wiz-local#rlfi=hd:;si:5998859764192974806,l,ChBHYW5nYXZhcmFtIGJlYWNokgEFYmVhY2g,y,LBuwx0VoLzY;mv:[[17.6235931,83.23671329999999],[17.6124573,83.23220730000001]]?hl=en-GB",
    },
    {
      id: 3, 
      image: "assets/telangang/Beaches/Om beach.jpg",
      name: "Om beach ", 
      category: "Beaches",
      description: "https://www.holidify.com/places/gokarna/om-beach-sightseeing-1890.html ",
      info : "Om beach is a wonderful beach located in the town of Gokarna. Shaped like the symbol 'Om', this beach offers plenty of adventure sports to the thrill-seekers. The view of this beach during sunset is one to be cherished forever. It is usually lined with shacks on the sides offering cheap accommodation and restaurants with global menus. There is also a bunch of fun water sports activities available on Om Beach, including speedboats, surfing etc. ",
      map : " https://www.google.com/search?q=om+beach+gokarna+telangana&tbm=lcl&sxsrf=ALiCzsaUJy79IpzyCwZb_5o9YbhTa2ol4A%3A1668100725607&ei=dTJtY9LUJMON2roPxaSIuAg&oq=Om+Beach%2C+Gokarna%2Ctelan&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAEYADIFCCEQoAEyBQghEKABMgUIIRCgATIFCCEQoAE6BAgjECc6BQgAEIAEOgoIABCABBCHAhAUOgYIABAWEB46CAgAEBYQHhAPOgUIABCGAzoICCEQFhAeEB06BwghEKABEAo6BAghEBVQhwtYteMBYLL0AWgDcAB4AoABpRaIAbFkkgELNS0yLjIuNC4xLjGYAQCgAQHAAQE&sclient=gws-wiz-local#rlfi=hd:;si:2976685267142006899,l,ChpvbSBiZWFjaCBnb2thcm5hIHRlbGFuZ2FuYUj-pKmr6oCAgAhaJBADGAAYARgCIhpvbSBiZWFjaCBnb2thcm5hIHRlbGFuZ2FuYZIBBWJlYWNo,y,AQrR1P4k1js;mv:[[14.551659499999998,74.3338945],[14.5134117,74.3096276]]?hl=en-GB",
    },
    {
      id: 4, 
      image: "assets/telangang/Beaches/manginapudi-beach.jpg",
      name: "Manginapudi Beach ",
      category: "Beaches",
      description: "https://www.holidify.com/places/machelipatnam/manginapudi-beach-sightseeing-5173.html ",
      info : "Once served as major port, Manginapudi is currently a fishing village located on the shores of a beach nearly 11 km from Machelipatnam. This beautiful natural beach is unique for its black soil and also a natural bay comprising shallow water level. ",
      map : " https://www.google.com/search?q=Manginapudi+Beach&tbm=lcl&sxsrf=ALiCzsYZhvpSx8FabkOTGZg0YMRKlIrIrw%3A1668100808616&ei=yDJtY7SjJZXL2roPpPmooAo&ved=0ahUKEwi0p5bhj6T7AhWVpVYBHaQ8CqQQ4dUDCAk&oq=Manginapudi+Beach&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAwyBAgjECcyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgARQAFgAYPoMaABwAHgAgAGuAogBrgKSAQMzLTGYAQCgAQKgAQHAAQE&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[16.243197077319028,81.24087335998075],[16.242837122680974,81.24049844001925]]?hl=en-GB",
    },
    {
      id: 5, 
      image: "assets/telangang/Beaches/mypadu.jpg",
      name: "Mypadu Beach ",
      category: "Beaches",
      description: "https://www.holidify.com/places/nellore/mypadu-beach-sightseeing-5494.html ",
      info : "Mypadu Beach, a mesmerising beach with pristine seawater and golden brown sand, is located on the west coast of India. It is about 25 kilometres from Nellore, Andhra Pradesh and lies on the coast of the magnificent Bay of Bengal. One can take a long peaceful stroll across the beach or sit in the sand, contemplate about life or just absorb the beauty of the location. ",
      map : " https://www.google.com/search?q=Mypadu+Beach&tbm=lcl&sxsrf=ALiCzsY6t7qf8jbJQCnBDSgsftezBOdKUg%3A1668100940822&ei=TDNtY7XnMcjM2roP8t2PmAo&ved=0ahUKEwi1vZugkKT7AhVIplYBHfLuA6MQ4dUDCAk&oq=Mypadu+Beach&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAwyBQgAEJECMgUIABCRAjIFCAAQkQIyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEUABYAGCYDmgAcAB4AIAB5QKIAeUCkgEDMy0xmAEAoAECoAEBwAEB&sclient=gws-wiz-local#rlfi=hd:;si:10950474224901544562,l,CgxNeXBhZHUgQmVhY2iSAQViZWFjaA,y,qYDIcxG1m28;mv:[[14.511865499999997,80.1799822],[14.5002532,80.1782013]]?hl=en-GB",
    },
    {
      id: 6, 
      image: "assets/telangang/Beaches/ramakrishna-beach-.jpg",
      name: "Ramakrishna Beach ",
      category: "Beaches",
      description: "https://www.holidify.com/places/visakhapatnam/ramakrishna-beach-sightseeing-3914.html ",
      info : "One of the most popular beaches of Vishakapatnam, RK beach is a beach for to spend some relaxed time, enjoy strolls across the beach, sunbath and more.With a number of tourist spots in and around the area, one finds the beach engrossed in much hustle bustle. However, it is highly advisable to not swim at this beach, as it can be very dangerous and is said to have claimed lives in the past. ",
      map : " https://www.google.com/search?q=Ramakrishna+Beach&tbm=lcl&sxsrf=ALiCzsZT5YOEima19H7H54RRUoUiYgDx9A%3A1668101029108&ei=pTNtY_ObBsuv2roP8qCjoAc&ved=0ahUKEwizgqjKkKT7AhXLl1YBHXLQCHQQ4dUDCAk&oq=Ramakrishna+Beach&gs_lcp=Cg1nd3Mtd2l6LWxvY2FsEAwyBAgjECcyBAgAEEMyCggAEIAEEIcCEBQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEUABYAGCoF2gAcAB4AIABoAKIAaACkgEDMi0xmAEAoAECoAEBwAEB&sclient=gws-wiz-local#rlfi=hd:;si:15522251922841927462,l,ChFSYW1ha3Jpc2huYSBCZWFjaJIBBWJlYWNo,y,KYSOTJafyXU;mv:[[17.7192434,83.3343635],[17.7084318,83.3149052]]?hl=en-GB",
    },
    {
      id: 7, 
      image: "assets/telangang/forts/Rachakonda_Fort.jpg",
      name: "Rachakonda Fort ",
      category: "Fort ",
      description: "https://www.holidify.com/state/telangana/rachakonda-fort-sightseeing-125206.html ",
      info : "Rachakonda Fort is situated in the Indian state of Telangana, 56 kms from Hyderabad. Constructed around 1360 AD, the fort is a masterpiece of the Kakatiya dynasty. It also offers a beautiful 360 degree view of the surroundings. ",
      map : " https://www.google.com/maps/place/Rachakonda+Fort,+Telangana+508252/@17.1813258,78.8009342,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb0f9a6108dc79:0x7401b30716c245e7!8m2!3d17.1813258!4d78.8031229?hl=en-GB",
    },
    {
      id: 8, 
      image: "assets/telangang/forts/Medak_Fort.jpg",
      name: "Medak Fort ",
      category: "Fort",
      description: "holidify.com/state/telangana/medak-fort-sightseeing-125202.html ",
      info : "Medak Fort is situated in Telangana, 96 kms from Hyderabad and stands strong as an architectural masterpiece of the bygone era. Currently, the fort is mostly in ruins but it is still an important tourist attraction of the city. ",
      map : " https://www.google.com/maps/place/Medak+Fort/@18.043545,78.2549883,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcc1573362db551:0x4dcf74a4435e3307!8m2!3d18.0435399!4d78.257177?hl=en-GB",
    },
    {
      id: 9, 
      image: "assets/telangang/forts/Golconda Fort.jfif",
      name: "Golconda Fort ",
      category: "Fort",
      description: "https://www.holidify.com/places/hyderabad/golkonda-fort-sightseeing-2043.html ",
      info : "Situated in the Western part of the beautiful city of Hyderabad at a distance of approximately 9 km from Hussain Sagar Lake, Golconda Fort is one of the region's best-preserved monuments. The construction of this fort was completed in the 1600s and it is reputed for being the area where once, the mighty Koh-I-Noor diamond was stored. ",
      map : " https://www.google.com/maps/place/Golconda+Fort/@17.3833141,78.3988641,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb968ea6aea98f:0x6b76ecdfd65a335a!8m2!3d17.383309!4d78.4010528?hl=en-GB",
    },
    {
      id: 10, 
      image: "assets/telangang/forts/Asmangadh Fort.jfif",
      name: "Asmangadh Fort ",
      category: "Fort",
      description: "https://www.holidify.com/places/hyderabad/asmangadh-fort-sightseeing-125205.html ",
      info : "Asmangadh Fort or Asmangadh Palace is situated in Hyderabad. The name literally translates to home in the sky because the palace was situated on a hill top. Lately, it has been converted into a school for children, called the St. Joseph's Public School. ",
      map : " https://www.google.com/maps/place/Asmangadh,+Hyderabad,+Telangana+500027/@17.3825297,78.4897351,18z/data=!3m1!4b1!4m10!1m2!2m1!1sAsmangadh+Fort!3m6!1s0x3bcb99ccace042d1:0x181f825f05142aaa!8m2!3d17.3828349!4d78.4918875!15sCg5Bc21hbmdhZGggRm9ydJIBDHN1YmxvY2FsaXR5MeABAA!16s%2Fg%2F1hjgmbnm3?hl=en?hl=en-GB",
    },
    {
      id: 11, 
      image: "assets/telangang/forts/Gomajipet Fort.jfif",
      name: "Gomajipet Fort ",
      category: "Fort",
      description: "https://www.holidify.com/places/hyderabad/gomajipet-fort-sightseeing-125204.html ",
      info : "Gomajipet Fort is situated at a distance of 110 kms from Hyderabad and is a popular tourist attraction of the city. It has lately been restored and boasts of magnificent architecture and reflects grandeur and splendour in all its glory. ",
      map : "https://www.google.com/maps/place/Golconda+Fort/@17.3833497,78.392298,15z/data=!4m10!1m2!2m1!1sGomajipet+Fort+telangana!3m6!1s0x3bcb968ea6aea98f:0x6b76ecdfd65a335a!8m2!3d17.383309!4d78.4010528!15sChhHb21hamlwZXQgRm9ydCB0ZWxhbmdhbmFaGiIYZ29tYWppcGV0IGZvcnQgdGVsYW5nYW5hkgEIZm9ydHJlc3OaASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVUk5lWFZtZVZWUkVBReABAA!16zL20vMDdtd2p5?hl=en-GB",
    },
    {
      id: 12, 
      image: "assets/telangang/forts/Warangal Fort.jfif",
      name: "Warangal Fort ",
      category: "Fort",
      description: "https://www.holidify.com/places/warangal/warangal-fort-sightseeing-3943.html ",
      info : "A prominent landmark of the Telangana state and an apt example of architectural excellence and historical richness of the yore, the Warangal fort is situated in Warangal. The city is also known as Oru Kallu, which means 'a single stone'. Locals believe the city was built on a single rock in the medieval era. Sprawlingly spread across a stretch of 19 km between Warangal & Hanamkonda, this 12th-century fort is a prominent historical attraction in Telangana. ",
      map : " https://www.google.com/maps/place/Warangal+Fort/@17.9561269,79.6125159,17z/data=!3m1!4b1!4m5!3m4!1s0x3a335b2d6dcbafe3:0x97a58bc4da2ea1c4!8m2!3d17.9561218!4d79.6147046?hl=en-GB",
    },
    {
      id: 13, 
      image: "assets/telangang/forts/Khammam Fort.jfif",
      name: "Khammam Fort ",
      category: "Fort",
      description: "https://www.holidify.com/places/khammam/khammam-fort-sightseeing-4980.html ",
      info : " Initiated in 950 AD and completed by the year 1000, this fort has seen many change of reigns. Depicting architecture of both Muslim and Hindu reigns, Khammam Fort has recently completed 1000 years of existence and is a major tourist destination.",
      map : " https://www.google.com/maps/place/Khammam+Fort,+Nizampet,+Khammam,+Telangana+507001/@17.2465161,80.1428633,17z/data=!3m1!4b1!4m5!3m4!1s0x3a3459d2f07252df:0xc41fb35b8d1d8b85!8m2!3d17.2464715!4d80.1449518?hl=en-GB",
    },
    {
      id: 14, 
      image: "assets/telangang/heritage tours/Charminar, Hyderabad.jpg",
      name: "Charminar ",
      category: "Heritage",
      description: "https://www.holidify.com/places/hyderabad/charminar-sightseeing-2038.html ",
      info : "An identifying feature of the city, Charminar is the most prominent landmark located right in the heart of Hyderabad. The monument was erected by Quli Qutub Shah to signify the founding of Hyderabad. As is evident from the structure, it was so named as it consists of four minarets. Although it lies right in the centre of the city with traffic and crowds milling all about it, Charminar certainly manages to hold the gaze. ",
      map : " https://www.google.com/maps/place/Charminar/@17.3615687,78.4724758,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb978a6e1a939b:0xcb5a69e4aaf113fb!8m2!3d17.3615636!4d78.4746645?hl=en-GB",
    },
    {
      id: 15, 
      image: "assets/telangang/heritage tours/Alampur.jpg",
      name: "Alampur ",
      category: "Heritage",
      description: "https://www.tripadvisor.in/SmartDeals-g2295145-Alampur_Jogulamba_Gadwal_District_Telangana-Hotel-Deals.html ",
      info : "Situated on the banks of River Tungabhadra close to the place where the mighty rivers of Krishna and Tungabhadra merge, Alampur has rich historical and pilgrimage importance. Several dynasties ruled this place including Satavahanas, Chalukyas, Kakatiyas, Bahamani sultans, Vijayanagara kings and finally falling under Hyderabad. Alampur is one of the top attractions you must include in Hyderabad tour packages.",
      map : " https://www.google.com/maps/place/Alampur+(P),+Telangana+509152/@15.8824684,78.1149284,15z/data=!3m1!4b1!4m5!3m4!1s0x3bb5e8f5570d91ab:0x2424e322d27d376f!8m2!3d15.8843491!4d78.1193823?hl=en-GB",
    },
    {
      id: 16, 
      image: "assets/telangang/heritage tours/Mahabubnagar.jpg",
      name: " Mahbubnagar",
      category: "Heritage",
      description: "https://www.trawell.in/telangana/mahabubnagar ",
      info : "At a distance of 105 km from Hyderabad, 122 km from Kurnool and 110 km from Raichur, Mahabubnagar, also known as Palamoor is a town and headquarters of Mahaboobnagar district of Telangana. The name was changed to Mahbubnagar in 1890, in honour of Mir Mahbub Ali Khan Asaf Jah VI, the Nizam of Hyderabad.Mahaboobnagar and the surrounding places witnessed several wars between 14th and 16th centuries. It was a strategic place to control for Chalukyas, Bahmanis, Vijayanagar rulers and Golconda nawabs. Mahaboobnagar is also a land of Samsthanas (princely regions) with Gadwal, Wanaparthy and Kollapur regions successfully controlled for several centuries. ",
      map : " https://www.google.com/maps/place/Mahbubnagar,+Telangana+509001/@16.7471237,77.9803769,13z/data=!3m1!4b1!4m5!3m4!1s0x3bca2603faaea475:0xc6e3676d440af165!8m2!3d16.7488379!4d78.0035172?hl=en-GB",
    },
    {
      id: 17, 
      image: "assets/telangang/heritage tours/Ramappa  temple.jpg",
      name: "Ramappa Temple ",
      category: "Heritage",
      description: "https://www.trawell.in/telangana/ramappa-temple ",
      info : "Dedicated to Lord Shiva, Ramappa Temple or Ramalingeshwara Temple was built by General Recherla Rudra, during the period of the Kakatiya ruler Ganapati Deva in 1213 AD. As per history, it took 40 years to build this temple. The temple got its name from Ramappa, the chief sculptor of the temple. It's probably the only temple in the country to be known by the name of its sculptor, and among the popular places to experience Telangana Tourism. ",
      map : "https://www.google.com/maps/place/Ramappa+Temple/@18.2592811,79.9411291,17z/data=!3m1!4b1!4m5!3m4!1s0x3a330e7519eefc6f:0xacc2bee174187d8a!8m2!3d18.2593486!4d79.9433156?hl=en-GB",
    },
    {
      id: 18, 
      image: "assets/telangang/heritage tours/Medak_Church.jpg",
      name: "Medak Church ",
      category: "Heritage ",
      description: "https://www.trawell.in/telangana/medak/medak-church ",
      info : " The Cathedral built in Gothic style was inaugurated in 1914 and completed in 1924. The main tower of the church is 175 feet high and the cathedral can accommodate 5000 people at a time. There are 3 magnificent stained glass windows depicting the life of Jesus Christ. The farmers toiled to erect the church and Thomas Edward Harding, the architect, left no stone unturned in building the cathedral. The tile's design is an intricate one in six colours red, brown, black, yellow, chocolate and grey.      ",
      map : " https://www.google.com/maps/place/Medak+church/@18.0542076,77.7081,10z/data=!4m10!1m2!2m1!1sMedak+Church!3m6!1s0x3bcb9bd4e5a894b3:0xf6fba740712d4e02!8m2!3d18.0542092!4d78.2684032!15sCgxNZWRhayBDaHVyY2haDiIMbWVkYWsgY2h1cmNokgEGY2h1cmNomgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVU15ZDNWUGRYZDNSUkFC4AEA!16s%2Fg%2F11llfcpzw6?hl=en-GB",
    },
    {
      id: 19, 
      image: "assets/telangang/heritage tours/Jatprole.jpg",
      name: "Jatprole Temples ",
      category: "Heritage",
      description: "https://www.hellotravel.com/india/jatprole-jetaprolu ",
      info : "Jatprole or Jataprolu in Kollapur Mandal, Nagarkurnool District is popular for two temples known as Madana Gopala Swamy Temple and a group of Shiva temples including the famous Agasthyeswara Swamy.The temples were moved to Jetprole from the villages of Malleswaram and Manchalakota during the construction of Srisailam.Madana Gopala Swamy temple, also known as Venu Gopala Swamy temple is dedicated to Lord Krishna. It was built by Rajas of Jetprole during the 16th century. ",
      map : " https://www.google.com/maps/place/Jatprole+Group+of+Temples+(20+Shivalayams)/@16.0563921,78.2075608,17z/data=!3m1!4b1!4m5!3m4!1s0x3bb5f22f1ae48431:0xe15ca44bece6203d!8m2!3d16.0563049!4d78.2097546?hl=en-GB",
    },
    {
      id: 20, 
      image: "assets/telangang/heritage tours/Kusumanchi temple.jpg",
      name: "Kusumanchi temple ",
      category: "Heritage",
      description: "https://www.trawell.in/telangana/khammam/kusumanchi-temples ",
      info : "Kusumanchi was known as Krupamani in the Kakatiya period. It is home to Sri Ganapeshwaralayam and Mukkanteswaralayam, the two Siva temples built by the Kakatiya rulers during 12th and 13th centuries. These temples stand as testimony to the architectural skills of the Kakatiya kings. The historical shrines have a striking resemblance to famous Ghanpur and Ramappa temples of Kakatiya period in the Warangal district. ",
      map : " https://www.google.com/maps/place/6WMX%2BFXP+Shivalayam,+Kusumanchi,+Telangana+507159/@17.2336582,79.9482207,17z/data=!3m1!4b1!4m5!3m4!1s0x3a34f070d6d9904d:0x6887a4c893cd5b3f!8m2!3d17.2336087!4d79.9503099?hl=en-GB",
    },
    {
      id: 21, 
      image: "assets/telangang/heritage tours/Sri Narayana Swamy Temple.jpg",
      name: "Sri Narayana Swamy Temple ",
      category: "Heritage",
      description: "https://www.trawell.in/telangana/adilabad/sri-narayana-swamy-temple-jainath ",
      info : "Sri Narayan Swamy Temple also known as Jainath Temple is an ancient temple built by Pallava chiefs. This temple is also popular for its Jain style architecture, thus, the village is called Jainath. The pillars inside the temple are extensive carved with beautiful sculptures. The outer walls of the temple and the vimana over the sanctum exhibit wonderful piece of art work. ",
      map : " ?hl=en-GB",
    },
    {
      id: 22, 
      image: "assets/telangang/hill stations/Araku Valley.webp",
      name: "Araku Valley ",
      category: "HillStation",
      description: "https://www.holidify.com/places/araku-valley/ ",
      info : "Perhaps one of the most popular hill destinations in South India, Araku Valley has many picaresque locals to boast of. The scenic beauty of the place draws people in like a magnet and one can experience a number of plantations a short distance from the valley. ",
      map : " https://www.google.com/maps/place/Araku+Valley,+Andhra+Pradesh/@18.3294716,82.8365932,14z/data=!3m1!4b1!4m5!3m4!1s0x3a3a4a4c298a218d:0x2b8de4f914b5f996!8m2!3d18.3273486!4d82.8775218?hl=en-GB",
    },
    {
      id: 23, 
      image: "assets/telangang/hill stations/Lambasingi.jpg",
      name: "Lambasingi ",
      category: "HillStation",
      description: "https://www.holidify.com/places/visakhapatnam/lambasingi-sightseeing-1253632.html ",
      info : "Fondly called the ‘Kashmir of Andhra Pradesh’, Lambasingi is a quaint hamlet nestled in Chintapalli Mandal in the richly forested Arakku Valley at an elevation of 1025 m above the sea level. On of the best kept secrets of Andhra Pradesh, the dainty village is known for its majestic hills, apple orchards and panoramic views of the adjoining valleys. Also known as Korra Bayalu, the village is the only place in all of South India that experiences snowfall as the temperatures drop significantly.  ",
      map : " https://www.google.com/maps/place/Lambasingi,+Andhra+Pradesh+531116/@17.8191267,82.4840855,15z/data=!3m1!4b1!4m5!3m4!1s0x3a39f4044d3c05c7:0xe428ecd09f8338da!8m2!3d17.818596!4d82.4921961?hl=en-GB",
    },
    {
      id: 24, 
      image: "assets/telangang/hill stations/Chikmagalur.webp",
      name: "Chikmagalur ",
      category: "HillStation",
      description: "https://www.holidify.com/places/chikmagalur/ ",
      info : "Being the largest producer of coffee in the country, Chikmagalur is mainly all about its coffee.  So if you’re a coffee enthusiast as well as a nature lover, taking a walk through one (or a few) of the numerous coffee plantations in the city is a must-do activity. Many of these coffee estates not only allow visitors to take guided tours through the plantations, but they also provide home-stays right within the estates, so you can literally wake up to and end your day with the smell of coffee in the air.",
      map : "https://www.google.com/maps/place/Chikkamagaluru,+Karnataka/@13.3131943,75.7374289,13z/data=!3m1!4b1!4m5!3m4!1s0x3bbad762c8a889dd:0xb3cf49155294be16!8m2!3d13.3161441!4d75.7720439?hl=en-GB",
    },
    {
      id: 25, 
      image: "assets/telangang/hill stations/Yelagiri Hills.jpg",
      name: "Yelagiri ",
      category: "HillStation",
      description: "https://www.holidify.com/places/yelagiri/ ",
      info : "Yelagiri is one of those typical, silent places that seem ordinary on the outside but are more and more startling as you discover it. It has all the features of a great hill station, be it sunset points or lakes and parks. But the beauty of Yelagiri lies in all the more that it has to offer. Being one of the lesser known hill-stations in Tamil Nadu, the place is rarely overcrowded. The surroundings are pristine and the forests are home to some rare species of flora and fauna. The honey that is locally available is considered to be one of the purest and tastiest varieties. ",
      map : "https://www.google.com/maps/place/Yelagiri,+Tamil+Nadu+635853/@12.5856253,78.6257118,15z/data=!3m1!4b1!4m5!3m4!1s0x3badaaba63efaa8f:0x565d6a5d54337a3c!8m2!3d12.5856048!4d78.6344666?hl=en-GB",
    },
    {
      id: 26, 
      image: "assets/telangang/hill stations/Coorg.webp",
      name: "Coorg ",
      category: "HillStation",
      description: "https://www.holidify.com/places/coorg/ ",
      info : "Coorg, officially known as Kodagu, is the most affluent hill station in Karnataka. It is well known for its breathtakingly exotic scenery and lush greenery. Forest covered hills, spice and coffee plantations only add to the landscape. Madikeri is the region's centre point with all transportation for getting around starting from here. On a visit to Coorg, cover the beautiful towns like Virajpet, Kushalnagar, Gonikoppal, Pollibetta, and Somwarpet, and experience the beautiful concept of homestays ",
      map : "https://www.google.com/maps/place/Coorg+Hills+Top/@12.41746,75.7261176,17z/data=!4m10!1m2!2m1!1scoorg+hill+station!3m6!1s0x3ba5aaa6a648d3f7:0xfb69cc768b459613!8m2!3d12.41746!4d75.730495!15sChJjb29yZyBoaWxsIHN0YXRpb25aFCISY29vcmcgaGlsbCBzdGF0aW9ukgEKbmlnaHRfY2x1YpoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VOcE5uSkhSMnBSUlJBQuABAA!16s%2Fg%2F11fzb0lhl2?hl=en-GB",
    },
    {
      id: 27, 
      image: "assets/telangang/hill stations/Srisailam.jpg",
      name: " Srisailam",
      category: "HillStation",
      description: "https://traveltriangle.com/blog/hill-stations-near-hyderabad/",
      info : "promises a fantastic drive to the temples and the caves where you can rediscover mystical India. Situated on the banks of river Krishna, the place also has a wildlife sanctuary and a dam for you to explore. It is also one of the best places to enjoy ",
      map : " https://www.google.com/maps/place/Srisailam,+Andhra+Pradesh+518101/@16.074537,78.8615155,15z/data=!3m1!4b1!4m5!3m4!1s0x3bb5656d70792343:0xb2342e1f2ed1834b!8m2!3d16.0732748!4d78.8687291?hl=en-GB",
    },
    {
      id: 28, 
      image: "assets/telangang/religious tour/BHADRACHALAM.jpg",
      name: "Bhadrachalam ",
      category: "Religious",
      description: "https://www.holidify.com/places/bhadrachalam/ ",
      info : "Bhadrachalam can be a refreshing place to visit with a share of instances from the Ramayana, a glorious palace, a vibrant river and mystical terrain and surroundings. One of the major attractions of Bhadrachalam is the Sita Ramachandraswamy temple. One can also visit the Abhaya Anjaneya temple. The majestic River Godavari is found winding with its vast stretch of sand all throughout the town and is considered to be very holy. It can also be the host to a number of water sports that makes the river be a delightful experience. ",
      map : " https://www.google.com/maps/place/Bhadrachalam,+Telangana+507111/@17.6675275,80.8609793,14z/data=!3m1!4b1!4m5!3m4!1s0x3a36a8b3e5f7e94d:0x5500f9bb9038962e!8m2!3d17.6687912!4d80.8935925?hl=en-GB",
    },
    {
      id: 29, 
      image: "assets/telangang/religious tour/KHAMMAM.jpg",
      name: "Khammam",
      category: "Religious",
      description: "https://www.holidify.com/places/khammam/ ",
      info : "Khammam city, erstwhile known as Kammamet, is the fourth largest city in the Indian state of Telangana. It is located in the state of Telangana, approximately 200 km from the capital Hyderabad. A historically significant city, Khammam hosted many movements during India's freedom struggle. The Khammam Fort, which had periods of reign by both Hindu and Muslim leaders, is a famous cultural landmark of the city, and a popular tourist destination. ",
      map : " https://www.google.com/maps/place/Khammam,+Telangana/@17.2484342,80.1154153,13z/data=!3m1!4b1!4m5!3m4!1s0x3a3459d0d5cf738d:0xe18da4ae6d89da01!8m2!3d17.2472528!4d80.1514447?hl=en-GB",
    },
    {
      id: 30, 
      image: "assets/telangang/religious tour/Basara.jpg",
      name: "Basar ",
      category: "Religious",
      description: "https://www.trawell.in/telangana/basara ",
      info : "Basar or Basara is situated on the banks of River Godavari. It is a popular tourist and pilgrimage site because of the famous Saraswathi temple. The Basara temple in is a unique temple of Goddess Saraswati, the Hindu Goddess of Knowledge and Learning. Children are brought here to do the learning ceremony called Akshara Abyasam. It is believed to be one of the two oldest temples of Goddess Saraswathi in India, the other being located in Kashmir. ",
      map : " google.com/maps/place/BASARA+TEMPLE/@18.8772189,77.9520883,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcde1c6018ad225:0x65c23242a414d7c8!8m2!3d18.8772404!4d77.9565658?hl=en-GB",
    },
    {
      id: 31, 
      image: "assets/telangang/religious tour/Vemulawada.jpg",
      name: "Vemulawada ",
      category: "Religious",
      description: "https://www.trawell.in/telangana/vemulawada ",
      info : "Vemulawada is famous for the temple of Rajarajeshwara Swamy, an incarnation of Lord Shiva. It was built by one of the governors of Kalyani Chalukyas by name Rajadithya between 11th and 12th centuries. The presiding deity is locally popular as Rajanna who is accompanied by the idols of Sri Raja Rajeswari Devi and Siddi Vinayaka. It houses several temples dedicated to other deities including Anantha Padmanabha Swamy, Bhimeshwara Swamy, Kodanda Rama and Kasi Visweswara. Apart from these there is a tomb of Muslim saint. ",
      map : " https://www.google.com/maps/place/Vemulawada,+Telangana+505302/@18.4692466,78.8581553,15z/data=!3m1!4b1!4m5!3m4!1s0x3bcce290dcf2781d:0x1944abecb417a297!8m2!3d18.4681062!4d78.8671321?hl=en-GB",
    },
    {
      id: 32, 
      image: "assets/telangang/religious tour/Sri Rama Chandra Temple - Ammapalli.jpg",
      name: "Sri Rama Chandra Temple ",
      category: "Religious",
      description: "https://www.trawell.in/telangana/hyderabad/sri-rama-chandra-temple-ammapalli ",
      info : "The Rama temple was built by Vengi kings in 13th century but the idol was 1000 years old. The temple is adorned with a large seven-story tower which is quite famous among Telugu movie fans. There is a large image of Lord Vishnu is sleeping posture above the gateway of the tower.The tower is followed by the main temple with a large corridor around the temple. The Idols of Rama, Sita and Laxmana and its Makara Thoranam are beautifully formed from single black rock. Anjaneya, usually accompanying Lord Rama, is not seen in the garbhagriha. Instead, Anjaneya Swamy idol is placed near the Dwaja Sthambam facing Sri Rama. ",
      map : " https://www.google.com/maps/place/Sri+Seetha+Rama+Chandra+Swamy+Temple,+Ammapally+Narkhoda/@17.257209,78.3432245,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcbbee750a6884b:0x84eb9a257d92679c!8m2!3d17.2572039!4d78.3454132?hl=en-GB",
    },
    {
      id: 33, 
      image: "assets/telangang/religious tour/Wargal Saraswati Temple.jpg",
      name: "Wargal Saraswati Temple ",
      category: "Religious",
      description: "https://www.trawell.in/telangana/medak/wargal-saraswati-temple ",
      info : "The Wargal Temple is dedicated to Goddess Saraswati Devi. The garbhagriha is located at a level nearly equivalent to the third floor. The Goddess is seen to be in full glory decorated with a lot of jewels and garlands and adorned in a saree. There is an idol of Goddess about 10 feet high in front of the temple, which is a magnificent piece of art.",
      map : " https://www.google.com/maps/place/Sri+Vidya+Saraswathi+Shani+Temples+Wargal/@17.7697721,78.6187777,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcc7e5197a9ca27:0x1637a4125d8c58e5!8m2!3d17.7698027!4d78.6209644?hl=en-GB",
    },
    {
      id: 34, 
      image: "assets/telangang/religious tour/Dharmapuri.jpg",
      name: "Dharmapuri ",
      category: "Religious ",
      description: "https://www.trawell.in/telangana/karimnagar/dharmapuri ",
      info : "The town was ruled by King Dharma Varma and thus the name of the town was named after him as Dharmapuri. It is famous for its temples and artists, located on the banks of holy river Godavari. The most interesting fact of Dharmapuri is that the Godavari river flows from north to south direction unlike west to east in all other places where it flows and hence the river is termed here as Dakshina Vahini. Dharmapuri has one of the largest settlements of Vedic Brahmins in Telangana. Due to presence of many temples in the area, it is also known as 'Teertharajamu'. ",
      map : " https://www.google.com/maps/place/Dharmapuri,+Telangana+505425/@18.947582,79.058137,14z/data=!3m1!4b1!4m5!3m4!1s0x3bcd414fe57b0311:0x54f42ae0ff4def24!8m2!3d18.9480136!4d79.0947884?hl=en-GB",
    },
    {
      id: 35, 
      image: "assets/telangang/religious tour/Chaya Someswara Temple.jpg",
      name: "Chaya Someshwara Temple ",
      category: "Religious",
      description: "https://www.trawell.in/telangana/nalgonda/chaya-someshwara-temple-panagal ",
      info : " Sri temple was built during 11th - 12th centuries by Cholas. The temple got the name as it is believed that the formation of relentless shadow (Chaya in Telugu) of a pillar falls over the main deity of Shivalingam throughout the day. This amazing temple, engineered by the Kunduru, testifies the fantastic creative thinking and scientific knowledge of its architects. The complex houses three deities - Brahma, Vishnu and Shiva facing three different directions connected by common mahamandapa. The temple also demonstrates wonderful sculpture and art work.",
      map : " https://www.google.com/maps/place/Sri+Chaya+Someshwara+Temple/@17.0774565,79.2930513,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb2be0afae5df1:0x685abb9f11ea09f8!8m2!3d17.0774514!4d79.29524?hl=en-GB",
    },
    {
      id: 36, 
      image: "assets/telangang/whildlife santuaries/Pakhal Wildlife Sanctuary.jpg",
      name: "Pakhal Wildlife Sanctuary ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/warangal/pakhal-lake-wildlife-sanctuary ",
      info : "Pakhal Wildlife Sanctuary is spread over 839 sq. kms. The sanctuary presents a beautiful landscape with a dense and a rich store of animals. it is indeed a delight for the tourists to see so many animals amidst a wonderful backdrop.One can spot a tiger or a leopard or a bear and one can find a herd of deer roaming about freely in the wild. The sanctuary is also harboring Marmals like panthers, hyensa, wolf, wild dogs, jackals, sloth bear, nilgal, porcupine, langoor, Reptiles like python, cobra, common krait, monitor lizard and Crocodiles. ",
      map : " https://www.google.com/maps/place/Pakhal+Lake/@17.9537444,79.9955911,14z/data=!3m1!4b1!4m5!3m4!1s0x3a33798b120a91af:0xac562c4c2f525534!8m2!3d17.952583!4d80.005979?hl=en-GB",
    },
    {
      id: 37, 
      image: "assets/telangang/whildlife santuaries/Pocharam Dam _ Wildlife Sanctuary.jpg",
      name: "Pocharam Dam & Wildlife Sanctuary ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/medak/pocharam-dam-wildlife-sanctuary ",
      info : " The sanctuary is the homeland of various species of animals and birds. Panther, Sloth Bear, Wild Boar, Cheetal, Sambar, Nilgai, Chowsingha, Chinkara, Hyena and Jackal are the main attractions of the sanctuary. The river Manjira is the main river that adds life to the jungle. Crocodile, fresh water turtles, Cobra and Marsh can be located in this sanctuary.The flora of the sanctuary make the sanctuary livelier with green vegetation like Babul prosopis, Pistia, Hydrilla, Eichornia and Vallisneria. Nine small islands in the middle of the reservoir are the main breeding areas for birds, crocodiles and turtles. Birds like Painted Storks, herons, Coots, Teals, Cormorants, Pochards, Black and White Ibises, Spoon Bills and Open Billed Storks make their nests in these islands.",
      map : " https://www.google.com/maps/place/Pocharam+Wildlife+Sanctuary,+Pocharam+Forest+%26+Wildlife+Sanctuary+Trail+Rd,+Mirgudpally+(DP),+Telangana+502113/@18.1237462,78.1900771,15z/data=!3m1!4b1!4m5!3m4!1s0x3bcc3c264bc17841:0x1c4cd63faad5ea27!8m2!3d18.1233843!4d78.197765?hl=en-GB",
    },
    {
      id: 38, 
      image: "assets/telangang/whildlife santuaries/Eturnagaram Wildlife Sanctuary.jpg",
      name: "Eturnagaram Sanctuary ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/ramappa-temple/eturnagaram-sanctuary ",
      info : "Eturnagaram Sanctuary has a water source called Dayyam Vagu, which separates the sanctuary into two parts. This sanctuary provides shelter to Tiger, Leopard, Panther, Wolf, Wild Dogs, Jackals Sloth Bear, Chousingha, Black Buck, Nilgai, Sambar, Spotted Deer, Four Horned Antilope, Chinkara, Black Buck, Gaur, and Giant Squirrels. The sanctuary is also home to a wide range of bird species. ",
      map : " https://www.google.com/maps/place/Eturnagaram,+Telangana/@18.3428718,80.3944715,14z/data=!3m1!4b1!4m10!1m2!2m1!1s+Eturnagaram+Sanctuary+!3m6!1s0x3a33b85d1c18169b:0xee0a8f281b7e2e06!8m2!3d18.3378112!4d80.4298704!15sChVFdHVybmFnYXJhbSBTYW5jdHVhcnmSAQhsb2NhbGl0eeABAA!16s%2Fm%2F02rfcr2?hl=en-GB",
    },
    {
      id: 39, 
      image: "assets/telangang/whildlife santuaries/Kinnerasani Wildlife Sanctuary.jpg",
      name: "Kinnerasani Wildlife Sanctuary ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/khammam/kinnerasani-wildlife-sanctuary ",
      info : "The wildlife sanctuary is spread over an area of 635.4 sq km with the picturesque Kinnerasani Lake and densely forested islands in the middle of the sanctuary. The sanctuary is the home for many animals like Cheetal, Chinkara, Chousinghas, Sambar, Wild Boars, Gaurs, Hyena, Jackals, Panthers, Sloth Bear, Tigers and Black Bucks. The varieties of birds like Peafowl, Jungle Fowl, Quails, Partridges, Teals, Nuktas, Spoonbills and Doves are the common birds in the sanctuary. ",
      map : " https://www.google.com/maps/place/Kinnerasani+Wild+Life+Sanctuary/@18.3433967,79.8514789,9z/data=!4m10!1m2!2m1!1sKinnerasani+Wildlife+Sanctuary!3m6!1s0x3a34052f25ec59a7:0x7417b9c03d8a0fc2!8m2!3d17.6731152!4d80.6569281!15sCh5LaW5uZXJhc2FuaSBXaWxkbGlmZSBTYW5jdHVhcnlaICIea2lubmVyYXNhbmkgd2lsZGxpZmUgc2FuY3R1YXJ5kgESdG91cmlzdF9hdHRyYWN0aW9umgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVU5IYWtsTU9XTjNFQUXgAQA!16s%2Fg%2F11lgjrqj9c?hl=en-GB",
    },
    {
      id: 40, 
      image: "assets/telangang/whildlife santuaries/the Mrugavani National Park.jpg",
      name: "Mrigavani National Park ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/hyderabad/mrigavani-national-park ",
      info : "Situated near Himayatsagar lake in Chilkur, this park is established in 1994. Wildlife population includes sambar, deer, chital, wild boar, porcupine, hare, forest cat, civet cat and mongoose. Bird species include peacocks, warblers, babblers, flower peckers, partridges, lapwings, ducks, curlews and quails. Python, cobra, rat snakes, Russell's viper and monitor lizard are a few reptiles found. The park harbors over 600 plant species ranging from bryophytes, Pteridophytes, Climbers, Herbs, Shrubs and Trees. Prominent trees are Teak, Rosewood, Sandalwood, Neem, Bamboo, etc. ",
      map : " https://www.google.com/maps/place/Mrugavani+National+Park/@17.3540139,78.1951197,12z/data=!4m10!1m2!2m1!1sMrigavani+National+Park!3m6!1s0x3bcb95a77e94993b:0x5c6ad62be7fdb77!8m2!3d17.3540139!4d78.3351954!15sChdNcmlnYXZhbmkgTmF0aW9uYWwgUGFya1oZIhdtcmlnYXZhbmkgbmF0aW9uYWwgcGFya5IBDW5hdGlvbmFsX3BhcmvgAQA!16zL20vMDhfdjhz?hl=en-GB",
    },
    {
      id: 41, 
      image: "assets/telangang/whildlife santuaries/KBR National Park.jpg",
      name: "KBR National Park ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/hyderabad/kbr-national-park ",
      info : "Named after the former Chief Minister of Andhra Pradesh late Kasu Brahmananda Reddy, it covers an area of 156 hectares. It was established in 1994 to safeguard the biodiversity and richness of the area. The fauna comprises around 113 species of birds, 20 species of reptiles, 15 species of butterflies, 20 species of mammals and numerous invertebrates. It houses the stately Chiran palace of the former Nizam of Hyderabad. The park has nearly 600 species of trees, shrubs, climbers, herbs, grasses, besides several pteridophytes, bryophytes and xerophytes. ",
      map : " https://www.google.com/maps/place/Kasu+Brahmanandha+Reddy+National+Park+(KBR)/@17.4200114,78.4208659,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb96d242fcee65:0x6e3410d77ae1bf03!8m2!3d17.4200063!4d78.4230546?hl=en-GB",
    },
    {
      id: 42, 
      image: "assets/telangang/whildlife santuaries/Mahavir Harina Vanasthali National Park.jpg",
      name: "Mahavir Harina Vanasthali National Park ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/hyderabad/mahavir-harina-vanasthali-national-park ",
      info : "Named after the holy Jain saint 'Lord Mahavira', it was established in 1975 on 2500th birth anniversary of the saint. This sanctuary was once the exciting 'Shikargarh' or hunting ground of one of the Nizam rulers. It has now been converted into a protected national park. The park is in full bloom during monsoons when beautiful flowers of different colors blossom all around. This Park is home to the endangered Black Buck deer. An estimated 400 deer roam around the National Park fearlessly. ",
      map : " https://www.google.com/maps/place/Mahavir+Harina+Vanasthali+National+Park/@17.340868,78.5827547,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb9f5f616ffa6b:0x485ddebc6e5748ec!8m2!3d17.3408629!4d78.5849434?hl=en-GB",
    },
    {
      id: 43, 
      image: "assets/telangang/whildlife santuaries/Nehru Zoological Park.jpg",
      name: "Nehru Zoological Park ",
      category: "Wild",
      description: "https://www.trawell.in/telangana/hyderabad/nehru-zoological-park ",
      info : "Established in 1959, it is spread across 300 acres of lush green land. It houses over 1500 species of animals and birds. The park comprises a Natural History Museum, a Lion Safari Park and a children-s train. The Mir Alam Tank is with in the zoo park premise and boating facility is available here. Many species of birds like pelicans, peacock, dove, love birds, parakeets, pied horn bills, grey horn bills and manias, finches and buntings are found here. ",
      map : " https://www.google.com/maps/place/Nehru+Zoological+Park/@17.3506831,78.4491181,17z/data=!3m1!4b1!4m5!3m4!1s0x3bcb97c6c008fa9d:0x7b71bb447d86245b!8m2!3d17.350678!4d78.4513068?hl=en-GB",
    },
  ];
  
  export default TelanganaData;


 