const TripuraData= [
    {
      id: 1, 
      image: "assets/tripura/Beaches/Rudrasagar Lake.jfif",
      name: "Rudrasagar Lake",
      category: "Lake",
      description: "https://www.yatra.com/hotels/3-star-hotels-near-rudrasagar-lake-in-agartala",
      info : "Rudrasagar lake, about 55 Km. away from Agartala near Melaghar having 5.3 Sq.Km. water area is another big attraction In the centre of the lake the famous lake palace of Tripura namely Neermahal is built. The lake witnesses alarge number of migratory birds in every winter. Every year a boat race is organised in July/August. The visiting tourists can enjoy boating facility in the lake.",
      map : "https://www.google.com/maps/place/Rudrasagar+Lake/@23.4996365,91.2987011,15z/data=!3m1!4b1!4m5!3m4!1s0x375384431a79a1f3:0x32c7f118b99e05aa!8m2!3d23.5003515!4d91.3167996",
    },
    {
      id: 2, 
      image: "assets/tripura/Beaches/Dumboor Lake.jpg",
      name: "Dumboor Lake",
      category: "Lake",
      description: "https://www.travalour.com/attraction/2973-dumboor-lake/nearby-hotels",
      info : "A water area of 41 sq.km. with an un-ending spell of luxuriant green vegetation all around stands majestic for her exceedingly charming beauty and 48 islands in the midst of the lake. Migratory birds, Water sports facilities are additional attractions. 115 km away from Agartala, the place is connected by bus from Agartala and Udaypur. The panorama of transparent weaving water cover the vast span and the deep green dots of island in their midst are fascinating. There is a Hydel Project near the lake from where River Gomati originates and this is called Tirthamukh where on 14th January every year famous 'Pous Sankranti Mela' takes place. The lake is the confluence of rivers Raima and Sarma",
      map : "https://www.google.com/maps/place/Dumboor/@23.4984433,91.7814053,12z/data=!3m1!4b1!4m5!3m4!1s0x37525314578eca25:0x6e61af0dae08d87c!8m2!3d23.4756928!4d91.8440259",
    },
    {
      id: 3, 
      image: "assets/tripura/forts/Unakoti.jfifg",
      name: "Unakoti",
      category: "Forts",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3179303-Unakoti-Agartala_West_Tripura_District_Tripura.html",
      info : "70km away from Agartala. There is a profusion of rock-cut images, belonging to 11-12th century A.D., intricate and finely executed. This is as such, and open air art gallery.It is Shaiba pilgrimage and dates back to 7th - 9th centuries if not earlier. The marvelous rock carvings, murals with their primitive beauty, waterfalls are not to be missed. Unakoti means one less than a crore and it is said that these many rock cut carvings are available here. As per Hindu mythology, when Lord Shiva was going to Kashi along with one crore gods and goddesses he made a night halt at this location. He asked all the gods and goddesses to wake up before sun rise and proceed for Kashi.",
      map : "https://www.google.com/maps/place/Unakoti,+Tripura/@24.2022454,91.7729913,10z/data=!3m1!4b1!4m5!3m4!1s0x37518e8b771217df:0xc9d92f61f1fec710!8m2!3d24.1780881!4d92.027319",
    },
    {
      id: 4, 
      image: "assets/tripura/forts/Pilak.jpg",
      name: "Pilak",
      category: "Forts",
      description: "https://www.tripadvisor.in/HotelsNear-g12435856-d3179310-Pilak-Jolaibari_South_Tripura_District_Tripura.html",
      info : "Treasure house of Hindu and Buddhist Sculpture. It dates back to 8th and 9th centuries. Beautiful images scattered in an area of about 10 Sq.Km. have been found. The images, terracotta plaques and sealing found here reflect survival of heterodox creeds and sects representing both Hinduism and Buddhism. Colossal stone images of Avolokiteshwar and Narasimha have been found here. A good number of gold coins, rock-cut inscription, seals of burn clay, images of Buddha obtained in excavation indicate the place had a close contact with Mainamoti, an ancient Buddhist center",
      map : "https://www.google.com/maps/place/Pilak+Historical+Palace+(Shyam+Sundar+Ashram)/@23.2064549,91.599368,17z/data=!3m1!4b1!4m5!3m4!1s0x37530e0ca4b4b4cd:0xd717801f88a0cb24!8m2!3d23.20645!4d91.6038527",
    },
    {
      id: 5, 
      image: "assets/tripura/forts/Deotamura.jpg",
      name: "Deotamura",
      category: "Forts",
      description: "https://www.tripadvisor.in/HotelsNear-g12386111-d9859138-Devtamura-South_Tripura_District_Tripura.html",
      info : "Deotamura is famous for its panels of rock carvings on the steep mountain wall on the bank of Gomati. There are huge images carved of Shiva, Vishnu, Kartika, Mahisasur Mardini Durga and other gods and goddesses. This is also called Chabimura. These images date back to 15th-16th centuries. A panel of crude images engraved on the face of hill facing the river Gumati will welcome one in Deotamura, a hill range 75 km from Agartala. To approach Deotamura you have firstly to land up at Rangamati by bus from Udaipur and thereafter have to journey by boat to arrive at Deotamura.",
      map : "https://www.google.com/maps/place/Uttar+Baramura+Deotamura+R.F,+Tripura/@23.6249716,91.4253815,11z/data=!3m1!4b1!4m5!3m4!1s0x3753bc4e1ef6d709:0x3c7cea77ee049c47!8m2!3d23.6482738!4d91.5693045",
    }, 
    {
      id: 6, 
      image: "assets/tripura/religious tour/Laxmi Narayan Temple.jpg",
      name: "Laxmi Narayan Temple",
      category: "Religious",
      description: "https://www.tripadvisor.in/HotelsNear-g1156021-d3912840-Laxmi_Narayan_Temple-Chamba_Chamba_District_Himachal_Pradesh.html",
      info : "Lord Krishna was installed by Krishnananda Sevayet of Laxmi Narayan temple more than 45 years ago. The temple is also registered under Indian antiquitity act like monument. The main temple was constructed with some financial assistance of the royal family of Tripura. According to the legendary tale of the Bhagavata Tamal tree is closely associated with the life sport of Lord Krishna, probably considering this aspect, the sevayet planted Tamal tree in front of the temple about 35 years back.",
      map : "https://www.google.com/maps/place/LAXMI+NARAYAN+MANDIR/@23.8343347,90.7234525,10z/data=!4m10!1m2!2m1!1sLaxmi+Narayan+Temple+tripura!3m6!1s0x3753f505a37d2d6f:0xad080893d73c807f!8m2!3d23.8343252!4d91.2837549!15sChxMYXhtaSBOYXJheWFuIFRlbXBsZSB0cmlwdXJhkgEMaGluZHVfdGVtcGxl4AEA!16s%2Fg%2F11lt52fn3t",
    },
    {
      id: 7, 
      image: "assets/tripura/religious tour/Jagannath Temple.jpg",
      name: "Jagannath Temple",
      category: "Religious",
      description: "https://www.booking.com/landmark/in/jagannath-temple.en-gb.html?aid=356980&label=gog235jc-1DCAUobEIQamFnYW5uYXRoLXRlbXBsZUgzWANobIgBAZgBCbgBF8gBDNgBA-gBAYgCAagCA7gCgrWmnAbAAgHSAiQwYjg0MjFiNi1jMTA0LTRjYmUtYmJjZC0yNDAyZjg3NjBkMTbYAgTgAgE&sid=0e3aebcb054530a75a957f7cea0a89c8&inac=0&keep_landing=1&",
      info : "Famous not only from the pilgrims point of view, this temple is also a remarkable architectual feat with its octagonal baseand its impression pradhkshin patha round the sanctum. The pillars are crowned by square and pyramidal cones.",
      map : "https://www.google.com/maps/place/Jagannath+temple/@23.8403987,91.2822059,15z/data=!4m10!1m2!2m1!1sJagannath+Temple+tripura!3m6!1s0x3753f3e3e481e4e5:0xa9e00b25bb7a628d!8m2!3d23.8444274!4d91.301421!15sChhKYWdhbm5hdGggVGVtcGxlIHRyaXB1cmGSAQxoaW5kdV90ZW1wbGXgAQA!16s%2Fg%2F11nyp_vcjv",
    },
    {
      id: 8, 
      image: "assets/tripura/religious tour/Bhuvaneswari Temple.jpg",
      name: "Bhuvaneswari Temple",
      category: "Religious",
      description: "https://www.makemytrip.com/hotels/guwahati-hotels-near-bhuvaneswari_temple.html",
      info : "On the right bank of river Gomati at Udaipur is found the ruins of a big palace built by Maharaja Govinda Manikya (1660-75 A.D.). The Bhuveneswari temple is situated adjacent to this palace. It finds close literary reference in Great poet Rabindranath Tagore's novels and drama namely 'Bisharjan' and 'Rajarshi'",
      map : "https://www.google.com/maps/place/bhubeneswari+temple/@23.840793,91.0107579,10z/data=!4m10!1m2!2m1!1sBhuvaneswari+Temple+tripura!3m6!1s0x3753984955555555:0x6db34815855bb224!8m2!3d23.5360333!4d91.4869866!15sChtCaHV2YW5lc3dhcmkgVGVtcGxlIHRyaXB1cmFaHSIbYmh1dmFuZXN3YXJpIHRlbXBsZSB0cmlwdXJhkgEMaGluZHVfdGVtcGxlmgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVVJSTlU5aVZVZFJFQUXgAQA!16s%2Fg%2F11g9mgvx5k",
    },
    {
      id: 9, 
      image: "assets/tripura/religious tour/Tripurasundari Temple.jpeg",
      name: "Tripura Sundari Temple",
      category: "Religious",
      description: "https://www.holidify.com/places/agartala/tripura-sundari-temple-sightseeing-1010.html",
      info : "Tripura Sundari Temple is a beautiful temple situated in Udaipur, around 55 km away from Agartala, Tripura. This opulent temple is 500 years old thereby making it the oldest temple present in the Udaipur district. Tripura Sundari Temple is one of the 51 Sakti Peethas and is the place where the toe of the right foot of Sati fell. Owing to its history and beauty, this majestic temple remains flooded by tourists all through the year.",
      map : "https://www.google.com/maps/place/Tripurasundari+Temple/@23.5090145,91.4960419,17z/data=!3m1!4b1!4m5!3m4!1s0x375399ad7e70743b:0x5f779c1053e19df0!8m2!3d23.5089977!4d91.4982661",
    },
    {
      id: 10, 
      image: "assets/tripura/religious tour/Buddha Temple.jpg",
      name: "Buddha Temple",
      category: "Religious",
      description: "https://www.holidify.com/places/agartala/buddha-temple-sightseeing-1001.html",
      info : "Buddhist Temples in Tripura support the fact that Buddhism is quite prevalent in the state. Archaeological evidences have suggested that Buddhists have inhabited the region since ancient times. Several Buddhist rulers ruled over the state and left permanent influences on the culture of the state.",
      map : "https://www.google.com/maps/place/Buddha+temple/@23.3121,91.55755,17z/data=!3m1!4b1!4m5!3m4!1s0x37530b447abb7029:0xb16381201788053f!8m2!3d23.3120805!4d91.5620195",
    },
    {
      id: 11, 
      image: "assets/tripura/religious tour/Ummaneshwar Temple.jfif",
      name: "Ummaneshwar Temple",
      category: "Religious",
      description: "https://www.holidify.com/places/agartala/ummaneshwar-temple-sightseeing-1012.html",
      info : "Legend says that when Sati's toes fell on Kolkata, her divine right leg dropped here. This temple of Kali built in 1501 is a place for steady stream of pilgrims make almost endless animal sacrifices that leave the grounds as bloody as the temple's vivid-red shikhara. Even more people come here at the big Diwali festival (October/November) to bathe in the fish-filled tank by the temple.",
      map : "https://www.google.com/maps/place/Ummaheshwar+Temple/@23.8376155,91.2796108,17z/data=!3m1!4b1!4m5!3m4!1s0x3753f40e57efc0e9:0x3666c063bd66abf4!8m2!3d23.8376106!4d91.2817995",
    },
    {
      id: 12, 
      image: "assets/tripura/religious tour/fourteen goddes temple.webp",
      name: "Fourteen Goddess Temple",
      category: "Religious",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3179313-Fourteen_Goddess_Temple-Agartala_West_Tripura_District_Tripura.html",
      info : "It is located about 14 Km. away from Agartala at a place called Old Agartala. In the face of continued fight with Shamser Gazi, Maharaja Krishna Manikya had shifted the capital from Udaipur to Old Agartala. It continued to be the capital till it was shifted to Agartala. Near the sacred 14 goddess temple during the month of July every year a Kharchi festival is organised and thousands of pilgrims and devotees visit this festival. It is a local saying that one who visits Tripura Fourteen Goddess Temple once comes in Agartala fourteen times more.",
      map : "https://www.google.com/maps/place/Fourteen+Gods'+and+Goddesses'+Temple/@23.8414553,91.3430075,17z/data=!3m1!4b1!4m5!3m4!1s0x3753f222cfc90691:0xa2d6517bea797f18!8m2!3d23.8414522!4d91.3451582",
    },
    {
      id: 13, 
      image: "assets/tripura/religious tour/Mahamuni Buddha Mandir.webp",
      name: "Mahamuni Buddha Mandir",
      category: "Religious",
      description: "https://www.tripadvisor.in/HotelsNear-g295408-d3354679-Maha_Myat_Muni_Pagoda_Mahamuni_Buddha_Temple-Mandalay_Mandalay_Region.html",
      info : "Visiting the city where Lord Buddha is believed to have been inhabited and paying a visit to his temple is a mesmerising feeling that you don’t want to miss! This place is a beautiful piece of architecture and is very different from the ones we usually see. The whole architecture, including the Buddha statue in the temple, is golden in colour with Japanese aesthetics. This place offers peace and is opened all seven days of the week (timings differ from day to day).",
      map : "https://www.google.com/maps/place/Mahamuni+Buddha+Mandir/@23.1175116,91.6991928,17z/data=!3m1!4b1!4m5!3m4!1s0x37531a441ecbb4fd:0x67bfe6f001e84a3c!8m2!3d23.1175246!4d91.7013952",
    },
    {
      id: 14, 
      image: "assets/tripura/religious tour/Gunavati Temple.jpg",
      name: "Gunavati Group Of Temples",
      category: "Religious",
      description: "https://www.trip.com/hotels/gomati-hotels-list-536181/",
      info : "As the name suggests, the area is surrounded by a group of three temples. Constructed around the 17th century, the temples reveal an interesting sight of history. The stone inscription in the temple describes that the place was created in the name of Queen Gunabati. However, the inside of these temples presents the finest example of beautiful architectural designs.",
      map : "https://www.google.com/maps/place/Gunabati+Group+of+Temples/@23.5380539,91.5005538,17z/data=!3m1!4b1!4m5!3m4!1s0x3753986a42ae5087:0x43d6c4f66523c927!8m2!3d23.5380168!4d91.5027587",
    },
    {
      id: 15, 
      image: "assets/tripura/religious tour/Udayan Buddha Vihar.jpg",
      name: "Udayan Buddha Vihar",
      category: "Religious",
      description: "https://www.tripadvisor.in/Attraction_Review-g12386153-d15218680-Reviews-Udayan_Buddha_Vihar-North_Tripura_District_Tripura.html",
      info : "Lying almost 136 kilometers away from the city of Agartala, Udayan Budhha Vihar is another prominent tourist place in Tripura. Famous for being the residence to one of the unique idols of Lord Budhha, the place has earned massive significance among Buddhism followers. The idol is said to be made with ‘oshtodhatu’ which means 8 types of metals, making it an antique sculpture.",
      map : "https://www.google.com/maps/place/Udayan+Buddha+Vihara/@24.1901744,92.0823008,14z/data=!4m10!1m2!2m1!1sUdayan+Buddha+Vihar+tripura!3m6!1s0x37518ba66c03c527:0xfdc1539305cf0ef!8m2!3d24.1909313!4d92.1019832!15sChtVZGF5YW4gQnVkZGhhIFZpaGFyIHRyaXB1cmFaHSIbdWRheWFuIGJ1ZGRoYSB2aWhhciB0cmlwdXJhkgEPYnVkZGhpc3RfdGVtcGxlmgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVVJ2Y2kxVWJFMVJFQUXgAQA!16s%2Fg%2F1tjym1wm",
    },
    {
      id: 16, 
      image: "assets/tripura/heritage tours/Tripura Government Museum.jfif",
      name: "Tripura Government Museums",
      category: "Heritage",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3913113-Tripura_Government_Museum-Agartala_West_Tripura_District_Tripura.html",
      info : "Constructed around 1970, Tripura Government Museum is one of the prominent tourist places in Tripura. The whole museum consists of at least 76 galleries and is situated in the Ujjayanta Palace. From terracotta plaques to Cooper plates to Gold murals, the museum displays around 1406 antique items.",
      map : "https://www.google.com/maps/place/Ujjayanta+Palace/@23.8373552,91.2805241,17z/data=!3m1!4b1!4m5!3m4!1s0x3753f55d3fb69973:0x6f532f0800b2be03!8m2!3d23.8373503!4d91.2827128",
    },
    {
      id: 17, 
      image: "assets/tripura/heritage tours/Neermahal Palace.jfif",
      name: "Neer Mahal Palace",
      category: "Heritage",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3179319-Neermahal_Palace-Agartala_West_Tripura_District_Tripura.html",
      info : "Famously known as the Lake Palace of Tripura, Neer Mahal Palace is the living witness of Tripura’s Past glory. The antique architectural designs, lush green lawn, and royal decoration of this palace are enough to give you a wow factor. Located in the middle of Rudrasagar Lake, the palace was constructed by King Bir Bikram Kishore Manikya Bahadur.",
      map : "https://www.google.com/maps/place/Neermahal/@23.5065317,91.3134392,17z/data=!3m1!4b1!4m5!3m4!1s0x3753844599937959:0xd9f0f59ba87d8ffb!8m2!3d23.5065268!4d91.3156279",
    },
    {
      id: 18, 
      image: "assets/tripura/heritage tours/Malancha Niwas.jpg",
      name: "Malancha Niwas",
      category: "Heritage",
      description: "https://www.triphobo.com/hotels/near/malancha-niwas-55c1b126f8c2e5ce34000182",
      info : "Malancha Niwas is the house where Nobel laureate Rabindranath Tagore had stayed during his visit to Agartala in 1919. The king of Tripura was known to have very good ties with Tagore, and on the former’s invitation Tagore is known to have visited Agartala quite a few times. During one such visit in 1919, he stayed at a ‘kaccha’ house adjacent to the Kunjaban Palace, which was the private retreat of Maharaja Birendra Kishore Manikya Bahadur. The kaccha house subsequently became famous (for serving as the official guesthouse of the Kabiguru), and today it is a major tourist attraction. The kaccha Malancha Niwas has today been demolished and in its place stands a concrete two-storeyed structure. However, when Rabindranath Tagore visited Agartala in 1919, Malancha Niwas wasn’t known so. Only after the concrete construction was it rechristened as Malancha Niwas.",
      map : "https://www.google.com/maps/place/Malancha+Niwas/@23.8555781,91.2840185,17z/data=!3m1!4b1!4m5!3m4!1s0x3753f6aa51b6c1ff:0xb3ce2ba4e235b5a8!8m2!3d23.8555732!4d91.2862072",
    },
    {
      id: 19, 
      image: "assets/tripura/heritage tours/Kunjaban Palace.jpg",
      name: "Kunjaban Palace",
      category: "Heritage",
      description: "https://www.tripadvisor.in/Attraction_Review-g1028662-d3179284-Reviews-Kunjaban_Palace-Agartala_West_Tripura_District_Tripura.html",
      info : "A picturesque hillock that Maharaja Birendra Kishore Manikya Bahadur constructed ( 1909 -1923 ) as his country palace for private retreat, now serves as the Raj Bahavan, official residence of the Tripura Governor. Rabindra Nath Tagore stayed there in his seventh and last visit to the state. Poet Rabindranath Tagore stayed in the eastern apartment of this palace during his 7th and last visit to the state in 1926.This palace was the mute witness to many of the great poet's creations including a number of popular songs. There are well laid gardens and lawns inside the palace which is the official residence of the Governor of Tripura now.",
      map : "https://www.google.com/maps/place/Kunjaban,+Agartala,+Tripura/@23.8626486,91.2727883,15z/data=!3m1!4b1!4m10!1m2!2m1!1sKunjaban+Palace!3m6!1s0x3753f152e5a510a5:0xbb46d3dfdea48c4!8m2!3d23.8635079!4d91.2903074!15sCg9LdW5qYWJhbiBQYWxhY2WSAQxzdWJsb2NhbGl0eTHgAQA!16zL20vMGY1YzNr",
    },
    {
      id: 20, 
      image: "assets/tripura/heritage tours/Ujjayanta Palace.jpg",
      name: "Ujjayanta Palace",
      category: "Heritage",
      description: "https://www.makemytrip.com/hotels/agartala-hotels-near-ujjayanta_palace.html",
      info : "This royal house, which stands in the Capital city Agartala covering one sq.Km. area was built by Maharaja Radha Kishore Manikya during 1899-1901.It is a two storied mansion, having a mixed type of architecture with three high domes, the central one being 86' high. The magnificent tile floor, curved wooden ceiling and beautifully crafted doors are particularly notable. The palace is set with huge Mughal style gardens,beautified by pools and gardens and tiled floors. Flood lighting and fountains have also added to its beauty.",
      map : "https://www.google.com/maps/place/Ujjayanta+Palace/@23.8373503,91.2805241,18z/data=!4m10!1m2!2m1!1sGovernment+Museum+tripura!3m6!1s0x3753f55d3fb69973:0x6f532f0800b2be03!8m2!3d23.8373503!4d91.2827128!15sChlHb3Zlcm5tZW50IE11c2V1bSB0cmlwdXJhWhsiGWdvdmVybm1lbnQgbXVzZXVtIHRyaXB1cmGSAQZtdXNldW2aASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVTnBPRFpEZEVSM0VBReABAA!16s%2Fg%2F11bw677b3b",
    },
    {
      id: 21, 
      image: "assets/tripura/hill stations/Jampui Hills.jfif",
      name: "Jampui Hill",
      category: "HillStation",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3218030-Jampui_Hill-Agartala_West_Tripura_District_Tripura.html",
      info : "Jampui Hill is a popular hill station in Tripura, situated at an altitude of 3,000 ft above sea level. Also known as the land of eternal spring, the place offers panoramic views of the Chittagong Hills, the Kanchanpur-Dasda Valley and the sundry hill ranges of Tripura and Mizoram.",
      map : "https://www.google.com/maps/place/Jampui+Hills/@23.9424115,92.147015,11z/data=!4m10!1m2!2m1!1sJampui+Hill+tripura!3m6!1s0x37521aec20c41fe9:0xdb2b43c0200d164c!8m2!3d23.9664748!4d92.2763268!15sChNKYW1wdWkgSGlsbCB0cmlwdXJhWhUiE2phbXB1aSBoaWxsIHRyaXB1cmGSAQhlbGV2YXRlZJoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VOdE4ySmxYemQzUlJBQuABAA!16s%2Fg%2F11pd_7x_hx",
    },
    {
      id: 22, 
      image: "assets/tripura/whildlife santuaries/Gumti Wildlife Sanctuary.jfif",
      name: "Gumti Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.goibibo.com/hotels/hotels-in-kanpur/near-gumti-no-5-lh/",
      info : "Spread across a massive 390 sq. km, the Gumti Wildlife Sanctuary is situated in the south-eastern part of Tripura. The sanctuary is home to a wide range of animal and bird species such as Phayre’s leaf monkey, Asian Elephant, sambar, water buffalo, wild goat and several migratory birds. It is also home to various species of reptiles. There is a large water reservoir spread across an area of 300 sq. km near the sanctuary, which is used for water storage.",
      map : "https://www.google.com/maps/place/Gumti+Wildlife+Sanctuary/@23.4528904,91.8270894,17z/data=!3m1!4b1!4m5!3m4!1s0x3753ab4da7c86fa7:0x1105e581b44502a0!8m2!3d23.4528904!4d91.8292781",
    },
    {
      id: 23, 
      image: "assets/tripura/whildlife santuaries/Rowa Wildlife Sanctuary.jfif",
      name: "Rowa Wildlife Sanctuar",
      category: "Wildlife Sanctuaries",
      description: "https://www.trip.com/hotels/margaretta-township-rowa-wildlife-sanctuary/hotels-c344678m26648171/",
      info : "A paradise for nature lovers and photographers, Rowa Wildlife Sanctuary in Tripura is among the most popular tourist destinations in town. It covers an area of only 0.86 sq. km and is situated in the Dharmanagar Forest Sub Division. Considered a natural heritage spot, Rowa Wildlife Sanctuary was originally a forest. It was later converted into a sanctuary to protect its inhabitants. Rich in flora and fauna, the wildlife sanctuary is home to a wide variety of medicinal plants and reptiles as well.",
      map : "https://www.google.com/maps/place/Rowa+Wildlife+Sanctuary/@24.2927816,92.1643259,17z/data=!3m1!4b1!4m5!3m4!1s0x3751f2eb05d7ca09:0xc1c2d4b933b76b8f!8m2!3d24.2927767!4d92.1665146",
    },
    {
      id: 24, 
      image: "assets/tripura/whildlife santuaries/Sepahijala Wildlife Sanctuary.jfif",
      name: "Sepahijala Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.tripadvisor.in/HotelsNear-g1028662-d3202751-Sepahijala_Wildlife_Sanctuary-Agartala_West_Tripura_District_Tripura.html",
      info : "Measuring about 19 sq. km, Sepahijala Wildlife Sanctuary was established in 1987. It is located in Bishalgarh, at an approximate distance of 25 km from the city centre. It is a famous hub for migratory birds, making it one of the best spots for nature lovers. The wildlife sanctuary is home to a wide range of interesting bird species such as Asian openbill stork, white ibis and whistling teal. Some of the animal species that you can spot here are slow loris, Rhesus macaque, capped langur and dusky leaf monkey, among others. Owing to the large variety of animal and plant species, Sepahijala Wildlife Sanctuary is a must-visit tourist destination for all wildlife enthusiasts and photographers.",
      map : "https://www.google.com/maps/place/Sepahijala+Wildlife+Sanctuary+%26+Zoo/@23.6684101,90.2022174,9z/data=!4m10!1m2!2m1!1sSepahijala+Wildlife+Sanctuary!3m6!1s0x37538c263e606ca5:0xe92de0a0882b05f3!8m2!3d23.6684101!4d91.3228229!15sCh1TZXBhaGlqYWxhIFdpbGRsaWZlIFNhbmN0dWFyeVofIh1zZXBhaGlqYWxhIHdpbGRsaWZlIHNhbmN0dWFyeZIBA3pvb5oBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSak5uRXlSMnRuUlJBQuABAA!16s%2Fg%2F11hbc4n012",
    },
    {
      id: 25, 
      image: "assets/tripura/whildlife santuaries/Trishna Wildlife Sanctuary.jfif",
      name: "Trishna Wildlife Sanctuary",
      category: "Wildlife Sanctuaries",
      description: "https://www.tripadvisor.in/Attraction_Review-g1028662-d3179324-Reviews-Trishna_Wildlife_Sanctuary-Agartala_West_Tripura_District_Tripura.html",
      info : "Established in 1988, spread across an area of 163 sq. km, Trishna Wildlife Sanctuary houses both tropical semi-evergreen and mixed deciduous forests. The sanctuary also has many patches of virgin forests that are rich in rare vegetation, serving as the perfect place for nature enthusiasts. It is dotted with about 230 tree species, 400 herbs, 110 shrubs and 150 climbers. Trishna Wildlife Sanctuary is home to several water bodies and perennial water rivulets. Some of the prominent fauna species at the sanctuary include hoolock gibbon, Indian bison and golden langur.",
      map : "https://www.google.com/maps/place/Trishna+Wildlife+Sanctuary/@23.2678402,91.3252637,14z/data=!4m10!1m2!2m1!1sTrishna+Wildlife+Sanctuary!3m6!1s0x37537a0f40769ad1:0x25c6232fefa23971!8m2!3d23.2678402!4d91.3602826!15sChpUcmlzaG5hIFdpbGRsaWZlIFNhbmN0dWFyeZIBGHdpbGRsaWZlX2FuZF9zYWZhcmlfcGFya-ABAA!16s%2Fg%2F11g9nd_k42",
    },
    {
      id: 26, 
      image: "assets/Maharshtra/Forts/lohogad.jpg",
      name: "Mui Borok",
      category: "Food",
      info : "The traditional cuisine of the state of Tripura is Mui Borok as it is affectionately called by its people. You will always find one ingredient in the traditional food plate of Tripurian people, Berma. ",
    },
    {
      id: 27, 
      image: "assets/Maharshtra/Forts/lohogad.jpg",
      name: " Mosdeng Serma",
      category: "Food",
      info : "The spicy and tangy chutney to compliment the other dishes on the plate. Mosdeng Serma is primarily a tangy tomato chutney prepared with berma, red chilli, and garlic to add the deep flavours to the dish.",
    },
    {
      id: 28, 
      image: "assets/Maharshtra/Forts/lohogad.jpg",
      name: "Wahan Mosdeng",
      category: "Food",
      info : "A pork dish which is quite famous among the Tripurian people. My suggestion, if you are in Tripura you must grab a bite of this heavenly dish if you are a meat lover.",
    },
    {
      id: 29, 
      image: "assets/Maharshtra/Forts/lohogad.jpg",
      name: "Gudok",
      category: "Food",
      info : "A traditional dish prepared by boiling vegetables and fermented fish. This dish is mainly prepared during festivals and special occasions.",
    },
    {
      id: 30, 
      image: "assets/Maharshtra/Forts/lohogad.jpg",
      name: "Wahan Mosdeng",
      category: "Food",
      info : "It is also one of the traditional dishes of Tripura, which is prepared with pork, onion, coriander leaves, and green chili. The dish is delicious and lip-smacking with the addition of Green chili and local spices.",
    },
];
  
  export default TripuraData;


 