const UttarPradeshData= [
  {
    id: 1, 
    image: "assets/uttar pradesh/Beaches/chuka-beach.jpg",
    name: "chuka-beach",
    category: "Beaches",
    description: "https://www.culturalsafaritours.com/tourpackage/pilibhit-tiger-reserve-safari",
    info : "Chukha beach is the part of the Pilibhit Tiger Reserve. Famous among nature lovers & wildlife enthusiasts, this beach is located in the terai region of Uttar Pradesh. Chuka beach is situated on the bank of Sharda river in Pilibhit district. The Sharda Sagar dam on Sharda river forms Sharda Sagar reservoir which along with the forest areas presents a beautiful landscape. Tourists can come and enjoy the stay at Chuka Beach huts in the forest. It is a beautiful tourist destination. Chuka Beach is having facility of accomodation at bamboo hut, tree hut and Tharu huts.",
    map : "https://www.google.com/maps/dir//Chuka+Beach,+Kanjia+Singhpur+Bhauria,+Uttar+Pradesh/@28.7531933,80.0747323,15z/data=!4m18!1m9!3m8!1s0x39a04dcbe0144cfb:0x25f980149f26a290!2sChuka+Beach!3b1!8m2!3d28.749809!4d80.0821275!15sChdjaHVrYSBiZWFjaCBodXQgYm9va2luZ1oZIhdjaHVrYSBiZWFjaCBodXQgYm9va2luZ5IBBWJlYWNomgEjQ2haRFNVaE5NRzluUzBWSlEwRm5TVU50TkRkNloxaG5FQUXgAQA!16s%2Fg%2F12lrlbkjt!4m7!1m0!1m5!1m1!1s0x39a04dcbe0144cfb:0x25f980149f26a290!2m2!1d80.0821275!2d28.749809?hl=en-GB",
  },
  {
    id: 2, 
    image: "assets/uttar pradesh/forts/ramnagar-fort.jpg",
    name: "Ram Nagar Fort",
    category: "Forts",
    description: "https://www.tourtravelworld.com/india/varanasi/ramnagar-fort.htm",
    info : "The most important structure inside Varanasi Ram Nagar Fort is the famous Hall of public audience, popularly called as the 'Durbar Hall'. The architecture of this fort is a subtle combination of Islamic and Indian styles. The utilization of marbles for the decorative pattern gives this fort a splendid outlook. What is open for the tourists are the famous Ram Nagar Fort Museum and the temple. The temple is dedicated to Ved Vyasa, who is considered the author of the great Indian epic, Mahabharata.",
    map : "https://www.google.com/maps/place/Ramnagar+Fort/@25.2695094,83.0228989,17z/data=!3m1!4b1!4m5!3m4!1s0x398e31a57f4a1123:0xa2906ff69bbcc05a!8m2!3d25.2695094!4d83.0250876?hl=en-GB",
  },
  {
    id: 3, 
    image: "assets/uttar pradesh/forts/jhansi-fort.jpg",
    name: "Jhansi Fort",
    category: "Forts",
    description: "https://www.tourtravelworld.com/india/jhansi/jhansi-fort.htm",
    info : "The Jhansi Fort is one of the fortified areas located atop a hill in the city of jhansi in Uttar Pradesh, India. It was Raja Bir Singh Deo of Orchha who had commissioned this fort during early 17th century. This fort has treasured a few of the remnants of the Sepoy Mutiny. In June 1857 some of the soldiers of 12th native infantry seized the fort. The fort had stored ample supplies of treasure and magazine. They used the supplies from the Jhansi Fort, Jhansi and killed an number of European officers of the garrison.",
    map : "https://www.google.com/maps/place/Jhansi+Fort/@25.4575963,78.5742724,17z/data=!3m1!4b1!4m5!3m4!1s0x397776d740050301:0x5475a7d9e44707b4!8m2!3d25.4575915!4d78.5764611?hl=en-GB",
  },
  {
    id: 4, 
    image: "assets/uttar pradesh/forts/Chunar Fort.webp",
    name: "Chunar Fort",
    category: "Forts",
    description: "https://www.tourtravelworld.com/india/mirzapur/chunar-fort.htm",
    info : "The area is rich in sand stone and for centuries Chunar sand stone has been used. The highly polished Ashokan pillar was built from the sand stone from Chunar. History says that the place was existing in days of Vikamaditya, who had occupied the place way back in 56 BC. There is also a well-known fort at Chunar that every ruler coveted. One of the mightiest fortresses of medieval India, it caught the concentration of Humayun, the Mughal Emperor, and Sher Shah, the Afghan ruler, drawing both to the battlefield with a common purpose -the fort had to be captured. The fort is attributed to the legendary Sher Shah Suri.",
    map : "https://www.google.com/maps/place/Chunar+Fort/@25.1233557,82.8735554,17z/data=!3m1!4b1!4m5!3m4!1s0x398fca9ab966d9b7:0xe7373052fefe2f1d!8m2!3d25.1233509!4d82.8757441?hl=en-GB",
  },
  {
    id: 5, 
    image: "assets/uttar pradesh/forts/agra-red-fort.jpg",
    name: "Agra Fort",
    category: "Forts",
    description: "https://www.holidify.com/places/agra/agra-fort-sightseeing-1013.html",
    info : "Also known as Lal –Qila, Fort Rouge or Qila-i-Akbari, Agra Fort is a symbol of Agra and is so massive that it is often referred to as a walled city. It is the perfect example of Mughal art and architecture, built purely out of red sandstone. Within the premises of Agra Fort lie the most exquisite structures like the Pearl Mosque, Diwan-i I Khas, Diwan-i I Aam, Moti Masjid and Jahangiri Mahal.",
    map : "https://www.google.com/maps/search/Agra+Fort/@27.179825,78.0071762,14z/data=!3m1!4b1?hl=en-GB",
  }, 
  {
    id: 6, 
    image: "assets/uttar pradesh/forts/allahabad-fort.jpg",
    name: "Allahabad Fort",
    category: "Forts",
    description: "https://www.holidify.com/places/allahabad/allahabad-fort-sightseeing-1115.html",
    info : "Allahabad Fort is a splendid work of architecture that was built during the reign of Akbar, the Mughal Emperor in 1583. The marvellous structure is located on the banks of the confluence of the Rivers Ganga and Yamuna and is well-known for being the largest fort ever built by Akbar.",
    map : "https://www.google.com/maps/place/Allahabad+fort,+Prayagraj,+Uttar+Pradesh/@25.4301756,81.870588,15z/data=!3m1!4b1!4m10!1m2!2m1!1sAllahabad+Fort!3m6!1s0x39854aa938cd169b:0x4d0de80b329574f7!8m2!3d25.433923!4d81.8711034!15sCg5BbGxhaGFiYWQgRm9ydJIBDHN1YmxvY2FsaXR5MeABAA!16s%2Fg%2F1jkxtnrl1?hl=en-GB",
  },
  {
    id: 7, 
    image: "assets/uttar pradesh/forts/Kalinjar Fort.webp",
    name: "Kalinjar Fort",
    category: "Forts",
    description: "https://www.holidify.com/places/chitrakoot/kalinjar-sightseeing-4405.html",
    info : "Kalinjar is an ancient fort situated in the Banda District of Uttar Pradesh. Being one of the eight famous forts that were built by the Chandela kings, it is located on the Vindhya mountain range near the World Heritage Site of Khajuraho. The mighty fortress goes up to a height of 1203 ft and overlooks the Bundelkhand plains",
    map : "https://www.google.com/maps/place/Kalinjar+Fort/@24.9973546,80.4852635,17z/data=!3m1!4b1!4m5!3m4!1s0x39834038f85a54ad:0xbe24641e72d48e5d!8m2!3d24.9973546!4d80.4852635?hl=en-GB",
  },
  {
    id: 8, 
    image: "assets/uttar pradesh/forts/Orchha Fort Complex.jpg",
    name: "Orchha Fort Complex",
    category: "Forts",
    description: "https://www.holidify.com/places/jhansi/orchha-fort-complex-sightseeing-1255406.html",
    info : "The small town of Orchha situated 16 km from Jhansi in Madhya Pradesh emanates an architecturally historicized complex called the Orchha Fort Complex. It was built in 1501 AD by Raja Rudra Pratap Singh of the Bundela dynasty. It is a manifestation of Rajput and Mughal architecture flamboyantly decorated with latticed windows, projected platforms and balconies and mirrors on ceilings.",
    map : "https://www.google.com/maps/place/Orchha+Fort+and+contact+for+cycling+as+well/@25.350675,78.6427026,17z/data=!4m5!3m4!1s0x3977785eaaaaaaab:0xad980cf18cd2ffbe!8m2!3d25.350675!4d78.6427026?hl=en-GB",
  },
  {
    id: 9, 
    image: "assets/uttar pradesh/forts/aligarh-fort.jpg",
    name: "Aligarh Fort",
    category: "Forts",
    description: "https://www.holidify.com/places/aligarh/aligarh-fort-sightseeing-1255354.html",
    info : "Aligarh Fort, also known as Aligarh Quila, is one of India's strongest forts. Popularly called as Bonay Chor ka Kila (dwarf thief's fort), it represents historic Islamic influences through its exquisite architecture and intricate symbolic carvings, though most of it is in ruins now.",
    map : "https://www.google.com/maps/place/Aligarh+Fort/@27.930607,78.0632653,17z/data=!3m1!4b1!4m5!3m4!1s0x3974a5a7daaaaaab:0x87ed7ee11ff6d1b5!8m2!3d27.930607!4d78.0632653?hl=en-GB",
  },
  {
    id: 10, 
    image: "assets/uttar pradesh/forts/bhuragarh-fort.jpg",
    name: "Bhuragarh fort",
    category: "Forts",
    description: "https://www.touristlink.com/india/bhuragarh-fort/overview.html",
    info : "Across the river Ken there are ruins of Bhuragarh fort said to be built with brown stones by Raja Guman Singh in 17th Century. This place was main center at the time of freedom struggle. A mela is orgainsed in this place called ‘Natbali Ka Mela’.",
    map : "https://www.google.com/maps/place/Bhuragarh+Fort/@25.4770607,80.3096891,17z/data=!3m1!4b1!4m5!3m4!1s0x399cce4e04daab63:0xee5e34ad74c22071!8m2!3d25.4770607!4d80.309689102659*5?hl=en-GB",
  },
  {
    id: 11, 
    image: "assets/uttar pradesh/heritage tours/agra.jpgg",
    name: "Taj Mahal ",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/agra/taj-mahal",
    info : "Taj Mahal is one of the most admired Mughal masterpieces in the world and it represents the Indian, Persian and Islamic styles of architecture. It is an integrated complex of structures that include a white marble mausoleum containing the tombs of Shah Jahan and his wife Mumtaz Mahal. The mausoleum is built entirely of white marble, set on a high plinth which includes four tall minarets. The interior chamber of the Taj Mahal is an octagon, which is decorated in lapidary work of precious and semiprecious gemstones. The cenotaph of Mumtaz Mahal is placed in the center of the inner chamber and the cenotaph of Shah Jahan lies west of Mumtaz Mahal.",
    map : "https://www.google.com/maps/place/Taj+Mahal/@26.3259126,79.1870748,8z/data=!4m10!1m2!2m1!1s+taj+mahal!3m6!1s0x39747121d702ff6d:0xdd2ae4803f767dde!8m2!3d27.1751448!4d78.0421422!15sCgl0YWogbWFoYWxaCyIJdGFqIG1haGFskgEIbW9udW1lbnTgAQA!16zL20vMGw4Y2I?hl=en-GB",
  },
  {
    id: 12, 
    image: "assets/uttar pradesh/heritage tours/Fatehpur_Sikri.jpg",
    name: "Fatehpur Sikri",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/fatehpur-sikri",
    info : "Akbar, the greatest Mughal Emperor, was commissioned Fatehpur Sikri in 1569. The city was constructed to honour Sufi saint, Sheikh Salim Chisti, who used to live in a cavern on the ridge at Sikri. Akbar revered him very much as the Saint had blessed him with a son who was named Salim in 1569. Akbar shifted his capital from Agra to Sikri in 1571 and named the city as Fatehabad meaning victorious.",
    map : "https://www.google.com/maps/place/Fatehpur+Sikri,+Uttar+Pradesh+283110/@27.0944338,77.6735415,14z/data=!3m1!4b1!4m5!3m4!1s0x397391584a53798d:0x893d46790c1fb40!8m2!3d27.0945291!4d77.6679292?hl=en-GB",
  },
  {
    id: 13, 
    image: "assets/uttar pradesh/heritage tours/Jhansi.jpg",
    name: "Jhansi",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/jhansi",
    info : "Jhansi is regarded as the gateway to Bundelkhand region and also the administrative headquarters of Jhansi district. It is one of the top places to visit near Kanpur. Earlier known as Balwant Nagar, Jhansi was the seat of the Chandela dynasty and flourished under their rule. The region got its name from the fort built by Raja Bir Singh Deo",
    map : "https://www.google.com/maps/place/Jhansi,+Uttar+Pradesh/@25.4411179,78.5622883,12z/data=!3m1!4b1!4m5!3m4!1s0x397776d458ba7703:0x96e9cda55c3481ca!8m2!3d25.4484257!4d78.5684594?hl=en-GB",
  },
  {
    id: 14, 
    image: "assets/uttar pradesh/heritage tours/Kushinagar.jpg",
    name: "Kushinagar",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/kushinagar",
    info : "Kushinagar is one of the four holy sites of Buddhism, the other three being Lumbini, Sarnath, and Bodh Gaya. Kushinagar is the place where Gautam Buddha delivered his last sermon, attained Mahaparinirvana (salvation) in 483 BC, and was cremated at Rambhar Stupa. It is an international Buddhist pilgrimage center, and the followers of Buddhism, especially from Asian countries, wish to visit this place at least once in their lifetime.",
    map : "https://www.google.com/maps/place/Kushinagar,+Uttar+Pradesh/@26.7416957,83.8893387,15z/data=!3m1!4b1!4m5!3m4!1s0x3993eb9e01eae47b:0x7a8909ed5f568540!8m2!3d26.7398787!4d83.8869698?hl=en-GB",
  },
  {
    id: 15, 
    image: "assets/uttar pradesh/heritage tours/Sarnath.jpg",
    name: "Sarnath",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/sarnath",
    info : "Also known as Ishipatna, and Mrigadaya, Sarnath is one of the four most important Buddhist pilgrimage centers of India, the other three being Lumbini, Bodh Gaya, and Kushinagar. According to the legend, Lord Buddha after attaining enlightenment at Bodh Gaya came to Sarnath and delivered his first sermon to his five disciples. Deer Park is the place where Buddha came to give his first sermon.",
    map : "https://www.google.com/maps/place/Sarnath,+Varanasi,+Uttar+Pradesh+221007/@25.3729372,83.0248348,14z/data=!3m1!4b1!4m5!3m4!1s0x398e2ee870d6a12b:0xa1c385b2ea1fa974!8m2!3d25.3715564!4d83.0252136?hl=en-GB",
  },
  {
    id: 16, 
    image: "assets/uttar pradesh/heritage tours/Shravasti.jpg",
    name: "Shravasti",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/shravasti",
    info : "Shravasti is an ancient city located in the northeastern state of Uttar Pradesh. It is one of the popular places of Buddhist pilgrimage in India and among the must include tourist destinations in Uttar Pradesh Tour Packages.",
    map : "https://www.google.com/maps/place/Shravasti,+Uttar+Pradesh/@27.6786244,81.9076159,10z/data=!3m1!4b1!4m5!3m4!1s0x39984af244455045:0xf9e41ece7700f67f!8m2!3d27.7350346!4d81.909826?hl=en-GB",
  },
  {
    id: 17, 
    image: "assets/uttar pradesh/heritage tours/Hastinapur.jpg",
    name: "Hastinapur",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/hastinapur",
    info : "Situated on the right bank of the holy Ganges near Meerut, Hastinapur is an ancient town that was the center of the glorious tales of the great Hindu epic Mahabharata. In Sanskrit, Hastinapura translates to 'the City of Elephants'. It was the legendary capital of Kauravas. Legend has it that the Great War of Mahabharata was fought between the Pandavas and Kauravas here.",
    map : "https://www.google.com/maps/place/Hastinapur,+Uttar+Pradesh+250404/@29.1564896,77.9949259,14z/data=!3m1!4b1!4m5!3m4!1s0x390b8c082f613de3:0x79d978841c5a29f7!8m2!3d29.1568812!4d77.9938497?hl=en-GB",
  },
  {
    id: 18, 
    image: "assets/uttar pradesh/heritage tours/Kusum_Sarovar.jpg",
    name: "Kusum Sarovar",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/mathura/kusum-sarovar",
    info : "Kusum Sarovar is 450 feet long and 60 feet deep tank and features a flight of stairs on all sides. The Sarovar is believed to be the place where Radha along with gopikas used to collect flowers and meet Lord Krishna. Kadamba trees are found all over the place and it is said that Kadamba tree was the favorite tree of Lord Krishna. ",
    map : "https://www.google.com/maps/place/Kusum+Sarovar/@28.0585525,77.2535039,9z/data=!4m10!1m2!2m1!1sKusum+Sarovar!3m6!1s0x39730ddba58ceea1:0xf71b98ff8e5c12d9!8m2!3d27.5120117!4d77.4782636!15sCg1LdXN1bSBTYXJvdmFykgEEbGFrZeABAA!16s%2Fg%2F121ln4g0?hl=en-GB",
  },
  {
    id: 19, 
    image: "assets/uttar pradesh/heritage tours/Kuchesar.jpg",
    name: "Kuchesar",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/bulandshahr/kuchesar",
    info : "Kuchesar is known for the Kuchesar Fort, also known as Rao Raj Vilas, built by the Jat rulers The fort was built in the mid-18th century by the Jat rulers and is surrounded by a 100-acre mango grove. During 1740, the Jats became strong military power who originally belong to Mandoti in Haryana and were the descendants from the Jats of the Dalal sub-caste.",
    map : "https://www.google.com/maps/place/Kuchesar,+Uttar+Pradesh+203402/@28.6844411,77.9400881,16z/data=!3m1!4b1!4m5!3m4!1s0x390b62b1f8171117:0x9d354304ec975b6!8m2!3d28.6849559!4d77.939954?hl=en-GB",
  },
  {
    id: 20, 
    image: "assets/uttar pradesh/heritage tours/Unchagaon.jpg",
    name: "Unchagaon",
    category: "Heritage",
    description: "https://www.trawell.in/uttar-pradesh/bulandshahr/unchagaon",
    info : "Unchagaon is also famous for Unchagaon Fort. This is a mud fort built during 1850s and belonged to Rajput Zamindars. Now it is owned by Raja Surendra Pal Singh, who inherited it at the age of 10. This palace was renovated by Surendra Pal Singh and now part of it is opened as a heritage resort.",
    map : "https://www.google.com/maps/place/Unchagaon,+Uttar+Pradesh+203398/@28.4873827,78.1521999,16z/data=!3m1!4b1!4m5!3m4!1s0x390b42f90cd64a75:0x7f7be357614587de!8m2!3d28.4871318!4d78.151455?hl=en-GB",
  },
  {
    id: 21, 
    image: "assets/uttar pradesh/hill stations/pauri garhwal.jpg",
    name: "Pauri Garhwal",
    category: "HillStation",
    description: "https://www.holidify.com/places/pauri-garhwal/",
    info : "Pauri Garhwal is a paradise that showcases the varied colors of nature all packed in to this one place. From snow covered Himalayan peaks and thick cover of lush green forests to deep rooted culture of the place and warm hearted people, this place oozes beauty and charm in every aspect.",
    map : "https://www.google.com/maps/place/Pauri,+Uttarakhand+246001/@30.1431942,78.7568019,14z/data=!3m1!4b1!4m5!3m4!1s0x3909a476b13ca115:0xa30049354e9659ca!8m2!3d30.1471155!4d78.7745393?hl=en-GB",
  },
  {
    id: 22, 
    image: "assets/uttar pradesh/hill stations/lansdowne.jpg",
    name: "Lansdowne",
    category: "HillStation",
    description: "https://www.holidify.com/places/lansdowne/",
    info : "Lansdowne is a quaint little hill town located at a distance of 258 km from Delhi in Pauri district of Uttarakhand. Laden with oak and pine forest and dotted with buildings of the colonial era, this hill station is a haven for bird watchers, casual hikers and weekenders from NCR.",
    map : "https://www.google.com/maps/place/Lansdowne,+Uttarakhand+246155/@29.8433511,78.6711537,15z/data=!3m1!4b1!4m5!3m4!1s0x390982b9e5122989:0x2798532cabd61501!8m2!3d29.8377457!4d78.6871069?hl=en-GB",
  },
  {
    id: 23, 
    image: "assets/uttar pradesh/ill stations/mussoorie 2.jpg",
    name: "Mussoorie",
    category: "HillStation",
    description: "https://www.holidify.com/places/mussoorie/",
    info : "Mussoorie is one of the most popular hill stations located at a distance of 290 km from Delhi in the Dehradun district of Uttarakhand. With a backdrop of the Shivalik range of Himalayas and doon valley, Mussoorie, also known as Queen of The Hills, stands at an altitude of 7000 feet above sea level. With a cool and pleasant climate throughout the year, Mussoorie was once the British summer capital.",
    map : "https://www.google.com/maps/place/Mussoorie,+Uttarakhand/@30.4547926,78.0414204,13z/data=!3m1!4b1!4m5!3m4!1s0x3908d0cfa61cda5b:0x197fd47d980e85b1!8m2!3d30.4597892!4d78.0643723?hl=en-GB",
  },
  {
    id: 24, 
    image: "assets/uttar pradesh/hill stations/almora-.jpg",
    name: "Almora",
    category: "HillStation",
    description: "https://www.holidify.com/places/almora/",
    info : "Set in the background of snow-capped Himalayan ranges of Uttarakhand, the sprawling town of Almora is a beautiful hill station. With easy accessibility from Delhi and other major cities of North India, Almora is known for its rich cultural heritage, unique handicrafts, sumptuous cuisine and magnificent wildlife.",
    map : "https://www.google.com/maps/place/Almora,+Uttarakhand/@29.6015457,79.6357828,14z/data=!3m1!4b1!4m5!3m4!1s0x39a0b7328910d81f:0x9811d25dd87d8ed5!8m2!3d29.5892407!4d79.646666?hl=en-GB",
  },
  {
    id: 25, 
    image: "assets/uttar pradesh/hill stations/kausani.jpg",
    name: "Kausani",
    category: "HillStation",
    description: "https://www.holidify.com/places/kausani/",
    info : "Kausani is a hill station located in Bageshwar district of Uttarakhand, 51km from Almora. The panoramic snow-clad view of Himalayas in Kausani is dominated by Trisul, Nanda Devi and Panchuli peaks.",
    map : "https://www.google.com/maps/place/Kausani,+Uttarakhand+263639/@29.8430212,79.5956414,15z/data=!3m1!4b1!4m5!3m4!1s0x39a74e7fb73633e1:0x173a54291447af4f!8m2!3d29.8445269!4d79.6038842?hl=en-GB",
  },
  {
    id: 26, 
    image: "assets/uttar pradesh/hill stations/Champawat.jpg",
    name: "Champawat",
    category: "HillStation",
    description: "https://www.holidify.com/places/champawat/",
    info : "Champawat is an intrepid town in Champawat district, Uttrakhand. Perched 5,299 feet above the sea level, this quaint town of Champaran is a perfect composite of adventure, religion and history. The place holds historical and religious significance attracting many drifters and pilgrims throughout the year. As the legend goes, Lord Vishnu incarnated in his Kurma Avatar in this region.",
    map : "https://www.google.com/maps/place/Champawat,+Uttarakhand+262523/@29.3349582,80.0833281,15z/data=!3m1!4b1!4m5!3m4!1s0x39a11e018975d1af:0x56237bebd221ef2c!8m2!3d29.3360974!4d80.0910275?hl=en-GB",
  },
  {
    id: 27, 
    image: "assets/uttar pradesh/hill stations/mukteshwar.jpg",
    name: "Mukteshwar",
    category: "HillStation",
    description: "https://www.holidify.com/places/mukteshwar/",
    info : "Mukteshwar is a small hill town located around 50 km from Nainital in Uttarakhand. Known for adventure sports and a dazzling view of Himalayan ranges, Mukteshwar is named after the 350-year-old Shiva Temple housed here called Mukteshwar Dham. ",
    map : "https://www.google.com/maps/place/Mukteshwar,+Uttarakhand/@29.4680325,79.6325108,14z/data=!3m1!4b1!4m5!3m4!1s0x39a0bbfdf924848f:0x72b5b5db99b0efdb!8m2!3d29.4604149!4d79.6558242?hl=en-GB",
  },
  {
    id: 28, 
    image: "assets/uttar pradesh/hill stations/naintial.jpg",
    name: "Nainital",
    category: "HillStation",
    description: "https://www.holidify.com/places/nainital/",
    info : "Nainital is a charming hill station located at the foothills of the Kumaon ranges in Uttarakhand. Located close to Dehradun and Delhi, it is the most visited hill station in North India. Nainital is a perfect weekend getaway from Delhi and the nearby places.",
    map : "https://www.google.com/maps/place/Nainital,+Uttarakhand/@29.3824865,79.4377611,14z/data=!3m1!4b1!4m5!3m4!1s0x39a0a1bc28fd9d61:0x7cae7ba916987db3!8m2!3d29.3919202!4d79.4542033?hl=en-GB",
  },
  {
    id: 29, 
    image: "assets/uttar pradesh/hill stations/bhimtal.jpg",
    name: "Bhimtal",
    category: "HillStation",
    description: "https://www.holidify.com/places/bhimtal/",
    info : "Perched at a height of 1370masl, Bhimtal is an idyllic and less-crowded version of Nainital, 23 km away. Bhimtal is a scenic hill station, the charm of which lies in its off-beat, tranquil atmosphere. The picturesque Bhimtal Lake is a popular attraction for paddle boating, birding and nature walk.",
    map : "https://www.google.com/maps/place/Bhimtal,+Uttarakhand+263136/@29.3489601,79.5360265,14z/data=!3m1!4b1!4m5!3m4!1s0x39a098214690ff0d:0x3adc3244429741dc!8m2!3d29.346082!4d79.5519144?hl=en-GB",
  },
  {
    id: 30, 
    image: "assets/uttar pradesh/hill stations/Devangana Hill.jpg",
    name: "Devangana Hill",
    category: "HillStation",
    description: " https://www.holidify.com/places/chitrakoot/",
    info : "Chitrakoot, a small town situated in the north Vindhyan range, is located over the districts of Chitrakoot in Uttar Pradesh and Satna in Madhya Pradesh. It holds great importance according to Hindu mythology and the epic Ramayana. Legends have it that Chitrakoot was the place where Lord Rama, his wife Sita and his brother Lakshmana stayed for eleven and half of their fourteen years of exile making it a reverred site among pilgrims.",
    map : "https://www.google.com/maps/place/Devangana+Hill,+Chitrakoot/@25.1700126,80.8225958,13z/data=!4m11!1m3!2m2!1sChitrakoot+hill+station!6e1!3m6!1s0x3984a5f738fddd93:0xd86920c75a380e52!8m2!3d25.1575119!4d80.916659!15sChdDaGl0cmFrb290IGhpbGwgc3RhdGlvbpIBDGhpbmR1X3RlbXBsZeABAA!16s%2Fg%2F11ny4739ly?hl=en-GB",
  },
  {
    id:31, 
    image: "assets/uttar pradesh/religious tour/VARANASI.jpg",
    name: "Varanasi",
    category: "Religious",
    description: "https://www.holidify.com/places/varanasi/",
    info : "World's oldest living city, Varanasi - also known as Kashi (City of Life) and Benaras, is the spiritual capital of India. It is one of Hinduism's seven holy cities. The old city of Varanasi lies along the western banks of the Ganges, spread across a labyrinth of narrow galis. Be prepared to walk on foot and encounter some holy cows! Temples at almost every turn engulf Varanasi but the Kashi Vishwanath Temple is the most visited",
    map : "https://www.google.com/maps/place/Varanasi,+Uttar+Pradesh/@25.3207461,82.9210686,12z/data=!3m1!4b1!4m5!3m4!1s0x398e2db76febcf4d:0x68131710853ff0b5!8m2!3d25.3176452!4d82.9739144?hl=en-GB",
  },
  {
    id: 32, 
    image: "assets/uttar pradesh/religious tour/VRINDAVAN.jpg",
    name: "Vrindavan",
    category: "Religious",
    description: "https://www.holidify.com/places/vrindavan/",
    info : "One of the oldest cities on the banks of Yamuna, Vrindavan is considered to be one of the most important places of pilgrimage for the devotees of Krishna. It is said that Lord Krishna had spent his childhood in Vrindavan. The name of the city has been derived from Vrinda (meaning basil) and van (meaning grove) which perhaps refer to the two small groves at Nidhivan and Seva Kunj.",
    map : "https://www.google.com/maps/place/Vrindavan,+Uttar+Pradesh/@27.564811,77.6243514,13z/data=!3m1!4b1!4m5!3m4!1s0x39736fcb5e9a2309:0x9868374c5faaf3ce!8m2!3d27.5650088!4d77.6593394?hl=en-GB",
  },
  {
    id: 33, 
    image: "assets/uttar pradesh/religious tour/MATHURA.jpg",
    name: "Mathura",
    category: "Religious",
    description: "https://www.holidify.com/places/mathura/",
    info : "One of Hinduism's seven sacred cities, Mathura is the birthplace of the very beloved Lord Krishna. Located in the state of Uttar Pradesh, Mathura and Vrindavan are often considered twin cities (located only 10km away from each other). Mathura is a small town dotted with temples from various ages and attracts a horde of pilgrims from all over the world. ",
    map : "https://www.google.com/maps/place/Mathura,+Uttar+Pradesh/@27.4743568,77.6141143,12z/data=!3m1!4b1!4m5!3m4!1s0x397371163d4d5205:0x4273a09defe10ea5!8m2!3d27.4924134!4d77.673673?hl=en-GB",
  },
  {
    id: 34, 
    image: "assets/uttar pradesh/religious tour/SARNATH.jpg",
    name: "Sarnath",
    category: "Religious",
    description: "https://www.holidify.com/places/sarnath/",
    info : "A quiet and spiritual town set amidst the otherwise densely populated state of Uttar Pradesh, Sarnath is a city of historical marvel with numerous Buddhist stupas, museums, excavated ancient sites and beautiful temples that prove to be a source of immense wonder and astonishment to tourists due to their mystical and serene setting. Being just 10 kms from Varanasi",
    map : "https://www.google.com/maps/place/Sarnath,+Varanasi,+Uttar+Pradesh+221007/@25.3729362,83.0073252,14z/data=!4m5!3m4!1s0x398e2ee870d6a12b:0xa1c385b2ea1fa974!8m2!3d25.3715564!4d83.0252136?hl=en-GB",
  },
  {
    id: 35, 
    image: "assets/uttar pradesh/religious tour/CHITRAKOOT.jpgg",
    name: "Chitrakoot",
    category: "Religious",
    description: "https://www.holidify.com/places/chitrakoot/",
    info : "Chitrakoot, a small town situated in the north Vindhyan range, is located over the districts of Chitrakoot in Uttar Pradesh and Satna in Madhya Pradesh. It holds great importance according to Hindu mythology and the epic Ramayana. Legends have it that Chitrakoot was the place where Lord Rama, his wife Sita and his brother Lakshmana stayed for eleven and half of their fourteen years of exile making it a reverred site among pilgrims.",
    map : "https://www.google.com/maps/place/Chitrakoot,+Madhya+Pradesh/@25.1697878,80.822596,13z/data=!3m1!4b1!4m5!3m4!1s0x3984a635ac470c09:0xf77828392d478da7!8m2!3d25.1788154!4d80.8654534?hl=en-GB",
  },
  {
    id: 36, 
    image: "assets/uttar pradesh/religious tour/AYODHYA.jpg",
    name: "Ayodhya",
    category: "Religious",
    description: "https://www.holidify.com/places/ayodhya/",
    info : "Ayodhya, located on the banks of river Sarayu in Uttar Pradesh, is one of the seven sacred cities for Hindus. Ayodhya plays a critical role in the Hindu epic of Ramayana as it is believed to be the birthplace of Lord Rama. This religious town is also the birthplace of four of Jainism's 24 Tirthankaras (religious teachers), beckoning tourists with its serene ghats.",
    map : "https://www.google.com/maps/place/Ayodhya,+Uttar+Pradesh/@26.7897741,82.1816582,14z/data=!3m1!4b1!4m5!3m4!1s0x399a07937e6d2823:0x5fc8f683b17f222b!8m2!3d26.7921605!4d82.1997954?hl=en-GB",
  },
  {
    id: 37, 
    image: "assets/uttar pradesh/religious tour/HASTINAPUR.jpg",
    name: "Hastinapur",
    category: "Religious",
    description: "https://www.holidify.com/places/hastinapur/",
    info : "Hastinapur is an ancient town which was the centre to the glorious tales of the epic Mahabharata. Situated on the banks of Ganga near Meerut in UP, Hastinapur is also the birth place of three Jain Teerthankara, and it has become an important centre of pilgrimage for the Jains.",
    map : "https://www.google.com/maps/place/Hastinapur,+Uttar+Pradesh+250404/@29.1564893,77.9861711,15z/data=!3m1!4b1!4m5!3m4!1s0x390b8c082f613de3:0x79d978841c5a29f7!8m2!3d29.1568812!4d77.9938497?hl=en-GB",
  },
  {
    id: 38, 
    image: "assets/uttar pradesh/religious tour/ALLAHABAD.jpg",
    name: "Allahabad",
    category: "Religious",
    description: "https://www.holidify.com/places/allahabad/",
    info : "Allahabad,  now officially known as Prayagraj, is a city located in the Indian state of Uttar Pradesh. Reminiscent of all that is spiritual and sacred in Hinduism, Allahabad is famous for Triveni Sangam or the meeting point of three rivers - the Ganga, the Yamuna, and the Saraswati. Built on the site of the ancient town of Prayag, Allahabad has, since time immemorial, held the largest Hindu gathering on the banks of the Sangam",
    map : "https://www.google.com/maps/place/Prayagraj,+Uttar+Pradesh/@25.4022472,81.7315442,12z/data=!3m1!4b1!4m5!3m4!1s0x398534c9b20bd49f:0xa2237856ad4041a!8m2!3d25.4358011!4d81.846311?hl=en-GB",
  },
  {
    id: 39, 
    image: "assets/uttar pradesh/religious tour/VINDHYACHAL.jpg",
    name:  "Vindhyachal",
    category: "Religious",
    description: "https://www.holidify.com/places/vindhyachal/",
    info : "Vindhyachal is a famous Hindu pilgrimage spot closer to Mirzapur and Varanasi and has several temples in the vicinity with their own interesting stories. This town is situated on the banks of holy river Ganga and people come here to take a dip into it to pray to Goddess Ganga.",
    map : "https://www.google.com/maps/place/Vindhyachal,+Mirzapur,+Uttar+Pradesh+231307/@25.1586568,82.4950457,15z/data=!3m1!4b1!4m5!3m4!1s0x398febbbdda15d3f:0xbc18a109f95c1a7a!8m2!3d25.1577106!4d82.5036997?hl=en-GB",
  },
  {
    id: 40, 
    image: "assets/uttar pradesh/whildlife santuaries/Lakh Bahosi Sanctuary.jfif",
    name: "Lakh Bahosi Sanctuary",
    category: "Wild ",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "If you are a bird watcher and lover, then perhaps this is going to be the perfect place for you. Located approximately 40 km (24.8 miles) from the city Kannauj, Lakh Bahosi Sanctuary is spread across two lakes near the two villages from where it derives its name - Lakh and Bahosi. One can see 49 different genera of birds. It is an initiative of the state government towards promoting UP Ecotourism apart from protecting the species. ",
    map : "https://www.google.com/maps/place/Lakh+Bahosi+Sanctuary/@26.9112899,79.6390252,17z/data=!3m1!4b1!4m5!3m4!1s0x399e0eebefdf6efd:0xc0483e8bae4c2c7!8m2!3d26.9112899!4d79.6412139?hl=en-GB",
  },
  {
    id: 41, 
    image: "assets/uttar pradesh/whildlife santuaries/kishanpur-wildlife-sanctuary.jpg",
    name: " Kishanpur Wildlife Sanctuary",
    category: "Wild",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "Founded in 1972, this wildlife sanctuary is located near the town of Mailani in Uttar Pradesh. Kishanpur Wildlife Sanctuary is 30 km (18.64 miles) from Dudhwa National Park and over four hour’s drive from Lucknow. Spread over 200 km (124 miles) this wildlife sanctuary is home to several animal species such as tigers, pythons, ghariyal, leopards, wild boar, swamp deers and more. Swamp deer, also called barasingha, is one of the most common animals that you may come across here.",
    map : "https://www.google.com/maps/place/Kishanpur+Wildlife+Sanctuary/@28.3884989,80.3905902,15z/data=!4m10!1m2!2m1!1s+Kishanpur+Wildlife+Sanctuary!3m6!1s0x39a1defd1aacc243:0x563b8b885d131547!8m2!3d28.3884989!4d80.4080997!15sChxLaXNoYW5wdXIgV2lsZGxpZmUgU2FuY3R1YXJ5Wh4iHGtpc2hhbnB1ciB3aWxkbGlmZSBzYW5jdHVhcnmSAQ9uYXRpb25hbF9mb3Jlc3TgAQA!16s%2Fm%2F04f_y9j?hl=en-GB",
  },
  {
    id: 42, 
    image: "assets/uttar pradesh/whildlife santuaries/Dudhwa National Park.jpg",
    name: "Dudhwa National Park",
    category: "Wild",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "This wildlife sanctuary is located in the northern part of Uttar Pradesh and covers a vast area of 490.3 kilometers square (305 miles square). Tigers and swamp deers are the main attractions here. However, you can also spot other animals and birds like ratel jackal, jungle cat, leopard, hispid hare, Indian rhinoceros, sambar deer, great salty woodpecker, Bengal florican, swamp francolin and more. Dudhwa National Park is also home to a number of migratory birds during the winter months.",
    map : "https://www.google.com/maps/place/Dudhwa+National+Park/@28.4901847,80.5756505,13z/data=!4m10!1m2!2m1!1s+Dudhwa+National+Park!3m6!1s0x390ce5ae41003fab:0xc64987ea6e33c41e!8m2!3d28.4901847!4d80.6456883!15sChREdWRod2EgTmF0aW9uYWwgUGFya1oWIhRkdWRod2EgbmF0aW9uYWwgcGFya5IBDW5hdGlvbmFsX3BhcmuaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTXdhVGhQWW5WM1JSQULgAQA!16zL20vMDhfc2Zt?hl=en-GB",
  },
  {
    id: 43, 
    image: "assets/uttar pradesh/whildlife santuaries/Sohagi Barwa Sanctuary.jfif",
    name: " Sohagi Barwa Sanctuary",
    category: "Wild",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "This quaint sanctuary in the Maharajganj district of Uttar Pradesh has a serene environment ideal to spot wildlife in their natural habitat. The sanctuary preserves animals like tigers, cheetah, wild boar, leopards and many more. The pleasant weather in Sohagi Barwa Sanctuary attracts tourists throughout the year. However, it can get slightly colder in December and January. The city of Gorakhpur is 56 km (about 35 miles) from this wildlife sanctuary.",
    map : "https://www.google.com/maps/place/Sohagi+Barwa+Sanctuary/@27.3497077,83.8313048,17z/data=!3m1!4b1!4m5!3m4!1s0x3996a9bd6fadd2c5:0x76621c173258b2c1!8m2!3d27.3497077!4d83.8334935?hl=en-GB",
  },
  {
    id: 44, 
    image: "assets/uttar pradesh/whildlife santuaries/Pilibhit Tiger Reserve.jpg",
    name: "Pilibhit Tiger Reserve",
    category: "Wild",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "Located in the district of Pilibhit and Shahjahanpur, Pilibhit Tiger Reserve covers a massive area of 730.2 square km (453 square miles). Located at the foothills of the Himalayas, this sanctuary is one of the 50 sanctuaries under India’s ambitious Project Tiger. The place has more than 50 tigers. Other species that can be spotted at this sanctuary include five different species of deer among others. They are swamp deer, spotted deer, barking deer, hog deer, and blackbuck.",
    map : " https://www.google.com/maps/place/Pilibhit+Tiger+Reserve/@28.7052803,80.0594658,17z/data=!3m1!4b1!4m5!3m4!1s0x39a1ca688f75f4bf:0x8b513ec2e32b2c8d!8m2!3d28.7052803!4d80.0616545?hl=en-GB",
  },
  {
    id: 45, 
    image: "assets/uttar pradesh/whildlife santuaries/Katarniaghat Wildlife Sanctuary.jpg",
    name: "Katarniaghat Wildlife Sanctuary",
    category: "Wild",
    description: "https://trip101.com/article/wildlife-sanctuaries-in-uttar-pradesh-india",
    info : "Covering a whopping 400.6 square km (248.9 square miles) in the Terai region of Bahraich district, Katarniaghat Wildlife Sanctuary was established in the year 1975 and was brought under the purview of Project Tiger. The wildlife sanctuary also stands important because it provides strategic connectivity to two tiger habitats - Bardia National Park of Nepal with Dudhwa and Kishanpur in India. Apart from the tigers, the sanctuary is a well-known place for several endangered species of wild animals like long-billed vultures, Bengal florican, swamp deer, and gharial. ",
    map : "https://www.google.com/maps/place/Katarniaghat+Wildlife+Sanctuary/@28.335926,81.121341,17z/data=!3m1!4b1!4m5!3m4!1s0x3998999f057dc34d:0x62ec1a814f2e3cec!8m2!3d28.335926!4d81.1235297?hl=en-GB",
  },
  {
    id: 46, 
    image: "assets/uttar pradesh/food/Bedhai.jpg",
    name: "Bedhai",
    category: "Food",
    info : "It is a famous dish in the areas of Agra, Firozabad, and Mathura. The crispy, deep-fried wheat chapattis (puri), with spicy curry based potato sabzi.",
  },
  {
    id: 47, 
    image: "assets/uttar pradesh/food/Tehri.jpg",
    name: "Tehri",
    category: "Food",
    info : "It is also known as vegetable pulao. The finest of all basmati rice is used to make this dish. Varieties of vegetables are cooked with the rice with different spices which provides it the taste and aroma.",
  },
  {
    id: 48, 
    image: "assets/uttar pradesh/food/Baigan Ki Longe.jpg",
    name: "Baigan Ki Longe",
    category: "Food",
    info : "This is a special dish. The brinjal is sliced from between and filled with masala. The stuffed masala is made of all types of different spices.",
  },
  {
    id: 49, 
    image: "assets/uttar pradesh/food/Galaouti Kebabs.jpg",
    name: "Galaouti Kebabs",
    category: "Food",
    info : "It’s the most famous dish of the city of Nawabs. The minced meat is mixed with spices and baked on a tava. The aroma and taste of the spices are mesmerizing.",
  },
  {
    id: 50, 
    image: "assets/uttar pradesh/food/Malpua.jpg",
    name: "Malpua",
    category: "Food",
    info : "It is a sweet dessert of Uttar Pradesh. It is a deep fried maida puri, soaked in cardamom flavored sugar syrup. It is decorated with dry fruits and chandi vark",
  },
  
     
  ];
  
  export default UttarPradeshData;


 